ydb-platform/nbs

cloud/disk_manager/test/ya.make

Comment-out remote tests in ya.make

Fix ya.make for disk manager tests

---

cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor_readblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_ut.cpp

NBS-4414: resync fast path should work even if there are fresh devices; added a ut for the resync with fresh devices case

---

cloud/storage/core/tools/testing/qemu/lib/recipe.py

https://github.com/ydb-platform/nbs/commit/09b53712e1341c24342d88dbbfecc4b83135bd27

Merge to stable-23-3: CLOUDDUTY-23951 : Fix qemu timeouts.

---

cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor_readblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor_resync.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_ut.cpp
cloud/blockstore/libs/storage/partition_nonrepl/resync_range.cpp
cloud/filestore/libs/storage/service/service_actor_createsession.cpp
cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/service/ut/ya.make
cloud/storage/core/libs/version/version.cpp
cloud/storage/core/libs/version/version_ut.cpp

https://github.com/ydb-platform/nbs/commit/c1a6d02c45326351d356c76ab557409cee9d6066
https://github.com/ydb-platform/nbs/commit/a0691f6d27d9f857a1c234596cbf30b384649148
https://github.com/ydb-platform/nbs/commit/782c11a04966d89eb6d0dfd07532e6d5398beec1
https://github.com/ydb-platform/nbs/commit/6ff8616f6d9c11ac63b5b8ac5acd8cfe17b1f0d8
https://github.com/ydb-platform/nbs/commit/52c5eacabbc0868b503d0540075d5034c9dcd0f5
https://github.com/ydb-platform/nbs/commit/441141534a97537f0d4f76bf388c6a4ada757655

merge to stable-23-3

---

cloud/filestore/apps/client/lib/ls.cpp
cloud/filestore/libs/diagnostics/request_stats.cpp
cloud/filestore/libs/diagnostics/request_stats.h
cloud/filestore/libs/diagnostics/request_stats_ut.cpp
cloud/filestore/libs/server/server.cpp
cloud/filestore/libs/service/context.h
cloud/filestore/libs/service/error.cpp
cloud/filestore/libs/service/error.h
cloud/filestore/libs/storage/service/service_state.cpp
cloud/filestore/libs/vfs_fuse/fs.cpp
cloud/filestore/libs/vfs_fuse/fs.h
cloud/filestore/libs/vfs_fuse/fs_impl.cpp
cloud/filestore/libs/vfs_fuse/fs_impl.h
cloud/filestore/libs/vfs_fuse/fs_impl_attr.cpp
cloud/filestore/libs/vfs_fuse/fs_impl_data.cpp
cloud/filestore/libs/vfs_fuse/fs_impl_list.cpp
cloud/filestore/libs/vfs_fuse/fs_impl_lock.cpp
cloud/filestore/libs/vfs_fuse/fs_impl_node.cpp
cloud/filestore/libs/vfs_fuse/fs_impl_stat.cpp
cloud/filestore/libs/vfs_fuse/loop.cpp

Data-race: https://proxy.sandbox.yandex-team.ru/5583222557/cloud/filestore/tests/fio_index/qemu-kikimr-nemesis-test/test-results/py3test/chunk2/testing_out_stuff/filestore-vhost.err
Uninitialized value: https://fps--man-0017-distbuild.n.yandex-team.ru/tmp39e3g94q/testing_out_stuff.tar.zstd/filestore-client.err.2

CLOUDDUTY-23898 : Fix data race and uninitialized value

---

cloud/blockstore/libs/notify/CMakeLists.darwin-x86_64.txt
cloud/blockstore/libs/notify/CMakeLists.linux-aarch64.txt
cloud/blockstore/libs/notify/CMakeLists.linux-x86_64.txt
cloud/blockstore/libs/notify/CMakeLists.windows-x86_64.txt
cloud/blockstore/tools/fs/cleanup-ext4-meta/CMakeLists.darwin-x86_64.txt
cloud/blockstore/tools/fs/cleanup-ext4-meta/CMakeLists.linux-aarch64.txt
cloud/blockstore/tools/fs/cleanup-ext4-meta/CMakeLists.linux-x86_64.txt
cloud/blockstore/tools/fs/cleanup-ext4-meta/CMakeLists.windows-x86_64.txt

disable notify & cleanup-ext4-meta unit tests

disable a few tests

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_create.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_create.cpp
cloud/blockstore/libs/storage/disk_registry/model/agent_list.cpp
cloud/blockstore/tests/storage_discovery/test.py

NBS-4358: fix UnadjustedBlockCount; added test_override_storage_discovery_config (#85)

merge to stabe-23-3

---

cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_register.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_ut.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_state.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_state.h

Revert "NBSNEBIUS-37: don't register disk agent with no devices"

---

example/0-setup.sh
example/1-start_storage.sh
example/2-init_storage.sh
example/3-start_nbs.sh
example/4-start_nbs_storage.sh
example/5-create_and_attach_disk.sh
example/6-run_qemu.sh
example/BUILD.md
example/README.md
example/prepare_binaries.sh

Need to update build documentation & adjust the documentation for running the example

NBSNEBIUS-79: Updating build documentation

---

.github/actions/build/action.yaml
.github/actions/s3cmd/action.yaml
.github/actions/test/action.yaml
.github/scripts/index.py
.github/scripts/templates/index.html
.github/workflows/nightly-index-rebuild.yaml

Added ability to generate directory listing in s3 (example: https://github-actions-s3.website.nemax.nebius.cloud/librarian/nbs/)
Script launched every night on the whole folder for consistency and after every build on build folder.

feature: add directory listing to s3 folder

---

cloud/tasks/scheduler_impl.go
cloud/tasks/storage/common.go
cloud/tasks/storage/compound_storage.go
cloud/tasks/storage/mocks/storage_mock.go
cloud/tasks/storage/storage.go
cloud/tasks/storage/storage_ydb.go
cloud/tasks/storage/storage_ydb_impl.go
cloud/tasks/storage/storage_ydb_test.go

In next PRs "cron tab" parameters will be added (and encapsulated inside TaskSchedule struct along with ScheduleInterval and MaxTasksInflight)

NBSNEBIUS-89: [Tasks] extract scheduleInterval and maxTasksInflight into TaskSchedule struct; rename tasks/storage.schedule to scheduleState

---

cloud/disk_manager/test/acceptance/test_runner/eternal_acceptance_test_runner.py

Single command execution in python tests ssh client is blocking, which causes a significant slowdown for some test cases.

Fix slow ssh client in python tests

---

cloud/disk_manager/internal/pkg/dataplane/register.go
cloud/disk_manager/internal/pkg/services/disks/register.go
cloud/disk_manager/internal/pkg/services/filesystem/register.go
cloud/disk_manager/internal/pkg/services/images/register.go
cloud/disk_manager/internal/pkg/services/placementgroup/register.go
cloud/disk_manager/internal/pkg/services/pools/register.go
cloud/disk_manager/internal/pkg/services/snapshots/register.go
cloud/tasks/mocks/scheduler_mock.go
cloud/tasks/scheduler.go
cloud/tasks/scheduler_impl.go
cloud/tasks/tasks_tests/tasks_test.go

In next PRs "cron tab" parameters will be added (and encapsulated inside TaskSchedule struct along with ScheduleInterval and MaxTasksInflight)

NBSNEBIUS-89: [Tasks] extract scheduleInterval and maxTasksInflight into TaskSchedule struct (for tasks.Scheduler)

---

cloud/blockstore/libs/storage/init/disk_agent/actorsystem.cpp
cloud/blockstore/libs/storage/init/server/actorsystem.cpp
cloud/filestore/libs/storage/init/actorsystem.cpp

This reverts commit c860035d23b4d11ceedfa44f043efa186eeb4577.

Revert "NBS-4787: enable ydb configs_dispatcher service (#109)"

---

cloud/blockstore/libs/storage/init/disk_agent/actorsystem.cpp
cloud/blockstore/libs/storage/init/server/actorsystem.cpp
cloud/filestore/libs/storage/init/actorsystem.cpp

This reverts commit c860035d23b4d11ceedfa44f043efa186eeb4577.

[Stable-23-3] Revert "NBS-4787: enable ydb configs_dispatcher service 

---

cloud/blockstore/libs/rdma/impl/server.cpp

(issue #291)
added a missed counter change

 NBS-4867: Errors in rdma metrics NBS-4867

---

cloud/disk_manager/internal/pkg/facade/private_service_nemesis_test/ya.make
cloud/disk_manager/test/recipe/__main__.py
cloud/disk_manager/test/recipe/disk_manager_launcher.py

Add minimum and maximum disk manager nemesis restart timeouts

[Disk Manager]: Tests: Increase nemesis restart timeout

---

cloud/tasks/logging/journald_tests/journald_logger_test.go

Broken in https://github.com/ydb-platform/nbs/pull/346

[Disk Manager] fix journald_logger_test after #346

---

.github/workflows/build_and_test_on_demand.yaml
.github/workflows/build_and_test_on_demand_cmake.yaml

Fixing this behaviour https://docs.github.com/en/actions/learn-github-actions/expressions#always

fix: move sleep to separate job and add correct condition to it

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/init/disk_agent/actorsystem.cpp
cloud/blockstore/libs/storage/init/server/actorsystem.cpp
cloud/blockstore/libs/storage/service/service_actor.h
cloud/blockstore/libs/storage/service/service_actor_actions.cpp
cloud/blockstore/libs/storage/service/service_actor_actions_get_nameservice_config.cpp
cloud/blockstore/libs/storage/service/ya.make
cloud/blockstore/private/api/protos/configs.proto
cloud/blockstore/private/api/protos/ya.make
cloud/blockstore/tests/client/canondata/result.json
cloud/blockstore/tests/client/canondata/test_with_client.test_configs_dispatcher/results.txt
cloud/blockstore/tests/client/canondata/test_with_client.test_disabled_configs_dispatcher/results.txt
cloud/blockstore/tests/client/canondata/test_with_client.test_enabled_configs_dispatcher/results.txt
cloud/blockstore/tests/client/test_with_client.py
cloud/blockstore/tests/client/ya.make
cloud/blockstore/tests/python/lib/nbs_runner.py
cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/init/actorsystem.cpp

Предлагаю влить пока так, с выключенным по дефолту configs dispatcher'ом. Когда договоримся с YDB о том, как будем включать его, то можно будет либо в коде включить, либо через конфиги при раскатке.

NBS-4787: test ydb configs dispatcher service

---

.github/workflows/pr.yaml

Add labels: blockstore, filestore, disk_manager, tasks to run tests from cloud/blockstore/, cloud/filestore/, cloud/disk_manager/ or cloud/tasks/ respectively

feature: add ability to run subset of tests based on labels

---

cloud/blockstore/libs/storage/service/service_actor_monitoring.cpp

NBS-4892: fix crash

---

cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp
cloud/storage/core/libs/actors/poison_pill_helper.cpp
cloud/storage/core/libs/actors/poison_pill_helper.h
cloud/storage/core/libs/actors/poison_pill_helper_ut.cpp
cloud/storage/core/libs/actors/ut/ya.make
cloud/storage/core/libs/actors/ya.make

Вынес логику про уничтожение дочерних акторов в отдельный класс.
Оно будет полезно и в других местах.

Introduce PoisonPill helper

---

cloud/blockstore/tools/testing/chaos-monkey/main.go
cloud/blockstore/tools/testing/chaos-monkey/nbs.go
cloud/blockstore/tools/testing/chaos-monkey/tests/canondata/result.json
cloud/blockstore/tools/testing/chaos-monkey/tests/canondata/tests.tests.TestFetchAnalyzeApply/test.golden
cloud/blockstore/tools/testing/chaos-monkey/tests/canondata/tests.tests.TestStateAnalysis/test.golden
cloud/blockstore/tools/testing/chaos-monkey/tests/canondata/tests.tests.TestStateAnalysisBreakDevice/test.golden
cloud/blockstore/tools/testing/chaos-monkey/tests/canondata/tests.tests.TestStateAnalysisBreakTwo/test.golden
cloud/blockstore/tools/testing/chaos-monkey/tests/canondata/tests.tests.TestStateAnalysisHealDevice/test.golden
cloud/blockstore/tools/testing/chaos-monkey/tests/canondata/tests.tests.TestStateAnalysisPreferFresh/test.golden
cloud/blockstore/tools/testing/chaos-monkey/tests/canondata/tests.tests.TestStateAnalysisPreferMinusOne/test.golden

Provide time and date in logs for more convenience

add date&time to chaos monkey logs

---

cloud/disk_manager/test/acceptance/test_runner/README.md
cloud/disk_manager/test/acceptance/test_runner/base_acceptance_test_runner.py

In golang part of the acceptance tests the uniqueness of disks was ensured using current timestamp and test type, which led to race condition between different test cases. Use the combination of disk-size, disk-blocksize and test type which is unique for our test runs.

[Disk Manager]: Test: Use per-disk suffix for acceptance tests

---

cloud/blockstore/libs/nbd/bench/main.cpp
cloud/blockstore/libs/nbd/server_handler.cpp
cloud/blockstore/libs/nbd/server_handler_ut.cpp

problem: nbd server didn't handle empty read/write/zero requests.
solution: support empty requests in nbd server and fill write requests in benchmark.

fix nbd/bench

---

cloud/blockstore/libs/rdma/impl/verbs.cpp

We need to empty the completion queue otherwise when using EWaitMode::Poll we
might not get additional notification on the event channel and the remaining
completions won't be consumed.

fix rdma completions polling

---

cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_secure_erase.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_state.cpp

Backport missing changes which were merged into stable during PR (#454) but not
into main

backport missing changes from PR (#454)

---

cloud/disk_manager/test/recipe/__main__.py
cloud/disk_manager/test/recipe/recipe.inc

Reconsider solution from https://github.com/ydb-platform/nbs/pull/359

[Disk Manager] use YDB from trunk if not OPENSOURCE

---

cloud/filestore/libs/storage/service/service_actor_readdata.cpp

issue-324: TServiceActor: fixing TReadDataActor leak

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_acquire.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_lifecycle.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_session.cpp

NBSNEBIUS-41: don't release NRD session on retriable errors

---

cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_counters.cpp

NBSNEBIUS-99: add per-fs MaxBlobsInRange/MaxDeletionsInRange counters
References #95

[Filestore] NBSNEBIUS-99: add counters for better introspective of data state (#466)

---

cloud/disk_manager/test/acceptance/test_runner/lib/disk_policy.py

[Disk Manager] fix typo in acceptance test disk policy

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_acquire.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_private.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_session.cpp
cloud/blockstore/libs/storage/disk_registry/testlib/test_env.h

* start acquiring a disk in place
* remove StartAcquireDisk private event
* remove StateFinish

NBSNEBIUS-41: simplify the process of acquiring a disk

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_acquire.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_private.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_session.cpp
cloud/blockstore/libs/storage/disk_registry/testlib/test_env.h

* NBSNEBIUS-41: don't release a NRD session on retriable errors

[merge to stable 23-3] NBSNEBIUS-41: don't release NRD session on retriable errors (#430)

---

cloud/blockstore/libs/storage/core/proto_helpers.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.h
cloud/blockstore/libs/storage/testlib/disk_registry_proxy_mock.h
cloud/blockstore/libs/storage/volume/volume_actor.cpp
cloud/blockstore/libs/storage/volume/volume_actor.h
cloud/blockstore/libs/storage/volume/volume_actor_forward.cpp
cloud/blockstore/libs/storage/volume/volume_actor_startstop.cpp
cloud/blockstore/libs/storage/volume/volume_ut_checkpoint.cpp

* NBS-4827 Prepare for shadow disk actor
* NBS-4827 fix review issues

NBS-4827 Prepare for shadow disk actor (#474)

---

cloud/filestore/libs/storage/api/tablet.h
cloud/filestore/libs/storage/service/service_actor.h
cloud/filestore/libs/storage/service/service_actor_actions.cpp
cloud/filestore/libs/storage/service/service_actor_actions_change_storage_config.cpp
cloud/filestore/libs/storage/service/service_actor_actions_describe_sessions.cpp
cloud/filestore/libs/storage/service/service_actor_actions_get_storage_config_fields.cpp
cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/service/ya.make
cloud/filestore/libs/storage/tablet/tablet_actor.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_request.cpp
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_sessions.cpp
cloud/filestore/private/api/protos/tablet.proto

issue-541: added DescribeSessions private api action

---

cloud/disk_manager/test/acceptance/test_runner/acceptance_test_runner.py
cloud/disk_manager/test/acceptance/test_runner/base_acceptance_test_runner.py
cloud/disk_manager/test/acceptance/test_runner/cleanup.py
cloud/disk_manager/test/acceptance/test_runner/lib/disk_policy.py
cloud/disk_manager/test/acceptance/test_runner/tests/test.py

In previous patches I have introduced a series of issue to disk manager acceptance tests. 
Fix most of them in a single PR.

[CI]: Fix acceptance tests issues 

---

cloud/blockstore/pylibs/common/helpers.py
cloud/blockstore/tools/ci/migration_test/lib/main.py
cloud/blockstore/tools/ci/migration_test/tests/canondata/result.json
cloud/blockstore/tools/ci/migration_test/tests/canondata/test.test_migration_test_locally_cluster1_/testing_out_stuff_results_locally.txt
cloud/blockstore/tools/ci/migration_test/tests/test.py

There is no ycp client on dev-lab so there is no way to run migration_test there. This PR makes it possible to run migration_test:
* locally on nbs-host (--run-locally arg) 
* in arbitrary zone (--zone arg)

Make migration test able to run locally

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_acquire.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_allocate.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_register.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_release.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_private.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_self_counters.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_self_counters.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_session.cpp
cloud/blockstore/libs/storage/disk_registry/testlib/test_env.cpp
cloud/blockstore/libs/storage/disk_registry/testlib/test_env.h

[stable-23-3] issue-499: Disk acquire cache in DR

---

.gitignore
cloud/filestore/libs/storage/service/service_actor_createsession.cpp
cloud/filestore/libs/storage/service/service_ut.cpp

issue-573: failed CreateSessionActors should stop working and should eventually be killed

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h

charry-pick of https://github.com/ydb-platform/nbs/commit/c16e85a7903b175071138409d5df63096e8e8e30
cherry-pick of https://github.com/ydb-platform/nbs/pull/603
---------

[merge to stable-23-3] Update placement groups view in monitoring (#603)

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
cloud/blockstore/libs/storage/disk_registry/model/agent_list.cpp
cloud/blockstore/libs/storage/disk_registry/model/agent_list.h

Cherry-pick of https://github.com/ydb-platform/nbs/pull/228
---------

[merge to stable-23-3] Show overridden AgentParams on monitoring page (#228)

---

cloud/blockstore/libs/storage/partition/part_actor_monitoring_check.cpp
cloud/blockstore/libs/storage/partition/part_actor_monitoring_describe.cpp
cloud/blockstore/libs/storage/partition/part_database.cpp
cloud/blockstore/libs/storage/partition/part_database.h
cloud/blockstore/libs/storage/partition/part_database_ut.cpp

Only DescribeBlob mon action was affected. This bug couldn't have caused any data corruptions.

issue-196: fixed DescribeBlob - using SkipMask in TPartDatabase::FindBlocksInBlobIndex, added a ut for FindBlocksInBlobsIndex

---

cloud/blockstore/libs/storage/partition/model/block.h
cloud/blockstore/libs/storage/partition/part_actor_monitoring_check.cpp
cloud/blockstore/libs/storage/partition/part_actor_monitoring_describe.cpp
cloud/blockstore/libs/storage/partition/part_database.cpp
cloud/blockstore/libs/storage/partition/part_database.h
cloud/blockstore/libs/storage/partition/part_database_ut.cpp
cloud/blockstore/libs/storage/partition/part_tx.h

issue-196: outputting block checksums upon DescribeBlob calls

---

cloud/blockstore/apps/client/lib/start_endpoint.cpp
cloud/blockstore/libs/endpoints/endpoint_manager.cpp
cloud/blockstore/libs/endpoints/ya.make
cloud/blockstore/libs/nbd/device.cpp
cloud/blockstore/public/api/protos/endpoints.proto
cloud/blockstore/tools/nbd/bootstrap.cpp

https://github.com/ydb-platform/nbs/issues/463

issues-463: start nbd-endpoint with a connected nbd-device

---

cloud/filestore/libs/storage/tablet/model/channels.cpp
cloud/filestore/libs/storage/tablet/model/channels.h
cloud/filestore/libs/storage/tablet/tablet_actor.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_channels.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_counters.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp
cloud/filestore/libs/storage/testlib/test_env.cpp
cloud/filestore/libs/storage/testlib/test_env.h

issue-679: channel count and reassign count sensors

---

cloud/blockstore/libs/storage/partition/part_actor_monitoring.cpp
cloud/blockstore/libs/storage/partition/ya.make
cloud/filestore/libs/storage/tablet/model/channels.cpp
cloud/filestore/libs/storage/tablet/model/channels.h
cloud/filestore/libs/storage/tablet/tablet_actor_monitoring.cpp
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_channels.cpp
cloud/filestore/libs/storage/tablet/ya.make
cloud/storage/core/libs/viewer/tablet_monitoring.cpp
cloud/storage/core/libs/viewer/tablet_monitoring.h
cloud/storage/core/libs/viewer/ya.make
cloud/storage/core/libs/ya.make

issue-679: extracted DumpChannels into cloud/storage/core/libs/viewer, using it to dump channel info on filestore tablet monpage

---

cloud/filestore/libs/storage/service/service_actor.h
cloud/filestore/libs/storage/service/service_actor_actions.cpp
cloud/filestore/libs/storage/service/service_actor_actions_reassign_tablet.cpp
cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/service/ya.make
cloud/filestore/private/api/protos/actions.proto

issue-679: implemented ReassignTablet private api action

---

cloud/storage/core/config/features.proto
cloud/storage/core/libs/features/CMakeLists.darwin-x86_64.txt
cloud/storage/core/libs/features/CMakeLists.linux-aarch64.txt
cloud/storage/core/libs/features/CMakeLists.linux-x86_64.txt
cloud/storage/core/libs/features/CMakeLists.windows-x86_64.txt
cloud/storage/core/libs/features/features_config.cpp
cloud/storage/core/libs/features/features_config.h
cloud/storage/core/libs/features/features_config_ut.cpp
cloud/storage/core/libs/features/filters.cpp
cloud/storage/core/libs/features/filters.h
cloud/storage/core/libs/features/ya.make

support both white and blacklist at the same time; issue-476

support both white and blacklist at the same time; issue-476

---

CONTRIBUTING.md

See https://github.com/ytsaurus/ytsaurus/commit/e2f301e0377cd94b19bf972d930429b1396c9c8a

Making CONTRIBUTING.md more similar to ytsaurus

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_acquire.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_init.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_release.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_ut.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_private.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_state.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_state.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_state_ut.cpp
cloud/blockstore/libs/storage/disk_agent/storage_initializer.cpp
cloud/blockstore/libs/storage/disk_agent/storage_initializer.h
cloud/blockstore/tests/storage_discovery/test.py

Ease deployment of the StorageDiscoveryConfig

---

CONTRIBUTING.md

See https://github.com/ytsaurus/ytsaurus/commit/341d720a42b37ffb34b9ded1a37e56640234c070

CONTRIBUTING.md: following the footsteps of YTsaurus and deleting the CLA completely

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_acquire.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_init.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_release.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_ut.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_private.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_state.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_state.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_state_ut.cpp
cloud/blockstore/libs/storage/disk_agent/storage_initializer.cpp
cloud/blockstore/libs/storage/disk_agent/storage_initializer.h
cloud/blockstore/tests/storage_discovery/test.py

[Stable-23-3] Ease deployment of the StorageDiscoveryConfig

---

cloud/filestore/libs/storage/tablet/rebase_logic_ut.cpp

issue-95: rebase logic ut

---

cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_util.h
cloud/blockstore/libs/storage/partition_nonrepl/resync_range.cpp
cloud/blockstore/libs/storage/partition_nonrepl/resync_range_ut.cpp

NBSNEBIUS-127: output proper replica indexes to log during resync

---

cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/tablet/model/compaction_map.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_compaction.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp

Running Compaction if there is too much garbage or too many blobs on average per 1 compaction range.
#95

issue-95: implemented average compaction thresholds

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp

* 733: Move "Reallocate" button into disk page in DR
* Print physical offset as a raw number

[Stable-23-3] 733: Move "Reallocate" button into disk page in DR (#737)

---

cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_monitoring.cpp
cloud/blockstore/libs/storage/disk_common/monitoring_utils.cpp
cloud/blockstore/libs/storage/disk_common/monitoring_utils.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp

* 733: render suspended and dirty states in DR monpage
* 733: review fixes
* 733: fix 2

[Stable-23-3] 733: render suspended and dirty states in DR monpage (#735)

---

cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/tablet/tablet_actor_compaction.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp

running Cleanup if there are too many DeletionMarkers on the whole FS
#95

issue-95: implemented average cleanup threshold

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp

Retry of https://github.com/ydb-platform/nbs/pull/755. Couldn't merge the PR due to github error.

issue-733: Render dirty and suspended devices on individual pages

---

cloud/blockstore/libs/storage/volume/testlib/test_env.cpp
cloud/blockstore/libs/storage/volume/testlib/test_env.h
cloud/blockstore/libs/storage/volume/volume_ut_checkpoint.cpp

NBS-4773 [Blockstore] Use NProto::ECheckpointType for checkpoint creation in tests

---

cloud/blockstore/libs/daemon/common/bootstrap.cpp
cloud/blockstore/libs/endpoints/endpoint_manager.cpp
cloud/blockstore/libs/endpoints/endpoint_manager.h
cloud/blockstore/libs/endpoints/endpoint_manager_ut.cpp
cloud/blockstore/libs/endpoints/service_endpoint_ut.cpp
cloud/blockstore/libs/nbd/device.cpp
cloud/blockstore/libs/nbd/device.h
cloud/blockstore/libs/nbd/public.h
cloud/blockstore/public/api/protos/endpoints.proto

Add flag UseFreeNbdDevice to StartEndpoint request. 
NBS gets first available nbd device and connects it to started nbd endpoint.

issue-463: start nbd-endpoint with any available nbd-device

---

cloud/blockstore/libs/storage/core/disk_counters.h
cloud/blockstore/libs/storage/partition/part_actor_confirmblobs.cpp

issue-122: add counter for ConfirmBlobs

---

cloud/blockstore/libs/storage/partition/part_actor_loadstate.cpp
cloud/blockstore/libs/storage/protos/part.proto
cloud/blockstore/libs/storage/volume/partition_requests.h

issue-356: cleanup after PR 786

---

cloud/blockstore/libs/storage/service/service_actor_actions_writable_state.cpp
cloud/blockstore/libs/storage/service/service_ut_actions.cpp
cloud/blockstore/private/api/protos/disk.proto

* make DiskRegistrySetWritableState request visible in private api
* remove unused include
* make conversion more explicit

make DiskRegistrySetWritableState request visible in private api (#778)

---

cloud/blockstore/tools/csi_driver/internal/driver/controller.go
cloud/blockstore/tools/csi_driver/internal/driver/node.go

https://github.com/ydb-platform/nbs/issues/782

NBSNEBIUS-85: introduce 'backend' field

---

cloud/blockstore/public/sdk/go/client/discovery.go
cloud/blockstore/public/sdk/go/client/durable.go
cloud/blockstore/public/sdk/go/client/grpc.go
cloud/blockstore/public/sdk/go/client/iface.go
cloud/blockstore/public/sdk/go/client/safe_client.go
cloud/blockstore/public/sdk/go/client/test_client.go
cloud/disk_manager/internal/pkg/clients/nbs/client.go
cloud/disk_manager/internal/pkg/clients/nbs/interface.go
cloud/disk_manager/internal/pkg/clients/nbs/mocks/client_mock.go

Divide [pr 754](https://github.com/ydb-platform/nbs/pull/754) into two separate parts: GetCheckpointStatus method introduction and functional enhancements for rapid NRD snapshots

NBS-4960 [Disk Manager] Add GetCheckpointStatus method to go clients

---

cloud/blockstore/libs/storage/disk_agent/actors/session_cache_actor.cpp
cloud/blockstore/libs/storage/disk_agent/actors/session_cache_actor.h
cloud/blockstore/libs/storage/disk_agent/actors/session_cache_actor_ut.cpp
cloud/blockstore/libs/storage/disk_agent/actors/ut/ya.make
cloud/blockstore/libs/storage/disk_agent/actors/ya.make
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_acquire.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_init.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_release.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_ut.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_private.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_state.cpp
cloud/blockstore/libs/storage/disk_agent/model/device_client.cpp
cloud/blockstore/libs/storage/disk_agent/model/device_client_ut.cpp

issue-170: sending responses to acquire/release requests w/o waiting for the cache update

---

cloud/blockstore/libs/storage/partition/part_state.cpp

issue-196: fixed incorrect assert

---

cloud/blockstore/config/server.proto
cloud/blockstore/libs/daemon/common/bootstrap.cpp
cloud/blockstore/libs/endpoints/endpoint_manager.cpp
cloud/blockstore/libs/server/config.cpp
cloud/blockstore/libs/server/config.h

https://github.com/ydb-platform/nbs/issues/463

issue-463: add nbdDevicePrefix to config

---

cloud/filestore/tests/loadtest/service-kikimr-newfeatures-test/nfs-storage.txt

issue-95: enabling average compaction and cleanup thresholds in the newfeatures suite

---

cloud/blockstore/public/sdk/go/client/request.go
cloud/disk_manager/internal/pkg/clients/nbs/session.go

https://github.com/ydb-platform/nbs/issues/831

#831: [Disk Manager] log blocks count on WriteBlocks request

---

cloud/blockstore/libs/storage/partition/part_actor_monitoring.cpp

Helps to detect if some write request is stuck or we forgot to decrement this counter

[Blockstore] output WriteAndZeroRequestsInProgress on partition mon-page

---

.githooks/pre-commit
VSCODE.md

Добавил простейший скрипт для проверки висящих пробелов.
Чтобы эта штука заработала, нужно чтобы каждый настроил себе гит такой командой:
```
git config core.hooksPath .githooks
```

Introduce git hooks

---

cloud/blockstore/public/sdk/go/client/safe_client.go

[Disk Manager] fix GetCheckpointStatus method

---

cloud/blockstore/libs/storage/volume/volume_ut.cpp

issue https://github.com/ydb-platform/nbs/issues/356

[Blockstore] fix ShouldHandleDescribeBlocksRequestForMultipartitionVolume test

---

cloud/tasks/storage/storage_ydb_test.go

Test for https://github.com/ydb-platform/nbs/pull/636

[Tasks] add test for #636

---

cloud/blockstore/libs/storage/service/service_events_private.h

* add missing constructor
* make explicit constructor

add missing constructor (#912)

---

cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/tablet/model/alloc.h
cloud/filestore/libs/storage/tablet/model/read_ahead.cpp
cloud/filestore/libs/storage/tablet/model/read_ahead.h
cloud/filestore/libs/storage/tablet/model/ya.make
cloud/filestore/libs/storage/tablet/tablet_actor_allocatedata.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_compaction.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_flush_bytes.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_readdata.cpp
cloud/filestore/libs/storage/tablet/tablet_state.cpp
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
cloud/filestore/libs/storage/tablet/tablet_state_impl.h
cloud/filestore/libs/storage/tablet/tablet_tx.h

This PR contains everything except the actual readahead strategy + caching strategy (TReadAheadCache is currently a stub). Will commit the implementation of TReadAheadCache + uts in the next PR.
#852

issue-852: tablet readahead stub

---

cloud/filestore/libs/storage/tablet/tablet_actor_monitoring.cpp

Fix YDB import build

---

cloud/blockstore/tests/plugin/uds/ya.make
cloud/blockstore/tests/python/lib/nbs_runner.py
cloud/blockstore/tests/python/lib/test_with_plugin.py

Use nbsd-lightweight in plugin tests

---

cloud/storage/core/libs/common/error.cpp
cloud/storage/core/libs/common/error_ut.cpp

* issue-924: make E_GRPC_UNIMPLEMENTED fatal
* use proper macro
* update
* update
* update
* update

issue-924: make E_GRPC_UNIMPLEMENTED fatal (#927)

---

cloud/blockstore/libs/nbd/device.cpp
cloud/blockstore/tools/nbd/bootstrap.cpp
cloud/blockstore/tools/nbd/bootstrap.h

blockstore-nbd tool has three mode of work. There were a few "if" in different methods in the code, and it was too difficult to read this code. So I moved this code to separated methods and replace "if" by "switch" in all places.

tweak blockstore-nbd

---

cloud/blockstore/tools/testing/eternal_tests/test_runner/lib/test_configs.py
cloud/blockstore/tools/testing/eternal_tests/test_runner/tests/canondata/test.test_eternal_load_test_case_all_ok_rerun-load-all-cluster1_/testing_out_stuff_results.txt

fix eternal local ssd v3 tests

---

cloud/blockstore/libs/storage/api/disk_registry_proxy.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_register.cpp
cloud/blockstore/libs/storage/disk_registry_proxy/disk_registry_proxy_actor.cpp
cloud/blockstore/libs/storage/disk_registry_proxy/disk_registry_proxy_ut.cpp

issue-885: fix for DA not registering sometimes

---

.github/scripts/manage-vm.py
.github/workflows/build_and_test_on_demand.yaml
.github/workflows/build_and_test_on_demand_cmake.yaml

also fixing possible collision with vm names

fix: better runner and vm labels and better vm names

---

cloud/filestore/libs/storage/model/range.h
cloud/filestore/libs/storage/tablet/model/read_ahead.cpp
cloud/filestore/libs/storage/tablet/model/read_ahead.h
cloud/filestore/libs/storage/tablet/model/read_ahead_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_readdata.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp

issue-852: readahead result filtration, fixes, tablet uts, cache uts

---

cloud/filestore/libs/storage/tablet/model/read_ahead.h
cloud/filestore/libs/storage/tablet/model/read_ahead_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_readdata.cpp
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp
cloud/filestore/libs/storage/testlib/tablet_client.h

issue-852: readahead cache counters

---

cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_checksumblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_readblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_readblocks_local.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_writeblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_zeroblocks.cpp

issue-885: more detailed logs when DA is unreachable

---

cloud/blockstore/config/notify.proto
cloud/blockstore/libs/daemon/ydb/bootstrap.cpp
cloud/blockstore/libs/notify/config.cpp
cloud/blockstore/libs/notify/config.h
cloud/blockstore/libs/notify/https.cpp
cloud/blockstore/libs/notify/https.h
cloud/blockstore/libs/notify/notify.cpp
cloud/blockstore/libs/notify/notify.h
cloud/blockstore/libs/notify/notify_ut.cpp
cloud/blockstore/libs/notify/ut/ya.make
cloud/blockstore/tools/testing/notify-mock/__main__.py

#932 notify update
notify now can use iam client to autorize

Issue-932 update notify (#939)

---

cloud/blockstore/apps/client/lib/resume_device.cpp
cloud/blockstore/libs/diagnostics/critical_events.h
cloud/blockstore/libs/service/request_helpers.h
cloud/blockstore/libs/service/request_helpers_inl.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_cms.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_resume_device.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_update_cms_device_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_private.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_cms.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_create.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_mirrored_disks.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_pending_cleanup.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_suspend.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_tx.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_pools.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_suspend.cpp
cloud/blockstore/libs/storage/disk_registry/testlib/test_env.h
cloud/blockstore/public/api/protos/disk.proto
cloud/blockstore/public/sdk/go/client/client_test.go
cloud/blockstore/public/sdk/go/client/safe_client.go
cloud/blockstore/public/sdk/python/client/safe_client.py
cloud/blockstore/public/sdk/python/client/ut/client_ut.py
cloud/blockstore/tests/external_endpoint/test.py
cloud/blockstore/tests/python_client/test.py
cloud/blockstore/tests/storage_discovery/test.py

[stable-23-3] ResumeDevice will add devices in DR

---

cloud/filestore/libs/storage/tablet/tablet_ut_data_stress.cpp
cloud/filestore/libs/storage/tablet/ut_stress/ya.make

this test keeps timing out under tsan

tweaking TIndexTabletTest_Data_Stress::ShouldTruncateAndAllocateFiles under tsan once again

---

cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_common.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_ut.cpp

Convert EIO to E_IO/E_IO_SILENT when handle errors in nonrepl partition

NEBDUTY-1084: handle EIO

---

cloud/blockstore/libs/storage/volume/model/checkpoint.cpp
cloud/blockstore/libs/storage/volume/model/checkpoint.h
cloud/blockstore/libs/storage/volume/model/checkpoint_ut.cpp
cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
cloud/blockstore/libs/storage/volume/volume_database_ut.cpp
cloud/blockstore/libs/storage/volume/volume_ut_checkpoint.cpp

Убрал не нужный drain для новых чекпонтов с теневыми дисками.

Skip drain for checkpoints with shadow disk

---

cloud/filestore/libs/storage/core/tablet_schema.h
cloud/filestore/libs/storage/init/actorsystem.cpp
cloud/filestore/libs/storage/tablet/tablet.cpp
cloud/filestore/libs/storage/tablet/tablet.h
cloud/filestore/libs/storage/tablet/tablet_actor.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_initschema.cpp
cloud/filestore/libs/storage/tablet/tablet_database.cpp
cloud/filestore/libs/storage/tablet/tablet_database.h
cloud/filestore/libs/storage/tablet/tablet_database_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_tx.h
cloud/filestore/libs/storage/testlib/test_env.cpp

issue-688: add (for now, unused) option to enforce usage of IndexTable compaction policy

---

cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_cleanup.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_collectgarbage.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_compaction.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_flush.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_flush_bytes.cpp
cloud/filestore/libs/storage/tablet/tablet_private.h
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
cloud/filestore/libs/storage/tablet/tablet_tx.h
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp

issue-95: implemented Count/RequestBytes/Time counters for background ops: Compaction/Cleanup/Flush/FlushBytes/TrimBytes/CollectGarbage

---

cloud/blockstore/apps/client/lib/command.cpp
cloud/blockstore/libs/endpoints/endpoint_manager.cpp
cloud/blockstore/libs/endpoints/session_manager.cpp
cloud/blockstore/libs/kms/iface/key_provider.cpp
cloud/blockstore/libs/service_local/storage_aio.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_monitoring.cpp
cloud/blockstore/libs/storage/disk_agent/model/config.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp
cloud/blockstore/libs/storage/partition/part_actor_monitoring_garbage.cpp
cloud/blockstore/libs/storage/partition/part_actor_readblob.cpp
cloud/blockstore/libs/storage/partition2/part2_actor_monitoring_garbage.cpp
cloud/blockstore/libs/storage/partition2/part2_actor_readblob.cpp
cloud/blockstore/libs/storage/partition2/part2_state.cpp
cloud/blockstore/libs/storage/partition_common/actor_describe_base_disk_blocks.cpp
cloud/blockstore/libs/storage/partition_common/actor_read_blob.cpp
cloud/blockstore/libs/storage/ss_proxy/ss_proxy_actor_createvolume.cpp
cloud/blockstore/libs/storage/ss_proxy/ss_proxy_actor_describevolume.cpp
cloud/blockstore/libs/storage/volume/model/client_state.cpp
cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp
cloud/blockstore/libs/storage/volume/volume_actor_startstop.cpp
cloud/blockstore/libs/validation/validation_client.cpp
cloud/storage/core/libs/coroutine/executor.h

Fixes of warnings from coverity

coverity 'Use of auto that causes a copy'

---

cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_fastpath_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_fastpath_actor.h

NBSNEBIUS-48, issue-980: make checksum and read requests in parallel during resync fast path

---

cloud/blockstore/libs/notify/https.cpp
cloud/blockstore/libs/notify/https.h
cloud/blockstore/libs/notify/notify.cpp
cloud/blockstore/libs/notify/notify.h

Fixes of errors from https://github.com/ydb-platform/nbs/pull/939
ticket [#932](https://github.com/ydb-platform/nbs/issues/932)

notify fixes

---

cloud/blockstore/apps/client/lib/command.cpp
cloud/blockstore/libs/endpoints/endpoint_manager.cpp
cloud/blockstore/libs/endpoints/session_manager.cpp
cloud/blockstore/libs/kms/iface/key_provider.cpp
cloud/blockstore/libs/service_local/storage_aio.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_monitoring.cpp
cloud/blockstore/libs/storage/disk_agent/model/config.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp
cloud/blockstore/libs/storage/partition/part_actor_monitoring_garbage.cpp
cloud/blockstore/libs/storage/partition/part_actor_readblob.cpp
cloud/blockstore/libs/storage/partition2/part2_actor_monitoring_garbage.cpp
cloud/blockstore/libs/storage/partition2/part2_actor_readblob.cpp
cloud/blockstore/libs/storage/partition2/part2_state.cpp
cloud/blockstore/libs/storage/partition_common/actor_describe_base_disk_blocks.cpp
cloud/blockstore/libs/storage/partition_common/actor_read_blob.cpp
cloud/blockstore/libs/storage/ss_proxy/ss_proxy_actor_createvolume.cpp
cloud/blockstore/libs/storage/ss_proxy/ss_proxy_actor_describevolume.cpp
cloud/blockstore/libs/storage/volume/model/client_state.cpp
cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp
cloud/blockstore/libs/storage/volume/volume_actor_startstop.cpp
cloud/blockstore/libs/validation/validation_client.cpp
cloud/storage/core/libs/coroutine/executor.h

This reverts commit 5e25719159e7ffcee81b821482267ae135b84f37.

Revert "coverity 'Use of auto that causes a copy' (#993)"

---

cloud/blockstore/libs/notify/https.cpp
cloud/blockstore/libs/notify/https.h
cloud/blockstore/libs/notify/notify.cpp
cloud/blockstore/libs/notify/notify.h

Fixes of errors from https://github.com/ydb-platform/nbs/pull/939
ticket https://github.com/ydb-platform/nbs/issues/932

(sync 23-3) notify fixes

---

cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/core/tablet_schema.h
cloud/filestore/libs/storage/init/actorsystem.cpp
cloud/filestore/libs/storage/service/service_actor_readdata.cpp
cloud/filestore/libs/storage/tablet/tablet.cpp
cloud/filestore/libs/storage/tablet/tablet.h
cloud/filestore/libs/storage/tablet/tablet_actor.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_initschema.cpp
cloud/filestore/libs/storage/tablet/tablet_database.cpp
cloud/filestore/libs/storage/tablet/tablet_database.h
cloud/filestore/libs/storage/tablet/tablet_database_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_schema.h
cloud/filestore/libs/storage/tablet/tablet_tx.h
cloud/filestore/libs/storage/testlib/test_env.cpp
cloud/filestore/tests/loadtest/service-kikimr-localdb-compaction-test/create-remove.txt
cloud/filestore/tests/loadtest/service-kikimr-localdb-compaction-test/read-write-validation.txt
cloud/filestore/tests/loadtest/service-kikimr-localdb-compaction-test/test.py
cloud/filestore/tests/loadtest/service-kikimr-localdb-compaction-test/ya.make
cloud/filestore/tests/loadtest/ya.make
cloud/filestore/tests/python/lib/daemon_config.py
cloud/filestore/tests/recipes/service-kikimr/__main__.py

b8b23596a6e735786d4757517e269011b4a02f96
37ac392d028e8bc3a12f7b8a2503cf2b0ca9c03a
af8d142b0cd158e7960751f5e8ad025ad3c1d618

[Filestore] merge to stable 23 3: compaction policy and memory leak fix for vhost-side read

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp
library/cpp/monlib/service/pages/templates.cpp
library/cpp/monlib/service/pages/templates.h

* Added checkbox to show only recently broken placements groups as broken
* removed unnecessary tags
---------

[merge to stable-23-3] Added checkbox to show only recently broken placements groups as broken (#1053)

---

cloud/blockstore/libs/storage/service/service_ut_destroy.cpp
cloud/blockstore/libs/storage/service/ut/ya.make

issue https://github.com/ydb-platform/nbs/issues/491

add test for overlay disk destroying when base disk is already destroyed

---

cloud/disk_manager/internal/pkg/services/pools/storage/storage_ydb_impl.go
cloud/disk_manager/internal/pkg/services/pools/storage/storage_ydb_test.go

https://github.com/ydb-platform/nbs/issues/1007

overlayDiskRebasedTx should be idempotent

---

cloud/disk_manager/internal/pkg/dataplane/nbs/target.go
cloud/disk_manager/internal/pkg/dataplane/replicate_disk_task.go

https://github.com/ydb-platform/nbs/issues/1097

[Disk Manager] fix data corruption in ReplicateDiskTask

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/partition_nonrepl/model/processing_blocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/model/processing_blocks.h
cloud/blockstore/libs/storage/partition_nonrepl/model/processing_blocks_ut.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_state.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_mirror.cpp
cloud/blockstore/libs/storage/volume/actors/shadow_disk_actor.cpp
cloud/blockstore/libs/storage/volume/actors/shadow_disk_actor.h
cloud/blockstore/libs/storage/volume/volume_ut.cpp
cloud/blockstore/libs/storage/volume/volume_ut_checkpoint.cpp

* Parallelize migration and shadow disk fill
* Fix review issues
* Fix review issues.
* Fix LOG priorities

Parallelize migration and shadow disk fill (#1096)

---

cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp
cloud/blockstore/libs/storage/volume/volume_actor_stats.cpp
cloud/blockstore/libs/storage/volume/volume_ut.cpp

* Calculating migration progress more accurately
* Make it better
* Fix review issue

Calculating migration progress more accurately (#1139)

---

cloud/blockstore/libs/diagnostics/profile_log.cpp
cloud/blockstore/libs/diagnostics/profile_log.h
cloud/blockstore/libs/storage/service/service_actor.h
cloud/blockstore/libs/storage/service/service_actor_actions.cpp
cloud/blockstore/libs/storage/service/service_actor_actions_flush_profile_log.cpp
cloud/blockstore/libs/storage/service/ya.make
cloud/blockstore/tests/client/test_with_client.py
cloud/blockstore/tests/python/lib/loadtest_env.py
cloud/blockstore/tests/python/lib/nbs_runner.py

При релизе NBS хочется не терять логи от NBS2

Add private API to flush profile log

---

cloud/tasks/persistence/s3.go

example 
https://github.com/aws/aws-sdk-go/blob/main/example/aws/request/customRetryer/custom_retryer.go

[Disk Manager] add logs on s3 client retries

---

cloud/filestore/libs/storage/perf/compaction_map.cpp
cloud/filestore/libs/storage/perf/ya.make
cloud/filestore/libs/storage/ya.make

add benchmark for compaction map

---

cloud/blockstore/libs/storage/partition/model/cleanup_queue.cpp
cloud/blockstore/libs/storage/partition/part_actor_compaction.cpp
cloud/blockstore/libs/storage/partition/part_ut.cpp

issue-1157: take cleanup blobs into account when cheking for compaction because of number of blobs per disk

---

cloud/blockstore/apps/endpoint_proxy/main.cpp
cloud/blockstore/apps/endpoint_proxy/ya.make
cloud/blockstore/apps/ya.make
cloud/blockstore/libs/endpoint_proxy/bootstrap.cpp
cloud/blockstore/libs/endpoint_proxy/bootstrap.h
cloud/blockstore/libs/endpoint_proxy/options.cpp
cloud/blockstore/libs/endpoint_proxy/options.h
cloud/blockstore/libs/endpoint_proxy/public.h
cloud/blockstore/libs/endpoint_proxy/server.cpp
cloud/blockstore/libs/endpoint_proxy/server.h
cloud/blockstore/libs/endpoint_proxy/ya.make
cloud/blockstore/libs/ya.make
cloud/blockstore/public/api/grpc/endpoint_proxy.proto
cloud/blockstore/public/api/grpc/ya.make
cloud/blockstore/public/api/protos/endpoints.proto

app, lib, grpc server, implementation stub
will add support for TBlockStoreEndpointProxy service to blockstore-client + integration test stub in the next PR
will make proper implementation + actual tests in the PR after the next one
#1164

issue-1164: endpoint_proxy stub

---

cloud/blockstore/libs/diagnostics/profile_log.cpp
cloud/blockstore/libs/diagnostics/profile_log.h
cloud/blockstore/libs/storage/service/CMakeLists.darwin-x86_64.txt
cloud/blockstore/libs/storage/service/CMakeLists.linux-aarch64.txt
cloud/blockstore/libs/storage/service/CMakeLists.linux-x86_64.txt
cloud/blockstore/libs/storage/service/CMakeLists.windows-x86_64.txt
cloud/blockstore/libs/storage/service/service_actor.h
cloud/blockstore/libs/storage/service/service_actor_actions.cpp
cloud/blockstore/libs/storage/service/service_actor_actions_flush_profile_log.cpp
cloud/blockstore/libs/storage/service/ya.make
cloud/blockstore/tests/client/test_with_client.py
cloud/blockstore/tests/python/lib/loadtest_env.py
cloud/blockstore/tests/python/lib/nbs_runner.py

Cherry pick of https://github.com/ydb-platform/nbs/pull/1106

[stable-23-3] Add private API to flush profile log

---

cloud/disk_manager/cmd/disk-manager/main.go
cloud/disk_manager/pkg/monitoring/metrics/prometheus.go
cloud/disk_manager/pkg/monitoring/metrics/prometheus_test.go
cloud/disk_manager/pkg/monitoring/metrics/tests/ya.make
cloud/disk_manager/pkg/monitoring/metrics/ya.make
cloud/disk_manager/pkg/monitoring/ya.make

Add prometheus metrics as an option

[Disk Manager]: Add prometheus monitoring to opensource main

---

cloud/disk_manager/internal/pkg/common/inflight_queue.go

https://github.com/ydb-platform/nbs/issues/612

issue-612 [Disk Manager] inflight queue: fix comments

---

cloud/blockstore/apps/client/lib/command.cpp
cloud/blockstore/apps/client/lib/command.h
cloud/blockstore/apps/client/lib/endpoint_proxy.cpp
cloud/blockstore/apps/client/lib/endpoint_proxy.h
cloud/blockstore/apps/client/lib/factory.cpp
cloud/blockstore/apps/client/lib/ya.make
cloud/blockstore/libs/endpoint_proxy/client/client.cpp
cloud/blockstore/libs/endpoint_proxy/client/client.h
cloud/blockstore/libs/endpoint_proxy/client/public.h
cloud/blockstore/libs/endpoint_proxy/client/ya.make
cloud/blockstore/libs/endpoint_proxy/server/bootstrap.h
cloud/blockstore/libs/endpoint_proxy/server/public.h
cloud/blockstore/libs/endpoint_proxy/server/server.cpp
cloud/blockstore/libs/endpoint_proxy/server/server.h

issue-1164: endpoint-proxy client lib + cmd

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/diagnostics/critical_events.h
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/core/disk_counters.h
cloud/blockstore/libs/storage/partition_nonrepl/CMakeLists.darwin-x86_64.txt
cloud/blockstore/libs/storage/partition_nonrepl/CMakeLists.linux-aarch64.txt
cloud/blockstore/libs/storage/partition_nonrepl/CMakeLists.linux-x86_64.txt
cloud/blockstore/libs/storage/partition_nonrepl/checksum_range.cpp
cloud/blockstore/libs/storage/partition_nonrepl/checksum_range.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_mirror.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_stats.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_util.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_state.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_state.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_events_private.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_checksumblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/resync_range.cpp
cloud/blockstore/libs/storage/partition_nonrepl/resync_range.h
cloud/blockstore/libs/storage/partition_nonrepl/ya.make

* add data scrubbing for mirrored disks
* fix issues
* add processing of write requests intersecting with scrubbing
* fix issues
* fix issues
* fix issues

Merge stable-23-3

---

cloud/blockstore/apps/client/lib/endpoint_proxy.cpp
cloud/blockstore/apps/endpoint_proxy/ya.make
cloud/blockstore/libs/endpoint_proxy/server/server.cpp
cloud/blockstore/public/api/protos/endpoints.proto
cloud/blockstore/tests/client/canondata/result.json
cloud/blockstore/tests/client/canondata/test_with_client.test_endpoint_proxy/results.txt
cloud/blockstore/tests/client/test_with_client.py
cloud/blockstore/tests/client/ya.make

issue-1164: endpoint-proxy - test stub + minor tweaks

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/common/iovector.cpp
cloud/blockstore/libs/common/iovector.h
cloud/blockstore/libs/common/iovector_ut.cpp
cloud/blockstore/libs/service/storage.cpp
cloud/blockstore/libs/service/storage.h
cloud/blockstore/libs/service/storage_test.h
cloud/blockstore/libs/service/storage_ut.cpp
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_state.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_readblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_readblocks_local.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_ut.cpp
cloud/blockstore/libs/storage/testlib/disk_agent_mock.h
cloud/blockstore/public/api/protos/headers.proto

Поверх этого ПРа:
1. Бенчмарк https://github.com/ydb-platform/nbs/pull/1172
2. Статистика со стороны NBS https://github.com/ydb-platform/nbs/pull/1173
3. Замена write на zero  blocks при миграции https://github.com/ydb-platform/nbs/pull/1174

Optimize void buffers transfer

---

cloud/blockstore/libs/storage/partition/model/cleanup_queue.cpp
cloud/blockstore/libs/storage/partition/model/cleanup_queue.h
cloud/blockstore/libs/storage/partition/model/cleanup_queue_ut.cpp
cloud/blockstore/libs/storage/partition/part_actor_compaction.cpp
cloud/blockstore/libs/storage/partition/part_state.cpp
cloud/blockstore/libs/storage/partition/part_state_ut.cpp
cloud/blockstore/libs/storage/partition/part_ut.cpp

issue-1157: subtract blocks waiting for cleanup from disk garbage blocks counters

---

cloud/tasks/tasks_tests/.gitignore
cloud/tasks/tasks_tests/tasks_test.go

https://github.com/ydb-platform/nbs/issues/1035

[Tasks] fix TestTasksSendEvent test; add gitignore file

---

cloud/blockstore/apps/client/lib/command.cpp
cloud/blockstore/libs/endpoint_proxy/client/client.cpp
cloud/blockstore/libs/endpoint_proxy/client/client.h
cloud/blockstore/libs/endpoint_proxy/server/server.cpp

issue-1164: endpoint-proxy client retry policy

---

cloud/disk_manager/internal/pkg/configs/server/config/config.proto
cloud/disk_manager/pkg/app/run.go

[Disk Manager] add feature for disabling memory locking (currently we are facing crashes on start inside containers)

---

.github/workflows/build_and_test_cmake.yaml
.github/workflows/build_and_test_on_demand.yaml
.github/workflows/build_and_test_on_demand_cmake.yaml
.github/workflows/build_and_test_ya.yaml
.github/workflows/github_actions_scripts.yaml

Fixes `Committer identity unknown` error on rebase

fix: yet another rebase label fix

---

cloud/blockstore/libs/storage/volume/volume_actor.cpp
cloud/blockstore/libs/storage/volume/volume_actor.h
cloud/blockstore/libs/storage/volume/volume_actor_cleanup_history.cpp
cloud/blockstore/libs/storage/volume/volume_ut_stats.cpp

#1180 
Make volume hostory cleanup to run every time TEvUpdateCounters comes

issue-1180: run history cleanup on every TEvUpdateCounters

---

cloud/filestore/tests/build_arcadia_test/coreutils.py

Need for update flake8 in Arcadia

Fix flake8 checks

---

cloud/blockstore/libs/storage/volume/volume_state.cpp
cloud/blockstore/libs/storage/volume/volume_state_ut.cpp
cloud/blockstore/libs/storage/volume/volume_ut_stats.cpp

issue-1180: fix cleanup condition for cached history

---

cloud/blockstore/libs/storage/volume/volume_state.cpp
cloud/blockstore/libs/storage/volume/volume_state_ut.cpp

* issue-1180: fix cleanup condition for cached history
* update
* update

issue-1180: fix cleanup condition for cached history (#1224)

---

cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_readblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_readblocks_local.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_writeblocks.cpp

Небольшой рефакторинг кода про RDMA. 
В поведении ничего не меняется

Make rdma code better #1

---

cloud/disk_manager/internal/pkg/dataplane/url/formats.go
cloud/disk_manager/internal/pkg/dataplane/url/qcow2/image_map_reader.go
cloud/disk_manager/internal/pkg/dataplane/url/qcow2/tests/qcow2_test.go
cloud/disk_manager/internal/pkg/dataplane/url/source.go
cloud/disk_manager/internal/pkg/dataplane/url/vhd/footer.go
cloud/disk_manager/internal/pkg/dataplane/url/vhd/image_map_reader.go
cloud/disk_manager/internal/pkg/dataplane/url/vhd/tests/vhd_test.go
cloud/disk_manager/internal/pkg/dataplane/url/vmdk/image_map_reader.go
cloud/disk_manager/internal/pkg/dataplane/url/vmdk/tests/vmdk_test.go

https://github.com/ydb-platform/nbs/issues/498

[Disk Manager] refactor packages related to work with images

---

cloud/blockstore/apps/client/lib/endpoint_proxy.cpp
cloud/blockstore/apps/client/lib/endpoint_proxy.h
cloud/blockstore/apps/client/lib/factory.cpp
cloud/blockstore/libs/endpoint_proxy/client/client.cpp
cloud/blockstore/libs/endpoint_proxy/client/client.h
cloud/blockstore/libs/endpoint_proxy/server/server.cpp
cloud/blockstore/public/api/grpc/endpoint_proxy.proto
cloud/blockstore/public/api/protos/endpoints.proto
cloud/blockstore/tests/client/canondata/test_with_client.test_endpoint_proxy/results.txt
cloud/blockstore/tests/client/test_with_client.py

Endpoint listing + a couple of minor fixes after https://github.com/ydb-platform/nbs/pull/1220
#1164

issue-1164: ListProxyEndpoints method for endpoint proxy

---

cloud/blockstore/libs/endpoint_proxy/client/device_factory.cpp
cloud/blockstore/libs/endpoint_proxy/client/device_factory.h
cloud/blockstore/libs/endpoint_proxy/client/device_factory_ut.cpp
cloud/blockstore/libs/endpoint_proxy/client/ut/ya.make
cloud/blockstore/libs/endpoint_proxy/client/ya.make
cloud/blockstore/libs/endpoint_proxy/server/server.cpp
cloud/blockstore/libs/endpoints/endpoint_manager.cpp
cloud/blockstore/libs/endpoints/endpoint_manager_ut.cpp
cloud/blockstore/libs/nbd/device.cpp
cloud/blockstore/libs/nbd/device.h

issue-1164: proxy device connection factory

---

cloud/disk_manager/internal/pkg/monitoring/metrics/buckets.go
cloud/disk_manager/internal/pkg/monitoring/metrics/empty.go
cloud/disk_manager/internal/pkg/monitoring/metrics/interface.go
cloud/disk_manager/pkg/monitoring/metrics/prometheus.go
cloud/disk_manager/pkg/monitoring/metrics/registry_wrapper.go
cloud/disk_manager/pkg/monitoring/metrics/ya.make
cloud/tasks/acceptance_tests/recipe/init-db/main.go
cloud/tasks/acceptance_tests/recipe/node/main.go
cloud/tasks/acceptance_tests/tasks_acceptance_test.go
cloud/tasks/metrics/buckets.go
cloud/tasks/metrics/buckets_test.go
cloud/tasks/metrics/empty/counter.go
cloud/tasks/metrics/empty/gauge.go
cloud/tasks/metrics/empty/histogram.go
cloud/tasks/metrics/empty/int_gauge.go
cloud/tasks/metrics/empty/registry.go
cloud/tasks/metrics/empty/timer.go
cloud/tasks/metrics/empty/ya.make
cloud/tasks/metrics/metrics.go
cloud/tasks/metrics/mocks/metrics_mock.go
cloud/tasks/metrics/ya.make
cloud/tasks/persistence/ydb_test.go
cloud/tasks/scheduler_test.go
cloud/tasks/storage/compound_storage.go
cloud/tasks/storage/storage_ydb_test.go
cloud/tasks/tasks_tests/tasks_test.go

issue-1246: cloud/tasks should not depend on library/go/core/metrics

---

cloud/blockstore/apps/client/lib/backup_volume.cpp
cloud/blockstore/libs/endpoints/endpoint_manager.cpp
cloud/blockstore/libs/endpoints/session_manager.cpp
cloud/blockstore/libs/kms/iface/key_provider.cpp
cloud/blockstore/libs/nbd/utils.cpp
cloud/blockstore/libs/service_local/storage_aio.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_monitoring.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp
cloud/blockstore/libs/storage/partition/part_actor_monitoring_garbage.cpp
cloud/blockstore/libs/storage/partition/part_actor_readblob.cpp
cloud/blockstore/libs/storage/partition2/part2_actor_monitoring_garbage.cpp
cloud/blockstore/libs/storage/partition2/part2_actor_readblob.cpp
cloud/blockstore/libs/storage/partition2/part2_state.cpp
cloud/blockstore/libs/storage/partition_common/actor_describe_base_disk_blocks.cpp
cloud/blockstore/libs/storage/partition_common/actor_read_blob.cpp
cloud/blockstore/libs/storage/ss_proxy/ss_proxy_actor_createvolume.cpp
cloud/blockstore/libs/storage/ss_proxy/ss_proxy_actor_describevolume.cpp
cloud/blockstore/libs/storage/volume/model/client_state.cpp
cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp
cloud/blockstore/libs/storage/volume/volume_actor_startstop.cpp
cloud/blockstore/tools/nbd/bootstrap.cpp
cloud/vm/blockstore/lib/plugin.cpp

* NBS-4870: fix auto ref in iface/client (stat.analysis)
* NBS-4806: fix 'Use of auto that causes a copy' (stat. analysis)
* NBS-4722: fix 'Use of auto that causes a copy'
* NBS-4699: 'Use of auto that causes a copy'
* NBS:4764  'Use of auto that causes a copy'

coverity 'Use of auto that causes a copy' (#993)

---

cloud/blockstore/libs/storage/volume_proxy/volume_proxy_ut.cpp
cloud/filestore/libs/storage/tablet_proxy/tablet_proxy_ut.cpp

main branch in git is not equal to arcadia trunk whick has a lot of changes in test actor system, so this pr fixes tests to work both in main and trunk

fix tests in arcadia trunk

---

cloud/disk_manager/internal/pkg/facade/disk_service_test/disk_relocation_test.go
cloud/disk_manager/internal/pkg/services/pools/storage/storage_ydb_impl.go
cloud/disk_manager/internal/pkg/services/pools/storage/storage_ydb_test.go

https://github.com/ydb-platform/nbs/issues/1306

[Disk Manager] prohibit to acquire target units if base disk is not from pool in relocation

---

doc/REPOSITORY_STRUCTURE.md

Will describe cloud/{blockstore,filestore,disk_manager,vm} in the upcoming PRs

Initial REPOSITORY_STRUCTURE.md document - describes util, library, contrib, cloud/storage/core

---

cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp

issue-1146: fix `NodeIndexCacheNodeCount` sensor type

---

cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_state.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_state.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_state_ut.cpp

https://github.com/ydb-platform/nbs/issues/1067

Fix migration order

---

cloud/filestore/tests/loadtest/service-kikimr-newfeatures-test/get-node-attr.txt
cloud/filestore/tests/loadtest/service-kikimr-newfeatures-test/nfs-storage.txt
cloud/filestore/tests/loadtest/service-kikimr-newfeatures-test/test.py
cloud/filestore/tests/loadtest/service-kikimr-test/get-node-attr.txt
cloud/filestore/tests/loadtest/service-kikimr-test/test.py
cloud/filestore/tools/testing/loadtest/lib/request_index.cpp
cloud/filestore/tools/testing/loadtest/protos/loadtest.proto

issue-1146: add getnodeattr loadtest for both `service-kikimr-test` and `service-kikimr-newfeatures-test`

---

cloud/blockstore/libs/endpoint_proxy/server/CMakeLists.txt
cloud/blockstore/libs/endpoint_proxy/server/proxy_storage.cpp
cloud/blockstore/libs/endpoint_proxy/server/proxy_storage.h
cloud/blockstore/libs/endpoint_proxy/server/proxy_storage_ut.cpp
cloud/blockstore/libs/endpoint_proxy/server/server.cpp
cloud/blockstore/libs/endpoint_proxy/server/ut/CMakeLists.txt
cloud/blockstore/libs/endpoint_proxy/server/ut/ya.make
cloud/blockstore/libs/endpoint_proxy/server/ya.make
cloud/blockstore/public/api/protos/endpoints.proto
cloud/blockstore/tests/client/canondata/test_with_client.test_endpoint_proxy/results.txt
cloud/blockstore/tests/client/canondata/test_with_client.test_endpoint_proxy_uds/results.txt
cloud/filestore/libs/endpoint/service.cpp
cloud/filestore/libs/storage/tablet/model/fresh_bytes.cpp
cloud/filestore/libs/storage/tablet/model/fresh_bytes.h
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_flush_bytes.cpp
cloud/filestore/libs/storage/tablet/tablet_counters.h
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
cloud/filestore/libs/storage/tablet/tablet_tx.h
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp
cloud/filestore/libs/storage/testlib/tablet_client.h
cloud/filestore/private/api/protos/tablet.proto
cloud/storage/core/libs/common/error.h
cloud/storage/core/libs/diagnostics/request_counters.cpp

https://github.com/ydb-platform/nbs/commit/34af57fb424c1cc7dbfaa2ef609cc70009f8a621
https://github.com/ydb-platform/nbs/commit/19a701f6a8c59e696b2fe6c88f9eab459cd719ff
https://github.com/ydb-platform/nbs/commit/c771d1a54533971539f7b74fef43675afb5871d7

merge to stable-23-3: filestore fixes (vhost shutdown race, DeletedFreshBytesCount inconsistency), blockstore-endpoint-proxy metrics

---

cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/tablet/tablet_actor_createsession.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_sessions.cpp
cloud/filestore/libs/vfs_fuse/loop.cpp
cloud/filestore/tests/loadtest/service-kikimr-newfeatures-test/nfs-storage.txt

c6740812f7fbea1c807e234eefd3175d4034343d

(merge-to-stable) [Filestore] issue-1289: rework ExtendedBlockSizeEnabled flag + increase vhost-side logging (#1402)

---

cloud/blockstore/libs/diagnostics/critical_events.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_cms.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_mirrored_disks.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_pools.cpp
cloud/blockstore/libs/storage/disk_registry/model/agent_list.cpp
cloud/blockstore/libs/storage/disk_registry/model/agent_list.h
cloud/blockstore/libs/storage/disk_registry/model/agent_list_ut.cpp
cloud/blockstore/libs/storage/disk_registry/model/device_list.cpp
cloud/blockstore/libs/storage/disk_registry/model/device_list.h
cloud/blockstore/libs/storage/disk_registry/model/device_list_ut.cpp
cloud/blockstore/libs/storage/disk_registry/model/replica_table_ut.cpp

merge to stable 23-3

---

cloud/blockstore/config/disk.proto
cloud/blockstore/libs/storage/api/disk_registry_proxy.h
cloud/blockstore/libs/storage/disk_registry_proxy/disk_registry_proxy_actor.cpp
cloud/blockstore/libs/storage/disk_registry_proxy/disk_registry_proxy_actor.h
cloud/blockstore/libs/storage/disk_registry_proxy/disk_registry_proxy_actor_create.cpp
cloud/blockstore/libs/storage/disk_registry_proxy/disk_registry_proxy_private.h
cloud/blockstore/libs/storage/disk_registry_proxy/disk_registry_proxy_ut.cpp
cloud/blockstore/libs/storage/disk_registry_proxy/model/config.cpp
cloud/blockstore/libs/storage/disk_registry_proxy/model/config.h
cloud/storage/core/libs/hive_proxy/hive_proxy_actor.cpp
cloud/storage/core/libs/hive_proxy/hive_proxy_ut.cpp

Make possible to get DR tablet id from config

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/core/disk_counters.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_mirror.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_stats.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp

retry scrubbing for 5 minutes before reporting checksum mismatch

---

cloud/blockstore/libs/storage/volume/model/checkpoint.cpp
cloud/blockstore/libs/storage/volume/model/checkpoint_ut.cpp
cloud/blockstore/libs/storage/volume/volume_ut_checkpoint.cpp

Fix of https://github.com/ydb-platform/nbs/pull/1134

[nbs] delete checkpoint successfully even if it never existed

---

cloud/blockstore/libs/storage/volume/model/checkpoint.cpp
cloud/blockstore/libs/storage/volume/model/checkpoint_ut.cpp
cloud/blockstore/libs/storage/volume/volume_ut_checkpoint.cpp

* [nbs] delete checkpoint successfully even if it never existed
* fix
* fix

[nbs] delete checkpoint successfully even if it never existed (#1411)

---

cloud/blockstore/config/server.proto
cloud/blockstore/libs/daemon/common/bootstrap.cpp
cloud/blockstore/libs/endpoints/endpoint_manager.cpp
cloud/blockstore/libs/endpoints/service_endpoint_ut.cpp
cloud/blockstore/libs/server/config.cpp
cloud/blockstore/libs/server/config.h
cloud/blockstore/libs/storage/volume/volume_actor_stats.cpp
cloud/blockstore/libs/storage/volume/volume_ut_stats.cpp
cloud/filestore/config/vhost.proto
cloud/filestore/libs/daemon/vhost/bootstrap.cpp
cloud/filestore/libs/endpoint/service.cpp
cloud/filestore/libs/endpoint_vhost/config.cpp
cloud/filestore/libs/endpoint_vhost/config.h
cloud/storage/core/libs/keyring/endpoints.cpp
cloud/storage/core/libs/keyring/endpoints.h
cloud/storage/core/libs/keyring/endpoints_ut.cpp

https://github.com/ydb-platform/nbs/commit/fa384e7494e872f5ebaf5b05b0f652b50b40111d
https://github.com/ydb-platform/nbs/commit/60e9fa90676750b004b70a540058e3b32af43b55

merge to stable-23-3: BytesCount fix; minor EndpointStorage logging fix; 

---

cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp

fix asan & tsan error

---

cloud/blockstore/config/ydbstats.proto
cloud/blockstore/libs/daemon/ydb/bootstrap.cpp
cloud/blockstore/libs/ydbstats/config.cpp
cloud/blockstore/libs/ydbstats/config.h
cloud/blockstore/libs/ydbstats/ydbscheme.cpp
cloud/blockstore/libs/ydbstats/ydbscheme.h
cloud/blockstore/libs/ydbstats/ydbstats.cpp
cloud/blockstore/libs/ydbstats/ydbstats_ut.cpp
cloud/blockstore/libs/ydbstats/ydbstorage.cpp
cloud/blockstore/libs/ydbstats/ydbstorage.h

* configure ttl for stat and archive stats ydb tables
* update

configure ttl for stat and archive stats ydb tables (#1400)

---

cloud/blockstore/libs/endpoint_proxy/client/device_factory.cpp
cloud/blockstore/libs/endpoint_proxy/client/device_factory_ut.cpp
cloud/blockstore/libs/endpoints/endpoint_manager.cpp
cloud/blockstore/libs/nbd/device.cpp
cloud/blockstore/libs/nbd/device.h

issue-1164: NBD::IDevice::{Start,Stop} should return futures

---

cloud/blockstore/libs/endpoint_proxy/client/device_factory.cpp
cloud/blockstore/libs/endpoint_proxy/client/device_factory_ut.cpp
cloud/blockstore/libs/endpoints/endpoint_manager.cpp
cloud/blockstore/libs/nbd/device.cpp
cloud/blockstore/libs/nbd/device.h

* issue-1164: NBD::IDevice::{Start,Stop} should return futures
* issue-1164: ProxyDevice should not call StopProxyEndpoint if deleteDevice == false
* issue-1164: fix build

issue-1164: NBD::IDevice::{Start,Stop} should return futures (#1428)

---

cloud/disk_manager/internal/pkg/services/pools/storage/consistency_check.go
cloud/disk_manager/internal/pkg/services/pools/storage/mocks/storage_mock.go
cloud/disk_manager/internal/pkg/services/pools/storage/storage.go
cloud/disk_manager/internal/pkg/services/pools/storage/storage_ydb.go
cloud/disk_manager/pkg/admin/common.go
cloud/disk_manager/pkg/admin/consistency_check.go
cloud/disk_manager/pkg/admin/pools.go
cloud/disk_manager/pkg/admin/run.go
cloud/disk_manager/pkg/admin/ya.make

https://github.com/ydb-platform/nbs/issues/1306

[Disk Manager] add commands for checking pools consistency to admin tool

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp

count scrubbing bandwidth according to disk size

---

cloud/blockstore/libs/common/iovector.cpp

```
cloud/blockstore/libs/common/ut <unittest> [tags: sb:MULTISLOT, sb:cores=4, sb:logs_ttl=3, sb:ssd, sb:ttl=3]
17 tests: 16 - GOOD, 1 - CRASHED
------ sole chunk ran 32 tests
[fail] TIOVectorTest::ShouldTrimVoidBuffers [tags: sb:MULTISLOT, sb:cores=4, sb:logs_ttl=3, sb:ssd, sb:ttl=3] [default-linux-x86_64-release-usan] (0.00s)
Test crashed (return code: 100)
/place/sandbox-data/tasks/7/5/2385368357/__FUSE/mount_path_79f41383-a47d-4688-851e-0f48ebe70820/cloud/blockstore/libs/common/iovector.cpp:183:9: runtime error: load of misaligned address 0x000003e17019 for type 'const TBigNumber' (aka 'const unsigned int'), which requires 4 byte alignment
0x000003e17019: note: pointer points here
00 00 00  10 00 00 00 00 00 00 00  00 00 55 45 53 54 45 44  00 5d e1 03 00 00 00 00  30 00 00 00 00
^ …
```

Fix unaligned memory access

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/service/service_actor_destroy.cpp
cloud/blockstore/libs/storage/service/service_ut_destroy.cpp
cloud/blockstore/libs/storage/service/ut/CMakeLists.darwin-x86_64.txt
cloud/blockstore/libs/storage/service/ut/CMakeLists.linux-aarch64.txt
cloud/blockstore/libs/storage/service/ut/CMakeLists.linux-x86_64.txt
cloud/blockstore/libs/storage/service/ut/CMakeLists.windows-x86_64.txt
cloud/blockstore/libs/storage/service/ut/ya.make

* Added DisableDiskWithCloudIdDestruction option
---------

[merge to stable-23-3] Added DisableDiskWithCloudIdDestruction

---

cloud/disk_manager/internal/pkg/services/snapshots/create_snapshot_from_disk_task.go

https://github.com/ydb-platform/nbs/issues/1461

[Disk Manager] suppport incremental snapshots for DR based disks

---

cloud/disk_manager/pkg/admin/disks.go
cloud/disk_manager/pkg/admin/filesystem.go

This reverts commit f26e87c67ec50b44480a73d28a28e9bd82a9ceae.

Revert "[Disk Manager] admin tool may not pass cloud-id param to create/delete requests (folder-id is enough) (#1452)"

---

cloud/blockstore/tests/local_ssd/test.py

Minor tweak: more info in asserts

NEBDUTY-1543: tweak tests/local_ssd

---

cloud/blockstore/libs/endpoints_grpc/socket_endpoint_listener_ut.cpp

Start and Stop are async calls which don't return futures so unfortunately we need to use Sleeps in tests. Added more sleep iterations, using better assert variations, stopping endpoints upon test failure to avoid asan leak reports.

stabilizing endpoints_grpc/ut::ShouldHandleClientDisconnection

---

cloud/disk_manager/internal/pkg/services/pools/storage/consistency_check.go

https://github.com/ydb-platform/nbs/issues/1306

[DIsk Manager] fix: use scan query for pools listing

---

cloud/blockstore/public/sdk/go/client/discovery.go
cloud/blockstore/public/sdk/go/client/durable.go
cloud/blockstore/public/sdk/go/client/grpc.go
cloud/blockstore/public/sdk/go/client/iface.go
cloud/blockstore/public/sdk/go/client/safe_client.go
cloud/blockstore/public/sdk/go/client/test_client.go
cloud/blockstore/public/sdk/python/client/base_client.py
cloud/blockstore/public/sdk/python/client/safe_client.py
cloud/blockstore/public/sdk/python/client/ut/client_ut.py
cloud/blockstore/tests/python_client/test.py
cloud/blockstore/tools/csi_driver/internal/driver/mocks/nbs_client_mock.go

Issue: https://github.com/ydb-platform/nbs/issues/1320

issue-1320: add QueryAgentsInfo to go/python clients

---

cloud/blockstore/libs/client/durable.cpp
cloud/blockstore/libs/client/session.cpp
cloud/blockstore/libs/diagnostics/request_stats.cpp
cloud/blockstore/libs/diagnostics/request_stats_ut.cpp
cloud/blockstore/libs/diagnostics/volume_stats.cpp
cloud/blockstore/libs/diagnostics/volume_stats.h
cloud/blockstore/libs/diagnostics/volume_stats_test.h
cloud/blockstore/libs/storage/volume_balancer/volume_balancer_ut.cpp

* Fix wrong media kind usage
* Test ShouldNotTrackRequestsForDefaultMediaKindAsHdd

Stable-23-3. Fix wrong media kind usage (#1465)

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/service/service_actor_destroy.cpp
cloud/blockstore/libs/storage/service/service_ut_destroy.cpp

Rework of https://github.com/ydb-platform/nbs/pull/1454

Add ability to destroy only those disks whose ids match a specific prefix

---

cloud/filestore/libs/storage/tablet/tablet_actor_compaction.cpp

remove compaction map range if foundnthat  o blobs are referncing it during compaction

---

cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_destroysession.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_unlinknode.cpp
cloud/filestore/libs/storage/tablet/tablet_private.h
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_nodes.cpp
cloud/filestore/libs/storage/tablet/tablet_tx.h
cloud/filestore/libs/storage/testlib/service_client.h

issue-1350: implementing multitablet fs TODOs - DestroySession in followers, UnlinkNode

---

cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp

issue-1519: add some tests that `AddData` changes the inode size

---

cloud/filestore/libs/diagnostics/critical_events.h
cloud/filestore/libs/storage/service/service_actor_listnodes.cpp
cloud/filestore/libs/storage/service/service_ut.cpp

issue-1350: we shouldn't fail the whole ListNodes request in case we somehow (due to bugs) lose some of the files in followers

---

cloud/blockstore/libs/storage/api/disk_agent.h
cloud/blockstore/libs/storage/disk_agent/CMakeLists.darwin-x86_64.txt
cloud/blockstore/libs/storage/disk_agent/CMakeLists.linux-aarch64.txt
cloud/blockstore/libs/storage/disk_agent/CMakeLists.linux-x86_64.txt
cloud/blockstore/libs/storage/disk_agent/CMakeLists.windows-x86_64.txt
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_partial_suspend.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_register.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_ut.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_private.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_state.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_state.h
cloud/blockstore/libs/storage/disk_agent/testlib/test_env.h
cloud/blockstore/libs/storage/disk_agent/ya.make
cloud/blockstore/libs/storage/protos/disk.proto
cloud/blockstore/libs/storage/service/CMakeLists.darwin-x86_64.txt
cloud/blockstore/libs/storage/service/CMakeLists.linux-aarch64.txt
cloud/blockstore/libs/storage/service/CMakeLists.linux-x86_64.txt
cloud/blockstore/libs/storage/service/CMakeLists.windows-x86_64.txt
cloud/blockstore/libs/storage/service/service_actor.h
cloud/blockstore/libs/storage/service/service_actor_actions.cpp
cloud/blockstore/libs/storage/service/service_actor_actions_suspend_disk_agent.cpp
cloud/blockstore/libs/storage/service/ya.make
cloud/blockstore/tests/client/test_with_client.py
cloud/blockstore/tests/client/test_with_multiple_agents.py
cloud/blockstore/tests/python/lib/client.py
cloud/blockstore/tests/python/lib/disk_agent_runner.py
cloud/blockstore/tests/python/lib/nonreplicated_setup.py
cloud/blockstore/tests/python/lib/test_base.py

Related to issue https://github.com/ydb-platform/nbs/issues/1502

[stable-23-3] blockstore-client API to suspend disk agent

---

cloud/blockstore/libs/storage/disk_registry/actors/restore_validator_actor.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_backup_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_loadstate.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_restore_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_database.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_database.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_database_ut.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_private.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_schema.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut.cpp

Remove obsolete agents table from the DR

---

cloud/blockstore/libs/storage/api/volume.h
cloud/blockstore/libs/storage/protos/volume.proto
cloud/blockstore/libs/storage/service/service_actor.h
cloud/blockstore/libs/storage/service/service_actor_actions.cpp
cloud/blockstore/libs/storage/service/service_actor_actions_get_storage_config.cpp
cloud/blockstore/libs/storage/service/service_ut_actions.cpp
cloud/blockstore/libs/storage/service/ya.make
cloud/blockstore/libs/storage/volume/testlib/test_env.cpp
cloud/blockstore/libs/storage/volume/testlib/test_env.h
cloud/blockstore/libs/storage/volume/volume_actor.cpp
cloud/blockstore/libs/storage/volume/volume_ut.cpp
cloud/blockstore/tests/cms/test.py
cloud/blockstore/tests/cms/ya.make
cloud/blockstore/tests/python/lib/client.py

add private api call to get storage service config

---

cloud/filestore/apps/client/lib/factory.cpp
cloud/filestore/apps/client/lib/set_node_attr.cpp
cloud/filestore/apps/client/lib/ya.make
cloud/filestore/tests/client/test.py
cloud/filestore/tests/python/lib/client.py

[Filestore] add SetNodeAttr command to filestore client

---

cloud/blockstore/libs/storage/disk_agent/storage_with_stats.cpp
cloud/blockstore/libs/storage/disk_agent/storage_with_stats_ut.cpp
cloud/storage/core/libs/aio/service.cpp

We discovered cases where aio_submit return with EAGAIN
This can happen when aio subsystem is temporarily out of requests for example
here https://elixir.bootlin.com/linux/latest/source/fs/aio.c#L2054
In this commit we start to handle EAGAIN as retryable error to avoid marking
devices as broken

NBSNEBIUS-356: retry io when io_submit return EAGAIN

---

cloud/filestore/libs/diagnostics/critical_events.h
cloud/filestore/libs/storage/tablet/tablet_actor_renamenode.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_unlinknode.cpp
cloud/filestore/libs/storage/tablet/tablet_tx.h

issue-1350: replacing TABLET_VERIFY with impossible events + errors in UnlinkNode and RenameNode

---

cloud/filestore/libs/storage/api/tablet.h
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/service/service_actor.h
cloud/filestore/libs/storage/service/service_actor_actions.cpp
cloud/filestore/libs/storage/service/service_actor_actions_get_storage_config.cpp
cloud/filestore/libs/storage/service/service_actor_actions_ut.cpp
cloud/filestore/libs/storage/service/ya.make
cloud/filestore/libs/storage/tablet/tablet_actor.cpp
cloud/filestore/libs/storage/tablet/tablet_ut.cpp
cloud/filestore/libs/storage/testlib/tablet_client.h
cloud/filestore/private/api/protos/tablet.proto

add getstorageconfig private api call to nfs

---

cloud/blockstore/libs/storage/service/service_actor_destroy.cpp
cloud/blockstore/libs/storage/service/service_ut_create.cpp
cloud/blockstore/libs/storage/service/service_ut_destroy.cpp

issue-1567: send DeallocateDisk in case a Volume is not found

---

cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
cloud/filestore/libs/storage/testlib/service_client.h

To show proper stats when user does things like `df -h`
#1350

issue-1350: followers->leader metrics aggregation

---

cloud/filestore/libs/storage/service/service_actor_createnode.cpp
cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_createnode.cpp
cloud/filestore/libs/storage/tablet/tablet_tx.h
cloud/filestore/public/api/protos/node.proto

issue-1350: hard links should work for external nodes

---

cloud/blockstore/libs/storage/service/service_actor_actions_get_disk_agent_node_id.cpp

https://github.com/ydb-platform/nbs/pull/1551

[stable-23-3] Do not trigger fatal error if DA is not found

---

cloud/filestore/libs/storage/service/service_actor_createnode.cpp
cloud/filestore/libs/storage/service/service_ut.cpp

09c4d43a666c26acc23702566366203ffda20fe6

[Filestore] (stable-23-3) issue-1350: hard links for external modes should return correct node

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_mirror.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_readblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp

resync range if scrubbing found a mismatch

---

cloud/filestore/apps/client/lib/create_session.cpp

[Filestore] print response of create session command

---

cloud/filestore/libs/storage/api/service.h
cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/testlib/service_client.h

issue-1350: locks should work for external nodes

---

cloud/filestore/tests/fio_index/qemu-kikimr-multishard-nemesis-test/test.py
cloud/filestore/tests/fio_index/qemu-kikimr-multishard-nemesis-test/ya.make
cloud/filestore/tests/fio_index/ya.make

issue-1350: fio_index nemesis test for multitablet filestores

---

cloud/blockstore/libs/storage/core/disk_counters.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_stats.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp

add checksum mismatch sensor per volume

---

cloud/filestore/libs/storage/api/service.h
cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/testlib/service_client.h

ac9205eb3009e9409e69d04884ef708c9b3dd8ac

[merge-to-stable] issue-1350: locks should work for external nodes (#1610)

---

cloud/filestore/apps/client/lib/command.cpp
cloud/filestore/apps/client/lib/command.h
cloud/filestore/libs/storage/service/service_actor.h
cloud/filestore/libs/storage/service/service_actor_createhandle.cpp
cloud/filestore/libs/storage/service/service_actor_createnode.cpp
cloud/filestore/libs/storage/service/service_actor_forward.cpp
cloud/filestore/libs/storage/service/service_actor_getnodeattr.cpp
cloud/filestore/libs/storage/service/service_actor_listnodes.cpp
cloud/filestore/libs/storage/service/service_actor_readdata.cpp
cloud/filestore/libs/storage/service/service_actor_writedata.cpp
cloud/filestore/public/api/protos/headers.proto
cloud/filestore/tests/client/canondata/result.json
cloud/filestore/tests/client/canondata/test.test_multitablet_ls/results.txt
cloud/filestore/tests/client/nfs-storage.txt
cloud/filestore/tests/client/test.py
cloud/filestore/tests/client/ya.make

issue-1350: DisableMultiTabletForwarding flag + multitablet test in tests/client with this flag

---

cloud/blockstore/public/sdk/python/client/base_client.py
cloud/blockstore/public/sdk/python/client/client.py
cloud/blockstore/public/sdk/python/client/credentials.py
cloud/blockstore/public/sdk/python/client/discovery.py
cloud/blockstore/public/sdk/python/client/durable.py
cloud/blockstore/public/sdk/python/client/error.py
cloud/blockstore/public/sdk/python/client/error_codes.py
cloud/blockstore/public/sdk/python/client/future.py
cloud/blockstore/public/sdk/python/client/grpc_client.py
cloud/blockstore/public/sdk/python/client/http_client.py
cloud/blockstore/public/sdk/python/client/request.py
cloud/blockstore/public/sdk/python/client/safe_client.py
cloud/blockstore/public/sdk/python/client/session.py

Issue: #1486
types can be verified via mypy: mypy "filename"

[Blockstore] add type hints to python blockstore client

---

cloud/blockstore/libs/rdma/iface/client.h
cloud/blockstore/libs/rdma/impl/client.cpp
cloud/blockstore/libs/rdma/impl/client_ut.cpp
cloud/blockstore/libs/rdma/impl/server.cpp
cloud/blockstore/libs/rdma_test/client_test.cpp
cloud/blockstore/libs/service_local/storage_rdma.cpp
cloud/blockstore/libs/service_local/storage_rdma_ut.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.cpp
cloud/blockstore/tools/testing/rdma-test/storage_rdma.cpp

[issue-1020](https://github.com/ydb-platform/nbs/issues/1020)

stop rdma endpoints; issue-1020

---

cloud/filestore/apps/client/lib/command.cpp
cloud/filestore/apps/client/lib/command.h
cloud/filestore/apps/client/lib/destroy.cpp
cloud/filestore/apps/client/lib/ls.cpp
cloud/filestore/apps/client/lib/mkdir.cpp
cloud/filestore/apps/client/lib/read.cpp
cloud/filestore/apps/client/lib/rm.cpp
cloud/filestore/apps/client/lib/stat.cpp
cloud/filestore/apps/client/lib/touch.cpp
cloud/filestore/apps/client/lib/write.cpp
cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/service/service_actor_destroyfs.cpp
cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/testlib/service_client.h
cloud/filestore/public/api/protos/fs.proto

issue: #1384
Cherry-pick:
[bc2f8e0](https://github.com/ydb-platform/nbs/commit/bc2f8e0966f19b88d9c3eb8fbc940d3a4d9b0871)
[9e79898](https://github.com/ydb-platform/nbs/commit/9e798987ec5e731cf37e8062721e25c231b728ef)

merge to stable-23-3: issue-1384

---

cloud/filestore/libs/storage/api/tablet.h
cloud/filestore/libs/storage/tablet/tablet_actor_getnodeattr.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_request.cpp
cloud/filestore/libs/storage/tablet/tablet_tx.h
cloud/filestore/libs/storage/tablet/tablet_ut_nodes.cpp
cloud/filestore/libs/storage/testlib/tablet_client.h
cloud/filestore/private/api/protos/tablet.proto

issue-1350: introduced TIndexTablet::GetNodeAttrBatch method to use it in multitablet ListNodes implementation

---

cloud/blockstore/apps/client/lib/command.cpp
cloud/blockstore/apps/client/lib/command.h
cloud/blockstore/apps/client/lib/create_volume.cpp
cloud/blockstore/apps/client/lib/read_blocks.cpp
cloud/blockstore/apps/client/lib/start_endpoint.cpp
cloud/blockstore/apps/client/lib/write_blocks.cpp
cloud/blockstore/apps/client/lib/ya.make
cloud/blockstore/apps/client/lib/zero_blocks.cpp
cloud/blockstore/libs/encryption/model/utils.cpp
cloud/blockstore/libs/encryption/model/utils.h
cloud/blockstore/libs/encryption/model/ya.make
cloud/blockstore/libs/encryption/ya.make
cloud/blockstore/libs/endpoints_vhost/external_vhost_server.cpp
cloud/blockstore/libs/endpoints_vhost/external_vhost_server_ut.cpp
cloud/blockstore/tools/nbd/options.cpp
cloud/blockstore/tools/nbd/ya.make
cloud/blockstore/vhost-server/options.cpp
cloud/blockstore/vhost-server/options.h
cloud/blockstore/vhost-server/ut/ya.make
cloud/blockstore/vhost-server/ya.make

Первая часть реализации https://github.com/ydb-platform/nbs/issues/1624
Сделано:
1. убирается копи-паста
2. в процесс vhost-server пробрасываются флаги, чтобы он знал каким ключом нужно шифровать

Pass encryption key info to external-vhost server

---

cloud/filestore/libs/storage/tablet/tablet_actor_getnodeattr.cpp
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
cloud/filestore/libs/storage/tablet/tablet_state_nodes.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_nodes.cpp

issue-1350: some fixes for GetNodeAttrBatch + NodeAttrCache

---

cloud/filestore/libs/storage/tablet/tablet_actor.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_counters.cpp

https://github.com/ydb-platform/nbs/issues/1175
fs tablets now report network every 15 seconds

merge to stable-23-3: issue-1175 

---

cloud/disk_manager/internal/pkg/resources/images.go
cloud/disk_manager/internal/pkg/resources/images_test.go
cloud/disk_manager/internal/pkg/resources/storage.go
cloud/disk_manager/internal/pkg/services/images/create_image_from_disk_task.go
cloud/disk_manager/internal/pkg/services/images/create_image_from_image_task.go
cloud/disk_manager/internal/pkg/services/images/create_image_from_snapshot_task.go

https://github.com/ydb-platform/nbs/issues/1636

[Disk Manager] add disk id to image meta

---

cloud/blockstore/libs/daemon/ydb/bootstrap.cpp
cloud/blockstore/libs/disk_agent/bootstrap.cpp
cloud/blockstore/libs/server/config.cpp
cloud/blockstore/libs/server/config.h
cloud/filestore/libs/daemon/common/bootstrap.cpp
cloud/filestore/libs/daemon/common/bootstrap.h
cloud/storage/core/libs/kikimr/node.cpp
cloud/storage/core/libs/kikimr/node.h
cloud/storage/core/libs/kikimr/node_registration_settings.cpp
cloud/storage/core/libs/kikimr/node_registration_settings.h
cloud/storage/core/libs/kikimr/ya.make

https://github.com/ydb-platform/nbs/issues/1445
refactor some code for node registration. To be used in filestore later

refactor node registration

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_secure_erase.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_writable_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_private.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_agents_info.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_create.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_migration.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_lifecycle.cpp
cloud/blockstore/libs/storage/disk_registry/testlib/test_env.h
cloud/blockstore/libs/storage/disk_registry/testlib/test_state.cpp
cloud/blockstore/libs/storage/disk_registry/testlib/test_state.h
cloud/filestore/apps/client/lib/CMakeLists.darwin-x86_64.txt
cloud/filestore/apps/client/lib/CMakeLists.linux-aarch64.txt
cloud/filestore/apps/client/lib/CMakeLists.linux-x86_64.txt
cloud/filestore/apps/client/lib/CMakeLists.windows-x86_64.txt
cloud/filestore/apps/client/lib/create_session.cpp
cloud/filestore/apps/client/lib/factory.cpp
cloud/filestore/apps/client/lib/set_node_attr.cpp
cloud/filestore/apps/client/lib/ya.make
cloud/filestore/tests/client/test.py
cloud/filestore/tests/python/lib/client.py
library/cpp/getopt/small/last_getopt_opt.h

cherry-pick: 
+ https://github.com/ydb-platform/nbs/pull/1469
+ https://github.com/ydb-platform/nbs/pull/1476
+ https://github.com/ydb-platform/nbs/pull/1513
+ https://github.com/ydb-platform/nbs/pull/1549
+ https://github.com/ydb-platform/nbs/pull/1578
+ update CMakeLists
+ [ffc1468](https://github.com/ydb-platform/nbs/pull/1650/commits/ffc1468732ed5526735c9dd3a2ede3b0df33373b) fix  unit tests
+  cherry-pick [Support StoreResult to std::optional in LastGetopt](https://github.com/ydb-platform/nbs/pull/1650/commits/0595fbeaecc1680b83886b299cf2bd39162cbb74)

merge to stable-23-3: issue-1394 issue-1395 issue-1474

---

cloud/filestore/config/vhost.proto
cloud/filestore/libs/daemon/common/bootstrap.h
cloud/filestore/libs/daemon/vhost/bootstrap.cpp
cloud/filestore/libs/daemon/vhost/bootstrap.h
cloud/filestore/libs/daemon/vhost/options.cpp
cloud/filestore/libs/daemon/vhost/options.h
cloud/filestore/libs/daemon/vhost/ya.make
cloud/filestore/libs/endpoint_vhost/config.cpp
cloud/filestore/libs/endpoint_vhost/config.h
cloud/filestore/libs/server/config.h
cloud/filestore/libs/server/server.cpp
cloud/filestore/libs/service_local/service.cpp
cloud/filestore/tests/fio/qemu-local-noserver-test/test.py
cloud/filestore/tests/fio/qemu-local-noserver-test/ya.make
cloud/filestore/tests/fio/ya.make
cloud/filestore/tests/python/lib/daemon_config.py
cloud/filestore/tests/recipes/vhost-local-noserver.inc
cloud/filestore/tests/recipes/vhost/__main__.py

issue-1668: LocalService mode for filestore-vhost

---

cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp

…k (#1694)
* fix test, we should wait until scrubbing will definitely scan all disk
* add comment

Merge 23-3

---

cloud/filestore/libs/storage/tablet/tablet_state.cpp
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp

collect barrier gen should match current current tablet generation

---

cloud/storage/core/libs/diagnostics/request_counters.cpp

The bug was introduced here https://github.com/ydb-platform/nbs/pull/1711 - not merged to 23-3 yet
#1161

issue-1161: fixed stupid lazy counter init race

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_cms.cpp

RemoveDevice request should mark all logical devices on the physical device to be removed. But so far, if a logical device belongs to a NRD, RemoveDevice only marks that device and returns E_TRY_AGAIN. Moreover, a disk from one logical device may migrate to another logical device on the same physical device, which greatly increases the time to remove a physical disk.

[bugfix] RemoveDevice request should trigger migration from all logical devices

---

cloud/blockstore/tools/csi_driver/internal/driver/node.go
cloud/blockstore/tools/csi_driver/internal/driver/node_test.go

Needed to be able to customize disk serial number visible to the guest operating system

Add capability of specifying device name in csi request

---

cloud/blockstore/libs/storage/ss_proxy/ss_proxy_actor_describevolume.cpp
cloud/blockstore/libs/storage/ss_proxy/ss_proxy_ut.cpp
cloud/filestore/libs/storage/ss_proxy/ss_proxy_actor_describefs.cpp
cloud/filestore/libs/storage/ss_proxy/ss_proxy_ut.cpp

* return retriable error when describe returns zero tablet id
* fix comment
* update
---------
#1735

return retriable error when describe returns zero tablet id (#1737)

---

cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_io.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_stats.cpp

* Remove repeated check-health errors when device broken
* Fix typo

23-3. Remove repeated check-health errors when device broken (#1731)

---

cloud/blockstore/libs/storage/core/volume_model.cpp
cloud/blockstore/libs/storage/core/volume_model.h
cloud/blockstore/libs/storage/core/volume_model_ut.cpp

* Fix channel count overflow
* Fix review issues
* Fix params mess
* Making calculations simpler
* Remove unused param

23-3. Fix channel count overflow (#1645)

---

cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/model/range.h
cloud/filestore/libs/storage/service/service_actor_writedata.cpp
cloud/filestore/libs/storage/service/service_ut.cpp

issue-1673: supported ThreeStageWrites for large unaligned requests in StorageServiceActor

---

cloud/filestore/tests/fio/qemu-kikimr-newfeatures-test/test.py
cloud/filestore/tests/fio/qemu-kikimr-newfeatures-test/ya.make
cloud/filestore/tests/fio/ya.make
cloud/filestore/tests/loadtest/service-kikimr-newfeatures-test/nfs-storage.txt
cloud/filestore/tests/loadtest/service-kikimr-newfeatures-test/read-write-validation.txt
cloud/storage/core/tools/testing/fio/lib/__init__.py

issue-1673: fio and loadtests for unaligned ThreeStageWrite

---

cloud/disk_manager/internal/pkg/facade/private_service_test/private_service_test.go
cloud/disk_manager/internal/pkg/facade/testcommon/common.go
cloud/disk_manager/internal/pkg/services/pools/storage/consistency_check.go
cloud/disk_manager/internal/pkg/services/pools/storage/mocks/storage_mock.go
cloud/disk_manager/internal/pkg/services/pools/storage/storage.go
cloud/disk_manager/internal/pkg/services/pools/storage/storage_ydb.go

https://github.com/ydb-platform/nbs/issues/1636

[Disk Manager] add overlay disks slots consistency check

---

cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.cpp
cloud/blockstore/libs/storage/volume/volume_actor.cpp

issue-1791: added logs

---

cloud/blockstore/tests/local_ssd/test.py

Fix a race condition: the test may check the agent's state before DR has changed it.

NBSDUTY-57: fix test_add_host_with_legacy_local_ssd

---

cloud/filestore/libs/storage/service/service_actor_writedata.cpp
cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_writeblob.cpp
cloud/filestore/private/api/protos/tablet.proto

issue-1814: passing StorageStatusFlags for written blobs from StorageServiceActor to tablets via AddData requests

---

cloud/tasks/persistence/ydb.go
cloud/tasks/persistence/ydb_metrics.go
cloud/tasks/persistence/ydb_test.go

[#1744 ](https://github.com/ydb-platform/nbs/issues/1744)

[Disk Manager] better YDB client errors metric

---

cloud/storage/core/libs/tablet/gc_logic.cpp
cloud/storage/core/libs/tablet/gc_logic_ut.cpp
cloud/storage/core/libs/tablet/model/partial_blob_id.h

issue-1825: deduplicate blobs in collect garbage with a linear complexity

---

cloud/filestore/libs/storage/service/service_actor_alterfs.cpp
cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_updateconfig.cpp
cloud/filestore/libs/storage/tablet/tablet_ut.cpp
cloud/filestore/libs/storage/testlib/service_client.h
cloud/filestore/public/api/protos/fs.proto

issue-1823: allowing FS size decrease with a Force flag + some cleanup

---

cloud/tasks/persistence/ydb.go
cloud/tasks/persistence/ydb_metrics.go
cloud/tasks/persistence/ydb_test.go

This reverts commit af346f3f27cb91bfcf39a5438d650f7e640bb6f6.

Revert "[Disk Manager] better YDB client errors metric (#1775)"

---

cloud/blockstore/libs/storage/partition/part_actor_monitoring.cpp
cloud/blockstore/libs/storage/partition/part_state.cpp
cloud/blockstore/libs/storage/partition/part_state.h
cloud/blockstore/libs/storage/partition2/part2_state.cpp
cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/service/service_actor_writedata.cpp
cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/tablet/model/channels.cpp
cloud/filestore/libs/storage/tablet/model/channels.h
cloud/filestore/libs/storage/tablet/model/channels_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_writeblob.cpp
cloud/filestore/libs/storage/tablet/tablet_state.cpp
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_channels.cpp
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
cloud/filestore/private/api/protos/tablet.proto
cloud/storage/core/libs/tablet/model/channels.cpp
cloud/storage/core/libs/tablet/model/channels.h
cloud/storage/core/libs/tablet/model/ya.make
cloud/storage/core/libs/viewer/tablet_monitoring.cpp
cloud/storage/core/libs/viewer/tablet_monitoring.h

issue-1824: filestore tablet channel balancing by ApproximateFreeSpaceShare

---

cloud/filestore/libs/storage/service/service_actor_createsession.cpp
cloud/filestore/libs/vfs_fuse/fs_impl_list.cpp

issue-1161: improved some diagnostics

---

cloud/filestore/libs/storage/service/service_actor_getnodeattr.cpp

Failed here: https://github.com/ydb-platform/nbs/actions/runs/10570154324

[Filestore] Fix incorrect format string in service_actor_getnodeattr.cpp

---

cloud/filestore/tools/testing/open_close_bench/main.c
cloud/filestore/tools/testing/open_close_bench/ya.make
cloud/filestore/tools/testing/ya.make

issue-1541: add tool for open/close benchmark

---

cloud/blockstore/tests/loadtest/local/canondata/test.test_load_version1-smallreqs_/stats_version1-smallreqs.txt
cloud/blockstore/tests/loadtest/local/canondata/test.test_load_version1-throttled-boosted_/stats_version1-throttled-boosted.txt
cloud/blockstore/tests/loadtest/local/canondata/test.test_load_version1-throttled-tracked_/stats_version1-throttled-tracked.txt
cloud/blockstore/tests/loadtest/local/canondata/test.test_load_version1-two-clients-remount-ro_/stats_version1-two-clients-remount-ro.txt
cloud/blockstore/tests/loadtest/local/canondata/test.test_load_version1-two-clients-remount-rw_/stats_version1-two-clients-remount-rw.txt
cloud/blockstore/tests/loadtest/local/canondata/test.test_load_version1-two-clients_/stats_version1-two-clients.txt
cloud/blockstore/tests/loadtest/local/canondata/test.test_load_version1_/stats_version1.txt
cloud/blockstore/tests/loadtest/local/canondata/test.test_load_version2-smallreqs-skew_/stats_version2-smallreqs-skew.txt
cloud/blockstore/tests/loadtest/local/canondata/test.test_load_version2-smallreqs_/stats_version2-smallreqs.txt
cloud/blockstore/tests/loadtest/local/canondata/test.test_load_version2_/stats_version2.txt
cloud/blockstore/tests/loadtest/local/test.py

TabletBSFailure may be true if the group is filled up

removed TabletBSFailure entry from loadtest canonical results

---

example/0-setup.sh
example/dynamic/Configure-Root.txt
example/dynamic/CreateTenant.txt
example/dynamic/DefineBox.txt
example/static/bs.txt

Configure YDB storage for multiple pdisks and vdisks

---

doc/filestore/design/cli/ls.md
doc/filestore/design/storage/tablet/data_index.md

See the added .md file for the details
#1795

issue-1795: tablet storage layers doc

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut.cpp

[Blockstore] do not account allocated bytes to DecommissionedBytes counter

---

cloud/blockstore/libs/nbd/netlink_device.cpp
cloud/blockstore/tests/python/lib/endpoint_proxy.py

cherry-pick: https://github.com/ydb-platform/nbs/commit/150ea4ca535db11a2206f9474db74122fffa03c5

merge to stable-23-3: issue-1657 

---

doc/disk_manager/tracing/design_doc.md

https://github.com/ydb-platform/nbs/issues/1199

[Disk Manager] add tracing design doc

---

cloud/filestore/libs/storage/service/service_actor_actions_ut.cpp

продолжение https://github.com/ydb-platform/nbs/pull/1909 (

Fix arcadia build #2

---

cloud/filestore/config/filesystem.proto
cloud/filestore/config/storage.proto
cloud/filestore/config/vfs.proto
cloud/filestore/libs/diagnostics/critical_events.h
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/tablet/tablet_actor_createsession.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_sessions.cpp
cloud/filestore/libs/vfs_fuse/config.cpp
cloud/filestore/libs/vfs_fuse/config.h
cloud/filestore/libs/vfs_fuse/create_destroy_queue.cpp
cloud/filestore/libs/vfs_fuse/create_destroy_queue.h
cloud/filestore/libs/vfs_fuse/fs.h
cloud/filestore/libs/vfs_fuse/fs_impl.cpp
cloud/filestore/libs/vfs_fuse/fs_impl.h
cloud/filestore/libs/vfs_fuse/fs_impl_data.cpp
cloud/filestore/libs/vfs_fuse/fs_ut.cpp
cloud/filestore/libs/vfs_fuse/handle_ops_queue.cpp
cloud/filestore/libs/vfs_fuse/handle_ops_queue.h
cloud/filestore/libs/vfs_fuse/loop.cpp
cloud/filestore/libs/vfs_fuse/protos/queue_entry.proto
cloud/filestore/libs/vfs_fuse/protos/ya.make
cloud/filestore/libs/vfs_fuse/ya.make
cloud/filestore/libs/vfs_fuse/ya.make.inc
cloud/filestore/libs/vhost/request.h
cloud/filestore/public/api/protos/fs.proto

issue-1541: implement async destroy handle processing

---

cloud/filestore/libs/storage/tablet/model/node_session_stat.cpp
cloud/filestore/libs/storage/tablet/model/node_session_stat.h

follow-up fix for https://github.com/ydb-platform/nbs/pull/1818
#1902

issue-1902: fixing use-after-free after https://github.com/ydb-platform/nbs/pull/1818

---

cloud/blockstore/libs/encryption/encryption_client.cpp
cloud/blockstore/libs/encryption/encryption_client_ut.cpp
cloud/blockstore/libs/encryption/encryptor.cpp
cloud/blockstore/libs/encryption/encryptor.h
cloud/blockstore/libs/encryption/encryptor_ut.cpp
cloud/blockstore/vhost-server/request_aio.cpp
cloud/blockstore/vhost-server/server_ut.cpp

issue-176: encryption operations should return TError

---

cloud/blockstore/vhost-server/gtest/ya.make

The test does a lot of work and can sometimes timeout. Making the test medium.

Change vhost-server/gtest to medium

---

cloud/blockstore/tests/csi_driver/test.py

issue-464: test csi-driver with mount access type

---

cloud/filestore/libs/vfs_fuse/fs_ut.cpp

issue-1541: fixed races in uts

---

cloud/blockstore/tests/loadtest/local-emergency/test.py

issue-757: simplify local-emergency test and enable it

---

cloud/blockstore/libs/storage/service/service_actor.h
cloud/blockstore/libs/storage/service/service_actor_actions.cpp
cloud/blockstore/libs/storage/service/service_actor_actions_backup_path_descriptions.cpp
cloud/blockstore/libs/storage/service/service_actor_actions_backup_tablet_boot_infos.cpp
cloud/blockstore/libs/storage/service/service_actor_actions_modify_tags.cpp
cloud/blockstore/libs/storage/service/ya.make

These actions will be used in local-emergency test
#757

issue-757: add BackupPathDescriptions, BackupTabletBootInfos execute actions

---

cloud/storage/core/tools/testing/qemu/lib/qemu.py
cloud/storage/core/tools/testing/virtiofs_server/lib/__init__.py

similar to https://github.com/ydb-platform/nbs/pull/1857

Ydb sync fix

---

cloud/blockstore/public/sdk/go/client/discovery.go
cloud/blockstore/public/sdk/go/client/durable.go
cloud/blockstore/public/sdk/go/client/grpc.go
cloud/blockstore/public/sdk/go/client/iface.go
cloud/blockstore/public/sdk/go/client/test_client.go
cloud/blockstore/tests/csi_driver/test.py
cloud/blockstore/tools/csi_driver/README.md
cloud/blockstore/tools/csi_driver/client/main.go
cloud/blockstore/tools/csi_driver/internal/driver/mocks/nbs_client_mock.go
cloud/blockstore/tools/csi_driver/internal/driver/node.go

issue: #1657 
doc: https://kubernetes-csi.github.io/docs/volume-expansion.html
Only online volume expansion for published volumes is supported

issue-1657: support EXPAND_VOLUME capability in CSI Driver

---

cloud/storage/core/libs/common/guarded_sglist.h

Переименовали метод в https://github.com/ydb-platform/nbs/commit/b46312f1f53ee97adf0826472610844170d113a5

Update comment after method renaming

---

cloud/blockstore/libs/endpoint_proxy/server/server.cpp
cloud/blockstore/libs/endpoint_proxy/server/server_ut.cpp
cloud/blockstore/libs/endpoint_proxy/server/ut/CMakeLists.txt
cloud/blockstore/libs/endpoint_proxy/server/ut/ya.make
cloud/blockstore/libs/nbd/device.cpp

merge to stable-23-3: issue-1657

---

cloud/blockstore/libs/daemon/ydb/bootstrap.cpp
cloud/blockstore/libs/disk_agent/bootstrap.cpp
cloud/blockstore/libs/nvme/nvme_stub.cpp
cloud/blockstore/tests/disk_agent_config/test.py

Fix crash of DA when DISK_AGENT_BACKEND_NULL is configured.

[Blockstore] setup NvmeManager for DISK_AGENT_BACKEND_NULL

---

cloud/blockstore/config/disk.proto
cloud/blockstore/libs/storage/disk_agent/actors/io_request_parser.cpp
cloud/blockstore/libs/storage/disk_agent/actors/io_request_parser.h
cloud/blockstore/libs/storage/disk_agent/actors/ya.make
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_init.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_ut.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_private.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_ut_large.cpp
cloud/blockstore/libs/storage/disk_agent/model/config.cpp
cloud/blockstore/libs/storage/disk_agent/model/config.h
cloud/blockstore/libs/storage/disk_agent/testlib/test_env.cpp
cloud/blockstore/libs/storage/disk_agent/testlib/test_env.h
cloud/blockstore/libs/storage/init/disk_agent/actorsystem.cpp
cloud/blockstore/tests/python/lib/config.py
cloud/blockstore/tests/python/lib/nonreplicated_setup.py

issue-1987: offload protobuf parsing of IO requests to a separate actor

---

cloud/filestore/libs/storage/tablet/tablet_actor_compaction.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_flush.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_flush_bytes.cpp

issue-1922: making background ops' read/writeblob requests async

---

cloud/filestore/libs/storage/tablet/tablet_actor_addblob.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp

issue-1922: avoiding Compaction loops by limiting BlobsCount increment made in AddBlob for Compaction requests by CompactionThreshold - 1

---

cloud/blockstore/libs/service/aligned_device_handler.cpp
cloud/blockstore/libs/service/aligned_device_handler.h
cloud/blockstore/libs/service/device_handler.cpp
cloud/blockstore/libs/service/ya.make

Переношу класс TAlignedDeviceHandler в отдельный cpp-файл

Move TAlignedDeviceHandler to separate cpp

---

.github/workflows/packer.yaml

Fixes https://github.com/ydb-platform/nbs/actions/runs/10844351604/job/30093059412#step:9:55

fix: presumably this fixes rate limit error on packer

---

cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/tablet/model/operation.h
cloud/filestore/libs/storage/tablet/tablet_actor_cleanup.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_compaction.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_flush_bytes.cpp
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp

issue-1993: proper Cleanup / Compaction prioritization for target levels which are close to Backpressure thresholds

---

cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/tablet/tablet_actor.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp
cloud/filestore/tests/loadtest/service-kikimr-newfeatures-test/nfs-storage.txt
doc/filestore/design/storage/config.md

issue-1922: introduced UseMixedBlocksInsteadOfAliveBlocksInCompaction flag

---

cloud/blockstore/tools/csi_driver/internal/driver/node.go
cloud/blockstore/tools/csi_driver/internal/driver/node_test.go

issue: #1917
csi driver doesn't support AccessMode_MULTI_NODE_MULTI_WRITER for nbs volumes

issue-1917: MULTI_NODE_MULTI_WRITER access mode is not supported with nbs backend

---

cloud/blockstore/public/sdk/go/client/safe_client.go

Small fixes of a typo and wrong style

Cosmetics in Blockstore go SDK

---

cloud/disk_manager/internal/pkg/clients/nbs/client.go
cloud/disk_manager/internal/pkg/clients/nbs/multi_zone_client.go
cloud/disk_manager/internal/pkg/clients/nbs/session.go
cloud/tasks/persistence/ydb.go
cloud/tasks/tracing/init.go

#1199
Это черновик правки, в которой пранируется добавить спаны, отвечающие запросам в NBS и YDB. Прежде чем доводить этот pr до финального варианта, предлагаю определиться с тем, какие спаны и как мы будем создавать (см. комментарии в pr).
В частности, для nbs пока что сделал только спаны для запроса на создание диска. Если мы решим, что так создавать спаны -- ок, то доделаю для остальных запросов.
UPD:
Привёл pr к чистовому виду.

[Disk Manager] Tracing: Add spans for nbs and ydb clients, add simple parent-based sampling

---

cloud/blockstore/libs/daemon/ydb/config_initializer.cpp
cloud/blockstore/libs/daemon/ydb/config_initializer.h
cloud/blockstore/libs/disk_agent/config_initializer.cpp
cloud/blockstore/libs/disk_agent/config_initializer.h
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h

* issue-1946: remove duplicated code
* fix build
* update
* update

issue-1946: remove duplicated code (#2040)

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_create.cpp

Related to #2060
Правлю валенок, где мы всегда создаём SSD_NONREPLICATED с точки зрения DR, хотя диск может быть локальным

Deduce MediaKind from PoolKind while creating a disk from device

---

cloud/blockstore/libs/encryption/encryption_client.cpp
cloud/blockstore/libs/encryption/encryption_client.h
cloud/blockstore/libs/encryption/encryption_client_ut.cpp
cloud/blockstore/libs/encryption/encryption_service.cpp
cloud/blockstore/libs/encryption/encryption_service_ut.cpp
cloud/blockstore/public/api/protos/volume.proto

`TVolumeEncryptionClient` waits for MounVolume request to create a default encryption client or use the original one.

issue-176: creating an encryption client depending on the volume configuration

---

cloud/filestore/apps/client/lib/ls.cpp
cloud/filestore/apps/client/lib/text_table.cpp
cloud/filestore/apps/client/lib/text_table.h
cloud/filestore/libs/storage/tablet/tablet_actor_flush_bytes.cpp
cloud/filestore/libs/storage/tablet/tablet_private.h
cloud/filestore/libs/storage/tablet/tablet_tx.h
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp
cloud/filestore/tests/client/canondata/result.json
cloud/filestore/tests/client/canondata/test.test_ls/results.txt
cloud/filestore/tests/client/canondata/test.test_write_ls_rm_ls/results.txt
cloud/filestore/tests/client/test.py

4282375 b4ad72693dfa6718dcc6017022bad9b68a870737

merge to stable-23-3: issue-652: do not acquire barriers from the past upon, fix ls command in client without --json flag

---

cloud/storage/core/libs/diagnostics/critical_events.h
cloud/storage/core/libs/kikimr/config_dispatcher_helpers.cpp
cloud/storage/core/libs/kikimr/config_dispatcher_helpers.h
cloud/storage/core/libs/kikimr/config_dispatcher_helpers_ut.cpp
cloud/storage/core/libs/kikimr/ut/ya.make
cloud/storage/core/libs/kikimr/ya.make
cloud/storage/core/protos/config_dispatcher_settings.proto
cloud/storage/core/protos/ya.make
cloud/storage/core/protos/ydb_config_dispatcher_settings.proto

issue-370: common code to support config dispatcher

---

cloud/blockstore/tests/client/test_with_multiple_agents.py
cloud/blockstore/tests/infra-cms/test.py
cloud/blockstore/tests/loadtest/local-change-device/test.py
cloud/blockstore/tests/loadtest/local-metrics/test.py
cloud/blockstore/tests/loadtest/local-mirror/test.py
cloud/blockstore/tests/loadtest/local-nonrepl/test.py
cloud/blockstore/tests/loadtest/local-user-metrics/test.py
cloud/blockstore/tests/monitoring/test.py
cloud/blockstore/tests/mount/test.py
cloud/blockstore/tests/notify/test.py
cloud/blockstore/tests/python/lib/daemon.py
cloud/blockstore/tests/python/lib/loadtest_env.py
cloud/blockstore/tests/recipes/local-kikimr/__main__.py
cloud/disk_manager/test/recipe/ydb_launcher.py
cloud/filestore/tests/recipes/service-kikimr/__main__.py
cloud/filestore/tests/registration/test.py

YDB убрали в main параметр. Если мы не уберем его использование - это поломает нам синк в транк аркадии.

Remove unused param

---

cloud/blockstore/tests/loadtest/local-emergency/test.py
contrib/ydb/tests/library/harness/kikimr_runner.py

issue-757: move spoil_bs_controller_config and format_static_pdisks methods out from contrib/ydb

---

cloud/filestore/libs/vfs_fuse/file_ring_buffer.cpp
cloud/filestore/libs/vfs_fuse/file_ring_buffer.h
cloud/filestore/libs/vfs_fuse/file_ring_buffer_ut.cpp
cloud/filestore/libs/vfs_fuse/handle_ops_queue.cpp
cloud/filestore/libs/vfs_fuse/handle_ops_queue.h
cloud/filestore/libs/vfs_fuse/ut/ya.make
cloud/filestore/libs/vfs_fuse/ya.make.inc

issue-1541: implemented a ring buffer over a file to use it in HandleOpsQueue

---

cloud/filestore/libs/storage/tablet/tablet_actor_loadstate.cpp
cloud/filestore/libs/storage/tablet/tablet_database.cpp
cloud/filestore/libs/storage/tablet/tablet_database.h
cloud/filestore/libs/storage/tablet/tablet_database_ut.cpp

issue-1128: add precharge for compaction map loading

---

cloud/filestore/libs/storage/service/service_actor_readdata.cpp
cloud/filestore/libs/storage/service/service_ut.cpp

issue-1285: report readblob operation once even for multiple blobs in service sensors

---

cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/init/actorsystem.cpp
cloud/filestore/tests/config_dispatcher/test.py
cloud/filestore/tests/config_dispatcher/ya.make
cloud/filestore/tests/ya.make

issue-370: add config dispatcher support for filestore

---

cloud/blockstore/public/sdk/go/client/error.go
cloud/blockstore/public/sdk/python/client/error.py
cloud/filestore/public/sdk/go/client/error.go
cloud/filestore/public/sdk/python/client/error.py

https://github.com/ydb-platform/nbs/blob/eb1cbf388a1d774d020419fba46b117a03734012/cloud/storage/core/libs/common/error.cpp#L43

blockstore & filestore SDK retriable error codes should be in sync with cloud/storage/core/libs/common/error.cpp

---

cloud/filestore/tools/testing/open_close_bench/main.c

fix open close bench

---

cloud/filestore/libs/vfs_fuse/fs_impl.cpp
cloud/filestore/libs/vfs_fuse/fs_ut.cpp

add missing DestroyHandle request completion

---

cloud/filestore/libs/storage/api/ss_proxy.h
cloud/filestore/libs/storage/service/service_actor_list.cpp
cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/ss_proxy/ss_proxy_actor.cpp
cloud/filestore/libs/storage/ss_proxy/ss_proxy_actor.h
cloud/filestore/libs/storage/ss_proxy/ss_proxy_actor_alterfs.cpp
cloud/filestore/libs/storage/ss_proxy/ss_proxy_actor_createfs.cpp
cloud/filestore/libs/storage/ss_proxy/ss_proxy_actor_describefs.cpp
cloud/filestore/libs/storage/ss_proxy/ss_proxy_actor_destroyfs.cpp
cloud/filestore/libs/storage/ss_proxy/ss_proxy_ut.cpp
cloud/filestore/libs/storage/ss_proxy/ya.make
cloud/filestore/libs/storage/testlib/ss_proxy_client.h
cloud/storage/core/libs/api/ss_proxy.cpp
cloud/storage/core/libs/api/ss_proxy.h
cloud/storage/core/libs/api/ya.make
cloud/storage/core/libs/hive_proxy/hive_proxy_actor.h
cloud/storage/core/libs/kikimr/components.h
cloud/storage/core/libs/ss_proxy/public.h
cloud/storage/core/libs/ss_proxy/ss_proxy_actor.cpp
cloud/storage/core/libs/ss_proxy/ss_proxy_actor.h
cloud/storage/core/libs/ss_proxy/ss_proxy_actor_describescheme.cpp
cloud/storage/core/libs/ss_proxy/ss_proxy_actor_modifyscheme.cpp
cloud/storage/core/libs/ss_proxy/ss_proxy_actor_waitschemetx.cpp
cloud/storage/core/libs/ss_proxy/ya.make
cloud/storage/core/libs/ya.make

issue-2100: extract TSSProxyActor from cloud/filestore - this actor implements DescribeScheme, ModifyScheme and WaitSchemeTx requests

---

cloud/tasks/persistence/ydb_metrics.go

https://github.com/ydb-platform/nbs/issues/1744

[Disk Manager] Add logging for unknown ydb errors

---

cloud/filestore/libs/storage/tablet/tablet_actor.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_cleanup.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_compaction.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_truncate.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_zerorange.cpp
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp

issue-1795: LargeDeletionMarkers backpressure - some fixes and cleanup

---

cloud/filestore/tests/auth/new/ya.make
cloud/filestore/tests/ya.make
cloud/storage/core/tests/recipes/ya.make
cloud/storage/core/tools/testing/access_service_new/lib/__init__.py
cloud/storage/core/tools/testing/ya.make

Аркадия ругается на недостижимость проектов и проверки flake8

Fix sync with arcadia

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/disk_agent/ya.make
cloud/blockstore/libs/storage/ss_proxy/ya.make
cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/ss_proxy/ss_proxy_actor.cpp
cloud/storage/core/libs/api/ss_proxy.h
cloud/storage/core/libs/diagnostics/critical_events.h
cloud/storage/core/libs/hive_proxy/tablet_boot_info_backup.cpp
cloud/storage/core/libs/hive_proxy/ya.make
cloud/storage/core/libs/ss_proxy/path_description_backup.cpp
cloud/storage/core/libs/ss_proxy/path_description_backup.h
cloud/storage/core/libs/ss_proxy/protos/path_description_backup.proto
cloud/storage/core/libs/ss_proxy/protos/ya.make
cloud/storage/core/libs/ss_proxy/public.h
cloud/storage/core/libs/ss_proxy/ss_proxy_actor.cpp
cloud/storage/core/libs/ss_proxy/ss_proxy_actor.h
cloud/storage/core/libs/ss_proxy/ss_proxy_actor_describescheme.cpp
cloud/storage/core/libs/ss_proxy/ss_proxy_actor_modifyscheme.cpp
cloud/storage/core/libs/ss_proxy/ss_proxy_actor_waitschemetx.cpp
cloud/storage/core/libs/ss_proxy/ss_proxy_events_private.h
cloud/storage/core/libs/ss_proxy/ya.make

Later this code will be reused by Blockstore also
#2100

issue-2100: cloud/storage/core/libs/ss_proxy should be able to backup path descriptions

---

cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_ut.cpp

fixing tests added in https://github.com/ydb-platform/nbs/pull/2142
https://github-actions-s3.website.nemax.nebius.cloud/ydb-platform/nbs/PR-check/11108887622/1/nebius-x86-64-asan/logs/cloud/blockstore/libs/storage/partition_nonrepl/ut/test-results/unittest/chunk5/testing_out_stuff/TNonreplicatedPartitionMigrationTest.ShouldNotFailRequestOnFollowerNonRetriableError.err
```
==337201==ERROR: AddressSanitizer: heap-use-after-free on address 0x60700005dd78 at pc 0x0000241a61c7 bp 0x7ffe69320d90 sp 0x7ffe69320d88
WRITE of size 8 at 0x60700005dd78 thread T0
#0 0x241a61c6 in AtomicAdd /actions-runner/_work/nbs/nbs/library/cpp/deprecated/atomic/atomic_gcc.h:51:12
#1 0x241a61c6 in AtomicAdd<unsigned long> /actions-runner/_work/nbs/nbs/library/cpp/deprecated/atomic/atomic_ops.h:61:27
#2 0x241a61c6 …
```

fixed use-after-free in partition_nonrepl uts

---

cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp

issue-1795: fixed usage of uninitialized memory in ut

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_mirrored_disks.cpp

issue-2076: replace broken devices on the agent registration

---

cloud/tasks/persistence/ydb_metrics.go

https://github.com/ydb-platform/nbs/issues/1744

[Disk Manager] Move metric counters initialization to avoid no data

---

cloud/blockstore/tests/csi_driver/test.py
cloud/blockstore/tools/csi_driver/client/main.go

1. Test NodeStageVolume
2. Test NodeUnstageVolume
3. Test VM Mode
4. Set VhostEnabled by default
5. Test publishing volume twice on the same node in VM Mode

test csi driver in vm mode

---

.github/config/muted_ya.txt

Mute external vhost tests

---

cloud/disk_manager/internal/pkg/services/pools/config/config.proto
cloud/disk_manager/internal/pkg/services/pools/storage/metrics/metrics.go
cloud/disk_manager/internal/pkg/services/pools/storage/storage_ydb_impl.go

https://github.com/ydb-platform/nbs/issues/1979

[Disk Manager] Speeding up takeBaseDisksToSchedule

---

cloud/blockstore/libs/common/block_range.h
cloud/storage/core/libs/common/error.h

issue-2233: fix clang++ 18 compilation errors

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_allocate.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_get_agent_node_id.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_pending_cleanup.cpp
cloud/blockstore/libs/storage/protos/disk.proto
cloud/blockstore/libs/storage/service/service_actor_actions_get_disk_agent_node_id.cpp
cloud/blockstore/tests/client/test_with_multiple_agents.py
cloud/blockstore/tests/external_endpoint/multiple_endpoints.py

https://github.com/ydb-platform/nbs/issues/2139

Merge to stable

---

cloud/blockstore/libs/storage/ss_proxy/ss_proxy_ut.cpp
cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/ss_proxy/ss_proxy.cpp
cloud/filestore/libs/storage/ss_proxy/ss_proxy_actor.cpp
cloud/filestore/libs/storage/ss_proxy/ss_proxy_fallback_actor.cpp
cloud/filestore/libs/storage/ss_proxy/ss_proxy_fallback_actor.h
cloud/filestore/libs/storage/ss_proxy/ss_proxy_ut.cpp
cloud/filestore/libs/storage/ss_proxy/ya.make
cloud/filestore/libs/storage/testlib/test_env.cpp
cloud/filestore/libs/storage/testlib/test_env.h
cloud/storage/core/libs/hive_proxy/hive_proxy_fallback_actor.cpp
cloud/storage/core/libs/ss_proxy/public.h
cloud/storage/core/libs/ss_proxy/ss_proxy.cpp
cloud/storage/core/libs/ss_proxy/ss_proxy.h
cloud/storage/core/libs/ss_proxy/ss_proxy_actor.cpp
cloud/storage/core/libs/ss_proxy/ss_proxy_actor.h
cloud/storage/core/libs/ss_proxy/ss_proxy_fallback_actor.cpp
cloud/storage/core/libs/ss_proxy/ss_proxy_fallback_actor.h
cloud/storage/core/libs/ss_proxy/ya.make

issue-2100: implement fallback mode for filestore SS proxy

---

cloud/filestore/libs/storage/ss_proxy/ss_proxy_fallback_actor.cpp
cloud/filestore/libs/storage/ss_proxy/ss_proxy_ut.cpp

issue-2100: fix TSSProxyTest.ShouldDescribeFileStoreInFallbackMode

---

cloud/blockstore/libs/common/block_range.h

добавляяю явно нужный инклуд, до этого приезжал неявно из утилёвого инклуда, который хочется почистить (comes from IGNIETFERRO-2096)

[Blockstore] add include that comes transparently

---

cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data_stress.cpp
cloud/filestore/libs/storage/testlib/test_env.h

followup for https://github.com/ydb-platform/nbs/pull/2229

moved ShouldHandleRangeIdCollisionsInCompactionMapStats to tablet_ut_data_stress

---

cloud/tasks/collect_lister_metrics_task.go
cloud/tasks/tasks_tests/tasks_test.go

[Disk Manager]: Report default hanging tasks metric value

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/diagnostics/critical_events.h
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_notify.cpp
cloud/blockstore/libs/storage/volume/CMakeLists.darwin-x86_64.txt
cloud/blockstore/libs/storage/volume/CMakeLists.linux-aarch64.txt
cloud/blockstore/libs/storage/volume/CMakeLists.linux-x86_64.txt
cloud/blockstore/libs/storage/volume/CMakeLists.windows-x86_64.txt
cloud/blockstore/libs/storage/volume/testlib/test_env.cpp
cloud/blockstore/libs/storage/volume/testlib/test_env.h
cloud/blockstore/libs/storage/volume/volume_actor_allocatedisk.cpp
cloud/blockstore/libs/storage/volume/volume_actor_read_history.cpp
cloud/blockstore/libs/storage/volume/volume_actor_read_meta_history.cpp
cloud/blockstore/libs/storage/volume/volume_events_private.h
cloud/blockstore/libs/storage/volume/volume_tx.h
cloud/blockstore/libs/storage/volume/volume_ut.cpp
cloud/blockstore/libs/storage/volume/ya.make

[stable-23-3] Add possibility to do lite reallocations

---

cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data_stress.cpp
cloud/filestore/libs/storage/testlib/test_env.h

ut_data suite sometimes times out

moved heavy uts ShouldTruncateLargeFiles and ShouldTruncateLargeFiles128_KB to tablet_ut_data_stress.cpp

---

cloud/blockstore/libs/disk_agent/bootstrap.cpp
cloud/storage/core/libs/http/simple_http_server.cpp
cloud/storage/core/libs/http/simple_http_server.h

Fix Simple HTTP server listening address

---

cloud/disk_manager/internal/pkg/services/pools/config/config.proto
cloud/disk_manager/internal/pkg/services/pools/optimize_base_disks_task.go
cloud/disk_manager/internal/pkg/services/pools/optimize_base_disks_task_test.go

https://github.com/ydb-platform/nbs/issues/2130

[Disk Manager] Fix base disk pools changing their size

---

cloud/storage/core/tools/ops/config_generator/main.go

issue-2263: generate nfs-vhost-local.txt config file

---

cloud/blockstore/libs/storage/core/disk_counters.cpp
cloud/blockstore/libs/storage/core/disk_counters.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_readblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_writeblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_ut.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_ut.cpp
cloud/blockstore/libs/storage/volume/volume_ut_stats.cpp

[NBS] add label "transport" to read/writeblocks counters 

---

cloud/blockstore/libs/storage/init/disk_agent/actorsystem.cpp
cloud/blockstore/libs/storage/init/server/actorsystem.cpp
cloud/filestore/libs/storage/init/actorsystem.cpp
cloud/storage/core/libs/kikimr/kikimr_initializer.cpp
cloud/storage/core/libs/kikimr/kikimr_initializer.h
cloud/storage/core/libs/kikimr/ya.make

issue-2250: start ydb grpc proxy to enable web monitoring authorization

---

cloud/blockstore/libs/storage/core/disk_counters.cpp
cloud/blockstore/libs/storage/core/disk_counters.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_readblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_writeblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_ut.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_ut.cpp
cloud/blockstore/libs/storage/volume/volume_ut_stats.cpp

* add label "transport" to counters

[NBS] add label "transport" to read/writeblocks counters  (#2235)

---

cloud/blockstore/public/sdk/go/client/durable.go
cloud/disk_manager/internal/pkg/clients/nbs/factory.go
cloud/tasks/tracing/init.go

https://github.com/ydb-platform/nbs/issues/1199

[Disk Manager] tracing: add events on retries in blockstore Go SDK

---

cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/tablet/CMakeLists.darwin-x86_64.txt
cloud/filestore/libs/storage/tablet/CMakeLists.linux-aarch64.txt
cloud/filestore/libs/storage/tablet/CMakeLists.linux-x86_64.txt
cloud/filestore/libs/storage/tablet/CMakeLists.windows-x86_64.txt
cloud/filestore/libs/storage/tablet/tablet_actor.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_loadstate.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_loadstate_noderefs.cpp
cloud/filestore/libs/storage/tablet/tablet_database.cpp
cloud/filestore/libs/storage/tablet/tablet_database.h
cloud/filestore/libs/storage/tablet/tablet_private.h
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_cache.cpp
cloud/filestore/libs/storage/tablet/tablet_state_cache.h
cloud/filestore/libs/storage/tablet/tablet_state_iface.h
cloud/filestore/libs/storage/tablet/tablet_state_nodes.cpp
cloud/filestore/libs/storage/tablet/tablet_tx.h
cloud/filestore/libs/storage/tablet/tablet_ut_cache.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp
cloud/filestore/libs/storage/tablet/ya.make

fc27cb9507932b2f837f049c5161829de7dcba9b

[Filestore merge-to-stable] issue-1146: load NodeRefs upon tablet load

---

cloud/storage/core/libs/coroutine/executor.h

issue-2233: fix one more clang18 compiler errors

---

cloud/tasks/execution_context.go
cloud/tasks/runner_test.go

[Tasks] fix hanging tasks metric that was broken after #2016

---

cloud/filestore/libs/storage/tablet/tablet_actor.cpp
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp

issue-2137: ordering Compaction ranges by GarbageScore for Garbage-triggered Compaction

---

cloud/blockstore/libs/endpoints/endpoint_manager.cpp
cloud/blockstore/libs/nbd/utils.cpp
cloud/blockstore/libs/nbd/utils.h
cloud/blockstore/libs/nbd/utils_ut.cpp

cherry-pick: 47a9000027d66cc50353d7b043c0a5131fa89dad

merge to stable-23-3: revert NBSNEBIUS-199

---

cloud/blockstore/libs/diagnostics/critical_events.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_secure_erase.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut.cpp
cloud/blockstore/libs/storage/disk_registry/model/pending_cleanup.cpp
cloud/blockstore/libs/storage/disk_registry/model/pending_cleanup.h
cloud/blockstore/libs/storage/disk_registry/model/pending_cleanup_ut.cpp
cloud/storage/core/libs/diagnostics/critical_events.cpp

PendingCleanup insert can fail now

---

cloud/filestore/tests/loadtest/service-kikimr-emergency-test/ya.make

issue-2100: temporarily make service-kikimr-emergency-test large

---

cloud/filestore/tests/loadtest/service-kikimr-emergency-test/ya.make

[merge-to-stable-23-3] issue-2100: temporarily make service-kikimr-emergency-test large (#2334)

---

cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/tablet/model/compaction_map.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_compaction.cpp
cloud/filestore/libs/storage/tablet/tablet_tx.h
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp

issue-2137: implemented ability to skip compaction ranges which are almost perfectly compacted (will speed-up full compaction by orders of magnitude)

---

cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_monitoring.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_counters.cpp

issue-2137: CMGarbageBlocksCount metric + Top ranges by GarbageBlocksCount on monpage

---

cloud/filestore/libs/storage/service/service_actor.h
cloud/filestore/libs/storage/service/service_actor_actions.cpp
cloud/filestore/libs/storage/service/service_actor_actions_stats.cpp
cloud/filestore/libs/storage/service/service_actor_actions_unsafe_node_ops.cpp
cloud/filestore/libs/storage/service/service_actor_actions_ut.cpp
cloud/filestore/libs/storage/service/tablet_action_actor.cpp
cloud/filestore/libs/storage/service/tablet_action_actor.h
cloud/filestore/libs/storage/service/ya.make

The most important thing in GetStorageStats is the ability to fetch Compaction ranges sorted by BlobsCount/DeletionsCount/GarbageBlocksCount
#2137

issue-2137: GetStorageStats private API action

---

cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_counters.cpp

issue-2137: MaxGarbageBlocksInRange metric

---

cloud/filestore/tools/analytics/profile_tool/lib/dump_events.cpp

filestore-profile-tool now supports request filtering by request name, not only type

---

cloud/blockstore/libs/endpoint_proxy/server/bootstrap.cpp
cloud/blockstore/tests/csi_driver/lib/csi_runner.py
cloud/blockstore/tests/python/lib/endpoint_proxy.py

1. set EndpointProxySocketPath to run csi tests with endpoint proxy/netlink devices
2. configure log level for endpoint proxy

NBSDUTY-135: run csi tests with endpoint proxy & configure log level

---

cloud/filestore/libs/service_local/fs_data.cpp
cloud/filestore/libs/service_local/service_ut.cpp
cloud/filestore/libs/vfs_fuse/fs_impl_data.cpp
cloud/storage/core/libs/common/aligned_buffer.cpp
cloud/storage/core/libs/common/aligned_buffer.h
cloud/storage/core/libs/common/aligned_buffer_ut.cpp

- AccessBuffer -> TakeBuffer
- (void*) -> static_cast<void*>
- remove ExtractAlignedData

refactor aligned buffer

---

cloud/filestore/libs/service_local/fs_data.cpp
cloud/filestore/libs/service_local/service_ut.cpp
cloud/filestore/libs/vfs_fuse/fs_impl_data.cpp
cloud/storage/core/libs/common/aligned_buffer.cpp
cloud/storage/core/libs/common/aligned_buffer.h
cloud/storage/core/libs/common/aligned_buffer_ut.cpp

- **Fix msan test flakiness (#2347)**
- **refactor aligned buffer (#2358)**

[merge to stable] Fix msan test flakiness, refactor aligned buffer

---

cloud/blockstore/libs/logbroker/topic_api_impl/ya.make

Because of https://github.com/ydb-platform/ydb/issues/10992

NBSDUTY-136: mute tsan tests for topic api

---

cloud/blockstore/tools/csi_driver/internal/driver/node.go

issue: #2285
1. Return back chmod calls. these calls were removed [here](https://github.com/ydb-platform/nbs/pull/2326/files#diff-021fd610a4ef17348cd72682382ac75500e3207f4f055627a06300ba7c962f9eL1156) It's not enough to pass required permissions to create file as permissions can be modified by umask.
2. check that mount point already exists to make "read-only" publish volume calls idempotent. Otherwise second NodePublishVolume call fails on chmod.

issue-2285: use chmod to set access permissions

---

cloud/disk_manager/api/disk.proto
cloud/disk_manager/internal/pkg/clients/nbs/client.go
cloud/disk_manager/internal/pkg/services/disks/service.go
cloud/disk_manager/internal/pkg/types/types.proto
cloud/disk_manager/pkg/admin/disks.go

https://github.com/ydb-platform/nbs/issues/2307
Следом за https://github.com/ydb-platform/nbs/pull/2291 добавляю новый тип диска в DM

Add HDD local disks to disk manager

---

cloud/blockstore/vhost-server/backend_aio.cpp
cloud/blockstore/vhost-server/backend_null.cpp
cloud/blockstore/vhost-server/gtest/ya.make
cloud/blockstore/vhost-server/options.cpp
cloud/blockstore/vhost-server/options.h
cloud/blockstore/vhost-server/request_aio.cpp
cloud/blockstore/vhost-server/request_aio.h
cloud/blockstore/vhost-server/request_aio_ut.cpp
cloud/blockstore/vhost-server/server_ut.cpp
cloud/blockstore/vhost-server/ut/ya.make

https://github.com/ydb-platform/nbs/issues/2307
Добавил возможность vhost_aio работать с блоком любого размера. Задаётся через command line. Сам параметр уже был, т.к. он используется в RDMA.

Add support for variable block size in the vhost server

---

cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/service/service_actor_readdata.cpp
cloud/filestore/libs/storage/service/service_actor_writedata.cpp
cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_createsession.cpp
cloud/filestore/libs/storage/testlib/test_env.cpp
cloud/filestore/public/api/protos/fs.proto

issue-2376: implement special switches to disable TwoStageReads and ThreeStageWrites for hdd fs

---

cloud/filestore/apps/client/lib/execute_action.cpp
cloud/filestore/apps/client/lib/factory.cpp
cloud/filestore/apps/client/lib/forced_compaction.cpp
cloud/filestore/apps/client/lib/ya.make
cloud/filestore/tests/client/canondata/result.json
cloud/filestore/tests/client/canondata/test.test_forced_compaction/results.txt
cloud/filestore/tests/client/test.py
cloud/filestore/tests/python/lib/client.py

issue-2137: filestore-client forcedcompaction command

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_register.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_config.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_create.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_mirrored_disks.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_suspend.cpp
cloud/blockstore/libs/storage/disk_registry/testlib/test_state.cpp

issue-2074: tweak agent registration

---

cloud/storage/core/libs/grpc/init.cpp

Recommendations from TSAN developers: https://github.com/google/sanitizers/issues/1415#issuecomment-1176209745

teach TSAN to shut up and do not report data race in cloud/storage/core/libs/grpc/init.cpp

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.cpp
cloud/blockstore/libs/storage/disk_registry/testlib/test_env.h
cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp

Подготовка к обновлению С++ SDK в аркадии.

Fix includes

---

cloud/blockstore/config/disk.proto
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_init.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_private.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_state.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_state.h
cloud/blockstore/libs/storage/disk_agent/storage_initializer.cpp
cloud/blockstore/libs/storage/disk_agent/storage_initializer.h
cloud/blockstore/libs/storage/disk_agent/storage_initializer_ut.cpp
cloud/blockstore/libs/storage/disk_agent/ut/ya.make

#2074
Detect a change in the device serial number during agent initialization (using the config cache).

issue-2074: serial number change detection

---

cloud/blockstore/tools/csi_driver/internal/driver/node.go

issue: #1657 
ResizeDevice method will be removed in the next pull request https://github.com/ydb-platform/nbs/pull/2028

issue-1657: use refresh endpoint method to resize device

---

cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp

issue-2141: resync range after scrubbing mismatch only if majority of checksums are equal

---

cloud/blockstore/tests/csi_driver/lib/csi_runner.py
cloud/blockstore/tests/e2e-tests/test.py

Use default retryTimeout(5 minutes) instead of hardcoded 1 millisecond

test: use default retry timeout

---

cloud/blockstore/libs/endpoints/endpoint_manager.cpp
cloud/blockstore/libs/endpoints/endpoint_manager_ut.cpp
cloud/blockstore/tools/csi_driver/internal/driver/node.go

This reverts commit b6734bce482c7f09150c9092625b0e006d549488.
issue: #2270

Revert "issue-2270: return error if nbd device name is missing (#2375)"

---

cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/service/service_actor_readdata.cpp
cloud/filestore/libs/storage/service/service_actor_writedata.cpp
cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_createsession.cpp
cloud/filestore/libs/storage/testlib/test_env.cpp
cloud/filestore/public/api/protos/fs.proto

* issue-2376: implement special switches to disable TwoStageReads and ThreeStageWrites for hdd fs
* update
* update

[merge-to-stable-23-3] issue-2376: implement special switches to disable TwoStageReads and ThreeStageWrites for hdd fs (#2377)

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/tests/python/lib/test_base.py

Починка флакнувшего теста https://github-actions-s3.website.nemax.nebius.cloud/ydb-platform/nbs/PR-check/11739424289/1/nebius-x86-64/summary/ya-test.html#FAIL

Fix race in test; fix DR pool metrics

---

cloud/filestore/config/filesystem.proto
cloud/filestore/config/server.proto
cloud/filestore/config/storage.proto
cloud/filestore/libs/service_local/config.cpp
cloud/filestore/libs/service_local/config.h
cloud/filestore/libs/service_local/fs_session.cpp
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/tablet/tablet_actor_createsession.cpp
cloud/filestore/libs/vfs_fuse/config.cpp
cloud/filestore/libs/vfs_fuse/config.h
cloud/filestore/libs/vfs_fuse/loop.cpp
cloud/filestore/public/api/protos/fs.proto
contrib/libs/fuse/include/fuse_common.h
contrib/libs/fuse/include/fuse_kernel.h
contrib/libs/fuse/lib/fuse_lowlevel.c

- **issue-1751: add WRITEBACK_CACHE flag to fuse contrib (#2430)**
- **[Filestore] issue-1751: support guest writeback cache (#2397)**

[merge-to-stable-23-3] [Filestore] issue-1751: support guest writeback cache

---

cloud/filestore/libs/vfs_fuse/fs_impl.cpp
cloud/filestore/libs/vfs_fuse/fs_impl.h
cloud/filestore/libs/vfs_fuse/fs_impl_data.cpp
cloud/filestore/libs/vfs_fuse/fs_ut.cpp
cloud/filestore/libs/vfs_fuse/handle_ops_queue.cpp
cloud/filestore/libs/vfs_fuse/handle_ops_queue.h

issue-1541: postpone DestroyHandle request if HandleOpsQueue overflows

---

cloud/disk_manager/internal/pkg/dataplane/create_snapshot_from_disk_task.go

Scenario:
* Creating incremental snapshot
* Deleting incremental snapshot right after base checkpoint was deleted but before `storage.SnapshotCreated` was called
* Calling `storage.SnapshotCreated` returns an error like this `snapshot with id XXX and status deleting can't be created`
* Bingo, we have not created incremental snapshot but managed to corrupt state of the previous one (base snapshot) because its corresponding checkpoint is deleted

[Disk Manager] fix race where base checkpoint might be deleted even if incremental snapshot was not created successfully

---

cloud/storage/core/libs/common/persistent_table.h
cloud/storage/core/libs/common/persistent_table_ut.cpp

issue-2461: support clear operation on persistent table

---

cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_base_request.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_base_request.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_checksumblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_readblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_readblocks_local.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_writeblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_zeroblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/ya.make

Рефакторинг копипасты акторов, которые отправляют запросы в дискагент по интерконнекту.
Вынес общий код в TDiskAgentBaseRequestActor.

Refactor nonrepl requests

---

cloud/filestore/libs/storage/api/tablet.h
cloud/filestore/libs/storage/service/service_actor_destroyfs.cpp
cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.cpp
cloud/filestore/private/api/protos/tablet.proto

automatic shard creation was implemented here: https://github.com/ydb-platform/nbs/pull/2415
automatic shard destruction is implemented in this PR
automatic shard addition upon resize will be implemented in the next PR
#1932

issue-1932: automatically destroying filesystem shards during main filesystem destruction

---

cloud/blockstore/libs/storage/partition_nonrepl/CMakeLists.linux-x86_64.txt
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_base_request.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_base_request.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_checksumblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_readblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_readblocks_local.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_writeblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_zeroblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/ya.make

* Refactor nonrepl requests
* Remove TOperationCompleted coping
* Simplify message dispatching

23-3. Refactor nonrepl requests (#2453)

---

cloud/filestore/libs/vfs_fuse/fs_impl.cpp
cloud/filestore/libs/vfs_fuse/fs_impl.h
cloud/filestore/libs/vfs_fuse/fs_impl_data.cpp
cloud/filestore/libs/vfs_fuse/fs_ut.cpp
cloud/filestore/libs/vfs_fuse/handle_ops_queue.cpp
cloud/filestore/libs/vfs_fuse/handle_ops_queue.h

…s (#2394)
* postpone DestroyHandle request if HandleOpsQueue overflows
* get rid of unnecessary copying
* fix issue
* fix issues

Merge 23-3: postpone DestroyHandle request if HandleOpsQueue overflows

---

cloud/blockstore/libs/endpoints/endpoint_manager.cpp
cloud/blockstore/libs/endpoints/endpoint_manager_ut.cpp
cloud/blockstore/libs/endpoints/ut/ya.make
cloud/blockstore/tests/e2e-tests/test.py
cloud/blockstore/tests/e2e-tests/ya.make

issue-2387: remove endpoint if volume is not found

---

cloud/filestore/libs/storage/tablet/tablet_ut_cache_stress.cpp
cloud/filestore/libs/storage/tablet/ut_cache_stress/ya.make
cloud/filestore/libs/storage/tablet/ya.make
cloud/filestore/libs/storage/testlib/tablet_client.h

issue-1146: add stress test comparing tablet performance with and without cache enabled

---

cloud/blockstore/libs/storage/core/tablet_schema.h
cloud/blockstore/libs/storage/service/service_ut_create.cpp
cloud/filestore/libs/storage/core/tablet_schema.h
cloud/storage/core/libs/auth/authorizer_ut.cpp

В аркадии очередное подлитие, которое разломало компиляцию.

Fix arcadia sync

---

cloud/storage/core/tools/common/python/daemon.py
cloud/storage/core/tools/testing/unstable-process/__main__.py
cloud/storage/core/tools/testing/unstable-process/ya.make

issue-2500: unstable-process will dump backtrace when terminating process is stuck

---

cloud/filestore/libs/storage/core/model.cpp
cloud/filestore/libs/storage/service/service_actor_alterfs.cpp
cloud/filestore/libs/storage/service/service_actor_destroyfs.cpp
cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/tests/client_sharded/canondata/result.json
cloud/filestore/tests/client_sharded/canondata/test.test_shard_autoaddition/results.txt
cloud/filestore/tests/client_sharded/nfs-storage.txt
cloud/filestore/tests/client_sharded/test.py
cloud/filestore/tests/client_sharded/ya.make
cloud/filestore/tests/ya.make

automatic shard creation was implemented here: https://github.com/ydb-platform/nbs/pull/2415
automatic shard destruction was implemented here: https://github.com/ydb-platform/nbs/pull/2481
automatic shard addition upon resize is implemented in this PR
#1932

issue-1932: automatic shard addition upon filestore resize

---

cloud/filestore/libs/storage/tablet/tablet_actor_resetsession.cpp
cloud/filestore/libs/storage/tablet/tablet_tx.h
cloud/filestore/libs/storage/tablet/tablet_ut_cache.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_cache_stress.cpp

issue-1146: resetsession should update in-memory cache as it can modify node index

---

cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
cloud/filestore/libs/storage/tablet/tablet_state.cpp
cloud/filestore/libs/storage/tablet/tablet_state_cache.cpp
cloud/filestore/libs/storage/tablet/tablet_state_cache.h
cloud/filestore/libs/storage/tablet/tablet_ut_cache.cpp

issue-1146: base cache capacity calculations relative to the MaxNodes value, add cache capacity sensors

---

cloud/storage/core/tools/common/python/daemon.py
cloud/storage/core/tools/testing/unstable-process/__main__.py

Fix arcadia linter

---

cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_updateconfig.cpp
cloud/filestore/libs/storage/testlib/service_client.h
cloud/filestore/tests/client_sharded/canondata/test.test_shard_autoaddition/results.txt
cloud/filestore/tests/client_sharded/test.py

issue-1932: rebooting tablet after shard list reconfiguration to force the clients to recreate their sessions and fetch new shard lists

---

cloud/blockstore/tools/testing/eternal_tests/test_runner/lib/main.py

Cut out functions that don't rely on `EternalTestHelper`'s instance out from the class

[Misc] Cut some some functions from EternalTestHelper class

---

cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_base_request.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_common.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_common.h

Move code to part_nonrepl_common.cpp file

---

cloud/disk_manager/internal/pkg/services/disks/migrate_disk_task.go
cloud/disk_manager/internal/pkg/services/pools/storage/mocks/storage_mock.go
cloud/disk_manager/internal/pkg/services/pools/storage/storage.go
cloud/disk_manager/internal/pkg/services/pools/storage/storage_ydb.go

https://github.com/ydb-platform/nbs/issues/1806

[Disk Manager] fix race in migrate task

---

cloud/blockstore/tests/csi_driver/e2e_tests_nfs/test.py
cloud/blockstore/tests/csi_driver/e2e_tests_nfs/ya.make
cloud/blockstore/tests/csi_driver/lib/csi_runner.py
cloud/blockstore/tests/csi_driver/lib/ya.make
cloud/blockstore/tools/csi_driver/client/main.go
cloud/blockstore/tools/csi_driver/cmd/nbs-csi-driver/main.go
cloud/blockstore/tools/csi_driver/internal/driver/controller.go
cloud/blockstore/tools/csi_driver/internal/driver/controller_test.go
cloud/blockstore/tools/csi_driver/internal/driver/driver.go
cloud/blockstore/tools/csi_driver/internal/driver/node.go
cloud/blockstore/tools/csi_driver/internal/driver/node_test.go
cloud/filestore/tests/python/lib/vhost.py

[Filestore] issue-2547: support local filesystems overrides in csi driver

---

cloud/blockstore/apps/server/main.cpp
cloud/blockstore/apps/server/ya.make
cloud/blockstore/config/root_kms.proto
cloud/blockstore/config/ya.make
cloud/blockstore/libs/daemon/common/bootstrap.cpp
cloud/blockstore/libs/daemon/common/bootstrap.h
cloud/blockstore/libs/daemon/local/bootstrap.h
cloud/blockstore/libs/daemon/ydb/bootstrap.cpp
cloud/blockstore/libs/daemon/ydb/bootstrap.h
cloud/blockstore/libs/daemon/ydb/config_initializer.cpp
cloud/blockstore/libs/daemon/ydb/config_initializer.h
cloud/blockstore/libs/daemon/ydb/options.cpp
cloud/blockstore/libs/daemon/ydb/options.h
cloud/blockstore/libs/daemon/ydb/ya.make
cloud/blockstore/libs/root_kms/impl/client.cpp
cloud/blockstore/libs/root_kms/impl/client.h
cloud/blockstore/libs/root_kms/impl/client_ut.cpp

Setup RootKMS client & key provider via the command line parameter `--root-kms-file` and CMS.

issue-176: setup root kms client & key provider

---

cloud/blockstore/libs/daemon/common/bootstrap.cpp
cloud/filestore/libs/daemon/common/bootstrap.cpp
cloud/storage/core/libs/diagnostics/critical_events.cpp
cloud/storage/core/libs/diagnostics/critical_events.h

https://github.com/ydb-platform/nbs/commit/d3cd2bf9736419401e9bba9ea565b178ad70e8a7

merge to stable-23-3: Write all crit events to cerr (#696)

---

cloud/blockstore/vhost-server/server_ut.cpp

Fix https://github-actions-s3.website.nemax.nebius.cloud/ydb-platform/nbs/Nightly-build-(ubsan)/12077560734/1/nebius-x86-64-ubsan/test_data/actions-runner/_work/nbs/nbs/cloud/blockstore/vhost-server/gtest/test-results/gtest/chunk4/testing_out_stuff/TServerTest.ShouldStatAllZeroesBlocks.ENCRYPTION_AES_XTS_bc2_bs4096_unaligned.err

Fix test flakyness

---

cloud/filestore/config/server.proto
cloud/filestore/libs/service_local/config.cpp
cloud/filestore/libs/service_local/config.h
cloud/filestore/libs/service_local/fs_session.cpp

issue-1541: pass AsyncDestroy config options in local service

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/tests/infra-cms/test.py

#2606 
Просто флаг без изменения поведения

Separate config flag for forgetting devices

---

cloud/blockstore/libs/storage/api/disk_agent.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_direct_copy.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_ut.cpp
cloud/blockstore/libs/storage/disk_agent/testlib/test_env.cpp
cloud/blockstore/libs/storage/disk_agent/testlib/test_env.h
cloud/blockstore/libs/storage/disk_agent/ya.make
cloud/blockstore/libs/storage/protos/disk.proto

Второй ПР по задаче https://github.com/ydb-platform/nbs/issues/2368
Здесь учу DiskAgent обрабатывать новый запрос TDirectCopyBlocksRequest, он должен прочитать данные у себя и записать на другого агента.

Introduce DiskAgent method DirectCopyBlocks

---

cloud/blockstore/libs/common/iovector.cpp
cloud/blockstore/libs/common/iovector.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_direct_copy.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_ut.cpp
cloud/blockstore/libs/storage/protos/disk.proto

Третья часть  https://github.com/ydb-platform/nbs/issues/2368
Здесь диск агент учится:
1. возвращать в ответе сколько времени ушло на чтение и запись
2. возвращать, все ли содержимое было заполнено нулями

Use ZeroBlocks request in DirectCopy

---

cloud/filestore/libs/storage/service/service_actor_actions_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_monitoring.cpp
cloud/filestore/libs/storage/tablet/tablet_private.h
cloud/filestore/private/api/protos/tablet.proto

issue-2559: collecting per-shard stats in main tablet, reporting AggregateUsedBytesCount, reporting per-shard stats on tablet monpage

---

cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_monitoring.cpp
cloud/filestore/libs/storage/tablet/tablet_private.h
cloud/filestore/private/api/protos/tablet.proto

issue-2381: aggregating Suffer stats from shards

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp

issue-2637: remove limits at list rendering

---

cloud/filestore/libs/storage/service/service_actor_createnode.cpp
cloud/filestore/libs/storage/tablet/model/shard_balancer.cpp
cloud/filestore/libs/storage/tablet/model/shard_balancer.h
cloud/filestore/libs/storage/tablet/model/ya.make
cloud/filestore/libs/storage/tablet/tablet_actor_createhandle.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_createnode.cpp
cloud/filestore/libs/storage/tablet/tablet_state.cpp
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
cloud/filestore/libs/storage/tablet/tablet_state_impl.h
cloud/filestore/libs/storage/tablet/tablet_tx.h

In the next PR I will commit the version of the balancer which will take shard free space into account
#2559

issue-2559: dummy tablet-level shard balancer which behaves exactly the same as service-level shard balancer

---

cloud/blockstore/config/diagnostics.proto
cloud/blockstore/libs/diagnostics/config.h
cloud/blockstore/libs/diagnostics/hostname.cpp
cloud/blockstore/libs/diagnostics/hostname.h
cloud/blockstore/libs/storage/partition/part_actor_monitoring.cpp
cloud/blockstore/libs/storage/partition2/part2_actor_monitoring.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_monitoring.cpp
cloud/storage/core/libs/viewer/tablet_monitoring.cpp
cloud/storage/core/libs/viewer/tablet_monitoring.h

#2656
При добавлении соответствующих параметров конфига в списке каналов появится ссылка на дашборд группы:

Issue-2656: Add optional dashboard link

---

cloud/blockstore/libs/endpoints/endpoint_manager.cpp
cloud/blockstore/libs/endpoints/ya.make
cloud/filestore/libs/endpoint/endpoint_manager.cpp
cloud/filestore/libs/endpoint/endpoint_manager_ut.cpp
cloud/filestore/libs/endpoint/ya.make
cloud/filestore/public/sdk/python/client/endpoint.py
cloud/filestore/tests/endpoints/test.py
cloud/filestore/tests/endpoints/ya.make
cloud/filestore/tests/recipes/vhost-restore-endpoint.inc
cloud/filestore/tests/recipes/vhost-restore-endpoint/__main__.py
cloud/filestore/tests/recipes/vhost-restore-endpoint/ya.make
cloud/filestore/tests/recipes/vhost-restore-endpoint/ya.make.inc
cloud/filestore/tests/recipes/vhost/__main__.py
cloud/filestore/tests/ya.make

issue: #2553
Remove endpoint if restore endpoint fails with "filesystem is not found" error

issue-2553: remove endpoint if filesystem is not found 

---

cloud/blockstore/apps/client/lib/command.cpp
cloud/filestore/apps/client/lib/app.cpp
cloud/filestore/apps/client/lib/app.h
cloud/filestore/apps/client/lib/bootstrap.cpp
cloud/filestore/apps/client/lib/bootstrap.h
cloud/filestore/apps/client/lib/command.cpp
cloud/filestore/apps/client/lib/command.h
cloud/filestore/apps/client/lib/factory.h
cloud/filestore/apps/client/lib/ya.make
cloud/filestore/apps/client/main.cpp
cloud/filestore/apps/client/ya.make
cloud/filestore/config/client.proto
cloud/filestore/config/ya.make

issue-2631: add iam token support to filestore-client

---

.github/actions/build/action.yaml
.github/actions/build_cmake/action.yaml
.github/actions/nebius_cli/action.yaml
.github/actions/prepare/action.yaml
.github/actions/s3cmd/action.yaml
.github/actions/ssh_keys/action.yaml
.github/actions/test/action.yaml
.github/actions/test_cmake/action.yaml
.github/scripts/shell-extractor.py
.github/workflows/github_actions_scripts.yaml
.github/workflows/packer.yaml
.github/workflows/pr-github-actions.yaml
.github/workflows/pr.yaml

Shell extractor walks through actions/workflows and extracts all shell commands to .temporary dir. After that we launch shellcheck on those commands.
This PR consists of, basically, three parts: extractor script, fixes to pr check workflow and fixes for those shell commands

feat: add shell extractor script and fix shellcheck errors in scripts inside actions/workflows

---

cloud/tasks/scheduler_impl.go

https://github.com/ydb-platform/nbs/issues/1199
Now spans for regular are inconvenient. Tasks have no common parent. For example, if a regular tasks had several generations, each generation will create spans in separate trace.
In this pr we create common parent span for spans created by a regular task.

[Disk Manager] add parent span for regular tasks

---

cloud/storage/core/libs/common/thread_pool.cpp
cloud/storage/core/libs/common/thread_pool.h

To more detailed stats, TThreadPool setups the memory scope tag

Setup memory scope tag to TThreadPool

---

cloud/blockstore/tools/testing/eternal_tests/test_runner/lib/main.py

Была такая ошибка при попытке установки дб тестов:
bash: line 1: /usr/bin/postgresql-nfs.sh: Text file busy
Была вызвана тем, что через scp скрипт отправлялся на сервер, и сразу же пытался запуститься до того как его отпустил sftp-server

Fix eternal nfs db tests

---

cloud/filestore/libs/storage/tablet/tablet_actor.cpp
cloud/filestore/libs/storage/tablet/tablet_state_sessions.cpp

issue-2710: logging operations with SessionByOwner mapping

---

cloud/blockstore/libs/storage/core/disk_counters.h
cloud/blockstore/libs/storage/partition_nonrepl/copy_range.cpp
cloud/blockstore/libs/storage/partition_nonrepl/direct_copy_range.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_events_private.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_stats.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_ut.cpp
cloud/blockstore/libs/storage/volume/actors/shadow_disk_actor.cpp
cloud/blockstore/libs/storage/volume/actors/shadow_disk_actor.h
cloud/blockstore/libs/storage/volume/testlib/test_env.cpp
cloud/blockstore/libs/storage/volume/testlib/test_env.h
cloud/blockstore/libs/storage/volume/ut/ya.make
cloud/blockstore/libs/storage/volume/volume_ut_stats.cpp

Продолжение https://github.com/ydb-platform/nbs/issues/2368
Добавляю статистику на операцию прямого копирования блоков. Статистика учитывается на диск источника в новое поле  CopyBlocks

Statistics for DirectBlockCopy

---

cloud/blockstore/tests/python/lib/nbs_runner.py

save ydbd stdout/stderr to investigate e2e tests failures

NBSDUTY-190: save ydbd stdout/stderr

---

cloud/filestore/libs/storage/service/service_ut_sharding.cpp
cloud/filestore/libs/storage/tablet/model/shard_balancer.cpp
cloud/filestore/libs/storage/tablet/model/shard_balancer.h
cloud/filestore/libs/storage/tablet/model/shard_balancer_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_state.cpp

issue-2559: ShardBalancer: blocks vs bytes fix + service_ut_sharding testcase

---

cloud/blockstore/libs/disk_agent/bootstrap.cpp

issue-2713: add version on DA stub mon page

---

cloud/filestore/libs/storage/service/service_ut_sharding.cpp
cloud/filestore/libs/storage/tablet/model/shard_balancer.h

issue-2559: initializing BlockSize + added comments to ut

---

cloud/filestore/libs/diagnostics/critical_events.h
cloud/filestore/libs/storage/service/service_ut_sharding.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp

issue-2559: shard metrics collection and critical event

---

cloud/filestore/libs/storage/core/model.cpp
cloud/filestore/libs/storage/core/model.h
cloud/filestore/libs/storage/core/model_ut.cpp
cloud/filestore/libs/storage/service/service_actor_alterfs.cpp
cloud/filestore/libs/storage/service/service_actor_createfs.cpp
cloud/filestore/libs/storage/service/service_ut_sharding.cpp
cloud/filestore/libs/storage/testlib/service_client.h
cloud/filestore/public/api/protos/fs.proto

issue-1932: ability to set ShardCount explicitly via T{Create,Resize}FileStoreRequest

---

cloud/filestore/apps/client/lib/cache_warmup.cpp
cloud/filestore/apps/client/lib/factory.cpp
cloud/filestore/apps/client/lib/find.cpp
cloud/filestore/apps/client/lib/ya.make
cloud/filestore/tests/client/canondata/result.json
cloud/filestore/tests/client/canondata/test.test_find/results.txt
cloud/filestore/tests/client/test.py
cloud/filestore/tests/python/lib/client.py

issue-1146: filestore-client find command

---

cloud/blockstore/tools/csi_driver/internal/driver/node.go
cloud/blockstore/tools/csi_driver/internal/driver/node_test.go

[CSI] Forbid to execute several operations with the same volume in parallel

---

cloud/storage/core/libs/common/error.h
cloud/storage/core/protos/error.proto
doc/blockstore/diagnostics/result-codes.md

[NBS] Document result codes

---

cloud/filestore/libs/service_local/lowlevel.cpp

#2784 
similar approach taken here
https://gitlab.com/virtio-fs/virtiofsd/-/blob/3bf77b7cfa42b23935968c757a4f22ed31bc35d6/src/passthrough/util.rs#L39

[Filestore] issue-2784: ignore user O_NOFOLLOW flag when opening file through /proc/self/fd

---

cloud/filestore/apps/client/lib/start_endpoint.cpp

[Filestore] issue-2788: allow specifying vhost queue count in filestore-client startendpoint command

---

cloud/filestore/apps/client/lib/command.cpp
cloud/filestore/apps/client/lib/command.h
cloud/filestore/apps/client/lib/diff.cpp
cloud/filestore/apps/client/lib/factory.cpp
cloud/filestore/apps/client/lib/find.cpp
cloud/filestore/apps/client/lib/find_garbage.cpp
cloud/filestore/apps/client/lib/ya.make
cloud/filestore/tests/client/canondata/result.json
cloud/filestore/tests/client/canondata/test.test_diff/results.txt
cloud/filestore/tests/client/test.py
cloud/filestore/tests/python/lib/client.py

issue-2674: implemented filestore-client diff command - will use it for sharded vs non-sharded filesystem integration tests

---

cloud/filestore/apps/client/lib/create.cpp
cloud/filestore/apps/client/lib/resize.cpp
cloud/filestore/tests/client_sharded/canondata/result.json
cloud/filestore/tests/client_sharded/canondata/test.test_explicit_shard_count_addition/results.txt
cloud/filestore/tests/client_sharded/test.py
cloud/filestore/tests/python/lib/client.py

forgot to do it here https://github.com/ydb-platform/nbs/pull/2749
#1932

issue-1932: added explicit shard count setting (--shard-count) to filestore-client

---

cloud/filestore/tests/fio_index/mount-kikimr-test/ya.make
cloud/filestore/tests/recipes/mount/__main__.py

issue-2831 increase the verbosiy of fio_index/mount-kikimr-test and make it large

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp

Correcting rendering issue from pr: #2655

fix broken device rendering on disk registry mon page

---

cloud/blockstore/libs/storage/volume/actors/shadow_disk_actor.cpp
cloud/blockstore/libs/storage/volume/volume_ut_checkpoint.cpp

Обнаружил проблему: после перехода теневого диска в состояние Ready мы производили перезахват диска, но использовали короткий таймаут, как будто записи на основной диск заблокированы. Однако это не так и нужно использовать длинный таймаут.

Reacquire shadow disk to read-only after changed to ready with long timeout

---

cloud/filestore/tests/loadtest/service-kikimr-newfeatures-test/nfs-storage.txt

issue-1146: add InMemoryIndexCacheLoadOnTabletStart and InMemoryIndexCacheLoadOnTabletStartRowsPerTx flags to the newfeatures tests

---

cloud/filestore/libs/storage/service/service_ut_sharding.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_oplog.cpp

issue-2674: RenameNodeInDestination replay upon tablet start

---

cloud/disk_manager/internal/pkg/facade/testcommon/common.go

```
common.go:676: 
Error Trace:	/-S/cloud/disk_manager/internal/pkg/facade/testcommon/common.go:676
/-S/cloud/disk_manager/internal/pkg/facade/facade_test/facade_test.go:56
Error:      	Received unexpected error:
Get "http://localhost:21298/metrics/": dial tcp [::1]:21298: connect: connection refused
Test:       	TestFacadeShouldSendErrorMetrics
```

[Disk Manager] fix TestFacadeShouldSendErrorMetrics

---

cloud/filestore/libs/service_local/fs_data.cpp
cloud/filestore/libs/service_local/fs_node.cpp
cloud/filestore/libs/service_local/lowlevel.cpp
cloud/filestore/libs/service_local/lowlevel.h

[Filestore] issue-2813: use uid/gid from fuse context when creating node

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_state_benchmark.cpp
cloud/blockstore/tests/.gitignore
cloud/blockstore/tests/recipes/disk-registry-state/__main__.py

Исправил путь для генерации. Теперь он будет во временном каталоге, а не в репе.

Fix generated state file path

---

cloud/filestore/libs/storage/service/service_ut_sharding.cpp

sharding ut cleanup

---

cloud/filestore/libs/storage/service/service_ut_sharding.cpp

issue-2674: cross-shard RenameNode ut with error upon RenameNodeInDestination

---

cloud/filestore/tests/fio_index/mount-kikimr-test/ya.make

 issue-2831: suppress mount-kikimr-test in sanitizer builds

---

cloud/blockstore/libs/storage/core/config.h

correcting linter issues from pr #2704

issue-2703: correct linter problems

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/init/disk_agent/actorsystem.cpp
cloud/blockstore/libs/storage/init/server/actorsystem.cpp
cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/init/actorsystem.cpp

Add ydb viewer service option

---

cloud/storage/core/libs/hive_proxy/hive_proxy_events_private.h
cloud/storage/core/libs/hive_proxy/tablet_boot_info.h
cloud/storage/core/libs/hive_proxy/tablet_boot_info_backup.cpp
cloud/storage/core/libs/hive_proxy/tablet_boot_info_backup.h

[Filestore] add ListTabletBootInfoBackups request/response to TabletBootInfoBackup - later it will be used for booting tablets in emergency mode

---

example/nbs/nbs-storage.txt

Buttons made in https://github.com/ydb-platform/nbs/pull/2760

Enable change state of devices and agents from monpage

---

cloud/filestore/tests/fio_index/mount-kikimr-test/ya.make

 issue-2831: suppress mount-kikimr-test in all builds

---

.github/config/muted_ya_nebius.txt

issue-2831: mute cloud/filestore/tests/fio_index/qemu-{local,kikimr}-test

---

cloud/blockstore/tests/recipes/local-kikimr/__main__.py
cloud/filestore/tests/recipes/service-kikimr/__main__.py

В Аркадии происходят улучшения, и поменяли пути на красивые. Чтобы не переписать это при синке, делаю изменения в гитхабе.

Remove Berkanavt from path

---

cloud/blockstore/libs/storage/volume/volume_ut_session.cpp

fix sanitize issue in test from pr #2911

fix sanitize issue

---

cloud/blockstore/libs/client/session_ut.cpp
cloud/storage/core/libs/common/error.h

Раздебажил проблему с загоранием алертов:
1. сломался НРД, но клиент продолжает читать/писать на диск
2. первые 20минут отдается E_REJECTED, счетчик HWProblems инкрементируется, т.к. выставляется NCloud::NProto::EF_HW_PROBLEMS_DETECTED
3. по истечению таймаута в клиента отдается ошибка E_IO_SILENT тоже с флагом                 NCloud::NProto::EF_HW_PROBLEMS_DETECTED
4. по пути происходит конвертирование NProto::TError в TErrorResponse, который чуть позже снова конвертируется в NProto::TError
5. в процессе конвертаций флаги терялись, и счетчик HWProblems не инкрементировался https://github.com/ydb-platform/nbs/blob/main/cloud/blockstore/libs/client/session.cpp#L970

Fix the error of dropping the HwProblems flag when receiving E_IO_SILENT

---

cloud/blockstore/tests/csi_driver/e2e_tests_part2/test.py
cloud/blockstore/tools/csi_driver/internal/driver/node.go
cloud/blockstore/tools/csi_driver/internal/driver/node_test.go
cloud/blockstore/tools/csi_driver/internal/mounter/iface.go
cloud/blockstore/tools/csi_driver/internal/mounter/mock.go
cloud/blockstore/tools/csi_driver/internal/mounter/mounter.go

[CSI] NodePublishVolume must return error if FS was remounted to RO

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_state_benchmark.cpp
cloud/blockstore/tools/testing/disk-registry-state-generator/main.cpp

Benchmark for DiskAgent registration in DiskRegistry

Register agent benchmark

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp

На мон странице сейчас нигде не посмотреть тип диска с точки зрения DR. Исправляю это.

Add volume kind to DR mon page

---

cloud/blockstore/libs/storage/disk_agent/disk_agent_actor.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_register.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_stats.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_migration.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_publish_disk_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_secure_erase.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_volume_config.cpp
cloud/blockstore/libs/storage/disk_registry/testlib/test_env.h
cloud/blockstore/libs/storage/disk_registry_proxy/disk_registry_proxy_actor.cpp
cloud/blockstore/libs/storage/service/service_actor.cpp
cloud/blockstore/libs/storage/service/service_actor_actions_wait_dependent_disks_switched_node.cpp
cloud/blockstore/libs/storage/testlib/disk_agent_mock.h
cloud/blockstore/libs/storage/volume_balancer/volume_balancer_actor.cpp
cloud/filestore/libs/storage/service/service_actor.cpp
cloud/storage/core/libs/user_stats/user_stats_actor.cpp
contrib/ydb/library/actors/core/actor.cpp
contrib/ydb/library/actors/core/actor.h

Also revert
- https://github.com/ydb-platform/nbs/pull/2998
- https://github.com/ydb-platform/nbs/pull/3001

[Misc] Fix Arcadia build

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.cpp

Продолжение https://github.com/ydb-platform/nbs/pull/3012

Fix arcadia build

---

contrib/ydb/core/blobstorage/nodewarden/node_warden_group_resolver.cpp

https://github.com/ydb-platform/ydb/pull/13282

Backport https://github.com/ydb-platform/ydb/pull/13282

---

cloud/disk_manager/internal/pkg/facade/facade_test/facade_test.go

[Disk Manager] Fix race in facade metrics test

---

cloud/blockstore/libs/storage/volume/volume_actor.cpp

issue-3033: change floor to round

---

cloud/filestore/libs/endpoint/endpoint_manager.cpp
cloud/filestore/libs/endpoint/endpoint_manager_ut.cpp

issue-3017: restore filestore endpoints despite of missing socket directory

---

cloud/filestore/libs/vfs_fuse/handle_ops_queue.cpp
cloud/filestore/libs/vfs_fuse/handle_ops_queue.h
cloud/filestore/libs/vfs_fuse/ut/ya.make
cloud/filestore/libs/vfs_fuse/ya.make.inc
cloud/storage/core/libs/common/file_ring_buffer.cpp
cloud/storage/core/libs/common/file_ring_buffer.h
cloud/storage/core/libs/common/file_ring_buffer_ut.cpp
cloud/storage/core/libs/common/ut/ya.make
cloud/storage/core/libs/common/ya.make

[Filestore] move TFileRingBuffer to cloud/storage/core/libs/common - later it will be used for write-back cache

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_update_agent_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_cms.cpp
cloud/blockstore/libs/storage/disk_registry/testlib/test_env.h

issue-3015: doesn't schedule SwitchAgentDisksToReadOnly event after agent rm in UpdateAgentState

---

cloud/blockstore/libs/diagnostics/critical_events.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
cloud/blockstore/libs/storage/partition_nonrepl/ut_env.h
cloud/blockstore/libs/storage/service/service_actor_actions_modify_tags.cpp
cloud/blockstore/libs/storage/service/service_ut_actions.cpp
cloud/blockstore/libs/storage/testlib/service_client.cpp
cloud/blockstore/libs/storage/testlib/service_client.h

issue-2722: fix adding use-intermediate-write-buffer tag

---

cloud/filestore/libs/diagnostics/critical_events.h
cloud/filestore/libs/storage/service/service_ut_sharding.cpp
cloud/filestore/libs/storage/tablet/protos/tablet.proto
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_getnodeattr.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_oplog.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_renamenode.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_renamenode_destination.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_renamenode_source.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_unlinknode.cpp
cloud/filestore/libs/storage/tablet/tablet_state_iface.h
cloud/filestore/libs/storage/tablet/tablet_tx.h
cloud/filestore/libs/storage/testlib/service_client.h
cloud/filestore/private/api/protos/tablet.proto

issue-2674: add isExternal method to the nodeRef structure, extract TUnlinkNodeRequestInShard method, add UnlinkNode ut

---

cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_get_device_for_range.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_readblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor_readblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_ut.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_state.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_state.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_state_ut.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
cloud/blockstore/libs/storage/partition_nonrepl/ut_env.h
cloud/blockstore/public/api/protos/headers.proto

https://github.com/ydb-platform/nbs/issues/3005

added the ability to select the number of replicas to read from

---

cloud/filestore/config/filesystem.proto
cloud/filestore/config/server.proto
cloud/filestore/config/storage.proto
cloud/filestore/libs/service_local/config.cpp
cloud/filestore/libs/service_local/config.h
cloud/filestore/libs/service_local/fs_session.cpp
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/tablet/tablet_actor_createsession.cpp
cloud/filestore/libs/vfs_fuse/config.cpp
cloud/filestore/libs/vfs_fuse/config.h
cloud/filestore/libs/vfs_fuse/fs_impl_attr.cpp
cloud/filestore/libs/vfs_fuse/fs_impl_data.cpp
cloud/filestore/libs/vfs_fuse/loop.cpp
cloud/filestore/public/api/protos/fs.proto

[Filestore] issue-3045: Add flags to disable xattrs and guest page cache

---

cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_mirror.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_readblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor_forward.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_writeblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_zeroblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_events_private.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_mirror.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_writeblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_zeroblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_ut.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_ut.cpp
cloud/blockstore/libs/storage/volume/volume_actor.h
cloud/blockstore/libs/storage/volume/volume_actor_forward.cpp
cloud/blockstore/public/api/protos/headers.proto

[NBS] issue-3058: remove use of cookies for VolumeRequestId purposes

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_agent_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_device_state.cpp

[NBS] issue-2732: fix redirect after device/agent state change from monpage

---

cloud/blockstore/apps/client/lib/command.cpp
cloud/blockstore/config/client.proto
cloud/blockstore/libs/client/bench/main.cpp
cloud/blockstore/libs/client/config.cpp
cloud/blockstore/libs/client/config.h
cloud/blockstore/libs/client/durable.cpp
cloud/blockstore/libs/client/durable.h
cloud/blockstore/libs/client/durable_ut.cpp
cloud/blockstore/libs/endpoint_proxy/server/server.cpp
cloud/blockstore/libs/endpoints/endpoint_manager.cpp
cloud/blockstore/libs/endpoints/session_manager.cpp
cloud/blockstore/libs/endpoints_grpc/socket_endpoint_listener_ut.cpp
cloud/blockstore/libs/nbd/server_ut.cpp
cloud/blockstore/libs/server/server_test.cpp
cloud/blockstore/tools/nbd/bootstrap.cpp
cloud/blockstore/tools/testing/loadtest/lib/bootstrap.cpp
cloud/blockstore/vhost-server/backend_rdma.cpp
cloud/vm/blockstore/lib/plugin.cpp

[NBS] Parameters to set first retry delay by durable client

---

cloud/blockstore/libs/endpoints/session_manager.cpp

issue-3081: add weak ptr capture of TStorageDataClient

---

cloud/disk_manager/internal/pkg/facade/image_service_test/image_service_test.go
cloud/disk_manager/internal/pkg/facade/snapshot_service_test/snapshot_service_test.go
cloud/disk_manager/internal/pkg/services/images/create_image_from_disk_task.go
cloud/disk_manager/internal/pkg/services/snapshots/create_snapshot_from_disk_task.go

https://github.com/ydb-platform/nbs/issues/2923

[Disk Manager] Remove useless checkpoints after taking snapshot/image from disk registry-based disks

---

cloud/disk_manager/internal/pkg/clients/nbs/factory.go
cloud/disk_manager/internal/pkg/clients/nfs/factory.go

Print correct line number in nbs logs

[Disk Manager] Make line number reporting correct for NBS client #1401

---

cloud/blockstore/apps/client/lib/create_volume_link.cpp
cloud/blockstore/apps/client/lib/create_volume_link.h
cloud/blockstore/apps/client/lib/destroy_volume_link.cpp
cloud/blockstore/apps/client/lib/destroy_volume_link.h
cloud/blockstore/apps/client/lib/factory.cpp
cloud/blockstore/apps/client/lib/ya.make
cloud/blockstore/libs/service/auth_scheme.cpp
cloud/blockstore/libs/service/request.h
cloud/blockstore/libs/service/request_helpers.h
cloud/blockstore/libs/service_local/service_local.cpp
cloud/blockstore/libs/storage/api/service.h
cloud/blockstore/libs/storage/api/volume.h
cloud/blockstore/libs/storage/protos/volume.proto
cloud/blockstore/libs/storage/service/service_actor_create_volume_link.cpp
cloud/blockstore/libs/storage/service/service_actor_destroy_volume_link.cpp
cloud/blockstore/libs/storage/service/service_ut_link_volume.cpp
cloud/blockstore/libs/storage/service/ut/ya.make
cloud/blockstore/libs/storage/service/ya.make
cloud/blockstore/libs/storage/testlib/service_client.cpp
cloud/blockstore/libs/storage/testlib/service_client.h
cloud/blockstore/libs/storage/volume/volume_actor.cpp
cloud/blockstore/libs/storage/volume/volume_actor_link_volume.cpp
cloud/blockstore/libs/storage/volume/ya.make
cloud/blockstore/public/api/grpc/service.proto
cloud/blockstore/public/api/protos/volume.proto
cloud/blockstore/tools/testing/chaos-monkey/monkey_test.go

Первая часть https://github.com/ydb-platform/nbs/issues/2999
Здесь добавляю новые команды в blockstore-client и заглушку на стороне TVolumeActor

Create and destroy volume link tag #1

---

cloud/filestore/libs/service_local/index.cpp
cloud/filestore/libs/service_local/lowlevel.cpp
cloud/filestore/libs/service_local/lowlevel.h

[Filestore] issue-2467: implement restore of invalidated node cache for vast nfs

---

cloud/blockstore/tools/csi_driver/internal/volume/volume_linux.go

We don't support verbosity levels for one log level in our logging

[CSI] fix log levels

---

cloud/blockstore/tools/csi_driver/cmd/nbs-csi-driver/main.go
cloud/blockstore/tools/csi_driver/internal/driver/driver.go

1. Add NfsLocalEndpointSocket parameter
2. Create nfs client if socket parameter is not empty

[CSI] Add NfsLocalEndpointSocket & NfsLocalFilestoreSocket parameter

---

cloud/blockstore/libs/storage/partition_nonrepl/lagging_agent_migration_actor.cpp

Фикс конфликта https://github.com/ydb-platform/nbs/pull/3075 и https://github.com/ydb-platform/nbs/pull/3080

Fix main compilation

---

cloud/blockstore/libs/daemon/common/bootstrap.cpp
cloud/blockstore/libs/service_rdma/rdma_target.cpp

issue-3133: pass to RDMA target service kikimr directly

---

cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_ut.cpp

Fix migration index update notifications

---

cloud/blockstore/libs/storage/core/monitoring_utils.cpp
cloud/blockstore/libs/storage/service/service_actor_create_volume_link.cpp
cloud/blockstore/libs/storage/volume/model/checkpoint.h
cloud/blockstore/libs/storage/volume/model/checkpoint_light.h
cloud/blockstore/libs/storage/volume/model/follower_disk.cpp
cloud/blockstore/libs/storage/volume/model/follower_disk.h
cloud/blockstore/libs/storage/volume/model/ya.make
cloud/blockstore/libs/storage/volume/testlib/test_env.cpp
cloud/blockstore/libs/storage/volume/testlib/test_env.h
cloud/blockstore/libs/storage/volume/volume_actor.cpp
cloud/blockstore/libs/storage/volume/volume_actor.h
cloud/blockstore/libs/storage/volume/volume_actor_link_volume.cpp
cloud/blockstore/libs/storage/volume/volume_actor_loadstate.cpp
cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp
cloud/blockstore/libs/storage/volume/volume_actor_updateconfig.cpp
cloud/blockstore/libs/storage/volume/volume_database.cpp
cloud/blockstore/libs/storage/volume/volume_database.h
cloud/blockstore/libs/storage/volume/volume_database_ut.cpp
cloud/blockstore/libs/storage/volume/volume_schema.h
cloud/blockstore/libs/storage/volume/volume_state.cpp
cloud/blockstore/libs/storage/volume/volume_state.h
cloud/blockstore/libs/storage/volume/volume_state_ut.cpp
cloud/blockstore/libs/storage/volume/volume_tx.h
cloud/blockstore/libs/storage/volume/volume_ut.cpp
cloud/blockstore/tests/monitoring/test.py

Продолжение https://github.com/ydb-platform/nbs/issues/2999
Здесь сохраняю информацию об подчиненном диске в локальную базу главного диска.

Persist follower disks

---

cloud/storage/core/tools/breakpad/sender/coredump.py
cloud/storage/core/tools/breakpad/sender/coredump_formatter.py
cloud/storage/core/tools/breakpad/sender/crash_processor.py
cloud/storage/core/tools/breakpad/sender/sender.py
cloud/storage/core/tools/breakpad/sender/sentry.py
cloud/storage/core/tools/breakpad/sender/ya.make

This PR adds the ability to send crash reports (including backtrace and minidump as attachment) to sentry.io platform

Support sentry format in breakpad-sender

---

cloud/filestore/libs/storage/tablet/model/mixed_blocks.cpp
cloud/filestore/libs/storage/tablet/model/mixed_blocks.h
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_cache.cpp

issue-1226: add observability for mixed index cache, and ut for ReadData cache scenario

---

cloud/blockstore/libs/storage/partition/part_ut.cpp
cloud/blockstore/libs/storage/partition2/part2_ut.cpp
cloud/blockstore/libs/storage/partition_common/actor_checkrange.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_ut.cpp
cloud/blockstore/libs/storage/partition_nonrepl/ut_env.h
cloud/blockstore/libs/storage/service/service_actor_actions_check_range.cpp
cloud/blockstore/libs/storage/service/service_actor_checkrange.cpp
cloud/blockstore/libs/storage/service/service_ut_actions.cpp
cloud/blockstore/libs/storage/service/service_ut_checkrange.cpp
cloud/blockstore/libs/storage/testlib/service_client.cpp
cloud/blockstore/libs/storage/testlib/service_client.h
cloud/blockstore/private/api/protos/volume.proto
cloud/blockstore/public/api/protos/volume.proto

https://github.com/ydb-platform/nbs/issues/2956 Теперь CheckRange может расчитывать чексумму блока при необходимости

Issue 2956: add checksum calculations to CheckRange

---

cloud/blockstore/libs/service_rdma/rdma_target.cpp
cloud/blockstore/libs/storage/partition_common/remote_partition_actor.cpp
cloud/blockstore/libs/storage/partition_common/remote_partition_actor.h
cloud/blockstore/libs/storage/partition_common/ya.make

issue-3163: add remote partition and fix void blocks bug in rdma target

---

cloud/blockstore/libs/endpoint_proxy/server/server.cpp
cloud/blockstore/libs/nbd/netlink_device.cpp

1. set disconnect result into correct promise
2. log error

issue-2869: set disconnect result into StopResult promise

---

cloud/filestore/libs/storage/tablet/tablet_database.cpp
cloud/filestore/libs/storage/tablet/tablet_database.h

issue-1146: slight follow-up refactoring: get rid of `IIndexTabletDatabase::` enclosing class specifier

---

cloud/filestore/buildall/ya.make

To better resemble https://github.com/ydb-platform/nbs/blob/54feff4ab10275fd37a234b498147ab2e2549e9f/cloud/blockstore/buildall/ya.make#L9-L12

Add `cloud/storage/core/tools/testing/qemu/{bin,image}` to `filestore/buildall/ya.make`

---

cloud/blockstore/libs/storage/partition/part_actor_addblobs.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp

Fix -Wc++11-narrowing-const-reference warning

Fix -Wc++11-narrowing-const-reference

---

cloud/storage/core/libs/vhost-client/vhost-queue.cpp

Also https://github.com/yandex-cloud/yc-libvhost-server/pull/18 should be merged and vhost submodule updated to latest
#3182

Use dynamic platform_page_size instead of static PAGE_SIZE

---

cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor_stats.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_ut.cpp
cloud/blockstore/libs/storage/partition_nonrepl/ut_env.h

issue-3152: start sending statistics from non replicated partitions during resync 

---

cloud/blockstore/libs/diagnostics/critical_events.h
cloud/blockstore/libs/storage/partition_nonrepl/migration_request_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/migration_request_actor_ut.cpp

issue-3161: distinguish leaders and followers by cookies in TMigrationRequestActor

---

cloud/blockstore/libs/rdma/fake/client.cpp
cloud/blockstore/tests/mirror_disks/test.py

issue-3161: fix fake rdma client: add a bunch of missed handlers of undelivery requests; add test_m3_rdma_restart_disk_agent_during_migration

---

cloud/blockstore/libs/storage/volume/volume_actor.h
cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp
cloud/blockstore/libs/storage/volume/volume_state.cpp
cloud/blockstore/libs/storage/volume/volume_state.h

issue-3: add info about lagging devices on volume mon page

---

cloud/blockstore/tests/.gitignore
vscode_generate_workspace.sh

1. git-ignore
2. workspace covers ydb proto

Small improvements for developer

---

cloud/blockstore/libs/rdma/fake/client.cpp

issue-3161: fix local-mirror rdma tests: track refs to endpoints

---

cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_mirror.cpp

Добавил детализации к критэвентам из-за расхождения реплик

Describe disk and range when crit event in mirror disk happens

---

cloud/blockstore/libs/storage/partition_nonrepl/lagging_agents_replica_proxy_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/lagging_agents_replica_proxy_ut.cpp

Migrate lagging devices by aligned to 4MiB ranges

---

cloud/blockstore/libs/common/iovector.cpp
cloud/blockstore/libs/common/iovector.h
cloud/blockstore/libs/common/iovector_ut.cpp

https://github.com/ydb-platform/nbs/issues/2999
Need to copy data from NProto::TIOVectort to TSgList with different blocks size.

Added CopyToSgList() with different block size

---

cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_base_request.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_events_private.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_ut.cpp
cloud/blockstore/libs/storage/partition_nonrepl/ut_env.h
cloud/blockstore/libs/storage/volume/actors/shadow_disk_actor.cpp
cloud/blockstore/libs/storage/volume/model/helpers.cpp
cloud/blockstore/libs/storage/volume/model/helpers.h
cloud/blockstore/libs/storage/volume/testlib/test_env.cpp
cloud/blockstore/libs/storage/volume/testlib/test_env.h
cloud/blockstore/libs/storage/volume/volume_actor.cpp
cloud/blockstore/libs/storage/volume/volume_actor_lagging_agents.cpp
cloud/blockstore/libs/storage/volume/volume_events_private.h
cloud/blockstore/libs/storage/volume/volume_lagging_agent_ut.cpp

issue-3: rename Timeouted -> TimedOut

---

cloud/blockstore/libs/storage/partition_nonrepl/model/replica_actors.cpp
cloud/blockstore/libs/storage/partition_nonrepl/model/replica_actors.h
cloud/blockstore/libs/storage/partition_nonrepl/model/replica_actors_ut.cpp
cloud/blockstore/libs/storage/partition_nonrepl/model/ut/ya.make
cloud/blockstore/libs/storage/partition_nonrepl/model/ya.make
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_mirror.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_stats.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_lagging_devices_ut.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor_readblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor_resync.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_state.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_state.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_state.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_state.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/replica_info.h
cloud/blockstore/libs/storage/partition_nonrepl/ut/ya.make
cloud/blockstore/libs/storage/volume/volume_actor_lagging_agents.cpp

#3
Это последний большой кусочек пазла. Здесь mirror partition начинает создавать проксю к реплике и работать через неё.

Create lagging proxy in mirror partition

---

cloud/blockstore/libs/service/aligned_device_handler.cpp
cloud/blockstore/libs/service/aligned_device_handler.h
cloud/blockstore/libs/vhost/server_ut_stress.cpp

Была гонка между чтениями и установкой флага CriticalErrorReported.

Fix race for on setting and reading flag

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/core/config_ut.cpp
example/nbs/nbs-storage.txt

https://github.com/ydb-platform/nbs/issues/2999
Конфиги со скоростью наливки связанного диска.

Linked disk bandwidth config

---

cloud/blockstore/libs/storage/volume/volume_actor_allocatedisk.cpp

#3162
Добавляю временный предохранитель. Чуть позже будем чинить правильно.
Фикс безопасный, он у нас уже в проде

Minimize the risk of data loss during nrd migration

---

cloud/filestore/libs/storage/tablet/tablet_actor.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp

[Filestore] Cleanup should work when UsedBytesCount = 0

---

cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_readblocks.cpp

Пример ошибки:
` Major checksum mismatch detected: replica [15:43:12290]: checksum 1, replica [15:44:12291]: checksum 2, replica [15:45:12292]: checksum 3`
И пример лога:
`2025-04-01T09:10:37.575378Z node 9 :BLOCKSTORE_PARTITION INFO: [test] Read range [100..199]: Major checksum mismatch detected: replica [9:105:12319]: checksum 1, replica [9:106:12328]: checksum 2, replica [9:107:12329]: checksum 3`

[NBS] More informative checksum mismatch error

---

cloud/blockstore/libs/storage/service/service_actor_forward.cpp

Добавил деталей в сообщение об ошибке, чтобы было проще диагностировать что происходит

Adding details to the error message E_BS_INVALID_SESSION

---

cloud/blockstore/libs/diagnostics/server_stats_ut.cpp
cloud/blockstore/libs/diagnostics/volume_stats.cpp
cloud/blockstore/libs/diagnostics/volume_stats_ut.cpp
cloud/blockstore/libs/storage/stats_service/stats_service_actor_solomon.cpp
cloud/blockstore/libs/storage/stats_service/stats_service_ut.cpp

[NBS] Add `cloud_id` label to `service_volume` and `server_volume` metrics

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/diagnostics/critical_events.h
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor_resync.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_ut.cpp
cloud/blockstore/libs/storage/protos_ydb/volume.proto
cloud/blockstore/libs/storage/volume/volume_actor_addclient.cpp
cloud/blockstore/libs/storage/volume/volume_actor_lagging_agents.cpp
cloud/blockstore/libs/storage/volume/volume_actor_resync.cpp
cloud/blockstore/libs/storage/volume/volume_actor_startstop.cpp
cloud/blockstore/libs/storage/volume/volume_lagging_agent_ut.cpp
cloud/blockstore/libs/storage/volume/volume_state.h
cloud/blockstore/libs/storage/volume/volume_tx.h

#3
Включаю ресинк после миграции лагающего агента. Планирую включить это только на первое время, чтобы убедиться что проблем с миграцией нет.

Add ability to start resync after lagging migration

---

cloud/blockstore/libs/storage/service/volume_session_actor_start.cpp

Поменял уровень логирования на info для логов, которые полезны для понимания переезда таблеток.

[NBS] change some logs level in TStartVolumeActor

---

cloud/blockstore/libs/diagnostics/server_stats_ut.cpp
cloud/blockstore/libs/diagnostics/volume_stats.cpp
cloud/blockstore/libs/diagnostics/volume_stats_ut.cpp
cloud/blockstore/libs/storage/stats_service/stats_service_actor_solomon.cpp
cloud/blockstore/libs/storage/stats_service/stats_service_ut.cpp

Continue https://github.com/ydb-platform/nbs/pull/3300

[NBS] Add `folderId` label to `service_volume` and `server_volume` metrics

---

cloud/filestore/tests/fio/qemu-local-noserver-test/ya.make

issue-3343: disable qemu-local-noserver-test under asan, because it hangs

---

cloud/storage/core/libs/version/version.cpp

Add missed include <cmath>

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_acquire.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_release.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_session.cpp
cloud/blockstore/tests/loadtest/local-change-device/test.py

#3222 
Потерянные девайсы помечаются сломанными(DEVICE_STATE_ERROR), если не посылать запросы в сломанные девайсы, то проблем с неизвестными для диск агента девайсами не будет.

issue-3222: filter broken devices during acquire

---

cloud/blockstore/tools/csi_driver/internal/driver/controller.go
cloud/blockstore/tools/csi_driver/internal/driver/controller_test.go

[CSI] Set FolderId/CloudId for volumes and filestores

---

cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_readblocks_local.cpp
cloud/blockstore/tests/loadtest/local-nonrepl/test.py

issue-3161: add local-nonrepl rdma tests; fix AV for overlay disks + RDMA

---

cloud/blockstore/libs/common/block_range.h
cloud/blockstore/libs/storage/api/volume.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_stats.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor_stats.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_events_private.h
cloud/blockstore/libs/storage/partition_nonrepl/resync_range.cpp
cloud/blockstore/libs/storage/partition_nonrepl/resync_range.h
cloud/blockstore/libs/storage/partition_nonrepl/resync_range_block_by_block.cpp
cloud/blockstore/libs/storage/partition_nonrepl/resync_range_block_by_block.h
cloud/blockstore/libs/storage/partition_nonrepl/ut_env.h
cloud/blockstore/libs/storage/partition_nonrepl/ya.make
cloud/blockstore/libs/storage/volume/volume_actor.cpp
cloud/blockstore/libs/storage/volume/volume_actor.h
cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp
cloud/blockstore/libs/storage/volume/volume_actor_stats.cpp
cloud/blockstore/libs/storage/volume/volume_state.cpp
cloud/blockstore/libs/storage/volume/volume_state.h
example/nbs/nbs-storage.txt

Добавил на монстраничку вольюма текущий прогресс скрабинга и информацию про найденные/починенные блоки.

Show scrubbing details on volume mon-page

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/service/service_ut_mount.cpp
cloud/blockstore/libs/storage/service/volume_session_actor_start.cpp

https://github.com/ydb-platform/nbs/issues/3252

[Blockstore] add flag for new lock lost handling

---

cloud/blockstore/tools/csi_driver/internal/driver/node.go

I want to get rid of 
`2025-04-13T07:18:20.575886Z :BLOCKSTORE_SERVER INFO: cloud/blockstore/libs/diagnostics/server_stats.cpp:549: [...] StopEndpoint #... RESPONSE request completed (..., error: S_FALSE endpoint ".../nbs.sock" hasn't been started yet)` logs for non-vm clusters

[CSI] Stop endpoint on unpublish request only in vm mode

---

cloud/blockstore/libs/storage/partition/part_actor.cpp
cloud/blockstore/libs/storage/partition/part_actor_addconfirmedblobs.cpp
cloud/blockstore/libs/storage/partition/part_actor_addgarbage.cpp
cloud/blockstore/libs/storage/partition/part_actor_changedblocks.cpp
cloud/blockstore/libs/storage/partition/part_actor_checkpoint.cpp
cloud/blockstore/libs/storage/partition/part_actor_cleanup.cpp
cloud/blockstore/libs/storage/partition/part_actor_collectgarbage.cpp
cloud/blockstore/libs/storage/partition/part_actor_compaction.cpp
cloud/blockstore/libs/storage/partition/part_actor_confirmblobs.cpp
cloud/blockstore/libs/storage/partition/part_actor_deletegarbage.cpp
cloud/blockstore/libs/storage/partition/part_actor_describeblocks.cpp
cloud/blockstore/libs/storage/partition/part_actor_flush.cpp
cloud/blockstore/libs/storage/partition/part_actor_initfreshblocks.cpp
cloud/blockstore/libs/storage/partition/part_actor_initschema.cpp
cloud/blockstore/libs/storage/partition/part_actor_loadstate.cpp
cloud/blockstore/libs/storage/partition/part_actor_metadata_rebuild_blockcount.cpp
cloud/blockstore/libs/storage/partition/part_actor_metadata_rebuild_usedblocks.cpp
cloud/blockstore/libs/storage/partition/part_actor_monitoring.cpp
cloud/blockstore/libs/storage/partition/part_actor_patchblob.cpp
cloud/blockstore/libs/storage/partition/part_actor_readblob.cpp
cloud/blockstore/libs/storage/partition/part_actor_readblocks.cpp
cloud/blockstore/libs/storage/partition/part_actor_scan_disk.cpp
cloud/blockstore/libs/storage/partition/part_actor_trimfreshlog.cpp
cloud/blockstore/libs/storage/partition/part_actor_waitready.cpp
cloud/blockstore/libs/storage/partition/part_actor_writeblob.cpp
cloud/blockstore/libs/storage/partition/part_actor_writeblocks.cpp
cloud/blockstore/libs/storage/partition/part_actor_writefreshblocks.cpp
cloud/blockstore/libs/storage/partition/part_actor_writemergedblocks.cpp
cloud/blockstore/libs/storage/partition/part_actor_writemixedblocks.cpp
cloud/blockstore/libs/storage/partition/part_actor_zeroblocks.cpp

[NBS] Add disk id to partition tablet logs

---

cloud/blockstore/libs/storage/partition/part_actor_addblobs.cpp
cloud/blockstore/libs/storage/partition/part_actor_collectgarbage.cpp
cloud/blockstore/libs/storage/partition/part_actor_compaction.cpp
cloud/blockstore/libs/storage/partition/part_actor_patchblob.cpp
cloud/blockstore/libs/storage/partition/part_actor_writeblob.cpp

[NBS] Add disk id to partition logs, part 2

---

cloud/blockstore/libs/storage/partition_nonrepl/lagging_agents_replica_proxy_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/lagging_agents_replica_proxy_actor.h

Поменял порядок методов, удалил немного лишнего кода. Смысл никак не менялся

[NBS] Cleanup code of lagging proxy actor

---

cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp

исправляю use after free из теста добавленного в  #3391

issue-3: fix use after free

---

cloud/blockstore/libs/diagnostics/volume_stats.cpp
cloud/blockstore/libs/diagnostics/volume_stats_ut.cpp

[NBS] Add a sensor similar to DiskDown to disk metrics

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/partition_nonrepl/lagging_agent_migration_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/lagging_agents_replica_proxy_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/lagging_agents_replica_proxy_ut.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_lagging_devices_ut.cpp
cloud/blockstore/libs/storage/volume/volume_actor_lagging_agents.cpp
cloud/blockstore/libs/validation/validation_client.cpp
cloud/blockstore/tests/.gitignore
cloud/blockstore/tests/loadtest/local-mirror-lagging/local-mirror2-basic.txt
cloud/blockstore/tests/loadtest/local-mirror-lagging/local-mirror2-device-per-agent-multiple-replicas.txt
cloud/blockstore/tests/loadtest/local-mirror-lagging/local-mirror2-device-per-agent.txt
cloud/blockstore/tests/loadtest/local-mirror-lagging/local-mirror2-fresh-device-migration.txt
cloud/blockstore/tests/loadtest/local-mirror-lagging/local-mirror2-migration.txt
cloud/blockstore/tests/loadtest/local-mirror-lagging/local-mirror2-restart-nbs.txt
cloud/blockstore/tests/loadtest/local-mirror-lagging/local-mirror2-small-interval.txt
cloud/blockstore/tests/loadtest/local-mirror-lagging/local-mirror3-basic.txt
cloud/blockstore/tests/loadtest/local-mirror-lagging/test.py
cloud/blockstore/tests/loadtest/local-mirror-lagging/ya.make
cloud/blockstore/tests/loadtest/ya.make
cloud/blockstore/tests/python/lib/disk_agent_runner.py
cloud/blockstore/tests/python/lib/nbs_runner.py
cloud/blockstore/tests/python/lib/nonreplicated_setup.py
cloud/blockstore/tests/python/lib/test_base.py
cloud/storage/core/tools/testing/unstable-process/__main__.py
doc/blockstore/storage/dynamic_io_mirroring_proposal.md

#3
1) Добавил large тесты для фичи с лагающими дисками
2) Добавил параметры в конфиг влияющие на скорость миграции (синхронизации) лагающих девайсов
3) Небольшие правки логов

Lagging devices large tests; Logs fixes; Separate config params for migration speed of lagging devices; Actualize docs

---

cloud/blockstore/libs/diagnostics/probes.h
cloud/blockstore/libs/diagnostics/server_stats.cpp
cloud/blockstore/libs/storage/core/probes.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_base_request.cpp
cloud/blockstore/tools/analytics/find-perf-bottlenecks/lib/trace.py
cloud/storage/core/libs/common/public.h

Пример write запроса в mirror-3
Пример запроса на чтение

Write start block and device uuid in traces. Show this info in traces visualizer

---

cloud/blockstore/libs/storage/partition_nonrepl/lagging_agents_replica_proxy_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/lagging_agents_replica_proxy_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/lagging_agents_replica_proxy_ut.cpp

#3
Прокидываю запросы чексумм, которые прилетают от скраббинга из прокси в партишн

Handle ChecksumBlocks in the lagging proxy actor

---

cloud/blockstore/tests/csi_driver/e2e_tests_nfs/test.py
cloud/blockstore/tests/csi_driver/lib/csi_runner.py
cloud/blockstore/tools/csi_driver/internal/driver/controller.go
cloud/blockstore/tools/csi_driver/internal/driver/controller_test.go
cloud/blockstore/tools/csi_driver/internal/driver/driver.go
cloud/blockstore/tools/csi_driver/internal/driver/external_fs.go
cloud/blockstore/tools/csi_driver/internal/driver/node.go
cloud/blockstore/tools/csi_driver/internal/driver/node_test.go
cloud/blockstore/tools/csi_driver/internal/driver/ya.make

#3402 
- **[CSI] issue-3402: csi external fs support**
- **[CSI] issue-3402: remove external fs support from controller since only node driver is actually used**

[CSI] issue-3402: csi external fs support

---

cloud/filestore/libs/service_local/fs.cpp
cloud/filestore/libs/service_local/index.cpp
cloud/filestore/libs/service_local/index.h
cloud/filestore/libs/service_local/lowlevel.cpp
cloud/filestore/libs/service_local/lowlevel.h
cloud/filestore/libs/service_local/service_ut.cpp

[filestore] issue-3428: implement proper df (statfs) support for local filestore

---

.github/actions/nebius_runner_create/action.yaml
.github/actions/nebius_runner_remove/action.yaml
.github/scripts/github-runner.sh
.github/workflows/packer.yaml

https://github.com/nebius/pysdk/compare/v0.2.6...v0.2.28
Apparently there are some improvements with token renewal process and working with operations

chore: update nebius sdk 0.2.6 to 0.2.28

---

cloud/blockstore/config/server.proto
cloud/blockstore/libs/daemon/common/bootstrap.cpp
cloud/blockstore/libs/endpoints_vhost/vhost_server.cpp
cloud/blockstore/libs/endpoints_vhost/vhost_server.h
cloud/blockstore/libs/server/config.cpp
cloud/blockstore/libs/server/config.h
cloud/blockstore/public/api/protos/endpoints.proto
cloud/blockstore/tools/csi_driver/internal/driver/node.go
cloud/blockstore/tools/csi_driver/internal/driver/node_test.go

issue: #3371 
Move VhostDiscardEnabled parameter from StartEndpoint request to server config

issue-3371: move VhostDiscardEnabled to server config

---

cloud/blockstore/libs/daemon/ydb/bootstrap.cpp
example/3-start_nbs.sh
example/nbs/nbs-rdma.txt
example/nbs/nbs-server.txt
example/nbs/nbs-storage.txt

В примерах можно включить работу через фейковый rdma расскоментировав одну строчку

Prepare configs to use fake rdma in examples

---

cloud/disk_manager/api/filesystem_service.proto
cloud/disk_manager/internal/pkg/facade/filesystem_service_test/filesystem_service_test.go
cloud/disk_manager/internal/pkg/facade/testcommon/common.go
cloud/disk_manager/internal/pkg/resources/filesystems.go
cloud/disk_manager/internal/pkg/resources/storage.go
cloud/disk_manager/internal/pkg/services/filesystem/create_external_filesystem_task.go
cloud/disk_manager/internal/pkg/services/filesystem/create_filesystem_task.go
cloud/disk_manager/internal/pkg/services/filesystem/create_filesystem_task_test.go
cloud/disk_manager/internal/pkg/services/filesystem/delete_external_filesystem_task.go
cloud/disk_manager/internal/pkg/services/filesystem/delete_filesystem_task.go
cloud/disk_manager/internal/pkg/services/filesystem/delete_filesystem_task_test.go
cloud/disk_manager/internal/pkg/services/filesystem/protos/create_filesystem_task.proto
cloud/disk_manager/internal/pkg/services/filesystem/protos/delete_filesystem_task.proto
cloud/disk_manager/internal/pkg/services/filesystem/register.go
cloud/disk_manager/internal/pkg/services/filesystem/service.go
cloud/disk_manager/internal/pkg/services/filesystem/ya.make
cloud/disk_manager/internal/pkg/types/types.proto
cloud/tasks/storage/storage_ydb_impl.go
cloud/tasks/storage/storage_ydb_test.go

[Disk Manager] issue-3419: block on external filesystem create/delete task

---

cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/tablet/model/public.h
cloud/filestore/libs/storage/tablet/model/shard_balancer.cpp
cloud/filestore/libs/storage/tablet/model/shard_balancer.h
cloud/filestore/libs/storage/tablet/model/shard_balancer_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_state.cpp
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
cloud/filestore/libs/storage/tablet/tablet_state_impl.h

issue-3493: Implement random shard balancing policy alternative to the current round robin implementation

---

cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/tablet/model/fresh_bytes.cpp
cloud/filestore/libs/storage/tablet/model/fresh_bytes.h
cloud/filestore/libs/storage/tablet/protos/tablet.proto
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_compaction.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_counters.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp
cloud/filestore/private/api/protos/tablet.proto

[Filestore] Trigger FlushBytes by entries threshold (#3256)

---

cloud/blockstore/libs/server/server_ut.cpp

issue-3502: use port manager to avoid port conflicts

---

cloud/blockstore/libs/storage/partition/part_actor_writeblob.cpp
cloud/blockstore/libs/storage/partition/part_ut.cpp
cloud/blockstore/libs/storage/partition_common/actor_read_blob.cpp
cloud/blockstore/libs/storage/partition_common/events_private.h
cloud/blockstore/libs/storage/partition_common/long_running_operation_companion.cpp
cloud/blockstore/libs/storage/partition_common/long_running_operation_companion.h
cloud/blockstore/libs/storage/volume/volume_actor_stats.cpp

Добавил в логи ошибку, с которой отменилась операция по чтению или записи блоба.

Show error message for cancelled blob operations

---

cloud/disk_manager/internal/pkg/clients/nbs/tests/client_test.go

#3363
Add retries in order to avoid fails like this on DeleteSync requests:
```
stderr_y_alenm0:2025-05-06T23:27:17.030705Z :BLOCKSTORE_DISK_REGISTRY INFO: [72075186224037888] Received DeallocateDisk request: DiskId=TestAl
terPlacementGroupMembership1 Sync=1
stderr_y_alenm0:2025-05-06T23:27:32.026266Z :BLOCKSTORE_SERVER INFO: cloud/blockstore/libs/diagnostics/server_stats.cpp:317: [d:TestAlterPlace
mentGroupMembership1] [c:681a9ae4-6931-efb9-c54f-889d-54b1a422] DestroyVolume #11161187290746788360 REQUEST { Headers { ClientId: "681a9ae4-69
31-efb9-c54f-889d-54b1a422" Timestamp: 1746574052019718 RequestId: 11161187290746788360 RequestTimeout: 20000 } DiskId: "TestAlterPlacementGro
upMembership1" Sync: true }
stderr_y_alenm0:2025-05-06T23:27:32.026361Z :BLOCKSTORE_SERVICE INFO: Deleting …
```

[Disk Manager] tests: add retries for delete sync in DM client tests

---

cloud/blockstore/libs/storage/model/request_bounds_tracker.h
cloud/blockstore/libs/storage/model/request_in_progress_impl.h

В пре #3292 занес use after move

issue-3: fix use after move static analyzer issue

---

cloud/blockstore/libs/daemon/common/bootstrap.cpp
cloud/blockstore/tests/e2e-tests-vhost/test.py
cloud/blockstore/tests/e2e-tests-vhost/ya.make
cloud/blockstore/tests/ya.make

Fixes crash(verify condition failed https://github.com/ydb-platform/nbs/blob/main/cloud/blockstore/libs/service/aligned_device_handler.cpp#L154) in blockstore-server with enabled VhostDiscardEnabled parameter. e2e test to reproduce crash was added.

issue-3371: fix TVhostEndpointListener parameters

---

cloud/blockstore/libs/endpoints_rdma/rdma_server.cpp

В https://github.com/ydb-platform/nbs/pull/3509 был явно обозначен захват this, что не очень хорошо. Исправляю это.

Remove default lambda params capture by-value #1

---

cloud/blockstore/libs/common/iovector.cpp
cloud/blockstore/libs/common/iovector.h
cloud/blockstore/libs/diagnostics/critical_events.h
cloud/blockstore/libs/rdma_test/client_test.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_writeblocks_multi_agent.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_writeblocks_multi_agent.cpp
cloud/blockstore/libs/storage/partition_nonrepl/ya.make

Продолжение https://github.com/ydb-platform/nbs/issues/1720
Сделана отправка запроса на мульти-агентную запись через RDMA.

Multi-agent writes over RDMA (NBS part)

---

cloud/blockstore/apps/client/lib/check_range.cpp
cloud/blockstore/libs/common/block_range.h
cloud/blockstore/libs/storage/partition2/model/blob_index.cpp
cloud/blockstore/libs/storage/partition_common/actor_checkrange.cpp
cloud/blockstore/libs/storage/partition_nonrepl/model/processing_blocks_ut.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_checkrange.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_checkrange.cpp
cloud/blockstore/libs/storage/volume/model/checkpoint_light_ut.cpp

Достаточно более понятного конструктора TBlockRange::WithLength().

Remove TBlockRange construction function MakeHalfOpenInterval()

---

cloud/blockstore/libs/rdma/fake/client.cpp
cloud/blockstore/libs/rdma/fake/client_ut.cpp

Issue-3212: add cancel request function to fake rdma client

---

cloud/filestore/config/server.proto
cloud/filestore/libs/service_local/config.cpp
cloud/filestore/libs/service_local/config.h
cloud/filestore/libs/service_local/fs_node.cpp

[Filestore] issue-3544: when possible ignore filling node cache when listing directories

---

cloud/blockstore/libs/endpoints_grpc/socket_endpoint_listener_ut.cpp

1. Create server via bootstrap to avoid port conflicts and simply the test
2. add a comment regarding the test implementation.

refactor: ShouldNotAcceptClientAfterServerStopped test

---

cloud/blockstore/libs/diagnostics/critical_events.h
cloud/blockstore/libs/storage/api/disk_registry.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_add_lagging_devices.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_lagging_agents.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_tx.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_lifecycle.cpp
cloud/blockstore/libs/storage/disk_registry/testlib/test_env.h
cloud/blockstore/libs/storage/protos/disk.proto
cloud/blockstore/libs/storage/testlib/disk_registry_proxy_mock.h
cloud/blockstore/libs/storage/testlib/test_env_state.h
cloud/blockstore/libs/storage/volume/volume_actor.cpp
cloud/blockstore/libs/storage/volume/volume_actor.h
cloud/blockstore/libs/storage/volume/volume_actor_lagging_agents.cpp
cloud/blockstore/libs/storage/volume/volume_actor_startstop.cpp
cloud/blockstore/libs/storage/volume/volume_events_private.h
cloud/blockstore/libs/storage/volume/volume_lagging_agent_ut.cpp

#3505
Смысловых изменений нет. Только переименования

Rename AddLaggingDevices -> AddOutdatedLaggingDevices DR event

---

cloud/blockstore/libs/client/durable.cpp
cloud/blockstore/libs/client/durable_ut.cpp
cloud/blockstore/libs/storage/core/disk_counters.cpp
cloud/blockstore/libs/storage/core/disk_counters.h
cloud/blockstore/libs/storage/core/disk_counters_ut.cpp
cloud/blockstore/libs/storage/stats_service/stats_service_actor_ydb.cpp
cloud/blockstore/libs/storage/volume/volume_actor.h
cloud/blockstore/libs/storage/volume/volume_actor_forward.cpp
cloud/blockstore/libs/storage/volume/volume_actor_throttling.cpp
cloud/blockstore/libs/storage/volume/volume_ut_stats.cpp
cloud/blockstore/public/api/protos/headers.proto

Introduce IngestTime histogram to service and service_volume

---

cloud/filestore/config/server.proto
cloud/filestore/libs/service/error.cpp
cloud/filestore/libs/service/error.h
cloud/filestore/libs/service_local/config.cpp
cloud/filestore/libs/service_local/config.h
cloud/filestore/libs/service_local/fs_data.cpp
cloud/filestore/libs/service_local/fs_node.cpp
cloud/filestore/libs/service_local/index.cpp
cloud/filestore/libs/service_local/index.h
cloud/filestore/libs/service_local/lowlevel.cpp
cloud/filestore/libs/service_local/lowlevel.h
cloud/filestore/libs/service_local/lowlevel_ut.cpp
cloud/filestore/libs/service_local/ut/ya.make

[Filestore] issue-3617: trust guest kernel to validate file permissions in local filestore

---

cloud/blockstore/libs/storage/volume/volume_state.cpp
cloud/blockstore/libs/storage/volume/volume_state.h
cloud/blockstore/libs/storage/volume/volume_state_ut.cpp

Добавлен tag "disable-rdma" для отключения Rdma. 
([NBS] Add tag for disk that will forcefully disable RDMA #3688)
Также удалена неиспользуемая переменная  UseRdmaForThisVolume и ф-я  GetUseRdmaForThisVolume().

Add tag for disk that will forcefully disable RDMA

---

cloud/blockstore/libs/rdma/impl/client.cpp

Fixes `cloud/blockstore/libs/rdma/impl/ut/TRdmaClientTest.ShouldStartEndpoint`
```
/actions-runner/_work/nbs/nbs/cloud/blockstore/libs/rdma/impl/buffer.cpp:269:18: runtime error: member call on null pointer of type 'NCloud::NBlockStore::NRdma::TBufferPool::TImpl'
warning: address range table at offset 0xf0 has a premature terminator entry at offset 0x100
warning: address range table at offset 0x120 has a premature terminator entry at offset 0x130
warning: address range table at offset 0x150 has a premature terminator entry at offset 0x160
#0 0x4013b08 in NCloud::NBlockStore::NRdma::TBufferPool::ReleaseBuffer(NCloud::NBlockStore::NRdma::TBufferPool::TBuffer&) …
```

[RDMA] check if resources were actually allocated before freeing them when destroying TClientEndpoint

---

cloud/blockstore/libs/storage/service/volume_session_actor_start.cpp

```
2025-06-22T11:20:06.225640Z :BLOCKSTORE_SERVICE INFO: [v:72075186224037890 g:? d:nrd0 t:46.457ms] Successfully confirmed external boot with generation 2
2025-06-22T11:20:06.225661Z :BLOCKSTORE_SERVICE INFO: [v:72075186224037890 g:2 d:nrd0 t:46.495ms] Starting volume tablet
```

Log improvements for TStartVolumeActor

---

cloud/disk_manager/pkg/admin/private.go

[Disk Manager] add disk-manager-admin {finish-external-filesystem-creation, finish-external-filesystem-deletion} commands

---

cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.h

Revert "wait for all rdma endpoints to stop; resolves #1020"

---

cloud/filestore/config/vfs.proto
cloud/filestore/config/vhost.proto
cloud/filestore/libs/daemon/vhost/bootstrap.cpp
cloud/filestore/libs/endpoint_vhost/config.cpp
cloud/filestore/libs/endpoint_vhost/config.h
cloud/filestore/libs/endpoint_vhost/listener.cpp
cloud/filestore/libs/endpoint_vhost/listener.h
cloud/filestore/libs/vfs_fuse/loop.cpp
cloud/filestore/tests/recipes/vhost/__main__.py

Forward WriteBackCache parameters from vhost config
Add logging for WriteBackCache initialization.
https://github.com/ydb-platform/nbs/issues/1751

issue-1751: forward WriteBackCache parameters from vhost config; add logging for WriteBackCache initialization.

---

cloud/storage/core/libs/aio/service.cpp

Use eventfd to send a signal to wake up the polling thread.

Improve the responsiveness of AIO service stop

---

cloud/filestore/libs/storage/tablet/session.h
cloud/filestore/libs/storage/tablet/tablet_state_cache.cpp
cloud/filestore/libs/storage/tablet/tablet_state_cache.h
cloud/filestore/libs/storage/tablet/tablet_ut_state_cache.cpp
cloud/storage/core/libs/common/lru_cache.h
cloud/storage/core/libs/common/lru_cache_ut.cpp

LRU cache for NodeRefs added in TInMemoryIndexState

---

cloud/blockstore/tools/csi_driver/internal/driver/node.go
cloud/blockstore/tools/csi_driver/internal/driver/node_test.go

issue: #3793 
StopEndpoint if NodeStageVolume fails on the step after staring endpoint. It resolves issue with dangling endpoints.

[CSI] Stop endpoint on NodeStageVolume failure

---

cloud/storage/core/libs/aio/service.cpp
cloud/storage/core/libs/common/file_io_service.cpp
cloud/storage/core/libs/common/file_io_service.h
cloud/storage/core/libs/common/file_io_service_ut.cpp
cloud/storage/core/libs/common/ut/ya.make

issue-3314: add RoundRobinFileIOService adaptor

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/partition/part_actor.cpp
cloud/blockstore/libs/storage/partition/part_actor.h
cloud/blockstore/libs/storage/partition/part_ut.cpp
cloud/blockstore/libs/storage/partition2/part2_actor.cpp
cloud/blockstore/libs/storage/partition2/part2_actor.h
cloud/blockstore/libs/storage/partition2/part2_ut.cpp

#3755 
Добавил таймаут на запуск таблетки партишена, если таблетка не может загрузиться больше чем N времени, мы ее убиваем

issue-3755: kill partition if it takes too long to boot tablet

---

cloud/filestore/public/sdk/python/client/base_client.py
cloud/filestore/public/sdk/python/client/client.py
cloud/filestore/tests/service/service-kikimr-test/test.py

issue-3699: add a simple read/write test to the service sdk test

---

cloud/blockstore/apps/client/lib/command_ut.cpp
cloud/blockstore/config/server.proto
cloud/blockstore/libs/daemon/common/bootstrap.cpp
cloud/blockstore/libs/endpoints/session_manager.cpp
cloud/blockstore/libs/endpoints/session_manager.h
cloud/blockstore/libs/endpoints/session_manager_ut.cpp
cloud/blockstore/libs/server/config.cpp
cloud/blockstore/libs/server/config.h
cloud/blockstore/libs/service/service_test.h

#3772 
Добавляю флаг, который выключает клиентские троттлеры для всего процесса.

Add a config parameter to disable client throttler

---

cloud/blockstore/libs/storage/service/service_ut_mount.cpp
cloud/blockstore/libs/storage/service/volume_session_actor_start.cpp

https://github.com/ydb-platform/nbs/issues/3252

[Blockstore] Do not reboot tablet if it was killed by state storage

---

cloud/filestore/config/filesystem.proto
cloud/filestore/libs/storage/service/service_actor_readdata.cpp
cloud/filestore/libs/storage/service/service_actor_writedata.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_createsession.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_sessions.cpp
cloud/filestore/public/api/protos/fs.proto
cloud/filestore/public/sdk/python/client/client.py
cloud/filestore/tests/service/service-kikimr-parentless-handleless-test/nfs-storage-config-patch.txt
cloud/filestore/tests/service/service-kikimr-parentless-handleless-test/test.py
cloud/filestore/tests/service/service-kikimr-parentless-handleless-test/ya.make
cloud/filestore/tests/service/service-kikimr-test/test.py
cloud/filestore/tests/service/ya.make

References #3699
Fix for #3722

issue-3699: fix forwarding of handleless IO for the sharded filesystems

---

cloud/filestore/bin/nfs/nfs-storage.txt
cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_readdata.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_writedata.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp

issue-3699: change E_FS_INVAL to E_FS_NOENT error for invalid node in handleless IO

---

cloud/storage/core/libs/io_uring/service.cpp
cloud/storage/core/libs/io_uring/service.h
cloud/storage/core/libs/io_uring/service_ut.cpp
cloud/storage/core/libs/io_uring/ut/ya.make
cloud/storage/core/libs/io_uring/ya.make
cloud/storage/core/libs/ya.make

issue-3314: add io_uring service (TIoUringService)

---

cloud/blockstore/libs/storage/volume/volume_actor.cpp
cloud/blockstore/libs/storage/volume/volume_actor_acquire.cpp
cloud/blockstore/libs/storage/volume/volume_actor_addclient.cpp
cloud/blockstore/libs/storage/volume/volume_actor_allocatedisk.cpp
cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
cloud/blockstore/libs/storage/volume/volume_actor_cleanup_history.cpp
cloud/blockstore/libs/storage/volume/volume_actor_follower.cpp
cloud/blockstore/libs/storage/volume/volume_actor_forward.cpp
cloud/blockstore/libs/storage/volume/volume_actor_lagging_agents.cpp
cloud/blockstore/libs/storage/volume/volume_actor_leader.cpp
cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp
cloud/blockstore/libs/storage/volume/volume_actor_monitoring_removeclient.cpp
cloud/blockstore/libs/storage/volume/volume_actor_reallocatedisk.cpp
cloud/blockstore/libs/storage/volume/volume_actor_release.cpp
cloud/blockstore/libs/storage/volume/volume_actor_removeclient.cpp
cloud/blockstore/libs/storage/volume/volume_actor_reset_seqnumber.cpp
cloud/blockstore/libs/storage/volume/volume_actor_resync.cpp
cloud/blockstore/libs/storage/volume/volume_actor_startstop.cpp
cloud/blockstore/libs/storage/volume/volume_actor_stats.cpp
cloud/blockstore/libs/storage/volume/volume_actor_statvolume.cpp
cloud/blockstore/libs/storage/volume/volume_actor_throttling.cpp
cloud/blockstore/libs/storage/volume/volume_actor_updatestartpartitionsneeded.cpp
cloud/blockstore/libs/storage/volume/volume_actor_updateusedblocks.cpp
cloud/blockstore/libs/storage/volume/volume_actor_updatevolumeparams.cpp
cloud/blockstore/libs/storage/volume/volume_actor_waitready.cpp

Log title unification in TVolumeActor

---

cloud/blockstore/vhost-server/backend_aio.cpp
cloud/blockstore/vhost-server/request_aio.cpp
cloud/blockstore/vhost-server/request_aio.h
cloud/blockstore/vhost-server/server_ut.cpp

#3290 
Если встретиося несуществующий фай то вместо краша vhost server'а  помечаю эти девайсы флагом NullBackend
Если какой-то запрос приходит в этот девайс отвечаю IO ошибкой

Issue-3290: mark non-existing files as "null backend" and reply with an error on every request for these devices

---

cloud/storage/core/libs/opentelemetry/impl/trace_ut.cpp
cloud/storage/core/libs/opentelemetry/impl/ya.make
cloud/storage/core/libs/ya.make

issue-1223: add lib to ya make

---

cloud/blockstore/config/diagnostics.proto
cloud/blockstore/libs/daemon/ydb/bootstrap.cpp
cloud/blockstore/libs/daemon/ydb/config_initializer.cpp
cloud/blockstore/libs/daemon/ydb/config_initializer.h
cloud/blockstore/libs/daemon/ydb/options.cpp
cloud/blockstore/libs/daemon/ydb/options.h
cloud/blockstore/libs/diagnostics/config.cpp
cloud/blockstore/libs/diagnostics/config.h

issue-1223: move opentelemetry trace config inside diagnostics config

---

.github/workflows/approvals.yaml

https://github.com/ydb-platform/nbs/actions/runs/16169216366/job/45638311263?pr=3881 - check where there are exempt paths only
https://github.com/ydb-platform/nbs/actions/runs/16169292806/job/45638558931?pr=3881 - check where there are paths which are not exempt from check
https://github.com/ydb-platform/nbs/actions/runs/16169612985/job/45639586263 - check where there are exempt paths, but they are required to be approved by both teams.

feat: disable approvals from opposing team for certain paths

---

cloud/blockstore/libs/endpoints/endpoint_manager.cpp
cloud/blockstore/libs/rdma/impl/client.cpp
cloud/blockstore/libs/rdma/impl/server.cpp
cloud/blockstore/libs/server/server.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_notify_users.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_publish_disk_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/partition/part_actor.cpp
cloud/blockstore/libs/storage/partition/part_actor_collectgarbage.cpp
cloud/blockstore/libs/storage/partition/part_actor_initfreshblocks.cpp
cloud/blockstore/libs/storage/partition/part_actor_loadstate.cpp
cloud/blockstore/libs/storage/partition/part_actor_patchblob.cpp
cloud/blockstore/libs/storage/partition/part_actor_readblob.cpp
cloud/blockstore/libs/storage/partition/part_actor_writeblob.cpp
cloud/blockstore/libs/storage/partition2/part2_actor.cpp
cloud/blockstore/libs/storage/partition2/part2_actor_collectgarbage.cpp
cloud/blockstore/libs/storage/partition2/part2_actor_initfreshblocks.cpp
cloud/blockstore/libs/storage/partition2/part2_actor_loadstate.cpp
cloud/blockstore/libs/storage/partition2/part2_actor_readblob.cpp
cloud/blockstore/libs/storage/partition2/part2_actor_writeblob.cpp
cloud/blockstore/libs/storage/partition_common/actor_trimfreshlog.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp
cloud/blockstore/libs/storage/ss_proxy/path_description_backup.cpp
cloud/blockstore/libs/storage/stats_service/stats_service_actor_ydb.cpp
cloud/blockstore/libs/storage/volume/model/helpers.cpp
cloud/blockstore/libs/storage/volume/volume_actor_allocatedisk.cpp
cloud/blockstore/libs/vhost/server.cpp

Добавление описания к крит эвентам

add descriptions for crtitical events part 1

---

cloud/blockstore/libs/client_rdma/rdma_client.cpp
cloud/blockstore/libs/service_rdma/rdma_target.cpp

добавляю передачу времени, сколько троттлился запрос, для рдма транспорта в скейл юнитах

[NBS, SU] pass postpone time through rdma

---

cloud/blockstore/config/disk.proto
cloud/blockstore/libs/daemon/ydb/bootstrap.cpp
cloud/blockstore/libs/daemon/ydb/bootstrap.h
cloud/blockstore/libs/daemon/ydb/ya.make
cloud/blockstore/libs/disk_agent/bootstrap.cpp
cloud/blockstore/libs/disk_agent/bootstrap.h
cloud/blockstore/libs/disk_agent/ya.make
cloud/blockstore/libs/service_local/file_io_service_provider.cpp
cloud/blockstore/libs/service_local/file_io_service_provider.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_ut.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_ut_large.cpp
cloud/blockstore/libs/storage/disk_agent/model/bootstrap.cpp
cloud/blockstore/libs/storage/disk_agent/model/bootstrap.h
cloud/blockstore/libs/storage/disk_agent/model/config.cpp
cloud/blockstore/libs/storage/disk_agent/model/ya.make
cloud/blockstore/tests/loadtest/local-nonrepl/embedded/ya.make
cloud/blockstore/tests/loadtest/local-nonrepl/test.py
cloud/blockstore/tests/loadtest/local-nonrepl/ya.make
cloud/blockstore/tests/loadtest/local-nonrepl/ya.make.inc
cloud/blockstore/tests/python/lib/nonreplicated_setup.py

issue-3314: add io_uring backend to Disk Agent

---

cloud/blockstore/tools/csi_driver/cmd/nbs-csi-driver/main.go
cloud/blockstore/tools/csi_driver/internal/driver/driver.go
cloud/blockstore/tools/csi_driver/internal/driver/node.go
cloud/blockstore/tools/csi_driver/internal/driver/node_test.go

[CSI] Set request timeout for StartEndpoint request

---

cloud/blockstore/config/disk.proto
cloud/blockstore/libs/daemon/ydb/bootstrap.cpp
cloud/blockstore/libs/disk_agent/bootstrap.cpp
cloud/blockstore/libs/storage/disk_agent/model/bootstrap.cpp
cloud/storage/core/libs/io_uring/context.cpp
cloud/storage/core/libs/io_uring/context.h
cloud/storage/core/libs/io_uring/service.cpp
cloud/storage/core/libs/io_uring/service_ut.cpp

Use msg_ring instead of NOP to implement TIoUringServiceNull (NOP does not allow the request size to be passed to cqe).

add DISK_AGENT_BACKEND_IO_URING_NULL

---

.clang-tidy

Strengthening clangd checks

---

cloud/blockstore/tools/csi_driver/internal/driver/node.go

[CSI] return Unavailable error when NBD  device is not available

---

cloud/tasks/runner_test.go

https://github-actions-s3.storage.eu-north1.nebius.cloud/ydb-platform/nbs/PR-check/16623733157/1/nebius-x86-64/logs/1/cloud/tasks/tests/test-results/tests/testing_out_stuff/tests.TestTaskPingerFailureOnSecondIteration.log

[DM] Fix flapping tests in runner_test.go

---

cloud/blockstore/libs/storage/volume/volume_actor_lagging_agents.cpp
cloud/blockstore/libs/storage/volume/volume_tx.h

Код не менялся. Я лишь перенёс его внутрь транзакции чтобы обезопаситься от потенциальных гонок

Move lagging replicas code into a transaction

---

cloud/tasks/config/config.proto
cloud/tasks/storage/storage_ydb_impl.go
cloud/tasks/tasks_tests/tasks_test.go

Closes #1965
Optimize clearEndedTasks by removing all tasks at once, splitted by chunks.
Query plan for query from clearEndedTasksChunk function: https://gist.github.com/iamnalinor/db7476a390448738ed1ed29a59c02e52
Benchmark results: https://github.com/ydb-platform/nbs/pull/3851#issuecomment-3121389217

[DM] Optimize clearEndedTasks

---

cloud/blockstore/config/rdma.proto
cloud/blockstore/libs/rdma/iface/client.cpp
cloud/blockstore/libs/rdma/iface/client.h
cloud/blockstore/libs/rdma/iface/server.cpp
cloud/blockstore/libs/rdma/iface/server.h
cloud/blockstore/libs/rdma/impl/client.cpp
cloud/blockstore/libs/rdma/impl/client_ut.cpp
cloud/blockstore/libs/rdma/impl/server.cpp
cloud/blockstore/libs/rdma/impl/server_ut.cpp
cloud/blockstore/libs/rdma/impl/test_verbs.cpp
cloud/blockstore/libs/rdma/impl/test_verbs.h
cloud/blockstore/libs/rdma/impl/verbs.cpp
cloud/blockstore/libs/rdma/impl/verbs.h

Добавляю в конфиг значение, которое прорастает в TypeOfService для RDMA траффика. Может быть использовано для ECN

Allow to set TOS for RDMA traffic

---

cloud/tasks/storage/storage_ydb_impl.go

[Disk manager] Fix style

---

cloud/filestore/libs/vfs_fuse/loop.cpp
contrib/libs/fuse/include/fuse_lowlevel.h
contrib/libs/fuse/lib/cuse_lowlevel.c
contrib/libs/fuse/lib/fuse.c
contrib/libs/fuse/lib/fuse_loop.c

The only change we need is for contrib/libs/virtiofsd

[Filestore] issue-4035: revert api change to fuse_session_loop in contrib/libs/fuse

---

cloud/blockstore/libs/storage/stats_fetcher/stats_fetcher.cpp
cloud/blockstore/libs/storage/stats_fetcher/stats_fetcher.h
cloud/blockstore/libs/storage/volume_balancer/volume_balancer_actor.cpp
cloud/blockstore/libs/storage/volume_balancer/volume_balancer_actor.h
cloud/filestore/libs/storage/service/service_actor.cpp
cloud/filestore/libs/storage/service/service_actor.h
cloud/filestore/libs/storage/service/service_actor_update_stats.cpp

Switch timestamps to monotonic time and add checks to prevent division by zero

Switch timestamps to monotonic time and add checks to prevent division by zero

---

cloud/blockstore/libs/storage/ss_proxy/ss_proxy_actor_describescheme.cpp
cloud/blockstore/libs/storage/ss_proxy/ss_proxy_ut.cpp

#3997
Чиню создание таблетки DR. Для этой операции актор создания таблетки делает сначала запрос DescribeScheme. 
В этом ПРе научился отвечать на такие запросы

Fix describing DR tablet when using SchemeCache

---

cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp

issue-4015: Initialize ScrubbingRangeStarted for the first range during actor bootstrapping

---

cloud/filestore/libs/vfs_fuse/vhost/fuse_virtio.c

[Filestore] issue-4124: fix use after free when calling to virtio_session_exit

---

cloud/blockstore/libs/storage/ss_proxy/ss_proxy_actor_describescheme.cpp
cloud/blockstore/libs/storage/ss_proxy/ss_proxy_ut.cpp

#3997 
Заполняю список "children" при DescribeScheme запросе чтобы заработал ListVolumes через SchemeCache

Fix listing volumes with scheme cache

---

.github/workflows/pre-commit.yaml
.pre-commit-config.yaml

example of ci failure: https://github.com/ydb-platform/nbs/actions/runs/16991970628/job/48173366437?pr=4147

use pre-commit in github workflow

---

cloud/blockstore/libs/endpoints/service_endpoint_ut.cpp

test failure: http://release.nbs.kubevirt-testing.ik8s.man.nbhost.net/ci/logs/run_25_08_15__05/cloud/blockstore/libs/endpoints/ut/test-results/unittest/chunk10/testing_out_stuff/TServiceEndpointTest.ShouldTimeoutFrozenRequest.err
reproducible with stress utility

fix(test): increase request timeout

---

.github/actions/test/action.yaml
.github/scripts/tests/fail-checker.py
.github/scripts/tests/generate-summary.py

Examples of this behaviour:
https://github.com/ydb-platform/nbs/pull/4172#issuecomment-3201120703

feat: mark all retries failed if there was failed build

---

cloud/filestore/libs/vfs_fuse/write_back_cache/write_back_cache_ut.cpp

https://github-actions-s3.storage.eu-north1.nebius.cloud/ydb-platform/nbs/Nightly-build-(tsan)/17088047591/1/nebius-x86-64-tsan/logs/1/cloud/filestore/libs/vfs_fuse/write_back_cache/ut/test-results/unittest/chunk6/testing_out_stuff/TWriteBackCacheTest.ShouldRetryFlushOnFailure.err
```
2025-08-20T05:08:06.477700Z :WRITE_BACK_CACHE INFO: cloud/filestore/libs/vfs_fuse/write_back_cache/write_back_cache_ut.cpp:269: Recreating cache
2025-08-20T05:08:06.478121Z :WRITE_BACK_CACHE INFO: cloud/filestore/libs/vfs_fuse/write_back_cache/write_back_cache_ut.cpp:375: Written "hello" to @1 at offset 12
warning: address range table at offset 0x30 has a premature terminator entry at offset 0x40
warning: address range …
```

Resolve data race in unit test TWriteBackCacheTest::ShouldRetryFlushOnFailure

---

cloud/blockstore/libs/cells/impl/describe_volume.cpp
cloud/blockstore/libs/cells/impl/describe_volume_ut.cpp

https://github-actions-s3.storage.eu-north1.nebius.cloud/ydb-platform/nbs/Nightly-build-(tsan)/17059097451/1/nebius-x86-64-tsan/logs/1/cloud/blockstore/libs/cells/impl/ut/test-results/unittest/chunk7/testing_out_stuff/TDescribeVolumeTest.ShouldReplyRetriableErrorOnTimeout.err

fix tsan errors for DescribeVolume in cells

---

cloud/filestore/libs/vfs_fuse/write_back_cache/write_back_cache_ut.cpp

Problem:
```
2025-08-20T05:08:06.008229Z :WRITE_BACK_CACHE INFO: cloud/filestore/libs/vfs_fuse/write_back_cache/write_back_cache_ut.cpp:269: Recreating cache
2025-08-20T05:08:06.008867Z :WRITE_BACK_CACHE INFO: cloud/filestore/libs/vfs_fuse/write_back_cache/write_back_cache_ut.cpp:375: Written "abcde" to @1 at offset 11
2025-08-20T05:08:06.010115Z :WRITE_BACK_CACHE INFO: cloud/filestore/libs/vfs_fuse/write_back_cache/write_back_cache_ut.cpp:227: Flushing "abcde" to @1 at offset 11
2025-08-20T05:08:06.010121Z :WRITE_BACK_CACHE INFO: cloud/filestore/libs/vfs_fuse/write_back_cache/write_back_cache_ut.cpp:668: Waiting for flush attempt 1
2025-08-20T05:08:06.011658Z :WRITE_BACK_CACHE INFO: cloud/filestore/libs/vfs_fuse/write_back_cache/write_back_cache_ut.cpp:227: Flushing "efghij" to @1 at …
```

Resolve data race in unit test TWriteBackCacheTest::ShouldFlushAutomatically

---

contrib/libs/grpc/src/core/lib/event_engine/posix_engine/posix_endpoint.cc

https://github.com/ydb-platform/ydb/pull/20968

patch contrib/grpc:  Fix bug in Tx0cp code path in posix endpoint.

---

cloud/blockstore/tests/csi_driver/lib/csi_runner.py

1. Disable endpoint proxy
2. run nfs-vhost-local only for nfs tests

[CSI] Disable endpoint-proxy and nfs-vhost-local in e2e test configs

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp

add time formatting for disk registry Automatically replaced devices

---

cloud/storage/core/libs/user_stats/counter/user_counter.cpp
cloud/storage/core/libs/user_stats/counter/user_counter.h

[NBS, Filestore] Move TUserSumCounterWrapper & TUserSumHistogramWrapper to cpp file

---

cloud/filestore/tests/common_configs/nfs-storage-newfeatures-patch.txt

https://github.com/ydb-platform/nbs/issues/1751

issue-1751: Turn on ServerWriteBackCacheEnabled in nfs-storage-newfeatures-patch.txt

---

cloud/disk_manager/internal/pkg/resources/disks.go
cloud/disk_manager/internal/pkg/resources/disks_test.go
cloud/disk_manager/internal/pkg/services/disks/create_disk_from_image_task.go
cloud/disk_manager/internal/pkg/services/disks/create_disk_from_snapshot_task.go
cloud/disk_manager/internal/pkg/services/disks/create_empty_disk_task.go
cloud/disk_manager/internal/pkg/services/disks/create_empty_disk_task_test.go
cloud/disk_manager/internal/pkg/services/disks/create_overlay_disk_task.go
cloud/disk_manager/internal/pkg/services/disks/create_overlay_disk_task_test.go
cloud/disk_manager/internal/pkg/services/disks/delete_disk_task.go
cloud/disk_manager/internal/pkg/services/disks/delete_disk_task_test.go

Needed for https://github.com/ydb-platform/nbs/pull/4023/

[Disk Manager] Set disk status deleted for non-existing disks on storage.DeleteDisk

---

cloud/blockstore/tools/csi_driver/internal/driver/node.go
cloud/blockstore/tools/csi_driver/internal/driver/node_test.go

issue-3793: stop dangling nbs endpoint in vm mode

---

cloud/disk_manager/internal/pkg/clients/nbs/client.go
cloud/disk_manager/internal/pkg/clients/nbs/factory.go
cloud/disk_manager/internal/pkg/clients/nbs/interface.go
cloud/disk_manager/internal/pkg/clients/nbs/mocks/client_mock.go

https://github.com/ydb-platform/nbs/issues/4132
Need this method to correctly implement cell definition when creating disks.

[Disk Manager] Add GetZone method for nbsClient

---

cloud/disk_manager/internal/pkg/clients/nbs/client.go
cloud/disk_manager/internal/pkg/clients/nbs/interface.go
cloud/disk_manager/internal/pkg/clients/nbs/mocks/client_mock.go

Fix incorrectly named method for https://github.com/ydb-platform/nbs/pull/4288

[Disk Manager] Rename zone getter for NBS client

---

cloud/blockstore/libs/storage/core/block_handler.cpp
cloud/blockstore/libs/storage/core/block_handler.h
cloud/blockstore/libs/storage/core/block_handler_ut.cpp
cloud/blockstore/libs/storage/partition/part_actor_readblocks.cpp
cloud/blockstore/libs/storage/partition2/part2_actor_readblocks.cpp
cloud/blockstore/libs/storage/volume/actors/read_disk_registry_based_overlay.cpp
cloud/blockstore/libs/storage/volume/actors/read_disk_registry_based_overlay.h
cloud/blockstore/libs/storage/volume/actors/read_disk_registry_based_overlay_ut.cpp
cloud/blockstore/public/api/protos/io.proto

#2988
Переименовал переменные в коде, чтобы соответствовали флагам в .proto

Rename ChecksumValidation -> DataIntegrityValidation

---

cloud/filestore/libs/vfs_fuse/fs_impl_data.cpp
cloud/filestore/libs/vfs_fuse/write_back_cache/write_back_cache.cpp
cloud/filestore/libs/vfs_fuse/write_back_cache/write_back_cache.h
cloud/filestore/libs/vfs_fuse/write_back_cache/write_back_cache_impl.h
cloud/filestore/libs/vfs_fuse/write_back_cache/write_back_cache_ut.cpp
cloud/filestore/libs/vfs_fuse/write_back_cache/write_back_cache_util_ut.cpp

https://github.com/ydb-platform/nbs/issues/1751
https://github.com/ydb-platform/nbs/issues/4256

[Filestore] Make write-back cache associated with an inode instead of a handle 

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_self_counters.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_self_counters.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/model/replica_table.cpp
cloud/blockstore/libs/storage/disk_registry/model/replica_table.h
cloud/blockstore/libs/storage/disk_registry/model/replica_table_ut.cpp

Add fresh devices counter to disk registry

Add fresh devices counter to disk registry

---

cloud/filestore/libs/server/config.cpp

The problem was uncovered during PR https://github.com/ydb-platform/nbs/pull/4394
here we fix it in advance

[Filestore] change proto getter for filestore server

---

cloud/filestore/libs/client/config.cpp

The problem was uncovered during PR https://github.com/ydb-platform/nbs/pull/4394
here we fix it in advance

[Filestore] fix getname in proto filestore-client

---

cloud/filestore/libs/endpoint_vhost/config.cpp

The problem was uncovered during PR https://github.com/ydb-platform/nbs/pull/4394
here we fix it in advance

[Filestore] fix proto get value for endpoint_vhost

---

cloud/filestore/libs/service_local/config.cpp

The problem was uncovered during PR https://github.com/ydb-platform/nbs/pull/4394
here we fix it in advance

[Filestore] fix proto for filestore service-local

---

cloud/blockstore/config/rdma.proto
cloud/blockstore/libs/rdma/iface/client.cpp
cloud/blockstore/libs/rdma/iface/client.h
cloud/blockstore/libs/rdma/iface/server.cpp
cloud/blockstore/libs/rdma/iface/server.h
cloud/blockstore/libs/rdma/impl/client.cpp
cloud/blockstore/libs/rdma/impl/server.cpp
cloud/blockstore/libs/rdma/impl/utils.h
cloud/blockstore/tools/testing/rdma-test/bootstrap.cpp
cloud/blockstore/tools/testing/rdma-test/options.cpp
cloud/blockstore/tools/testing/rdma-test/options.h

configure rdma source interface #4187

---

cloud/blockstore/tools/testing/eternal_tests/eternal-load/lib/test_executor.cpp

```
2025-09-24 08:06:16,175 - INFO - ya.test - pytest_runtest_setup: ####################################################################################################
2025-09-24 08:06:16,176 - INFO - ya.test - pytest_runtest_setup: test_load_fails
2025-09-24 08:06:16,178 - INFO - ya.test - pytest_runtest_setup: ####################################################################################################
2025-09-24 08:06:16,179 - INFO - ya.test - pytest_runtest_setup: Test setup
2025-09-24 08:06:16,181 - INFO - ya.test - pytest_runtest_call: Test call (class_name: test.py, test_name: test_load_fails)
2025-09-24 08:06:16,184 - DEBUG - ya.test - get_binary: Binary was found by /home/github/.ya/build/build_root/igqr/0008c5/cloud/blockstore/tools/testing/eternal_tests/eternal-load/bin …
```

Fix leak in eternal-load (AsyncIO service was stopped before all operations were completed)

---

cloud/filestore/tests/common_configs/nfs-storage-newfeatures-patch.txt

issue-3295: add `GCT_ANY_READ` to newfeatures test

---

cloud/blockstore/tests/python/lib/nbs_runner.py
cloud/disk_manager/internal/pkg/clients/nfs/tests/client_test.go
cloud/disk_manager/internal/pkg/facade/filesystem_service_test/filesystem_service_test.go
cloud/disk_manager/test/recipe/__main__.py
cloud/disk_manager/test/recipe/nfs_launcher.py
cloud/disk_manager/test/recipe/ydb_launcher.py
cloud/filestore/tests/config_dispatcher/test.py
cloud/filestore/tests/python/lib/daemon_config.py
cloud/filestore/tests/python/lib/server.py
cloud/filestore/tests/recipes/service-kikimr/__main__.py
cloud/filestore/tests/registration/test.py

Fixes  https://github.com/ydb-platform/nbs/issues/4302

[Disk Manager] Use kikimr based filestore in tests

---

cloud/blockstore/libs/diagnostics/critical_events.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/model/replica_table.h

Заменяю Y_DEBUG_ABORT_UNLESS на Impossible event.

Add impossible event for DR's ReplicaTable replacement fails

---

cloud/filestore/tests/python/lib/kikimr.py

Follow up for https://github.com/ydb-platform/nbs/pull/4410

fix ss path after https://github.com/ydb-platform/nbs/pull/4410
