cloud/storage/core/tools/ci/runner/disk_manager_acceptance_common.sh
cloud/storage/core/tools/ci/runner/generate_index.py
cloud/storage/core/tools/ci/runner/index.xsl

The eternal and sync tests were not reported, due to incorrect path in
disk_manager_acceptance_common.sh.

[Disk Manager]: Fix eternal and sync tests reporting

---

cloud/storage/core/tools/ci/runner/disk_manager_acceptance_common.sh

In all the other tests the results path is either `stderr.txt` or `stdout.txt`

[Disk Manager]: Fix stdout and stderr paths naming in acceptance tests

---

cloud/disk_manager/test/acceptance/test_runner/acceptance_test_runner.py

We should use profile-name parameter in the s3 url if available.

[Disk Manager]: Fix s3 url in disk manager acceptance tests

---

cloud/filestore/libs/storage/service/service_actor_createsession.cpp
cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/service/ut/ya.make

NBSNEBIUS-46:
1. TCreateSessionActor should schedule EvWakeup only after TEvTabletPipe::EvClientConnected because otherwise it can decide that the session is idle before it could be physically pinged
2. added a ut that tests pipe restoration logic in TCreateSessionActor

Fixed idle session logic in TCreateSessionActor + added a ut for this logic

---

cloud/blockstore/libs/endpoints/service_endpoint_ut.cpp
cloud/filestore/libs/endpoint/service_ut.cpp
cloud/storage/core/libs/keyring/endpoints.cpp

мы для каждого ендпоинта создаем файл в который кладем запрос TStartEndpointRequest в бинарном виде.
При старте nbs мы вычитываем запросы из файлов. Проблема в том что при вычитывании мы делали Strip (видимо копипаста откуда-то), из-за этого если запрос в бинарном виде начинался или заканчивался с пробелов или переносов строк, то он не мог распарситься

NBSNEBIUS-36: fix endpoint storage reading

---

cloud/blockstore/pylibs/common/ssh_client.py

Pseudo terminal allocation was not previously supported in tests, the -t option caused significant divergence in test results with proprietary tests.

[Tests]: Do not allocate pseudo-terminal

---

cloud/disk_manager/pkg/admin/tasks.go
cloud/tasks/storage/compound_storage.go
cloud/tasks/storage/mocks/storage_mock.go
cloud/tasks/storage/storage.go
cloud/tasks/storage/storage_ydb.go
cloud/tasks/storage/storage_ydb_test.go
cloud/tasks/tasks_tests/tasks_test.go

need to return []TaskInfo not []string from ListTasksRunning/ListTasksCancelling methods because I want to use them in collect_lister_metrics_task
https://github.com/ydb-platform/nbs/blob/fc1dd1fa9accb81ec0f7c2a5df231817bc56fb90/cloud/tasks/collect_lister_metrics_task.go#L107

NBS-4789: [Disk Manager] refactor sre tools

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut.cpp

[NBS] Не фейлить валидацию конфига девайса, если Serial или PhysicalOffset поменялись из 0 в не-0
Иначе релиз выкатить невозможно - после рестарта DiskRegistry отстреливает все девайсы, для которых появились PhysicalOffset или Serial. Этих полей раньше не было, поэтому тут на уровне логики валидации ломается совместимость.

NBSNEBIUS-83: device config validation should not fail if Serial or PhysicalOffset changed from 0 to non-0

---

cloud/blockstore/config/diagnostics.proto
cloud/blockstore/libs/diagnostics/config.cpp
cloud/blockstore/libs/diagnostics/config.h
cloud/blockstore/libs/diagnostics/hostname.cpp
cloud/blockstore/libs/diagnostics/hostname.h
cloud/blockstore/libs/diagnostics/server_stats.cpp
cloud/blockstore/libs/storage/core/monitoring_utils.cpp
cloud/blockstore/libs/storage/core/monitoring_utils.h
cloud/blockstore/libs/storage/init/disk_agent/actorsystem.cpp
cloud/blockstore/libs/storage/init/server/actorsystem.cpp
cloud/blockstore/libs/storage/partition/part_actor_monitoring.cpp
cloud/blockstore/libs/storage/partition2/part2_actor_monitoring.cpp
cloud/blockstore/libs/storage/service/service_actor_monitoring.cpp
cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp
cloud/blockstore/tools/cms/lib/tools.py
cloud/blockstore/tools/cms/patcher/tests/data/files/dca1-ct5-13.cloud.net/nbs-diag.txt
cloud/blockstore/tools/cms/patcher/tests/data/files/dca1-ct5-17.cloud.net/nbs-diag.txt
cloud/blockstore/tools/cms/patcher/tests/data/files/dca1-ct5-18.cloud.net/nbs-diag.txt
cloud/filestore/config/diagnostics.proto
cloud/filestore/libs/diagnostics/config.cpp
cloud/filestore/libs/diagnostics/config.h
cloud/filestore/libs/storage/init/actorsystem.cpp

https://github.com/ydb-platform/nbs/pull/109
https://github.com/ydb-platform/nbs/pull/110

Merge to stable NBS-4787, NBS-4748

---

cloud/blockstore/libs/service_local/storage_rdma.cpp
cloud/blockstore/libs/service_local/storage_rdma_ut.cpp
cloud/blockstore/libs/service_local/ut/ya.make

This pr fixes the problem with connecting to multiple devices on the same host using rdma compound storage. Before the fix same storage was reused to access all devices which resulted in data corruption

NBS-179: support using multiple devices from the same rdma endpoint

---

cloud/storage/core/tools/ci/runner/disk_manager_acceptance_common.sh

Disk manager eternal tests for 8TiB disks take more than 24hours to complete. Since they are started with cron, next test run starts before the previous run is finished. Since those tests use the same disk per suite but not per run, the same disk is detached from the previous machine, crashing tests for the previous run.

[Disk Manager]: Ensure disk manager eternal tests are ran one at a time

---

cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_state.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_state_ut.cpp
cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp
cloud/blockstore/libs/storage/volume/volume_actor_startstop.cpp
cloud/blockstore/libs/storage/volume/volume_state.cpp
cloud/blockstore/libs/storage/volume/volume_state.h
cloud/blockstore/libs/storage/volume/volume_state_ut.cpp

There used to be a bug (fixed a couple months ago) because of which some garbage device ids were added to the configs of some volumes. Even though the bug is fixed, some old volumes still contain garbage in their FreshDeviceIds lists and show "ReplicationStatus:in progress" on their monpages. This PR fixes the monpages for those volumes.

NBSNEBIUS-86: impld garbage FreshDeviceIds filtration in TVolumeState

---

.github/actions/build/action.yaml
.github/actions/s3cmd/action.yaml
.github/actions/test/action.yaml
.github/scripts/tests/generate-summary.py
.github/scripts/tests/templates/summary.html
.github/scripts/tests/transform-ya-junit.py
.github/workflows/build_and_test_ya.yaml

1. Added logs for "chunk-event" internal test type (used in FORK_TESTS()/FORK_SUBTESTS() in ya make) in future we need to somehow merge them in human readable test
2. Summary, now, distinguishes between failed and timeouted test
3. Summary now is not editing comment but adding new comments 
4. Added special flag to disable upload of test results in s3 in case of emergency

fix: log handling in chunk tests, added more logs to summary, append summary instead of add or modify, add flag to disable all info sync

---

.github/workflows/build_and_test_on_demand.yaml

There is and ongoing problem with large (in terms of concurrency) tests that results in more or less random test failures. So to try and resolve this issue we want to limit amount of tests in parallel, so that those tests will have more resources.

fix: trying to lower test_threads to limit concurrency and free up resources for large tests

---

cloud/blockstore/libs/storage/volume/volume_actor.h
cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp

To be able to see all volume config fields (right now some fields cannot be seen in UI - e.g. CreationTs)

NBSNEBIUS-86: rendering raw volume config (pretty-printed proto) on volume monpage

---

cloud/blockstore/libs/endpoints_vhost/external_vhost_server.cpp
cloud/blockstore/libs/endpoints_vhost/external_vhost_server_ut.cpp

We are extending the command-line arguments of blockstore-vhost-server to
support the RDMA backend but to ensure compatibility during version upgrades we
will use old local disk arguments for aio backend.
For aio backend vhost-server will be started with:
```
blockstore-vhost-server --serial nvme-disk-0 --socket-path /tmp/1.sock -q 2 --device /dev/nvme3n1:394062200832:5518414315520
```
For rdma backend vhost-server will be started with  additional arguments:
```
blockstore-vhost-server ... --client-id aaa --disk-id bbb --device-backend rdma --block-size 4096
```

NBS-179: use backward compatible arguments to run vhost-server for local disks (#199)

---

example/prepare_binaries.sh

There is an issue with passing parameters In /example. The following request from console won't work:
```
REQUEST='{"Host": "eu-north1-a-2ct3-2.infra.dev-stands-lab.nebiuscloud.net"}'
blockstore-client executeaction --action GetDependentDisks --input-bytes "$REQUEST" --host localhost --port 9766 --secure-port 0 --verbose error
```
since bash `$@` statement will split "$REQUEST" argument into pieces producing following command:
```
../cloud/blockstore/buildall/cloud/blockstore/apps/client/blockstore-client executeaction --action GetDependentDisks --input-bytes '{"Host":' '"eu-north1-a-2ct3-2.infra.dev-stands-lab.nebiuscloud.net"}' --host localhost --port 9766 --secure-port 0 --verbose error
(NLastGetopt::TUsageException) required exactly 0 free args
```

Fix execution of json requests in /example

---

cloud/disk_manager/internal/pkg/clients/nbs/tests/client_test.go

Правка в тест TestDeleteCheckpointData. В этом тесте присылается запрос на удаление данных чекпоинта в момент, когда чекпоинта не существует. Я хочу сделать коммит, в котором такой запрос завершается ошибкой. Соответственно, с этим коммитом этот тест падает.
Временно правлю тест, чтобы он не падал. Уже правил этот тест здесь https://arcanum.yandex-team.ru/review/4845454/details, но там я поправил криво :( Поэтому исправляюсь.

NBS-4665: [disk-manager] fix test on delete checkpoint data

---

cloud/blockstore/vhost-server/backend.h
cloud/blockstore/vhost-server/backend_aio.cpp
cloud/blockstore/vhost-server/backend_null.cpp
cloud/blockstore/vhost-server/backend_rdma.cpp
cloud/blockstore/vhost-server/server.cpp
cloud/blockstore/vhost-server/server_ut.cpp

After refactoring the `Batch` array of iocb was incorrectly shared between
different vhost queues. This lead to memory corruption which was not detected
since tests were running with only 1 vhost queue configured.
```
qemu ... -device vhost-user-blk-pci,chardev=vhost0,id=vhost-user-blk0,num-queues=1
```

fix: vhost-server aio backend was incorrectly batching ios

---

cloud/blockstore/vhost-server/backend.h
cloud/blockstore/vhost-server/backend_aio.cpp
cloud/blockstore/vhost-server/backend_null.cpp
cloud/blockstore/vhost-server/backend_rdma.cpp
cloud/blockstore/vhost-server/server.cpp
cloud/blockstore/vhost-server/server_ut.cpp

After refactoring the `Batch` array of iocb was incorrectly shared between
different vhost queues. This lead to memory corruption which was not detected
since tests were running with only 1 vhost queue configured.
```
qemu ... -device vhost-user-blk-pci,chardev=vhost0,id=vhost-user-blk0,num-queues=1
```

fix: vhost-server aio backend was incorrectly batching ios (#248)

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
cloud/blockstore/libs/storage/disk_registry/model/agent_list.cpp
cloud/blockstore/libs/storage/disk_registry/model/agent_list.h

This PR modifies the `AgentList Parameters` section in monitoring page in order to display agents with overridden values.
New layout looks as following:

Show overridden AgentParams on monitoring page

---

cloud/blockstore/libs/storage/volume/volume_state.cpp
cloud/blockstore/libs/storage/volume/volume_state.h
cloud/blockstore/libs/storage/volume/volume_state_ut.cpp

I introduced this bug in https://github.com/ydb-platform/nbs/commit/9c45422d82a3cc2ff4791b117b286b5cb4c5edb7 (2 days ago), haven't merged it to stable-23-3 yet, caught it in cloud/blockstore/tests/loadtest/local-mirror mirror2-agent-removal test.

NBSNEBIUS-86: fixed stupid bug: FilteredFreshDeviceIds filtration should not drop all FreshDeviceIds for volumes created after 2023-08-30

---

cloud/tasks/storage/storage_ydb_impl.go
cloud/tasks/storage/storage_ydb_test.go

Support crontab-like params for regular tasks.
Example:
```
...
// Schedules one task at 19:30 of each day.
s.scheduler.ScheduleRegularTasks(
ctx,
"regular",
tasks.TaskSchedule{
MaxTasksInflight: 1,
UseCronTab:       true,
Hour:             19,
Minute:           30,
},
)
```

NBSNEBIUS-89: [Tasks] support 'crontab' parameters for regular tasks

---

cloud/storage/core/tools/ci/runner/run_test.sh

some files generated by ya-make (e.g. stdout_*) have 600 permissions, which results in 403 error when trying to access artifacts via web interface

fix test artifact permissions

---

cloud/disk_manager/internal/pkg/dataplane/snapshot/storage/storage_ydb_impl.go

InflightQueue was not closed after the shallowCopySnapshot was finished, which was causing a goroutine leak.

[Disk Manager]: Snapshot: Fix inflight queue not closing in ShallowCopySnapshot()

---

cloud/blockstore/libs/storage/disk_agent/model/ya.make
cloud/blockstore/libs/storage/disk_registry/model/ya.make
cloud/blockstore/libs/storage/disk_registry_proxy/model/ya.make
cloud/blockstore/libs/storage/model/ya.make
cloud/blockstore/libs/storage/partition/model/ya.make
cloud/blockstore/libs/storage/partition2/model/ya.make
cloud/blockstore/libs/storage/partition_common/model/ya.make
cloud/blockstore/libs/storage/partition_nonrepl/model/ya.make
cloud/blockstore/libs/storage/service/model/ya.make
cloud/blockstore/libs/storage/volume/model/ya.make
cloud/deny_ydb_dependency.inc
cloud/filestore/libs/storage/model/ya.make
cloud/filestore/libs/storage/tablet/model/ya.make
cloud/storage/core/libs/tablet/model/ya.make

Добавил проверки в каталогах model что они не зависят от contrib/ydb
теперь если попытаться заинклюить чтонить лишнего - будет ошибка сборки примерно такого содержания:
```
Error[-WBadDep]: in $B/cloud/blockstore/libs/storage/volume/model/libstorage-volume-model.a: forbids direct or indirect dependency to module $B/contrib/ydb/library/yql/core/expr_nodes_gen/gen/libpy3core-expr_nodes_gen-gen.a via CHECK_DEPENDENT_DIRS
$B/cloud/blockstore/libs/storage/volume/model/libstorage-volume-model.a -> $B/cloud/blockstore/libs/kikimr/libblockstore-libs-kikimr.a
$B/cloud/blockstore/libs/kikimr/libblockstore-libs-kikimr.a -> $B/cloud/storage/core/libs/kikimr/libcore-libs-kikimr.a
$B/cloud/storage/core/libs/kikimr/libcore-libs-kikimr.a -> $B/contrib/ydb/core/mind/libydb-core-mind.a …
```

Make forbidden dependency check for model dirs

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/diagnostics/block_digest.cpp
cloud/blockstore/libs/diagnostics/block_digest.h
cloud/blockstore/libs/diagnostics/block_digest_ut.cpp
cloud/blockstore/libs/diagnostics/critical_events.h
cloud/blockstore/libs/storage/core/block_handler.cpp
cloud/blockstore/libs/storage/core/block_handler.h
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/partition/part_actor.cpp
cloud/blockstore/libs/storage/partition/part_actor.h
cloud/blockstore/libs/storage/partition/part_actor_addblobs.cpp
cloud/blockstore/libs/storage/partition/part_actor_addconfirmedblobs.cpp
cloud/blockstore/libs/storage/partition/part_actor_compaction.cpp
cloud/blockstore/libs/storage/partition/part_actor_flush.cpp
cloud/blockstore/libs/storage/partition/part_actor_readblocks.cpp
cloud/blockstore/libs/storage/partition/part_actor_writemergedblocks.cpp
cloud/blockstore/libs/storage/partition/part_actor_writemixedblocks.cpp
cloud/blockstore/libs/storage/partition/part_actor_zeroblocks.cpp
cloud/blockstore/libs/storage/partition/part_events_private.h
cloud/blockstore/libs/storage/partition/part_tx.h
cloud/blockstore/libs/storage/partition/part_ut.cpp
cloud/blockstore/libs/storage/protos/part.proto
cloud/blockstore/tests/loadtest/local/test.py

implemented calculation of block checksums in the blobs stored in blobstorage
implemented checksum checking for those blobs upon read
enabled this logic for the first 1GiB of the disk space in most of the uts in part_ut and in tests/loadtest/local large test suite
checksum calculation and verification for patched blobs and unconfirmed blobs is a TODO

issue #196: implemented block checksum calculation and verification for the blobs stored in blobstorage

---

cloud/disk_manager/internal/api/private_service.proto
cloud/disk_manager/internal/pkg/facade/private_service.go
cloud/disk_manager/internal/pkg/services/pools/protos/retire_base_disk_task.proto
cloud/disk_manager/internal/pkg/services/pools/retire_base_disk_task.go
cloud/disk_manager/internal/pkg/services/pools/retire_base_disks_task.go
cloud/disk_manager/internal/pkg/services/pools/storage/common.go
cloud/disk_manager/internal/pkg/services/pools/storage/common_test.go
cloud/disk_manager/internal/pkg/services/pools/storage/mocks/storage_mock.go
cloud/disk_manager/internal/pkg/services/pools/storage/storage.go
cloud/disk_manager/internal/pkg/services/pools/storage/storage_ydb.go
cloud/disk_manager/internal/pkg/services/pools/storage/storage_ydb_impl.go
cloud/disk_manager/internal/pkg/services/pools/storage/storage_ydb_test.go
cloud/disk_manager/pkg/admin/private.go

исправление логики в generateBaseDisk 
заходим туда только если 
1) пул был удален в процессе retire
2) пул есть, но базовые диски еще не успели налиться 
в обоих случаях из дефолтных (больших) базовых дисков нужно создавать дефолтные (такие же)
иначе: из базовых дисков размером с образ можно создавать такие же диски размером с образ а не с чекпоинт, так как разница между этими двумя показателями незначительна (она не может быть больше чем disk_size - image_size, при этом порядок этой метрики очень мал. по подсчетам там максимум не больше примерно 30 гб)
после этих исправлений больше нет необходимости в полях checkpoint_id, checkpoint_size - поэтому удаляю их тоже

NBS-4759: [Disk Manager] remove unnecessary logic from generateBaseDisk

---

cloud/storage/core/tools/ci/runner/run_all.sh

Ya cache grows uncontrollably, consuming all the disk space.

[CI]: Add ya cache garbage collection before scripts

---

cloud/storage/core/tools/ci/runner/run_all.sh

Large tests logs consume almost all the disk space and need to be cleaned up.

[CI]: Remove logs in nebius CI run_all.sh

---

cloud/blockstore/pylibs/common/ssh_client.py

In python tests sftp client the temporary directory for file transfer was not properly created.

[CI]: Add missing temporary directory creation for the ssh client

---

cloud/blockstore/libs/endpoints_grpc/socket_endpoint_listener_ut.cpp
cloud/blockstore/libs/nbd/server_ut.cpp
cloud/blockstore/libs/server/server_ut.cpp
cloud/blockstore/libs/vhost/server_ut.cpp

cmake doesn't provide a unique tmpdir for each test chunk (unlike ya) that is why we should use unique paths (for unix sockets) in our tests.

Fix tests in cmake

---

cloud/disk_manager/internal/pkg/facade/disk_service_test/disk_relocation_test.go
cloud/disk_manager/internal/pkg/services/pools/storage/storage_ydb_impl.go
cloud/disk_manager/internal/pkg/services/pools/storage/storage_ydb_test.go

При релокации оверлейных дисков не хочется копировать данные еще и базовых дисков 
Оптимизация работает так:
1) создаем базовые диски в DST зоне 
2) при релокации не копируем информацию с базового диска в SRC зоне, а просто создаем оверлейные, которые ссылаются на базовые диски в DST зоне (то есть экономим наливку базовых дисков)
Это работало только для живых пулов (которые не удалили) - потому что для таких пулов eventually наливаются базовые диски 
Это изменение делает так, что если мы хотим релоцировать оверлейный диск и даже если пул удален - то мы создадим такие же базовые диски в DST зоне и тоже используем оптимизацию в этом месте

NBS-4759: [Disk Manager] optimize relocation of overlay disks without alive pool

---

cloud/blockstore/tools/testing/eternal_tests/eternal-load/lib/config/config.proto

Field `RangeBlockCount` in prefious config specification for eternal_tests (https://github.com/ydb-platform/nbs/blob/ac799e1fe11eaa3e3b31dc8bacad6d7010731037/cloud/blockstore/tools/testing/eternal_tests/eternal-load/lib/config.sc) used to be optional. In the PR #202 it has been mistakenly marked as required.

fix config.proto in eternal-load to make compatible with previous config.sc

---

build/scripts/split_unittest.py

when running tests using ya make we have TMPDIR set to unique name for each
chunk of unit tests.
In stable branch we still using cmake which doesn't pass unique TMPDIR and
therefore when running in parallel execution of different tests can overwrite
each other data and fail.
This commit fixes this by passing unique TMPDIR before calling cpp unit test.

NEBDUTY-500: use unique temp directories for unit tests data

---

cloud/blockstore/tools/testing/eternal_tests/eternal-load/lib/config.cpp
cloud/blockstore/tools/testing/eternal_tests/eternal-load/lib/config_ut.cpp

In prefious config specification for eternal_tests (https://github.com/ydb-platform/nbs/blob/ac799e1fe11eaa3e3b31dc8bacad6d7010731037/cloud/blockstore/tools/testing/eternal_tests/eternal-load/lib/config.sc) in the situations, where `IoDepth` was less than the number of specified ranges, the config generator was supposed to generate missing ranges. This was the default behavior of the config generator when using the .sc specification and should stay this way after the switch to .proto specification.

NBSNEBIUS-71: make .proto config more compatible with previous .sc config

---

cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_compactionforced.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_monitoring.cpp
cloud/filestore/libs/storage/tablet/tablet_private.h
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp
cloud/filestore/libs/storage/testlib/tablet_client.h

Currently there is a mechanism that forcefully compacts all ranges present in the fs. In this PR a forced cleanup is introduced, which similarly forcefully runs cleanup operation on all ranges. No new transactions are introduced – ForcedCompaction request is extended with a enum that specifies if compaction or a cleanup is to be performed on the range.

[Filestore] NBSNEBIUS-91: Add ForcedCleanup handle for fs

---

cloud/filestore/libs/storage/api/tablet.h
cloud/filestore/libs/storage/tablet/tablet_actor_readdata.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_request.cpp
cloud/filestore/libs/storage/tablet/tablet_tx.h
cloud/filestore/private/api/protos/tablet.proto
cloud/filestore/private/api/protos/ya.make

See https://github.com/ydb-platform/nbs/issues/324
This API will be used by filestore-vhost to look up blob ids where the data is stored to read those blobs by itself.

issue #324: DescribeData API and implementation stub

---

cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_compactionforced.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_monitoring.cpp
cloud/filestore/libs/storage/tablet/tablet_private.h
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp
cloud/filestore/libs/storage/testlib/tablet_client.h

Currently there is a mechanism that forcefully compacts all ranges present in the fs. In this PR a forced cleanup is introduced, which similarly forcefully runs cleanup operation on all ranges. No new transactions are introduced – ForcedCompaction request is extended with a enum that specifies if compaction or a cleanup is to be performed on the range.

[Filestore] NBSNEBIUS-91: Add ForcedCleanup handle for fs (#268)

---

cloud/tasks/logging/journald_logger.go

Write log level in dm log messages in journald. Now one can not see log level in log messages, because log level it is present in journald fields only, but not in the message itself. This pr fixes this problem.
Example of log message after this fix:
```
Feb 06 10:37:01 d9hnumvcrda87ck5kbpm disk-manager[139901]: factory.go:56 INFO => GetChangedBlocks (disk id: TestGetChangedBytes0, start index: 0, blocks count: 4096, low checkpoint id: checkpoint, high checkpoint id: checkpoint, ignore base disk: false) #5361924835004422012 request completed (time: 9.135911ms, size: 0, error: <nil>)
```
before:
```
Feb 06 13:20:06 d9hnumvcrda87ck5kbpm disk-manager[145876]: factory.go:56 GetChangedBlocks (disk id: TestGetChangedBytes0, start index: 0, blocks count: 4096, low checkpoint id: , high checkpoint …
```

NBS-4829: [disk-manager]: add log level to dm logs

---

cloud/blockstore/tests/python/lib/loadtest_env.py

save dmesg -T on the tear_down of blockstore loadtest

NEBDUTY-504: save dmesg -T on the tear_down of blockstore loadtest (#309)

---

cloud/blockstore/libs/rdma/impl/client.cpp
cloud/blockstore/libs/rdma/impl/rcu.h
cloud/blockstore/libs/rdma/impl/rcu_ut.cpp
cloud/blockstore/libs/rdma/impl/server.cpp
cloud/blockstore/libs/rdma/impl/ut/ya.make

Disconnected session was not deleted and all other sessions were deleted
instead due to problem in rcu list predicate implementation.
Just deleting the server session and calling DestroyQP is not enough and will
lead to deadlock. We need to wait for all WR's to flush and only then it's safe
to delete Connection object (calling rdma_destroy_id)

fix deletion of rdma server session

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_migration.cpp

reset MaxMigrationTime on the last finished device migration; show Start migration timestamp on the volume's mon. page

NBSNEBIUS-45: fix MaxMigrationTime

---

.github/workflows/nightly-index-rebuild.yaml

Seem like there is internal limit on 1000 lifecycle rules and this script simply would not work

Remove launch of ttl-watcher

---

cloud/filestore/libs/storage/service/service_actor_createsession.cpp
cloud/filestore/libs/storage/service/service_actor_destroysession.cpp
cloud/filestore/libs/storage/service/service_actor_monitoring.cpp
cloud/filestore/libs/storage/service/service_state.cpp
cloud/filestore/libs/storage/service/service_state.h

It contains feature flags, block size, etc.

issue #324: storing NProto::TFileStore in session state to use it in the two stage read implementation in TServiceActor

---

cloud/filestore/libs/storage/tablet/tablet_actor_readdata.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp

Otherwise the offsets corresponding to the ranges that contain only fresh bytes are incorrect (shown in the added ut)

issue #324: DescribeData: offset calculation shouldn't use TBlock::BlockIndex since this block might be not initialized

---

cloud/blockstore/libs/rdma/impl/client.cpp
cloud/blockstore/libs/rdma/impl/rcu.h
cloud/blockstore/libs/rdma/impl/rcu_ut.cpp
cloud/blockstore/libs/rdma/impl/server.cpp
cloud/blockstore/libs/rdma/impl/ut/ya.make

* fix deletion of rdma server session
Disconnected session was not deleted and all other sessions were deleted
instead due to problem in rcu list predicate implementation.
Just deleting the server session and calling DestroyQP is not enough and will
lead to deadlock. We need to wait for all WR's to flush and only then it's safe
to delete Connection object (calling rdma_destroy_id)
* add rcu list unit tests

fix deletion of rdma server session (#336)

---

cloud/disk_manager/internal/pkg/dataplane/common/util.go
cloud/disk_manager/internal/pkg/dataplane/common/ya.make
cloud/disk_manager/internal/pkg/dataplane/create_snapshot_from_disk_task.go
cloud/disk_manager/internal/pkg/dataplane/protos/replicate_disk_task.proto
cloud/disk_manager/internal/pkg/dataplane/replicate_disk_task.go

need to use proxy overlay disk in relocation 
now data path looks like
snapshot -> nbs control -> host with volume tablet -> nbs control -> snapshot 
after this optimization it will be
snapshot -> nbs control -> snapshot

NBS-4684: [Disk Manager] use proxy overlay disks in relocation if possible

---

cloud/storage/core/tools/ci/runner/run_all.sh

Otherwise if someone breaks something in the working copy our nightly builds will be broken until we manually fix the working copy

NEBDUTY-603: added git reset --hard before git pull for nightly builds on our ci vm

---

cloud/disk_manager/test/acceptance/test_runner/lib/disk_policy.py

We used to obtain random disk for sync/eternal disk manager tests. This way, the race condition with cleanup scripts existing outside and removing disks older then X is possible. Use only disk from the previous tests for incremental disks.

[Disk Manager]: Test: Obtain the disk from the previous test

---

cloud/filestore/libs/storage/model/ut/ya.make
cloud/filestore/libs/storage/service/service_actor_readdata.cpp
cloud/filestore/libs/storage/service/service_ut.cpp

TwoStageRead feature datapath: falling back to ReadData if the enhanced datapath fails
#324

issue-324: TServiceActor: ReadData fallback in case DescribeData or EvGet fail

---

cloud/contrib/vhost/memmap.c
cloud/contrib/vhost/memmap.h
cloud/contrib/vhost/vdev.c
cloud/contrib/vhost/vdev.h
cloud/contrib/vhost/vhost_spec.h
cloud/contrib/vhost/virtio/virt_queue.h

scripts/sync_with_arc: change the default sync branch NBS no longer uses trunk to synchronize their changes to GitHub, so switch the branch to the one they use now.
Add support for VHOST_USER_SET_VRING_ENABLE
aio_server: don't forget to free config strings on disk stop
vdev: advertise support for CONFIGURE_MEM_SLOTS
Now that we have all calls implemented we can finally advertise support for this feature.
vhost_spec: add definition for VHOST_USER_PROTOCOL_F_CONFIGURE_MEM_SLOTS
Implement VHOST_REM_MEM_REG
This reuses existing logic from set_mem_table, with the only difference being that instead of replacing the old mem table entirely we create a copy of the old mem table with one memory region removed and then pretend it's a SET_MEM_TABLE call.
Implement VHOST_USER_ADD_MEM_REG
memmap: add a …

[BB->arc sync] Libvhost support for MEM_SLOTS/VRING_ENABLE

---

cloud/blockstore/libs/endpoints/endpoint_manager.cpp
cloud/blockstore/libs/endpoints/endpoint_manager.h
cloud/blockstore/libs/endpoints/endpoint_manager_ut.cpp
cloud/blockstore/libs/endpoints/service_endpoint.cpp
cloud/storage/core/libs/coroutine/executor.h

https://github.com/ydb-platform/nbs/issues/353
- move checks of processing sockets to EndpointManager (reject control requests if the corresponding socket is processing)
- add checks of restoring sockets to EndpointService (reject control requests if the corresponding socket is restoring)
- move control request timeout to EndpointService

#353: move checks of processing sockets to EndpointManager

---

cloud/blockstore/libs/diagnostics/critical_events.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_io.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_secure_erase.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_ut.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_state.cpp
cloud/blockstore/libs/storage/disk_agent/rdma_target.cpp
cloud/blockstore/libs/storage/disk_agent/rdma_target.h
cloud/blockstore/libs/storage/disk_agent/rdma_target_ut.cpp
cloud/blockstore/libs/storage/disk_agent/recent_blocks_tracker.cpp
cloud/blockstore/libs/storage/disk_agent/recent_blocks_tracker.h

We encountered devices, after secure erase, which had a few non-zero 4K blocks. Since we suspect that there were in-flight I/Os during the NVMe deallocate, this commit will add extra protection and raise critical events in case we encounter such a situation.

disk agent should reject secure erase if there are inflight write or zero requests

---

cloud/storage/core/libs/vhost-client/vhost-client.h

Avoid
```
$(SOURCE_ROOT)/cloud/storage/core/libs/vhost-client/vhost-client.h:51:18: error: no member named 'thread' in namespace 'std'
TVector<std::thread> QueueThreads;
```
* Not for changelog (changelog entry is not required)

Add missed #include <thread>

---

cloud/blockstore/libs/rdma/impl/verbs.cpp

We need to empty the completion queue otherwise when using EWaitMode::Poll we
might not get additional notification on the event channel and the remaining
completions won't be consumed.

fix rdma completions polling (#449)

---

cloud/blockstore/libs/storage/init/disk_agent/actorsystem.cpp
cloud/blockstore/libs/storage/init/server/actorsystem.cpp
cloud/filestore/libs/storage/init/actorsystem.cpp

This setting was deprecated here https://github.com/ydb-platform/ydb/pull/688

Get rid of EnableNodeIdentifier setting because of its deprecation

---

cloud/blockstore/libs/storage/volume/volume_actor_forward_trackused.cpp

Разбил SendRequestToPartitionWithUsedBlockTracking 
теперь есть две реализации - для Read/Write/Zero и GetChangedBlocks.
Для остальных запросов явно сделал пустую заглушку.
Поведение не поменялось, просто рефакторинг.

NBS-4905 simplify SendRequestToPartitionWithUsedBlockTracking

---

cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_flush_bytes.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_writedata.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp

issue-95: 1. fixing a bug that caused FlushState to get stuck in the Enqueued state if FlushBytes got triggered before the complete initialization of CompactionMap 2. rebooting tablet after N backpressure errors to make it more resilient in case of similar bugs (#486)

merge to stable-23-3

---

.clang-format

Форматируем так:
```
std::unique_ptr<TEvService::TEvGetCheckpointStatusRequest>
TVolumeClient::CreateGetCheckpointStatusRequest(const TString& checkpointId)
```
А было так:
```
std::unique_ptr<TEvService::TEvGetCheckpointStatusRequest> TVolumeClient::
CreateGetCheckpointStatusRequest(const TString& checkpointId)
```

Improve clang-format. Prefer return type on its own line

---

cloud/disk_manager/test/acceptance/test_runner/tests/ya.make

to fix linter issue:
```
[2024-02-21 13:31:56]  * File cloud/disk_manager/test/acceptance/test_runner/tests/ya.make contains issues:
[2024-02-21 13:31:56]    - LINTER_ID_TRAILING_EOL: File should have EOL in the end
[2024-02-21 13:31:56]       cloud/disk_manager/test/acceptance/test_runner/tests/ya.make:13:6
```

[Disk Manager] add EOL to the file

---

cloud/disk_manager/internal/pkg/services/disks/migrate_disk_task.go

scenario of race condition:
1) migration is created, fillGeneration = 5
2) migration is created, fillGeneration = 6
3) complete RelocateOverlayDiskTx for migration with fillGeneration = 6
4) complete RelocateOverlayDiskTx for migration with fillGeneration = 5 (this step causing cancellation of previous base disk rebasing)
5) migration with fillGeneration = 6 is trying to clone src volume and get error because base disk from relocateInfo does not exists
**migration with fillGeneration = 5 will not cancel because dst volume is located in different zone than in migration with fillGeneration = 6**

NBS-4902: [Disk Manager] fix race condition in migrate disk task

---

cloud/filestore/libs/storage/service/service_actor_readdata.cpp
cloud/filestore/libs/storage/service/service_ut.cpp

1. Added `ReadData` fallback reason to logging of `NFS_SERVICE`
2. Fix the `TStorageServiceActor` not reporting `ReadData` counters and add a ut for it.
References #324

[Filestore] NBSNEBIUS-121: TwoStageRead: add logging for `ReadData` fallback reason + fix ServiceActor not reporting `ReadData` counters

---

cloud/filestore/libs/storage/model/block_buffer.cpp
cloud/filestore/libs/storage/model/block_buffer.h
cloud/filestore/libs/storage/service/service_actor_readdata.cpp
cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_readdata.cpp

Getting rid of unneeded allocations during DescribeData request processing (perf profile shows that those allocations really hurt our performance)
#324

issue-324: implemented LazyBlockBuffer and using it in TIndexTabletActor::HandleDescribeData

---

cloud/storage/core/tools/ci/runner/run_all.sh

Write run_all.sh output to the logs_dir for
the run instead of the logs root

[CI]: Write run_all.sh output to the logs_dir

---

.github/config/muted_ya.txt
cloud/disk_manager/internal/pkg/facade/disk_service_nemesis_test/ya.make

mute test and specify split factor corresponding to it's chunk size based on the number of skipped tests in nightly builds e.g. https://github-actions-s3.website.nemax.nebius.cloud/ydb-platform/nbs/Nightly-build/7967342719/1/nebius-x86-64/summary/ya-test.html

mute nemesis test

---

cloud/blockstore/libs/storage/service/service_actor_actions_get_dependent_disks.cpp

Some agents may be in inactive state: even though they exist and work, they are missing from DiskRegistry AgentList. In such case GetDependentDisk request leads to E_NOT_FOUND error causing false alert. This PR suppresses this error and returns empty list for missing agent.

Suppress E_NOT_FOUND error in GetDependentDisks

---

cloud/filestore/libs/storage/tablet/session.h
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_cleanupsessions.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_createsession.cpp
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_sessions.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_counters.cpp
cloud/filestore/libs/storage/testlib/tablet_client.h

#541 
Stateless sessions and session cleanup upon timeout usually indicate problems. Right now session timeouts happen due to our bugs more often than due to ungraceful guest shutdown.

issue-541: added counters: StatefulSessionsCount, StatelessSessionsCount, SessionTimeouts

---

cloud/filestore/libs/storage/tablet/tablet_actor_writedata.cpp

Most probably tablet suicide won't be triggered due to high compaction map load times because our current limit on the backpressure error count is quite high. But nevertheless let's add this check - just in case.
#95

issue-95: not counting backpressure errors until compaction state becomes fully loaded

---

cloud/filestore/apps/client/lib/create_session.cpp
cloud/filestore/apps/client/lib/factory.cpp
cloud/filestore/apps/client/lib/reset_session.cpp
cloud/filestore/apps/client/lib/ya.make
cloud/filestore/tests/client/canondata/result.json
cloud/filestore/tests/client/canondata/test.test_describe_sessions/results.txt
cloud/filestore/tests/client/test.py
cloud/filestore/tests/python/lib/client.py

Will use it in production in the following manner:
1. `filestore-client executeaction --action describesessions '{"FileSystemId": "some_fs_id"}'` - to get the list of sessions - both stateful and stateless
2. `filestore-client resetsession --filesystem some_fs_id --session-id some_stateless_session_id --client-id client_id --session-state some_state_base64` - to set the state of some stateless session using the state of one of the stateful sessions as a "reference"
#541

issue-541: added createsession and resetsession commands to filestore-client, testing create+reset+describe sessions in client tests

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_acquire.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_allocate.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_register.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_release.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_private.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_self_counters.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_self_counters.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_session.cpp
cloud/blockstore/libs/storage/disk_registry/testlib/test_env.cpp
cloud/blockstore/libs/storage/disk_registry/testlib/test_env.h

fixes #499.
Проверил на лабе, подложив бинари. Чтобы результат был явно видео на глаз, пришлось увеличить время между аквайрами до 15 секунд, т.к. по дефолту там сейчас всего 4 (`ClientRemountPeriod`).

issue-499: Disk acquire cache in DR

---

cloud/blockstore/libs/endpoints/endpoint_events.cpp
cloud/blockstore/libs/endpoints/endpoint_events.h
cloud/blockstore/libs/endpoints/endpoint_manager.cpp
cloud/blockstore/libs/endpoints/endpoint_manager_ut.cpp
cloud/blockstore/libs/endpoints/session_manager.cpp
cloud/blockstore/libs/storage/api/volume.h
cloud/blockstore/libs/storage/core/disk_counters.h
cloud/blockstore/libs/storage/init/server/actorsystem.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_ut.cpp
cloud/blockstore/libs/storage/partition_nonrepl/ut_env.h
cloud/blockstore/libs/storage/service/volume_client_actor.cpp
cloud/blockstore/libs/storage/service/volume_session_actor_start.cpp
cloud/blockstore/libs/storage/testlib/test_env.cpp
cloud/blockstore/libs/storage/volume/testlib/test_env.cpp
cloud/blockstore/libs/storage/volume/volume.cpp
cloud/blockstore/libs/storage/volume/volume.h
cloud/blockstore/libs/storage/volume/volume_actor.cpp
cloud/blockstore/libs/storage/volume/volume_actor.h
cloud/blockstore/libs/storage/volume/volume_actor_migration.cpp
cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp
cloud/blockstore/libs/storage/volume/volume_actor_stats.cpp
cloud/blockstore/libs/storage/volume/volume_state.cpp
cloud/blockstore/libs/storage/volume/volume_state.h
cloud/blockstore/libs/storage/volume/volume_ut.cpp

When volume starts migration the endpoint will be switched to use regular data
path (NRD volume through actor system).
Additionally when "use-fastpath" added/removed to volume tags the endpoint will
switch to use fast/regular data path
Additionally resolves #312

NBS #179: switch fast path volume to regular path during migrations

---

build/conf/opensource.conf

Дабы проще дебажить и подкладывать бинари на лабу добавил один флаг. 
Можно указывать либо при сборке:
`ya make -D FORCE_STATIC_LINKING=yes`
Либо сразу в ~/.ya/ya.conf
`[FORCE_STATIC_LINKING]`

Static linking flag for easy debugging

---

cloud/disk_manager/internal/pkg/facade/testcommon/common.go
cloud/tasks/logging/fields.go
cloud/tasks/logging/journald_logger.go
cloud/tasks/logging/journald_tests/journald_logger_test.go
cloud/tasks/logging/logger.go
cloud/tasks/logging/logger_test.go
cloud/tasks/persistence/ydb_logger.go
cloud/tasks/runner.go

Added methods that allow to add logging fields to context. Used that methods to improve ydb client logging: now it writes field from context.
Examples of rows after these changes:
```
Feb 27 13:00:29 d9hnumvcrda87ck5kbpm disk-manager[305304]: ydb_logger.go:73 DEBUG => COMPONENT: YDB, YDB_LOG_NAME: ydb.driver.resolver.init, ENDPOINT: localhost:32648, DATABASE: /Root, SECURE: false => start
Feb 27 13:00:29 d9hnumvcrda87ck5kbpm disk-manager[305304]: factory.go:69 DEBUG => calling client.Close for &{0xc0005c2480 300000000000 500000000 0x17f5fe0 0xc0004b0260}, localhost:17106
```
(in 'real' logs there also will be request id, idempotency key and operation id fiedls)

issue-487 NBS-4829 [disk manager]: make possible to add arbitrary logging field to context, write fields from context in ydb client logger

---

cloud/blockstore/libs/storage/api/volume.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_stats.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor_stats.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_stats.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_stats.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_stats.cpp
cloud/blockstore/libs/storage/protos/disk.proto
cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
cloud/blockstore/libs/storage/volume/volume_actor_stats.cpp
cloud/blockstore/libs/storage/volume/volume_events_private.h

Вынес часть изменений из большого ПРа https://github.com/ydb-platform/nbs/pull/598
1. добавляется идентификатор диска в статистику партишена.
2. прокидывается количество налитых блоков в TUpdateShadowDiskStateResponse
3. добавил комментарий в прото.

NBS-4827 Add DiskId to partition statistics

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h

Changes in placement group view:
* Added strategy type column
* Added disks/partition state column
* Disks are now sorted by states (broken first) and by partition_id
View before:
View after:

Update placement groups view in monitoring

---

cloud/blockstore/libs/endpoints/endpoint_events.cpp
cloud/blockstore/libs/endpoints/endpoint_events.h
cloud/blockstore/libs/endpoints/endpoint_manager.cpp
cloud/blockstore/libs/endpoints/endpoint_manager_ut.cpp
cloud/blockstore/libs/endpoints/session_manager.cpp
cloud/blockstore/libs/storage/api/volume.h
cloud/blockstore/libs/storage/core/disk_counters.h
cloud/blockstore/libs/storage/init/server/actorsystem.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_ut.cpp
cloud/blockstore/libs/storage/partition_nonrepl/ut_env.h
cloud/blockstore/libs/storage/service/volume_client_actor.cpp
cloud/blockstore/libs/storage/service/volume_session_actor_start.cpp
cloud/blockstore/libs/storage/testlib/test_env.cpp
cloud/blockstore/libs/storage/volume/testlib/test_env.cpp
cloud/blockstore/libs/storage/volume/volume.cpp
cloud/blockstore/libs/storage/volume/volume.h
cloud/blockstore/libs/storage/volume/volume_actor.cpp
cloud/blockstore/libs/storage/volume/volume_actor.h
cloud/blockstore/libs/storage/volume/volume_actor_migration.cpp
cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp
cloud/blockstore/libs/storage/volume/volume_actor_stats.cpp
cloud/blockstore/libs/storage/volume/volume_state.cpp
cloud/blockstore/libs/storage/volume/volume_state.h
cloud/blockstore/libs/storage/volume/volume_ut.cpp

When volume starts migration the endpoint will be switched to use regular data
path (NRD volume through actor system).
Additionally when "use-fastpath" added/removed to volume tags the endpoint will
switch to use fast/regular data path
Additionally resolves #312

NBS #179: switch fast path volume to regular path during migrations (#512)

---

cloud/blockstore/libs/storage/disk_agent/rdma_target.cpp

Disk agent actor cannot be released safely while RdmaTarget, which is used by
RdmaServer, can still get incoming requests from the server and submit them to
RdmaTarget's queue.
The proper release sequence should first disconnect all sessions on RdmaServer
and, therefore, ensure that no incoming requests can arrive. Then the RdmaTarget
can be released, and later the RdmaServer can be stopped.

NBS #592: Prevent RdmaServer deadlock during disk agent stopping

---

cloud/blockstore/libs/storage/disk_agent/rdma_target.cpp

Disk agent actor cannot be released safely while RdmaTarget, which is used by
RdmaServer, can still get incoming requests from the server and submit them to
RdmaTarget's queue.
The proper release sequence should first stop RdmaServer.

NBS #592: Prevent RdmaServer deadlock during disk agent stopping (#625)

---

cloud/tasks/storage/storage_ydb_impl.go

Otherwise, on 1 March, after 29 February it stops working.

fix 'next day' condition in tasks

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_acquire.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_session.cpp

Если не позволять захватывать сессию с пустым списком девайсов (был E_REJECTED), то (например при выходе всех агентов диска) вольюм будет ретраить захват сессии вечно, зажгутся алерты - машинерия по маскировке ошибок NRD не будет работать.

fix NRD acquire: allow acquiring empty list of devices

---

cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_writeblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_zeroblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_writeblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_zeroblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_ut.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_ut.cpp

Для фоновых запросов в cookie запросов лежит не номер запроса вольюма, а просто какая-та чиселка. Она пробрасывалась в дискагенты, и так это не ноль, то происходило отклонение таких фоновых запросов. Что поломало ресинхронизацию дисков.

NBS-4000 fix for background requests

---

cloud/disk_manager/internal/pkg/resources/disks.go
cloud/disk_manager/internal/pkg/resources/storage.go
cloud/disk_manager/internal/pkg/services/disks/create_overlay_disk_task.go

- we do use these parametrs
- now these parametrs can be not actual for disks
so, it will be better to remove them

NBS-4488: [Disk Manager] remove unused parametrs from disks table

---

cloud/disk_manager/test/acceptance/test_runner/lib/helpers.py

In some cases, 60 seconds is not enough for the os to detect the disk. Wait 120 seconds instead.

[CI]: Increase disk detection timeout for sync test

---

cloud/blockstore/libs/endpoints/endpoint_manager.cpp
cloud/filestore/libs/endpoint/service.cpp
cloud/storage/core/tools/common/go/configurator/configurator.go

When client stop endpoint we should remove this endpoint from endpoint storage.
It doesn’t matter whether this endpoint was persistent or not.
It also doesn’t matter if we have errors during stopping.

Remove endpoint from storage when client stop it. Fix typo.

---

.github/scripts/vm-watcher.py
.github/workflows/build_and_test_on_demand.yaml
.github/workflows/build_and_test_on_demand_cmake.yaml

If you do not add always() condition, VM creation could be cancelled, and we would not get necessary id to remove it
Example here: https://github.com/ydb-platform/nbs/actions/runs/8030802857
New push cancelled workflow and `release runner` didn't have an id to remove and now we have vm using resources
Script here to help find and remove those vms if they will happen in the future, it also helps with finding workflows that may have caused this behaviour

fix: vms whose creation was cancelled

---

cloud/blockstore/vhost-server/server_ut.cpp

sometimes ShouldHandleMutlipleQueues fails because it can't get the actual stats.

tweak ShouldHandleMutlipleQueues: wait for stats sync

---

cloud/blockstore/libs/storage/partition_nonrepl/config.h
cloud/blockstore/libs/storage/service/service_actor_actions_get_dependent_disks.cpp
cloud/blockstore/libs/storage/service/service_actor_actions_update_disk_registry_params.cpp
cloud/blockstore/libs/storage/service/service_ut_actions.cpp
cloud/blockstore/libs/storage/service/volume_session_actor_mount.cpp
cloud/blockstore/libs/storage/ss_proxy/ss_proxy_actor_describescheme.cpp
cloud/storage/core/libs/common/helpers.h

Some agents may be in inactive state: even though they exist and work, they are missing from DiskRegistry AgentList. In such case GetDependentDisk and UpdateDiskRegistryParams request leads to E_NOT_FOUND error causing false alert. 
This PR adds EF_SILENT flag to this error to suppress alert.

Silent E_NOT_FOUND in GetDependentDisks and UpdateDiskRegistryParams requests

---

cloud/blockstore/libs/storage/partition_nonrepl/config.h
cloud/blockstore/libs/storage/service/service_actor_actions_get_dependent_disks.cpp
cloud/blockstore/libs/storage/service/service_actor_actions_update_disk_registry_params.cpp
cloud/blockstore/libs/storage/service/service_ut_actions.cpp
cloud/blockstore/libs/storage/service/volume_session_actor_mount.cpp
cloud/blockstore/libs/storage/ss_proxy/ss_proxy_actor_describescheme.cpp
cloud/storage/core/libs/common/helpers.h

cherry-pick of #572
* Silent E_NOT_FOUND in GetDependentDisks and UpdateDiskRegistryParams requests
* Update test for GetDependentDisk
* Update test for UpdateDiskRegistryAgentListParams
---------

[merge to stable-23-3] Silent E_NOT_FOUND in GetDependentDisks and UpdateDiskRegistryParams requests (#572)

---

cloud/blockstore/libs/disk_agent/bootstrap.cpp

Due to stopping `FileIOService` before `ActorSystem`, some IO requests may hang.
[Here](https://github.com/ydb-platform/nbs/blob/cfac667d68c82641ca86bfea585461cbc24a7530/cloud/blockstore/libs/disk_agent/bootstrap.cpp#L556) we stop the `FileIOService`. This leads to the [stopping](https://github.com/ydb-platform/nbs/blob/cfac667d68c82641ca86bfea585461cbc24a7530/cloud/storage/core/libs/aio/service.cpp#L118) of a thread that invokes `io_getevents`. So requests that were in the completion queue after `Stop` was invoked can't be handled. In turn, the destructor of `TDiskAgentState` (somewhere inside the actor system) destroys [Devices](https://github.com/ydb-platform/nbs/blob/cfac667d68c82641ca86bfea585461cbc24a7530/cloud/blockstore/libs/storage/disk_agent/disk_agent_state.h#L57) and invokes a …

fix ActorSystem hanging on DiskAgent' shutdown

---

cloud/blockstore/libs/storage/disk_agent/actors/session_cache_actor.cpp
cloud/blockstore/libs/storage/disk_agent/actors/session_cache_actor.h
cloud/blockstore/libs/storage/disk_agent/actors/ya.make
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_acquire.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_release.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_ut.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_state.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_state.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_state_ut.cpp
cloud/blockstore/libs/storage/disk_agent/testlib/test_env.cpp
cloud/blockstore/libs/storage/disk_agent/testlib/test_env.h
cloud/blockstore/libs/storage/disk_agent/ya.make

In order not to block the User thread pool (where read/write requests are executed), the session cache update was moved to a special actor that runs in the IO thread pool. 
Issue #170

offload the session cache update to the IO pool

---

cloud/blockstore/libs/kikimr/components.h
cloud/blockstore/libs/storage/init/server/actorsystem.cpp
cloud/blockstore/libs/storage/partition2/part2_actor_monitoring_garbage.cpp
cloud/filestore/libs/storage/api/components.h
cloud/filestore/libs/storage/api/ya.make
cloud/filestore/libs/storage/init/actorsystem.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.cpp
cloud/storage/core/libs/kikimr/components.h
cloud/storage/core/libs/kikimr/components_start.cpp
cloud/storage/core/libs/kikimr/components_start.h
cloud/storage/core/libs/kikimr/ya.make
cloud/storage/core/libs/user_stats/user_stats.cpp
cloud/storage/core/libs/user_stats/user_stats.h
cloud/storage/core/libs/user_stats/user_stats_actor.cpp
cloud/storage/core/libs/user_stats/user_stats_actor.h

1. Removed TBlockStoreActivities, TFileStoreActivities, TStorageActivities
2. Moved some components magic numbers to separate header
3. Now TUserStats actor takes log component parameter, like in hive proxy and auth component. This was done because it is more clear to define storage components in terms of  NFS and NBS components, not a separate entity. Plus this eliminates the need for initializing logger for storage components.

issue-479: get rid of TxxxStoreActivities class

---

cloud/filestore/libs/storage/tablet/tablet_actor_request.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_resetsession.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_unlinknode.cpp

Sometimes session reset may cause large truncate operations which lead to problems like #702. We need to see what exactly is being done during the reset operation. Also it's convenient to have request ids in error messages to make request-error matching easier.

issue-702: logging removed handles and nodes for the handles that are destroyed upon session reset; added request id to error messages in responses

---

cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_io.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_ut.cpp
cloud/blockstore/libs/storage/disk_agent/rdma_target.cpp

Additionally report non health check reads during secure erase and add aditional
info to the critical event report

NBSNEBIUS-146: don't generate critical events on health check read during secure erase

---

cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_io.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_ut.cpp
cloud/blockstore/libs/storage/disk_agent/rdma_target.cpp

Additionally report non health check reads during secure erase and add extra info to the critical event report

NBSNEBIUS-146: don't generate critical events on health check read during secure erase (#699)

---

cloud/filestore/libs/storage/tablet/rebase_logic.cpp
cloud/filestore/libs/storage/tablet/rebase_logic.h
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp

Improves the following scenario:
1. WriteData(range1) -> blob1
2. WriteData(range2 which intersects with range1) -> blob2
3. Compaction -> blob3
4. Here the blocks from the intersection of range1 and range2 that were originally stored in blob1 and are in fact garbage get stored in blob3
This PR makes compaction discard those garbage blocks

issue-95: Compaction should rebase blocks in order not to write garbage blocks to dst blobs

---

.github/workflows/build_and_test_on_demand.yaml
.github/workflows/build_and_test_on_demand_cmake.yaml

By default checkout fetches only latest commit `fetch-depth: 1`.
To rebase we need to fetch some amount of commits PR commits + previous one, and then you can rebase it. But in GA you cant determine amount of commits to fetch so we fetch all `fetch-depth: 0` but realistically we can fetch some ambigious amount like 100 and this should be enough in most cases.

Rebase fix

---

cloud/blockstore/config/disk.proto
cloud/blockstore/libs/storage/disk_agent/disk_agent_state_ut.cpp
cloud/blockstore/libs/storage/disk_agent/model/device_scanner.cpp
cloud/blockstore/libs/storage/disk_agent/model/device_scanner_ut.cpp
cloud/blockstore/libs/storage/disk_agent/storage_initializer.cpp

For convinience we can infer `MinSize` from the layout as `HeaderSize` + `DeviceSize`. And if `MaxSize` is set to 0 we can assume that is no limit on the device max size for the current `PoolConfig`. In that way the config looks cleaner. For example, the pool config below will be applied to any device with a size >= 94 GiB
```
PoolConfigs {
Layout {
HeaderSize: 1073741824    #  1 GiB
DeviceSize: 99857989632   # 93 GiB
DevicePadding: 33554432   # 32 MiB
}
}
```

NBSNEBIUS-105: make MinSize & MaxSize parameters optional for the Pool Configs 

---

cloud/blockstore/libs/daemon/common/bootstrap.cpp
cloud/blockstore/libs/daemon/common/bootstrap.h
cloud/blockstore/libs/endpoints/endpoint_manager.cpp
cloud/blockstore/libs/endpoints/endpoint_manager.h
cloud/blockstore/libs/endpoints/endpoint_manager_ut.cpp
cloud/blockstore/libs/endpoints/public.h
cloud/blockstore/libs/endpoints/service_endpoint.cpp
cloud/blockstore/libs/endpoints/service_endpoint.h
cloud/blockstore/libs/endpoints/service_endpoint_ut.cpp

EndpointManager should implement all endpoint methods (including KickEndpoint and restore endpoints).
EndpointService should be just adapter from IBlockStore to IEndpointManager.

move EndpointStorage usage from endpoint_service to endpoint_manager

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/partition_nonrepl/migration_timeout_calculator.cpp
cloud/blockstore/libs/storage/partition_nonrepl/migration_timeout_calculator.h
cloud/blockstore/libs/storage/partition_nonrepl/migration_timeout_calculator_ut.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_actor.cpp
cloud/blockstore/libs/storage/volume/actors/shadow_disk_actor.cpp
cloud/blockstore/libs/storage/volume/actors/shadow_disk_actor.h
cloud/blockstore/libs/storage/volume/actors/ya.make
cloud/blockstore/libs/storage/volume/model/checkpoint.cpp
cloud/blockstore/libs/storage/volume/testlib/test_env.cpp
cloud/blockstore/libs/storage/volume/volume_actor.h
cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
cloud/blockstore/libs/storage/volume/volume_actor_resync.cpp
cloud/blockstore/libs/storage/volume/volume_actor_startstop.cpp
cloud/blockstore/libs/storage/volume/volume_ut_checkpoint.cpp
example/nbs/nbs-storage.txt

Здесь актор, который наливает теневой диск данными и позволяет читать чекпоинт с этого диска.

NBS-4827 Shadow disk actor

---

cloud/blockstore/libs/storage/volume/testlib/test_env.cpp
cloud/blockstore/libs/storage/volume/testlib/test_env.h
cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
cloud/blockstore/libs/storage/volume/volume_ut_checkpoint.cpp

The fix makes sure the withoutdata parameter is properly sent to the partition tablet. It's important to wait DM release (with [commit](https://github.com/ydb-platform/nbs/pull/102)) to merge this fix.

NBS-4773 [blockstore] Fix checkpoint without data creation

---

cloud/filestore/libs/storage/tablet/tablet_actor.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_allocatedata.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_deletecheckpoint.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_destroycheckpoint.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_destroyhandle.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_destroysession.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_setnodeattr.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_truncate.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_unlinknode.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_zerorange.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp

If a Truncate operation is executed before CompactionMap gets fully loaded, there is a chance that this Truncate op may cause a CompactionMap update based on 0 stats for the corresponding compaction range => real compaction stats for that range can be lost => automatic Compaction will work less efficiently.
#95

issue-95: operations that can potentially cause Truncate should not be allowed until compaction map gets fully loaded

---

cloud/blockstore/libs/storage/disk_agent/disk_agent_actor.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_init.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_monitoring.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_register.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_ut.cpp

The point of the Idle state is to not spam to DR with RegisterAgent and UpdateAgentStats events.

Disk Agent switches to the Idle state when it can't find devices

---

cloud/blockstore/libs/storage/volume/model/merge.cpp
cloud/blockstore/libs/storage/volume/model/merge.h
cloud/blockstore/libs/storage/volume/model/merge_ut.cpp
cloud/blockstore/libs/storage/volume/model/stripe.cpp
cloud/blockstore/libs/storage/volume/model/stripe.h
cloud/blockstore/libs/storage/volume/model/stripe_ut.cpp
cloud/blockstore/libs/storage/volume/partition_requests.h
cloud/blockstore/libs/storage/volume/volume_actor_forward.cpp
cloud/blockstore/libs/storage/volume/volume_ut.cpp

[Blockstore] support DescribeBlocks method for disks with several partitions 

---

cloud/filestore/libs/storage/tablet/actors/tablet_writedata.cpp
cloud/filestore/libs/storage/tablet/actors/tablet_writedata.h
cloud/filestore/libs/storage/tablet/actors/ya.make
cloud/filestore/libs/storage/tablet/model/garbage_queue.cpp
cloud/filestore/libs/storage/tablet/model/garbage_queue.h
cloud/filestore/libs/storage/tablet/tablet_actor.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_cleanup.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_compaction.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_deletecheckpoint.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_flush.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_flush_bytes.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_readdata.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_writebatch.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_writedata.cpp
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
cloud/filestore/libs/storage/tablet/ya.make

Some preliminary changes for #539, as mentioned here: https://github.com/ydb-platform/nbs/pull/707#pullrequestreview-1948429394
1. Extract `TWriteDataActor` into a separate file
2. Replace `ReleaseCollectBarrier` with `TryReleaseCollectBarrier`, add `TABLET_VERIFY` for validating the result
3. Extract the validator from the `HandleWriteData` method into a separate method.

issue-539: extract writedata actor into separate location + add TABLET_VERIFY for ReleaseCollectBarrier

---

cloud/storage/core/tools/common/python/daemon.py

#757 
Otherwise, we can get 'address already in use' error when restarting daemon in tests https://github.com/ydb-platform/nbs/blob/main/cloud/blockstore/tests/python/lib/nbs_runner.py#L624

issue-757: Daemon should wait when terminating or killing process

---

cloud/blockstore/libs/endpoints/endpoint_manager.cpp
cloud/blockstore/libs/nbd/ut/ya.make
cloud/blockstore/libs/nbd/utils.cpp
cloud/blockstore/libs/nbd/utils.h
cloud/blockstore/libs/nbd/utils_ut.cpp

Kubelet makes a loop device when attaches block device. The reason is described here: https://github.com/kubernetes/kubernetes/blob/a309fadbac3339bc8db9ae0a928a33b8e81ef10f/pkg/volume/util/util.go#L519 
This loop device blocks reconnecting to the block device when NBS is restarting.
So in this PR NBS removes corresponding loop device before starting endpoint.

NBSNEBIUS-199: remove kubelet's lock from nbd device

---

cloud/blockstore/libs/storage/partition/model/blob_to_confirm.cpp
cloud/blockstore/libs/storage/partition/model/blob_to_confirm.h
cloud/blockstore/libs/storage/partition/model/ya.make
cloud/blockstore/libs/storage/partition/part_actor_addconfirmedblobs.cpp
cloud/blockstore/libs/storage/partition/part_actor_writemergedblocks.cpp
cloud/blockstore/libs/storage/partition/part_database.cpp
cloud/blockstore/libs/storage/partition/part_database.h
cloud/blockstore/libs/storage/partition/part_events_private.h
cloud/blockstore/libs/storage/partition/part_state.cpp
cloud/blockstore/libs/storage/partition/part_state.h
cloud/blockstore/libs/storage/partition/part_tx.h
cloud/blockstore/libs/storage/partition/part_ut.cpp

#122 
For now, checksums are not persisted, so they will disappear after partition tablet restart

issue-122: pass blob checksums when adding unconfirmed blobs

---

cloud/blockstore/libs/endpoints/endpoint_manager.cpp
cloud/blockstore/libs/endpoints/endpoint_manager_ut.cpp
cloud/blockstore/libs/endpoints/service_endpoint_ut.cpp
cloud/blockstore/libs/vhost/server.cpp

There is a case when kubelet removes a created socket and sends again StartEndpointRequest to NBS. Then NBS reply S_ALREADY, but don’t recreate socket.

NBSNEBIUS-197: StartEndpointRequest creates socket file if needed

---

cloud/blockstore/libs/storage/volume/actors/shadow_disk_actor.cpp
cloud/blockstore/libs/storage/volume/volume_actor.cpp
cloud/blockstore/libs/storage/volume/volume_actor.h
cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp
cloud/blockstore/libs/storage/volume/volume_actor_startstop.cpp
cloud/blockstore/libs/storage/volume/volume_actor_stats.cpp
cloud/blockstore/libs/storage/volume/volume_state.cpp
cloud/blockstore/libs/storage/volume/volume_state.h
cloud/blockstore/libs/storage/volume/volume_ut_stats.cpp

Статистика для мониторингов по теневому диску.
Основная идея что мы регистрируем теневой диск, когда он появляется. И разрегистрируем в StorageService когда чекпоинт удаляет свой теневой диск.

NBS-4967 Shadow disk statistics

---

.github/actions/ncp/action.yaml
.github/actions/runner_create/action.yaml
.github/actions/runner_remove/action.yaml
.github/scripts/create-vm.py
.github/scripts/manage-vm.py
.github/workflows/build_and_test_on_demand.yaml
.github/workflows/build_and_test_on_demand_cmake.yaml

I replaced js github action with python one mostly because of that nobody knows js in the team and modifications and bugfixes are very difficult + python sdk can change endpoint without uploading the same code to npm repo.
Also I incorporated few useful features that before required additional steps in prepare stage:
1. Getting and adding ssh keys for github user (api calls and setting ssh keys at the creation of vm is faster)
2. Showing ip addresses is basically free now (it is in response of CreateInstanceRequest)
Future plans are:
1. Move it to separate repo and maybe create docker action
2. Test if we can launch runner as `github` user, not root (to remove annoying `sudo -H -E everywhere` and everything)

feature: omit yc-github-runner in favor of python script

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_cms.cpp

Return E_INVALID_STATE when ADD_HOST tries to add an unavailable host and when ADD_DEVICE tries to add a broken device

respond with fatal errors to CMS requests in some cases

---

cloud/blockstore/libs/storage/disk_agent/model/device_client.cpp
cloud/blockstore/libs/storage/disk_agent/model/public.h
cloud/blockstore/libs/storage/testlib/disk_registry_proxy_mock.h
cloud/blockstore/libs/storage/volume/actors/shadow_disk_actor.cpp
cloud/blockstore/libs/storage/volume/actors/shadow_disk_actor.h
cloud/blockstore/libs/storage/volume/volume_actor_startstop.cpp
cloud/blockstore/libs/storage/volume/volume_events_private.h
cloud/blockstore/libs/storage/volume/volume_ut_checkpoint.cpp

Столкнулся с проблемой создания теневого диска на боевом кластере из-за проверки clientId на строне диска-агентов.
Как сейчас работает:
1. во время наливки теневого диска он может захватываться либо клиентом который пишет на основной диск, либо "shadow-disk-client".
2. после наливки теневого диска он уже перемеонтируется "shadow-disk-client" навсегда
3. если в процессе наливки приходят-уходят клиенты, каждый раз происходит перемотирование.
4. после наливки - изменения клиента основного диска уже игнорируются
5. если происходит ошибка освобождения диска клиентом, которым последний раз захватили диск - делаем вторую попытку освобождения клиентом "any-writer", и не смотря на ее результат делаем попытку захвата диска.
Был вариант использовать клиента "migration", но он не требует захвата …

NBS-4827 fix clientId usage for shadow disk

---

cloud/blockstore/libs/storage/partition_nonrepl/model/processing_blocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/model/processing_blocks_ut.cpp

Turns out that this optimization is vital for large (e.g. 100TiB) disks
#843

issue-843: making TProcessingBlocks::SkipProcessedRanges 1024 times faster

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp

issue-654: limiting the number of volume MetaHistory records displayed on volume monpage

---

cloud/disk_manager/internal/pkg/clients/nbs/interface.go
cloud/disk_manager/internal/pkg/clients/nbs/mocks/client_mock.go
cloud/disk_manager/internal/pkg/clients/nbs/testing_client.go
cloud/disk_manager/internal/pkg/facade/disk_service_test/disk_relocation_test.go
cloud/disk_manager/internal/pkg/facade/disk_service_test/disk_service_test.go
cloud/disk_manager/internal/pkg/facade/image_service_test/image_service_test.go
cloud/disk_manager/internal/pkg/facade/private_service_test/private_service_test.go
cloud/disk_manager/internal/pkg/facade/snapshot_service_test/snapshot_service_test.go
cloud/disk_manager/internal/pkg/facade/testcommon/common.go
cloud/disk_manager/test/remote/cmd/main.go

https://github.com/ydb-platform/nbs/issues/831

#831: [Disk Manager] validate crc32 for each block; log new crc32 for each block after writing in tests;

---

.github/workflows/build_and_test_cmake.yaml
.github/workflows/build_and_test_on_demand.yaml
.github/workflows/build_and_test_on_demand_cmake.yaml
.github/workflows/build_and_test_ya.yaml
.github/workflows/github_actions_scripts.yaml

In github actions there is a ternary-like operator, but it is not really [ternary](https://docs.github.com/en/actions/learn-github-actions/expressions#example).
>  It is important to note that the first value after the && must be truthy. Otherwise, the value after the || will always be returned.
What means truthy?
> Note that in conditionals, falsy values (false, 0, -0, "", '', null) are coerced to false and truthy (true and other non-falsy values) are coerced to true.
And bug occurs because 0 is casted, for some reason, to false

fix: ternary-like expressions in github actions are weird. Also fix for missing rebase expressions

---

cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/api/service.h
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/service/service_actor_writedata.cpp
cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/service/ya.make
cloud/filestore/libs/storage/tablet/actors/tablet_adddata.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_createsession.cpp
cloud/filestore/libs/storage/tablet/tablet_private.h
cloud/filestore/libs/storage/tablet/tablet_ut_sessions.cpp
cloud/filestore/public/api/protos/fs.proto
cloud/filestore/tests/loadtest/service-kikimr-newfeatures-test/nfs-storage.txt

Continuation of #707, references #539.
Add the ability to perform client-side writes:
1. BlobIds are issued to a client via a `GenerateBlobIds` request.
2. Data is written directly to the BlobStorage
3. On the completion `AddData` request is called to complete the write.
On any error, a fallback to a regular write path is used.

issue-539: add service-side two-stage writes support for scaling throughput

---

cloud/blockstore/libs/rdma/impl/client.cpp
cloud/blockstore/vhost-server/backend_aio.cpp
cloud/blockstore/vhost-server/request_aio.cpp
cloud/blockstore/vhost-server/server.cpp

- NEBDUTY-965: promise object passed as pointer to different thread released too early
- NEBDUTY-965: Remove unsafe debug code in vhost-server aio backend
- NEBDUTY-965: help tsan to deduce happens-before relation properly in vhost-server
- NEBDUTY-965: avoid data race when reading WaitMode from rdma client config

NEBDUTY-965: fix thread sanitizer errors in ut

---

cloud/blockstore/libs/storage/volume/model/checkpoint.cpp
cloud/blockstore/libs/storage/volume/model/checkpoint.h
cloud/blockstore/libs/storage/volume/model/checkpoint_ut.cpp
cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp
cloud/blockstore/libs/storage/volume/volume_actor_startstop.cpp
cloud/blockstore/libs/storage/volume/volume_database.cpp
cloud/blockstore/libs/storage/volume/volume_database.h
cloud/blockstore/libs/storage/volume/volume_database_ut.cpp
cloud/blockstore/libs/storage/volume/volume_events_private.h
cloud/blockstore/libs/storage/volume/volume_schema.h
cloud/blockstore/libs/storage/volume/volume_state.cpp
cloud/blockstore/libs/storage/volume/volume_tx.h
cloud/blockstore/libs/storage/volume/volume_ut_checkpoint.cpp

Обработка ошибки от disk-registry, если тот не смог аллоцировать теневой диск.

NBS-4983 Handle allocation shadow disk error

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/service/service_actor.cpp
cloud/blockstore/libs/storage/service/service_actor.h
cloud/blockstore/libs/storage/service/service_events_private.h
cloud/blockstore/libs/storage/service/service_ut_stats.cpp
cloud/blockstore/libs/storage/service/ut/ya.make

We evaluate service actor load by periodicaly sending requests to it and measuring time of passing the message queue.

add selfping sensor to track service actor load

---

cloud/blockstore/tests/rdma/rdma-test/test.py

- check network before running rdma test
- double check network on error during rdma test
- increase extra execute timeout from 5 secs to 10

NEBDUTY-970: refactor rdma test to be more robust to network errors

---

cloud/filestore/tests/build_arcadia_test/__main__.py
cloud/filestore/tests/build_arcadia_test/coreutils.py
cloud/filestore/tests/build_arcadia_test/scripts/coreutils.sh

Remove unused "else" branch in test that builds coreutils.
Code on this branch was sending anonymous requests to sandbox proxy, which soon will be prohibited.

Remove redundant code that sends unauthorized request to sandbox proxy

---

cloud/storage/core/tools/testing/qemu/lib/recipe.py
cloud/storage/core/tools/testing/qemu/lib/ya.make

Adding retries on the startup of the QEMU recipe is a workaround for similar issues: 
https://github-actions-s3.website.nemax.nebius.cloud/ydb-platform/nbs/Nightly-build/8563837729/1/nebius-x86-64/summary/ya-test.html#FAIL

NEBDUTY-982: Add retries to bypass recurring `Connection timed out during banner exchange` error

---

cloud/blockstore/tests/plugin/uds/test.py
cloud/blockstore/tests/plugin/uds/ya.make

stable plugin is pre-compiled binary which we manually update. There is no need
to run with tsan for this binary

NEBDUTY-977: suppress tsan for stable plugin (#914)

---

cloud/blockstore/tests/rdma/rdma-test/test.py

- check network before running rdma test
- double check network on error during rdma test
- increase extra execute timeout from 5 secs to 10

NEBDUTY-970: refactor rdma test to be more robust to network errors (#882)

---

cloud/blockstore/config/server.proto
cloud/blockstore/libs/daemon/common/bootstrap.cpp
cloud/blockstore/libs/endpoints/endpoint_manager_ut.cpp
cloud/blockstore/libs/endpoints_grpc/socket_endpoint_listener.cpp
cloud/blockstore/libs/endpoints_grpc/socket_endpoint_listener.h
cloud/blockstore/libs/endpoints_grpc/socket_endpoint_listener_ut.cpp
cloud/blockstore/libs/endpoints_vhost/external_vhost_server.cpp
cloud/blockstore/libs/endpoints_vhost/external_vhost_server.h
cloud/blockstore/libs/endpoints_vhost/external_vhost_server_ut.cpp
cloud/blockstore/libs/nbd/server.cpp
cloud/blockstore/libs/nbd/server.h
cloud/blockstore/libs/server/config.cpp
cloud/blockstore/libs/server/config.h
cloud/blockstore/libs/server/server.cpp
cloud/blockstore/libs/vhost/server.cpp
cloud/blockstore/libs/vhost/server.h
cloud/blockstore/vhost-server/options.cpp
cloud/blockstore/vhost-server/options.h
cloud/blockstore/vhost-server/server.cpp
cloud/filestore/config/vhost.proto
cloud/filestore/libs/daemon/vhost/bootstrap.cpp
cloud/filestore/libs/endpoint/service.cpp
cloud/filestore/libs/endpoint/service.h
cloud/filestore/libs/endpoint/service_ut.cpp
cloud/filestore/libs/endpoint_vhost/config.cpp
cloud/filestore/libs/endpoint_vhost/config.h
cloud/filestore/libs/server/server.cpp
cloud/storage/core/libs/uds/endpoint_poller.cpp
cloud/storage/core/libs/uds/endpoint_poller.h

NBS and NFS create sockets with access permissions specified in this option.
We need it in k8s to give custom permissions to sockets.

NBSNEBIUS-219: Add SocketAccessMode option to NBS and NFS

---

cloud/filestore/libs/diagnostics/profile_log_events.cpp
cloud/filestore/libs/service/auth_scheme.cpp
cloud/filestore/libs/service/request.cpp
cloud/filestore/libs/service/request.h
cloud/filestore/libs/storage/service/service_actor_writedata.cpp
cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/tools/analytics/libs/event-log/dump_ut.cpp

Adding stats for `ThreeStageWrite` data path on the service side: generic counters for `GenerateBlobIds` and `AddData` requests.

[Filestore] issue-539: add client-side stats for GenerateBlobIds/AddData requests

---

cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/model/range.h
cloud/filestore/libs/storage/tablet/model/read_ahead.cpp
cloud/filestore/libs/storage/tablet/model/read_ahead.h
cloud/filestore/libs/storage/tablet/model/read_ahead_ut.cpp
cloud/filestore/libs/storage/tablet/model/ut/ya.make
cloud/filestore/libs/storage/tablet/tablet_actor_readdata.cpp
cloud/filestore/libs/storage/tablet/tablet_state.cpp
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
cloud/storage/core/libs/common/ring_buffer.h

LRU eviction is a TODO - currently I simply drop the whole cache when its size reaches MaxNodes. It's not a blocker though - this TODO can be implemented sometime later.
Tablet ut will come in the next PR.
#852

issue-852: TReadAheadCache implementation + ut + fixed its usage a bit

---

cloud/filestore/libs/storage/tablet/actors/tablet_adddata.cpp
cloud/filestore/libs/storage/tablet/actors/tablet_adddata.h
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
cloud/filestore/libs/storage/tablet/tablet_private.h
cloud/filestore/libs/storage/tablet/tablet_ut_counters.cpp

Adding stats for `ThreeStageWrite` data path on the tablet side: generic counters for `GenerateBlobIds` and `AddData` requests.
References #539

issue-539: add tablet-side stats for GenerateBlobIds/AddData requests

---

cloud/blockstore/buildall/ya.make
example/prepare_binaries.sh

```blockstore-vhost-server``` is useful for testing purposes, thus it should be added to ```buildall``` target

NBS-5000: Add blockstore-vhost-server to the list of targets in /buildall

---

cloud/blockstore/libs/storage/protos/volume.proto
cloud/blockstore/libs/storage/service/service_state.h
cloud/blockstore/libs/storage/service/service_ut_mount.cpp
cloud/blockstore/libs/storage/service/volume_session_actor_mount.cpp
cloud/blockstore/libs/storage/service/volume_session_actor_start.cpp
cloud/blockstore/libs/storage/volume/volume_actor_addclient.cpp
cloud/blockstore/libs/storage/volume/volume_state.cpp
cloud/blockstore/libs/storage/volume/volume_state.h
cloud/blockstore/libs/storage/volume/volume_tx.h

Restart volume tablet on local read-write mount if one of the following is true:
- client id changed
- mount seq number changed
- fill generation changed
Also add check of fillSeqNumber and fillGeneration in TVolumeSessionActor::ProcessMountRequest [here](https://github.com/ydb-platform/nbs/pull/797/files#diff-d4a5c28978ff23eec206ee6f023ceafccf0fc03ad05913c7af03974f2babaff7R947)

NBS-4503 [nbs] restart volume tablet on local mount when needed

---

cloud/filestore/libs/service/auth_scheme.cpp
cloud/filestore/libs/service/request.cpp
cloud/filestore/libs/service/request.h
cloud/filestore/libs/storage/service/service_actor_readdata.cpp
cloud/filestore/libs/storage/service/service_actor_writedata.cpp
cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp
cloud/filestore/tools/analytics/libs/event-log/dump_ut.cpp

Adding ReadBlob/WriteBlob stats for service. Both in read and write data pathes.
References #539, #324

issue-539: add stats for BS requests for clients

---

cloud/filestore/libs/storage/core/model.cpp
cloud/filestore/libs/storage/core/model.h
cloud/filestore/libs/storage/core/model_ut.cpp
cloud/filestore/libs/storage/service/service_actor_alterfs.cpp
cloud/filestore/libs/storage/service/service_actor_describefsmodel.cpp
cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/testlib/ss_proxy_client.h

filestore-client resize is unable to modify fs performance profile because of this
#999

issue-999: TStorageServiceActor should not ignore TResizeFileStoreRequest::GetPerformanceProfile()

---

cloud/blockstore/libs/daemon/ydb/bootstrap.cpp
cloud/blockstore/libs/disk_agent/bootstrap.cpp

In the old scheme disk agent config can come from cms and override the config
from file.
In the new rdma config scheme rdma-config.txt file will be the authority for
rdma config. Nevertheless we need to stay backward compatible and load disk
agent config from cms in case there is no rdma-config.txt file present.
If rdma-config.txt file is present we will use the config from there and ignore
any other source of config.

NEBDUTY-1076: fix rdma config not loading correctly when specified in cms

---

cloud/blockstore/tests/loadtest/local-overflow/test.py

This test can timeout if the hardware disk it is ran on is not fast enough

Reduce pdisk size in overflow test

---

cloud/blockstore/libs/daemon/ydb/bootstrap.cpp
cloud/blockstore/libs/disk_agent/bootstrap.cpp

In the old scheme disk agent config can come from cms and override the config
from file.
In the new rdma config scheme rdma-config.txt file will be the authority for
rdma config. Nevertheless we need to stay backward compatible and load disk
agent config from cms in case there is no rdma-config.txt file present.
If rdma-config.txt file is present we will use the config from there and ignore
any other source of config.

NEBDUTY-1076: fix rdma config not loading correctly when specified in cms (#1000)

---

cloud/blockstore/tests/storage_discovery/test.py

The check of DirtyDevices has been removed because its value depends on many factors that are hard to control. For example in tsan tests DR/DA can clean some of the added devices before the check takes place.

NEBDUTY-1076: fix storage_discovery/test.py.test_change_layout

---

cloud/filestore/libs/storage/tablet/tablet_actor.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_compaction.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_monitoring.cpp
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp

1. Outputting compaction and cleanup info on tablet monpage: actual thresholds, scores, etc - all the info needed to understand the reasons to run/not to run compaction/cleanup
2. Adjusting compaction threshold to the BlockSize/DefaultBlockSize ratio to avoid infinite compaction loops for filesystems with large BlockSize (see issue #95 for details)
#95

issue-95: 1. outputting compaction and cleanup info on monpage (thresholds, scores, etc.) 2. adjusting compaction threshold to bs/default_bs ratio

---

cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_mirror.cpp
cloud/blockstore/libs/storage/volume/volume_ut_checkpoint.cpp

Обнаружил баг, что когда даелатся чекпоинт для диска, находящегося в миграции, если на него были записи, то drain зависает навечно.

Fix drain when migration in progress

---

cloud/filestore/libs/storage/tablet/model/read_ahead.cpp
cloud/filestore/libs/storage/tablet/model/read_ahead.h
cloud/filestore/libs/storage/tablet/model/read_ahead_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_readdata.cpp
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
cloud/filestore/libs/storage/tablet/tablet_state_sessions.cpp

Some clients have read access patterns which are not sequential when observed at the node level but sequential (or close to sequential) when observed at the file handle level. Whereas other clients may have multiple open handles for a single file but the access pattern is sequential at the node level and __not__ sequential at a single handle level. That's why we need to track access patterns and cache result both per node and per handle.
#852

issue-852: detecting sequential access pattern and caching results not only per node but per handle as well

---

cloud/blockstore/libs/storage/volume/actors/shadow_disk_actor.cpp
cloud/blockstore/libs/storage/volume/actors/shadow_disk_actor.h
cloud/blockstore/libs/storage/volume/testlib/test_env.h
cloud/blockstore/libs/storage/volume/volume_ut_checkpoint.cpp

Исправлено:
1. в ответе на acquire список девайсов может приходить в другом порядке, не как в describe.
2. теперь мы считаем что захватили диски клиентом не в момент получения ответа, а в момент отправки запроса на захват диска. И убрал все проверки, чтобы не было рассинхронизации понимания кем захвачен теневой диск - просто делаю его захват тем клиентом, которым нужно.
3. обрабатываю PoisonPill в  TAcquireShadowDiskActor
4.  и самое главное - использую устройства в том порядке, как их вернул describe.

Fix shadow disk acquiring #2

---

cloud/blockstore/apps/client/lib/backup_volume.cpp
cloud/blockstore/tests/client/test_with_client.py

* fix: client backupvolume command
* fix: add test for backupvolume command without changed-blocks-count parameter

(sync 23-3) fix: client backupvolume command (#1036)

---

cloud/storage/core/tools/ci/runner/run_disk_manager_eternal_256_gib.sh
cloud/storage/core/tools/ci/runner/run_disk_manager_eternal_8_gib.sh
cloud/storage/core/tools/ci/runner/run_disk_manager_eternal_8_tib.sh

Disk limits:
https://nebius.ai/docs/overview/concepts/quotas-limits#compute-limits-vm-disks
- we have 15 MB/s max read/write bandwidth for 32G allocation unit
- we have 18 MB/s max bandwidth per vcpu
- we have 450 MB/s max bandwidth for read/write per disk
- for 8Tib disk it's enough 450/18 ~= 24 cores
- for 256GiB disk it's enough 256 / 32 * 15 / 18 ~= 6 cores
- for 8Gib disk we can reduce to 2 cores (one allocation unit 15MB/s,
2 vcpus 2*18=36 MB/s)

NEBDUTY-1127: reduce cores consumption in disk manager tests

---

cloud/filestore/libs/storage/service/service_actor_readdata.cpp

[Filestore] add missing Die(ctx) in two-stage-read fallback data path

---

cloud/filestore/libs/storage/tablet/model/fresh_bytes.cpp
cloud/filestore/libs/storage/tablet/model/fresh_bytes.h
cloud/filestore/libs/storage/tablet/model/fresh_bytes_ut.cpp
cloud/filestore/libs/storage/tablet/protos/tablet.proto
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_compaction.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_flush_bytes.cpp
cloud/filestore/libs/storage/tablet/tablet_database.h
cloud/filestore/libs/storage/tablet/tablet_schema.h
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
cloud/filestore/libs/storage/tablet/tablet_tx.h
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp

See #95 
Deletion markers are not cleared from the FreshBytes table and stay there forever. This PR fixes it.

issue-95: clearing deletion markers from the FreshBytes table via TxTrimBytes

---

cloud/blockstore/tests/rdma/rdma-test/test.py
cloud/blockstore/tools/testing/rdma-test/bootstrap.cpp
cloud/blockstore/tools/testing/rdma-test/options.cpp
cloud/blockstore/tools/testing/rdma-test/options.h
cloud/blockstore/tools/testing/rdma-test/storage.h
cloud/blockstore/tools/testing/rdma-test/storage_rdma.cpp

This allows to refactor rdma-test and avoid race between target and initiator
starting in delay. Initiator will keep trying to reconnect until much larger
timeout will pass

NEBDUTY-1133: add reconnect timeout option in rdma-test client

---

cloud/filestore/libs/storage/tablet/model/compaction_map.cpp
cloud/filestore/libs/storage/tablet/model/compaction_map.h
cloud/filestore/libs/storage/tablet/model/compaction_map_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_counters.cpp

Needed to check that tablet actor-based MixedBlobsCount and DeletionMarkersCount counters are in sync with the state of the compaction map
#95

issue-95: tracking BlobsCount and DeletionsCount in TCompactionMap and exposing this data as tablet counters

---

library/cpp/monlib/encode/prometheus/prometheus_encoder.cpp
library/cpp/monlib/encode/prometheus/prometheus_encoder_ut.cpp

For now there is a problem in prometheus format. Sensors with names "50" and "90" both transform into the name "_0".

Don't erase first numerical character in sensor name in prometheus format

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_switch_agent_to_read_only.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_lifecycle.cpp

The bug: if an agent does not connect after restarting DR, then dependent disks will not be transferred to the RO state by TEvSwitchAgentDisksToReadOnlyRequest.

fix: don't trigger DiskRegistryAgentNotFound when the agent is not in AgentRegInfo

---

cloud/disk_manager/internal/pkg/clients/nbs/client.go
cloud/disk_manager/internal/pkg/clients/nbs/interface.go
cloud/disk_manager/internal/pkg/clients/nbs/mocks/client_mock.go
cloud/disk_manager/internal/pkg/clients/nbs/session.go
cloud/disk_manager/internal/pkg/dataplane/nbs/source.go
cloud/disk_manager/internal/pkg/dataplane/transfer_from_disk_to_disk_task.go

We do not use optimization that provided by proxy overlay disks because of remote mounting 
data path was:
Snapshot ->  nbs control -> nbs control where disk is mounted -> nbs control -> snapshot 
now it will be: 
snapshot -> nbs control (proxy overlay disk will be mounted on it locally) -> snapshot 
Also we can probably improve load balancing on the nbs control using this approach

should mount proxy overlay disk locally

---

library/cpp/monlib/encode/prometheus/prometheus_encoder.cpp
library/cpp/monlib/encode/prometheus/prometheus_encoder_ut.cpp

If metric has no "sensor" label the assert is triggered causing crash. 
This has been already fixed in ydb repo: https://github.com/ydb-platform/ydb/commit/d7c2d188d2464ce858465870a39220c4dfbb5509 Applying the same in NBS

Removed assert on metrics without sensor label (prometheus format)

---

library/cpp/monlib/encode/prometheus/prometheus_encoder.cpp
library/cpp/monlib/encode/prometheus/prometheus_encoder_ut.cpp

- Don't erase first numerical character in sensor name in prometheus format (#1094)
- Removed assert on metrics without sensor label (prometheus format) (#1102)

[merge to stable-23-3] fixes in monlib 

---

library/cpp/actors/interconnect/interconnect_common.h
library/cpp/actors/interconnect/interconnect_tcp_proxy.cpp
ydb/core/driver_lib/run/kikimr_services_initializers.cpp
ydb/core/protos/config.proto

Бекпорт изменений в YDB: https://github.com/ydb-platform/ydb/pull/3748
Самое важное изменение для нас - снижение максимального времени "сна" интерконнекта с 10 до 1 секунды.
Логика там примерно следующая:
Пытаемся отправить сообщение на ноду которая лежит
Интерконнект пытается установить соединение, но у него не получается
Впадает в "сон" на 10мс.
Во сне любые сообщение до ноды не пытаются отправляться и происходит синхроный undelivery.
Интерконнект просыпается, ждёт посылку сообщения
Повторяем отправку сообщения
Соединение опять не установлено, теперь спим уже 40мс
и т.д.
До этой правки, из-за backoff коэффициента в 4, мы довольно быстро дорастали до 10 секунд. При рестартах диск агента, это означало, что если он не поднимется достаточно быстро, мы попадём в этот десятисекудный сон. Но …

[stable-23-3][Backport] Make interconnect proxy retry timeout parameters configurable

---

cloud/blockstore/libs/storage/volume/model/checkpoint.cpp
cloud/blockstore/libs/storage/volume/model/checkpoint_ut.cpp
cloud/blockstore/libs/storage/volume/volume_actor.h
cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
cloud/blockstore/libs/storage/volume/volume_tx.h

In this pr some changes in processing checkpoint requests are made. Before, we saved a request to database immediately after receiving the request. Now we save a request later -- just before executing it.
In particular, we call SetCheckpointRequestInProgress method before saving the request. Consequently, there is always at most one uncompleted saved request.
This change will help to simplify this https://github.com/ydb-platform/nbs/pull/239. Namely, there will be no need in in-memory queue of postponed requests: all 'waiting' requests are already in memory. By the moment when we save the request, we will already have all the information required to take decision to save or not to save the request.

NBS-4665, NBS-4262 [nbs] save checkpoint request just before execution, i.e. after setting it in progress

---

cloud/filestore/libs/service/auth_scheme.cpp
cloud/filestore/libs/service_kikimr/auth_provider_kikimr_ut.cpp

Removed empty required permissions for fs requests.
Did not create test for this since functionality is tested under https://github.com/ydb-platform/nbs/blob/main/cloud/filestore/tests/loadtest/local-auth/test.py
Removed test that checked that we don't verify permissions for read(inherited from nbs)

issue-944: fix empty permissions

---

cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_io.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_ut.cpp

NBSNEBIUS-281: don't report critical event when BackgroundOps client reads during secure erase

---

cloud/disk_manager/internal/pkg/util/mlock.go
cloud/disk_manager/internal/pkg/util/mlock_test.go
cloud/disk_manager/internal/pkg/util/tests/ya.make
cloud/disk_manager/internal/pkg/util/ya.make
cloud/disk_manager/pkg/app/run.go

Lock process memory ranges containing binary and .so files when process starts. Similar to nbs: https://github.com/ydb-platform/nbs/blob/main/cloud/storage/core/libs/daemon/mlock.cpp
After memory is locked, /proc/<pid>/status and /proc/<pid>/maps for dm process look like this:
[dm_memory_state.txt](https://github.com/ydb-platform/nbs/files/15027268/dm_memory_state.txt) 
As we see, 39572 kB are locked.
NOTE! Before starting dm with this change, LimitMEMLOCK parameter in [Service] section of `/usr/lib/systemd/system/yc-disk-manager.service` should be set. Otherwise the process will fail to lock memory and disk manager will not start. I suggest `LimitMEMLOCK=268435456` (256 MiB).

NBS-1526 [disk manager] call mlock on dm process start

---

cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_compaction.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp

If Compaction doesn't have any blobs to read or write it exits prematurely without re-enqueueing another BlobIndexOp - fixed it. It's hard to write a ut for this thing so I decided to skip it this time. Added a Compaction.DudCount metric as well.
#95

issue-95: Compaction.DudCount metric + enqueueing BlobIndexOp upon dud compactions

---

cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_io.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_ut.cpp

NBSNEBIUS-281: don't report critical event when BackgroundOps client reads during secure erase (#1121)

---

cloud/filestore/libs/storage/tablet/tablet_actor_cleanup.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_flush.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_flush_bytes.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp

Affects forced Cleanup - it skips most of the ranges if some other ops are running concurrently (which is a bug fixed in this PR).
#95

issue-95: fixed BlobIndexOps status codes for the case when another op is running - correct response code is E_TRY_AGAIN

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/partition_nonrepl/model/processing_blocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/model/processing_blocks.h
cloud/blockstore/libs/storage/partition_nonrepl/model/processing_blocks_ut.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_state.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_mirror.cpp
cloud/blockstore/libs/storage/volume/actors/shadow_disk_actor.cpp
cloud/blockstore/libs/storage/volume/actors/shadow_disk_actor.h
cloud/blockstore/libs/storage/volume/volume_actor_stats.cpp
cloud/blockstore/libs/storage/volume/volume_ut.cpp
cloud/blockstore/libs/storage/volume/volume_ut_checkpoint.cpp

Столкнулись с тем что попыки увеличения скорости миграции и наливки теневых дисков ничего не дают. Скорость не поднимается выше 150 МБ/с.
Скорее всего упираемся в то что делаем все в один поток.
В этом ПР добавляю настройку, которой можно управлять количеством одновременно выполняемых запросов миграции.

Parallelize migration and shadow disk fill

---

cloud/filestore/README.md

GPL license (libfuse.so) prohibits static linking. Remove the instructions that violate that rule

Remove instructions for static linking

---

cloud/blockstore/libs/logbroker/topic_api_impl/topic_api.cpp
cloud/blockstore/libs/logbroker/topic_api_impl/topic_api_ut.cpp
cloud/blockstore/libs/logbroker/topic_api_impl/ut/ya.make

Due to the fact that the ReadyToAccept event sometimes does not arrive for a new session (bug?), the session is now being reused.

topic api: use a single write session

---

cloud/disk_manager/internal/pkg/services/snapshots/create_snapshot_from_disk_task.go

Divide [pr 754](https://github.com/ydb-platform/nbs/pull/754) into two separate parts: GetCheckpointStatus method introduction and functional enhancements for rapid NRD snapshots

NBS-4960 [Disk Manager] support GetCheckpointStatus for snapshot creation

---

.github/actions/build/action.yaml
.github/actions/build_cmake/action.yaml
.github/actions/ncp/action.yaml
.github/actions/prepare/action.yaml
.github/actions/runner_create/action.yaml
.github/actions/runner_remove/action.yaml
.github/actions/s3cmd/action.yaml
.github/actions/test/action.yaml
.github/actions/test_cmake/action.yaml
.github/packer/github-runner.pkr.hcl
.github/scripts/github-runner.sh
.github/scripts/index.py
.github/scripts/manage-images.py
.github/scripts/manage-vm.py
.github/scripts/tests/transform-ya-junit.py
.github/scripts/ttl-watcher.py
.github/scripts/workflow-artifact-download.py
.github/workflows/README.md
.github/workflows/build_and_test_cmake.yaml
.github/workflows/build_and_test_on_demand.yaml
.github/workflows/build_and_test_on_demand_cmake.yaml
.github/workflows/build_and_test_ya.yaml
.github/workflows/github_actions_scripts.yaml
.github/workflows/nightly-index-rebuild.yaml
.github/workflows/nightly-packer.yaml
.github/workflows/nightly.yaml
.github/workflows/packer.yaml
.github/workflows/pr-github-actions.yaml

Overview of what has been done:
1. Increased quotas for our cloud and since we have allocated hosts I increased VM memory to its limit and therefore we can increase number of test threads. This gave biggest performance boost: for nightly build, _build_ time decreased by 1hr. But if we upload .ya dir it takes this time back (archiving and uploading takes ~ 1hr)
2. Added task to build VM image on schedule. In result we shave off approximately 2-3 minutes each time, saving on creating VM (before we needed to unpack and update github runner software) and installing necessary packages (or checking that we installed them).
3. Said VM image can contain .ya dir with built code and downloaded artifacts. If we use network-ssd with overlayed VM image we usually shave off 1-2m. But we use …

Speed up checks

---

cloud/blockstore/libs/storage/volume/model/checkpoint.cpp
cloud/blockstore/libs/storage/volume/model/checkpoint.h
cloud/blockstore/libs/storage/volume/model/checkpoint_ut.cpp

Added ValidateCheckpointRequest to checkpoint store. For each checkpoint request, it chooses one of three possible options:
1) Request is invalid and must return error
2) Request is duplicate and should do nothing
3) Request should be saved to database and executed as usual.
This method should be called before saving and executing checkpoint request. We are going to do this in another pull request. These two pull requests are supposed to replace #239, which is going to be discarded. I took in account all comments by reviewers from #239.

NBS-4665 [NBS] Add checkpoint validation method to checkpoint store

---

example/0-setup.sh

From ```test``` man page:
```
-d FILE
FILE exists and is a directory
-e FILE
FILE exists
-f FILE
FILE exists and is a regular file
```
So these ```test``` commands will always fail.
This pr fixes it

Fix example setup script

---

.github/workflows/build_and_test_cmake.yaml
.github/workflows/build_and_test_on_demand.yaml
.github/workflows/build_and_test_on_demand_cmake.yaml
.github/workflows/build_and_test_ya.yaml
.github/workflows/github_actions_scripts.yaml
.github/workflows/pr-github-actions.yaml

problem was, that when you use --global flag it writes to ~/.gitconfig and for that it needs to know $HOME, and for some reason $HOME is not set.

fix: git config flags in rebase

---

.github/scripts/github-runner.sh
.github/workflows/packer.yaml

Turns out VMs were shutting down too fast to sync changes to disks and without sync it produced _sometimes_ inconsistent results, like not writing authorized_keys or, in recent example, not writing part of python library.
Also added few healthchecks to test whether we have everything we need to debug this issue faster (maybe later we will add some other checks too).

fix: empty files produced after running setup script, fixed by running sync + fix for setting github user password

---

cloud/blockstore/libs/storage/volume/volume_actor_throttling.cpp
cloud/blockstore/libs/storage/volume/volume_ut.cpp

#1196
Also fixes issue with local-overflow[version1-throttled] test https://github-actions-s3.website.nemax.nebius.cloud/ydb-platform/nbs/Nightly-build/9072536131/1/nebius-x86-64/summary/ya-test.html#FAIL
```
--- /actions-runner/_work/nbs/nbs/cloud/blockstore/tests/loadtest/local-overflow/canondata/test.test_load_version1-throttled_/stats_overflow-version1-throttled.txt	2024-05-14 01:58:40.817442973 +0000
+++ /home/github/.ya/build/build_root/0k9p/001d62/canon_tmp7gbhff_m/stats_overflow-version1-throttled.txt	2024-05-14 04:39:40.438115267 +0000
@@ -1,3 +1 @@
component:server/sensor:AppCriticalEvents/ReassignTablet=False
-component:service/sensor:ThrottlerRejectedRequests=True
-component:service/sensor:ThrottlerRejectedRequests/type:hdd=True
```

issue-1196: return E_BS_THROTTLED instead of E_REJECTED(Throttled)

---

cloud/filestore/libs/storage/tablet/tablet_actor_collectgarbage.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_generatecommitid.cpp
cloud/filestore/libs/storage/tablet/tablet_private.h
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp
cloud/filestore/libs/storage/tablet/ya.make
cloud/filestore/libs/storage/testlib/tablet_client.h

References #652
Cleanup operation acquires a collect barrier with the current commitId to protect the data with the current commitId (or greater) from being tampered with.
Thus, it will be more logical to modify the CollectGarbage operation not to use the `currentCommitId`, but use `currentCommitId - 1`, if no barriers are present.

[Filestore] issue-652: use `currentCommitId-1` instead of `currentCommitId` for `CollectGarbage`

---

.clang-format
cloud/blockstore/libs/daemon/common/bootstrap.cpp
cloud/blockstore/libs/disk_agent/bootstrap.cpp
cloud/blockstore/tools/testing/rdma-test/bootstrap.cpp
cloud/filestore/libs/daemon/common/bootstrap.cpp
cloud/storage/core/libs/diagnostics/trace_processor.cpp
cloud/storage/core/libs/diagnostics/trace_processor.h
cloud/storage/core/libs/diagnostics/trace_processor_mon.cpp
cloud/storage/core/libs/diagnostics/trace_processor_mon.h
cloud/storage/core/libs/diagnostics/trace_processor_mon_ut.cpp
cloud/storage/core/libs/diagnostics/trace_reader.cpp
cloud/storage/core/libs/diagnostics/trace_reader.h
cloud/storage/core/libs/diagnostics/ut/ya.make
cloud/storage/core/libs/diagnostics/ya.make
cloud/vm/blockstore/bootstrap.cpp

Разбил trace_processor на 3 отдельные части:
- trace_processor - отвечает за то, что бы периодически "сбрасывать" трейсы
- trace_processor_mon - декоратор предыдущего класса, добавляет возможность отображать трейсы на mon странице
- trace_reader - ридеры для трейсов (просто вынес в отдельный файл)

small trace processor refactoring

---

cloud/blockstore/apps/client/lib/endpoint_proxy.cpp
cloud/blockstore/libs/endpoint_proxy/client/client.cpp
cloud/blockstore/libs/endpoint_proxy/server/bootstrap.cpp
cloud/blockstore/libs/endpoint_proxy/server/bootstrap.h
cloud/blockstore/libs/endpoint_proxy/server/options.cpp
cloud/blockstore/libs/endpoint_proxy/server/options.h
cloud/blockstore/libs/endpoint_proxy/server/server.cpp
cloud/blockstore/libs/endpoint_proxy/server/server.h
cloud/blockstore/libs/endpoint_proxy/server/ya.make
cloud/blockstore/libs/nbd/client.cpp
cloud/blockstore/public/api/protos/endpoints.proto
cloud/blockstore/tests/client/canondata/result.json
cloud/blockstore/tests/client/canondata/test_with_client.test_endpoint_proxy/results.txt
cloud/blockstore/tests/client/test_with_client.py

Fixed nbd client Start/StopEndpoint race as well. Can't properly test proxy<->kernel nbd logic in autotests now. Tested manually using the following scripts:
```
root@ubuntu:~/github/blockstore/nbs_setup/example# LD_LIBRARY_PATH=../cloud/blockstore/buildall/cloud/blockstore/apps/client/ ../cloud/blockstore/buildall/cloud/blockstore/apps/client/blockstore-client startendpoint --socket sockets/vol0.sock --disk-id vol0 --ipc-type nbd --mount-mode local
root@ubuntu:~/github/blockstore/nbs_setup/example# LD_LIBRARY_PATH=../cloud/blockstore/buildall/cloud/blockstore/apps/client/ ../cloud/blockstore/buildall/cloud/blockstore/apps/client/blockstore-client startendpoint --socket sockets/vol1.sock --disk-id vol1 --ipc-type nbd --mount-mode local …
```

issue-1164: endpoint-proxy - implemented nbd proxying

---

cloud/filestore/libs/storage/tablet/tablet_database.cpp
cloud/filestore/libs/storage/tablet/tablet_database_ut.cpp

Otherwise we end up with gigabytes of zero ranges in the CompactionMap tables of big filesystems.

issue-1128: entries in the CompactionMap table should be deleted instead of updating of both BlobCount and DeletionCount are 0

---

cloud/filestore/libs/vfs_fuse/loop.cpp

there are still some races happening during shutdown - they don't lead to crashes but lead to hangups in rare cases
can't reproduce it locally - running large tests in a loop for several days in a row fails to detect the problem => decided to commit some logging to have the required debug info in nightly builds

filestore-vhost loop shutdown logging

---

cloud/filestore/tests/loadtest/service-kikimr-localdb-compaction-test/create-remove.txt
cloud/filestore/tests/loadtest/service-kikimr-nemesis-test/create-remove.txt

The mentioned tests are running some load during constant filestore restarts.
Sometimes the request is processed by the server, yet the response is not sent back to the client due to the server restart. To mitigate this issue, a DupCache is used to store the latest requests and their responses. The DupCache is used to match non-idempotent requests with their responses and resend the responses to the client after the server restart.
By its nature, the DupCache is limited in size and by default stores only 1024 entries.
In the latest test failure (https://github-actions-s3.website.nemax.nebius.cloud/ydb-platform/nbs/PR-check/9228148116/1/nebius-x86-64/summary/ya-test.html#FAIL) there have been >1100 requests between two retries of the same `UnlinkNode` request. This caused the DupCache to …

[Filestore] decrease iodepth of nemesis tests because of dup cache limitations

---

cloud/blockstore/libs/storage/volume/model/checkpoint.cpp
cloud/blockstore/libs/storage/volume/model/checkpoint.h
cloud/blockstore/libs/storage/volume/model/checkpoint_ut.cpp
cloud/blockstore/libs/storage/volume/volume_actor.h
cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
cloud/blockstore/libs/storage/volume/volume_actor_forward.cpp
cloud/blockstore/libs/storage/volume/volume_actor_startstop.cpp
cloud/blockstore/libs/storage/volume/volume_ut_checkpoint.cpp

This pr is to replace #239.
When we start to process a checkpoint request, we should call ValidateCheckpointRequest method added in #1134. Depending on the result of validation, we either reply to the request immediately or save the request to the database and execute it as usual.

NBS-4665 [NBS] Validate checkpoint requests and reply without saving/exection when needed

---

cloud/blockstore/apps/client/lib/command.cpp
cloud/blockstore/apps/client/lib/command.h
cloud/blockstore/apps/client/lib/endpoint_proxy.cpp
cloud/blockstore/libs/endpoint_proxy/client/client.cpp
cloud/blockstore/libs/endpoint_proxy/client/client.h
cloud/blockstore/libs/endpoint_proxy/server/bootstrap.cpp
cloud/blockstore/libs/endpoint_proxy/server/options.cpp
cloud/blockstore/libs/endpoint_proxy/server/options.h
cloud/blockstore/libs/endpoint_proxy/server/server.cpp
cloud/blockstore/libs/endpoint_proxy/server/server.h
cloud/blockstore/libs/endpoint_proxy/server/ya.make
cloud/blockstore/tests/client/canondata/result.json
cloud/blockstore/tests/client/canondata/test_with_client.test_endpoint_proxy_uds/results.txt
cloud/blockstore/tests/client/test_with_client.py

blockstore-server <-> blockstore-endpoint-proxy communication will most probably be local to the host so a unix socket channel is preferable 
#1164

issue-1164: support for uds in blockstore-endpoint-proxy

---

cloud/blockstore/libs/storage/api/service.h
cloud/blockstore/libs/storage/service/service_actor.cpp
cloud/blockstore/libs/storage/service/service_actor.h
cloud/blockstore/libs/storage/service/service_actor_monitoring.cpp
cloud/blockstore/libs/storage/service/service_state.cpp
cloud/blockstore/libs/storage/service/service_state.h
cloud/blockstore/libs/storage/volume/volume_actor.cpp
cloud/blockstore/libs/storage/volume/volume_actor.h
cloud/blockstore/libs/storage/volume/volume_actor_addclient.cpp

#1268 
Сделал чтобы на контролах в мониторинге сервиса контрола были видны отселенные на него диски. Ну и на мон. страничку таблетки вывел что таблетка была отселена. Коллеги просили

issue-1268: show preempted volumes at nbs-control monitoring page

---

cloud/filestore/libs/service/context.h
cloud/filestore/libs/vfs_fuse/fs.cpp
cloud/filestore/libs/vfs_fuse/fs.h
cloud/filestore/libs/vfs_fuse/fs_impl.cpp
cloud/filestore/libs/vfs_fuse/fs_impl.h
cloud/filestore/libs/vfs_fuse/loop.cpp

issue-1307: calling fuse_cancel_request instead of fuse_reply_err for cancelled AcquireLock requests

---

cloud/blockstore/libs/common/iovector.cpp

```
[crashed] TIOVectorTest::ShouldTrimVoidBuffers [default-linux-x86_64-release-usan] (0.00s)
Test crashed (return code: 100)
/place/sandbox-data/tasks/3/8/2357407883/__FUSE/mount_path_19fadc74-2bdf-4619-8912-39cad0885237/cloud/blockstore/libs/common/iovector.cpp:183:9: runtime error: load of misaligned address 0x000003371019 for type 'const TBigNumber' (aka 'const unsigned long'), which requires 8 byte alignment
0x000003371019: note: pointer points here
00 00 00  10 00 00 00 00 00 00 00  00 00 55 45 53 54 45 44  00 fd 36 03 00 00 00 00  30 00 00 00 00
^ 
#0 0x1562ca5 in NCloud::NBlockStore::IsAllZeroes /-S/cloud/blockstore/libs/common/iovector.cpp:183:9
#1 0x1562ca5 in NCloud::NBlockStore::TrimVoidBuffers(NCloud::NBlockStore::NProto::TIOVector&) …
```

Fix unaligned access to memory

---

cloud/filestore/libs/endpoint/service.cpp

```
WARNING: ThreadSanitizer: data race (pid=224360)
Read of size 8 at 0x7b44000095c0 by main thread:
#0 NCloud::NFileStore::(anonymous namespace)::TEndpointManager::Drain() /actions-runner/_work/nbs/nbs/cloud/filestore/libs/endpoint/service.cpp:135:34 (filestore-vhost+0x26c5935b) (BuildId: 636bcafcca3e067b10e7765df584d9849a883dc8)
#1 NCloud::NFileStore::(anonymous namespace)::TAuthService::Drain() /actions-runner/_work/nbs/nbs/cloud/filestore/libs/endpoint/service_auth.cpp:47:18 (filestore-vhost+0x26c8cf1f) (BuildId: 636bcafcca3e067b10e7765df584d9849a883dc8)
#2 NCloud::NFileStore::NDaemon::TBootstrapVhost::Drain() /actions-runner/_work/nbs/nbs/cloud/filestore/libs/daemon/vhost/bootstrap.cpp:332:26 (filestore-vhost+0x26c2273a) (BuildId: 636bcafcca3e067b10e7765df584d9849a883dc8)
#3 …
```

issue-1307: accessing Endpoints map under a lock

---

cloud/disk_manager/internal/pkg/services/pools/storage/common.go
cloud/disk_manager/internal/pkg/services/pools/storage/storage_ydb_impl.go

https://github.com/ydb-platform/nbs/issues/1306
we can not mark base disk as deleted if creation failed because we violate `d.activeSlots == 0` invariant in that case 
https://github.com/ydb-platform/nbs/blob/0aef3171f800ec3989ef1bbedf094c0a55a9f3c8/cloud/disk_manager/internal/pkg/services/pools/storage/common.go#L141
added baseDiskStatusCreationFailed - it `isDoomed`, but active_slots may not be equal to 0

[Disk Manager] add baseDiskStatusCreationFailed

---

cloud/filestore/libs/daemon/vhost/bootstrap.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_flush_bytes.cpp

issue-1351: enqueueing Flush and BlobIndexOps upon backpressure error and upon FlushBytes shortcut

---

cloud/filestore/libs/vfs_fuse/fs.cpp
cloud/filestore/libs/vfs_fuse/fs_impl_lock.cpp
cloud/filestore/libs/vfs_fuse/fs_ut.cpp

issue-1373: cancelled requests should not trigger fatal errors during nfs-vhost restart

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_pools.cpp

#1369 
How to reproduce: change the non-standard layout (with BlocksCount != 24379392) to the standard layout. Then on the DR's monpage we will see that all other device parameters will be as expected, but BlocksCount will remain the same.
In this PR was added [unit test](https://github.com/ydb-platform/nbs/pull/1364/files#diff-e634cc966228e6d782a5547e872bab6c32d5d7ca1352d2ff1e626b00d5227019R666) in which the above situation is reproduced: an agent is configured with two devices of different sizes, then the configuration is changed to the standard one. Without the fix, both devices will get the old BlocksCount (262144 and 26214400 respectively, instead of 24379392).

[NBS] bugfix: device's BlocksCount is not adjusted when DevicePool changes

---

cloud/disk_manager/internal/pkg/services/images/config/config.proto
cloud/disk_manager/internal/pkg/services/images/service.go

Enable ability to create pooled images by default

[Disk Manager] add ConfigurePoolsByDefault flag to images config

---

cloud/blockstore/tools/csi_driver/internal/driver/node.go
cloud/blockstore/tools/csi_driver/internal/driver/node_test.go

Right now if two pods try to mount the same filestore, they will use the same clientId. this PR fixes it

NBSNEBIUS-228: deduplicate names of the filestore clients on the same host for csi driver

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_cms.cpp
cloud/blockstore/libs/storage/disk_registry/model/agent_list.cpp
cloud/blockstore/libs/storage/disk_registry/model/agent_list.h
cloud/blockstore/libs/storage/disk_registry/model/agent_list_ut.cpp

Now UpdateConfig doesn't invoke RegisterAgent and therefore STORAGE_VERIFY will not be called.
#1236

issue-1236: update DR config w/o triggering STORAGE_VERIFY

---

cloud/blockstore/libs/storage/volume/volume_actor_stats.cpp
cloud/blockstore/libs/storage/volume/volume_ut_stats.cpp

VBytesCount is 0 for STORAGE_MEDIA_SSD_* media kinds, BytesCount can be 0 for STORAGE_MEDIA_SSD media kinds which have never been mounted for at least somewhere around 30-60 seconds. Fixing this problem in a very simple way. Will get rid of VBytesCount later - when we are sure that noone uses it anymore.

NBSNEBIUS-5: BytesCount is now Max(CalculateVBytesCount(), BytesCount) - preparing to get rid of VBytesCount

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/storage/api/disk_registry.h
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/core/proto_helpers.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_get_agent_node_id.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_get_dependent_disks.cpp
cloud/blockstore/libs/storage/disk_registry/testlib/test_env.h
cloud/blockstore/libs/storage/disk_registry/ya.make
cloud/blockstore/libs/storage/protos/disk.proto
cloud/blockstore/libs/storage/service/service_actor.h
cloud/blockstore/libs/storage/service/service_actor_actions.cpp
cloud/blockstore/libs/storage/service/service_actor_actions_flush_profile_log.cpp
cloud/blockstore/libs/storage/service/service_actor_actions_get_dependent_disks.cpp
cloud/blockstore/libs/storage/service/service_actor_actions_get_disk_agent_node_id.cpp
cloud/blockstore/libs/storage/service/service_actor_actions_wait_dependent_disks_switched_node.cpp
cloud/blockstore/libs/storage/service/service_ut_actions.cpp
cloud/blockstore/libs/storage/service/ya.make
cloud/blockstore/public/api/protos/volume.proto
cloud/blockstore/tests/client/test_with_multiple_agents.py
cloud/blockstore/tests/client/ya.make
cloud/blockstore/tests/python/lib/client.py
cloud/storage/core/libs/diagnostics/critical_events.cpp
cloud/storage/core/libs/diagnostics/critical_events.h

Сделал 2 ручки в blockstore-client:
1) `GetDiskAgentNodeId` - тут всё понятно думаю. Просто получаем численный nodeId
2) `WaitDependentDisksToSwitchNode` - ручка, которая будет дожидаться пока все зависимые диски сменят NodeId
Вкратце логика blue-green скрипта будет такая:
1) Получаем NodeId первого DA
2) Стартуем DA2
3) Ждем с `WaitDependentDisksToSwitchNode` пока диски переедут на DA2
4) Получаем NodeId DA2
5) Рестартуем DA1
6) Ждем с `WaitDependentDisksToSwitchNode` пока диски переедут на DA1

blockstore client API to manage blue-green DA deploy

---

cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/tablet/tablet_actor_createsession.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_sessions.cpp
cloud/filestore/libs/vfs_fuse/loop.cpp
cloud/filestore/tests/loadtest/service-kikimr-newfeatures-test/nfs-storage.txt

Replacement of ExtendedBlockSizeEnabled(bool) with PreferredBlockSizeMultiplier(ui32) should be safe, according to protobuf documentation.
References #1289

[Filestore] issue-1289: rework ExtendedBlockSizeEnabled flag + increase vhost-side logging

---

cloud/blockstore/libs/diagnostics/critical_events.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_mirrored_disks.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_pools.cpp
cloud/blockstore/libs/storage/disk_registry/model/device_list.cpp
cloud/blockstore/libs/storage/disk_registry/model/device_list.h
cloud/blockstore/libs/storage/disk_registry/model/device_list_ut.cpp
cloud/blockstore/libs/storage/disk_registry/model/replica_table_ut.cpp

#1369
The free device pool could include devices with non-standard size. This could have caused the non-consistent size of replicas of mirrored disks. For example, if there is a 186 GiB device in the pool (twice the standard allocation unit) and DR allocate a 186 GiB mirror disk. Then we can get 2 replicas with two 93 GiB devices and one replica with one 186 GiB device. This situation can lead to unexpected consequences (such as nbs crash).

[NBS] do not add devices with non-standard size to the free device pool

---

cloud/blockstore/config/ydbstats.proto
cloud/blockstore/libs/daemon/ydb/bootstrap.cpp
cloud/blockstore/libs/ydbstats/config.cpp
cloud/blockstore/libs/ydbstats/config.h
cloud/blockstore/libs/ydbstats/ydbscheme.cpp
cloud/blockstore/libs/ydbstats/ydbscheme.h
cloud/blockstore/libs/ydbstats/ydbstats.cpp
cloud/blockstore/libs/ydbstats/ydbstats_ut.cpp
cloud/blockstore/libs/ydbstats/ydbstorage.cpp
cloud/blockstore/libs/ydbstats/ydbstorage.h

Right now we limit the size of ydb stats table by setting ttl in a cloud console. It better to have an option to specify ttl in config files.
Ttl as a duration is set in milliseconds as usual. 0 means "do not update ttl for table"
#1412

configure ttl for stat and archive stats ydb tables

---

cloud/blockstore/libs/storage/core/disk_counters.cpp
cloud/blockstore/libs/storage/core/disk_counters.h

Убираю макросы в счетчиках. При таком подходе объявление счетчика чуть сложнее, его нужно прописать в двух местах, но код при этом становится читаемым.
Есть защита от дурака, если не прописать новый счетчик в общем списке всех счетчиков, сломается static_assert.

Get rid macros for counters

---

cloud/filestore/config/diagnostics.proto
cloud/filestore/libs/daemon/common/bootstrap.cpp
cloud/filestore/libs/diagnostics/config.cpp
cloud/filestore/libs/diagnostics/config.h

Right now the filename for cpuWait is equal to `/sys/fs/cgroup/cpu/system.slice/%s.service/cpuacct.wait`, where `%s` is the service name, which can be defined at the `nfs-diagnostics.txt` config as `CpuWaitServiceName`. Analogous to blockstore, we may need to overwrite this statFile path to something custom. This is what `CpuWaitFilename` option in `nfs-diagnostics.txt` does. If not set, `CpuWaitServiceName` will be used in the same manner, as usual

[Filestore] Add CpuWaitFilename field for filestore diagnostics config, analogous to the one in blockstore

---

cloud/blockstore/apps/client/lib/factory.cpp
cloud/blockstore/apps/client/lib/query_agents_info.cpp
cloud/blockstore/apps/client/lib/query_agents_info.h
cloud/blockstore/apps/client/lib/ya.make
cloud/blockstore/libs/service/auth_scheme.cpp
cloud/blockstore/libs/service/request.h
cloud/blockstore/libs/service/request_helpers.h
cloud/blockstore/libs/storage/api/disk_registry.h
cloud/blockstore/libs/storage/api/service.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_query_agents_info.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_agents_info.cpp
cloud/blockstore/libs/storage/disk_registry/testlib/test_state.cpp
cloud/blockstore/libs/storage/disk_registry/testlib/test_state.h
cloud/blockstore/libs/storage/disk_registry/ut/ya.make
cloud/blockstore/libs/storage/disk_registry/ya.make
cloud/blockstore/public/api/grpc/service.proto
cloud/blockstore/public/api/protos/disk.proto
cloud/blockstore/tools/http_proxy/main_test.go
cloud/blockstore/tools/testing/chaos-monkey/monkey_test.go

https://github.com/ydb-platform/nbs/issues/1320
Adding new handle 'QueryAgentsInfo' to grpc/blockstore-client to query information about agents/disks
Current output: list of agent ids with device info: total space, allocated space, suspended space, dirty space
Out of scope for this pull request as a diff is too big already:
1. python mock test: blockstore/tests/client/test_with_client.py
2. Broken space
3. Decommission space

issue-1320: Query agents info

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/service/service_actor_destroy.cpp
cloud/blockstore/libs/storage/service/service_ut_destroy.cpp

Quick fix to be able to distinguish old-style disks (with CloudId field) from new-style disks (without CloudId field) in Destroy operation.

Added DisableDiskWithCloudIdDestruction option

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_agents_info.cpp
cloud/blockstore/public/api/protos/disk.proto

Issue: https://github.com/ydb-platform/nbs/issues/1320
Add  DeviceBrokenSpaceInBytes and DeviceDecommissionedSpaceInBytes to DeviceInfo to return them as part of QueryAgentsInfo response

issue-1320: Add broken and decommissioned space to DeviceInfo

---

cloud/disk_manager/internal/pkg/auth/config/config.proto
cloud/disk_manager/internal/pkg/auth/credentials.go

AuthConfig.CertFile is intended as a certificate for verifying TLS for access service, not for token signing. Fix the semantic.

[Disk Manager]: Add separate certificate for IAM

---

.github/actions/build/action.yaml
.github/actions/prepare/action.yaml
.github/scripts/github-runner.sh
cloud/blockstore/libs/endpoint_proxy/server/server.cpp
cloud/blockstore/libs/nbd/netlink_device.cpp

Follow-up to https://github.com/ydb-platform/nbs/pull/1437
Properly propagates device status to the future returned by Start and Stop methods. Also sets up proper context for HandleStatus and catches exception potentially thrown by TNetlinkDevice constructor

properly set future returned by Start/Stop methods; issue-1164

---

cloud/filestore/config/storage.proto
cloud/filestore/libs/service/request.h
cloud/filestore/libs/storage/api/service.h
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/model/utils.h
cloud/filestore/libs/storage/service/service_actor.h
cloud/filestore/libs/storage/service/service_actor_createhandle.cpp
cloud/filestore/libs/storage/service/service_actor_createnode.cpp
cloud/filestore/libs/storage/service/service_actor_forward.cpp
cloud/filestore/libs/storage/service/service_actor_getnodeattr.cpp
cloud/filestore/libs/storage/service/service_actor_listnodes.cpp
cloud/filestore/libs/storage/service/service_actor_readdata.cpp
cloud/filestore/libs/storage/service/service_actor_writedata.cpp
cloud/filestore/libs/storage/service/service_state.h
cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/service/ya.make
cloud/filestore/libs/storage/tablet/tablet_actor_createhandle.cpp
cloud/filestore/libs/storage/testlib/service_client.h
cloud/filestore/libs/vfs_fuse/fs_impl_attr.cpp
cloud/filestore/public/api/protos/data.proto
cloud/filestore/public/api/protos/node.proto

Forwarded based on NodeId:
* AccessNode
* SetNodeAttr
* GetNodeXAttr
* SetNodeXAttr
* ListNodeXAttr
* RemoveNodeXAttr
Forwarded based on Handle:
* DestroyHandle
* AllocateData
Former handling logic augmented by shard selection based on Handle:
* WriteData
* ReadData
Two-stage handling (request leader -> request follower[s]):
* CreateHandle
* GetNodeAttr
* ListNodes
#1350

issue-1350: support for multitablet filesystems in StorageServiceActor

---

cloud/blockstore/libs/client/durable.cpp
cloud/blockstore/libs/client/session.cpp
cloud/blockstore/libs/diagnostics/request_stats.cpp
cloud/blockstore/libs/diagnostics/request_stats_ut.cpp
cloud/blockstore/libs/diagnostics/volume_stats.cpp
cloud/blockstore/libs/diagnostics/volume_stats.h
cloud/blockstore/libs/diagnostics/volume_stats_test.h
cloud/blockstore/libs/storage/volume_balancer/volume_balancer_ut.cpp

Тут мы можем получить nullptr в volumeInfo
https://github.com/ydb-platform/nbs/blob/main/cloud/blockstore/libs/client/session.cpp#L954
GetStorageMediaKind(nullptr) -> STORAGE_MEDIA_DEFAULT
STORAGE_MEDIA_DEFAULT превращается в TotalHDD
https://github.com/ydb-platform/nbs/blob/main/cloud/blockstore/libs/diagnostics/request_stats.cpp#L498
и начинаем всю статистику ретраев валить в hdd

Fix wrong media kind usage

---

cloud/blockstore/libs/storage/api/disk_agent.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_partial_suspend.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_register.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_ut.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_private.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_state.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_state.h
cloud/blockstore/libs/storage/disk_agent/testlib/test_env.h
cloud/blockstore/libs/storage/disk_agent/ya.make
cloud/blockstore/libs/storage/protos/disk.proto
cloud/blockstore/libs/storage/service/service_actor.h
cloud/blockstore/libs/storage/service/service_actor_actions.cpp
cloud/blockstore/libs/storage/service/service_actor_actions_suspend_disk_agent.cpp
cloud/blockstore/libs/storage/service/ya.make
cloud/blockstore/tests/client/test_with_client.py
cloud/blockstore/tests/client/test_with_multiple_agents.py
cloud/blockstore/tests/python/lib/client.py
cloud/blockstore/tests/python/lib/disk_agent_runner.py
cloud/blockstore/tests/python/lib/nonreplicated_setup.py
cloud/blockstore/tests/python/lib/test_base.py

Related to issue #1502
Added a new message to Disk Agent: `PartiallySuspendAgent`. Only used for blue-green deployment for now. It's sent from the blockstore-client and basically means "another agent will be launched soon, prepare to die".
While the Disk Agent is in this state:
1) It ignores connection loss to the DR.
2) Acquire and Release requests will be rejected, except for acquires which do not change anything.
3) If the Disk Agent is temporary, it will dump the session cache on disk.

blockstore-client API to suspend disk agent

---

cloud/filestore/apps/client/lib/command.cpp
cloud/filestore/apps/client/lib/command.h
cloud/filestore/apps/client/lib/ls.cpp
cloud/filestore/apps/client/lib/mkdir.cpp
cloud/filestore/apps/client/lib/read.cpp
cloud/filestore/apps/client/lib/rm.cpp
cloud/filestore/apps/client/lib/stat.cpp
cloud/filestore/apps/client/lib/touch.cpp
cloud/filestore/apps/client/lib/write.cpp
cloud/filestore/libs/storage/service/service_actor_destroyfs.cpp
cloud/filestore/libs/storage/service/service_ut.cpp

issue: #1384 
1. Reject DestroyFileStore request in case of available active sessions.
2. Destroy session after executing commands in filestore client: 35fef8a180947a75af2fa2f8e583d82bcc44dde7

issue-1384: check active sessions before destroying fs

---

cloud/disk_manager/internal/pkg/dataplane/snapshot/storage/storage_ydb_impl.go

In disk manager nemesis tests, the milestone of the snapshot creation is not being updated, despite write of all the chunks to the YDB is started. Add more verbose logging for finished chunk writes.

[Disk Manager]: Add logging on chunk write success

---

cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_createhandle.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_renamenode.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_updateconfig.cpp
cloud/filestore/libs/storage/testlib/service_client.h

issue-1350: XAttr ut and some request validation + uts

---

cloud/blockstore/tools/ci/check_emptiness_test/lib/main.py
cloud/blockstore/tools/ci/check_emptiness_test/tests/canondata/test.test_check_emptiness_test_cluster1_/testing_out_stuff_results.txt

1. Log "Waiting for 2 tests..." before running scan_disk in thread pool to have stable output order.
2. Log correct test number

fix: emptiness test

---

cloud/filestore/libs/storage/service/service_actor_writedata.cpp
cloud/filestore/libs/storage/service/service_ut.cpp

`TEvBlobStorage::TEvPut` constructor's default handle class is NKikimrBlobStorage::TabletLog:
https://github.com/ydb-platform/nbs/blob/c2d7171d98e18699e072461d486908392662c72d/contrib/ydb/core/base/blobstorage.h#L912-L913
This is not the handle class we want to use for user data.
Long overdue fix for #539.

issue-539: use `NKikimrBlobStorage::UserData` for three-stage write, not `NKikimrBlobStorage::TabletLog`

---

cloud/filestore/libs/diagnostics/critical_events.h
cloud/filestore/libs/storage/tablet/tablet_actor_createhandle.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_createnode.cpp
cloud/filestore/libs/storage/tablet/tablet_tx.h

issue-1350: replacing TABLET_VERIFY with impossible events + errors in CreateNode and CreateHandle

---

cloud/blockstore/tests/.gitignore
cloud/blockstore/tests/vhost-server/run_and_die/__main__.py
cloud/blockstore/tests/vhost-server/run_and_die/ya.make
cloud/blockstore/tests/vhost-server/test.py
cloud/blockstore/tests/vhost-server/ya.make
cloud/blockstore/vhost-server/main.cpp
cloud/blockstore/vhost-server/options.cpp
cloud/blockstore/vhost-server/options.h

1. Оторвал время жизни vhost-server от порождающего его процесса. 
2. Однако оставшись без родителя он будет жить не вечно, а пока не истечет таймаут wait-after-parent-exit. 
3. процесс выставляет себе имя главного потока как vhost-disk-id, которое могут читать другие процессы через /proc/process-id/proc. Из-за ограничений ОС это имя обрезается.
4. сделал закрытие всех хэндлов, унаследованных от родительского процесса, на старте

External vhost server exits from parent process group and works along with timeout

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_secure_erase.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_agents_info.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_create.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_migration.cpp
cloud/blockstore/libs/storage/disk_registry/testlib/test_state.cpp
cloud/blockstore/libs/storage/disk_registry/testlib/test_state.h

Issue: #1394
1. Pass all devices as an argument for MarkDevicesAsClean
2. Update each agent only once.
TryUpdateDevices iterates via devices and save agents in the map to call UpdateAgent and DeviceList.UpdateDevices for each agent only once.

issue 1394: optimize cleanup devices

---

cloud/filestore/apps/client/lib/destroy.cpp
cloud/filestore/config/storage.proto
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/service/service_actor_destroyfs.cpp
cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/testlib/service_client.h
cloud/filestore/public/api/protos/fs.proto

issue: #1384 
1. Add AllowFileStoreForceDestroy flag to storage configuration
2. Add ForceDestroy flag to filestore client
ForceDestroy flag should allow to destroy mounted filestore(with active sessions) if it's allowed in the storage configuration.

issue-1384: add force flag to destroy fs

---

cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_renamenode.cpp

Observed the following problem:
```
2024-07-10T14:51:26.782934Z       GetNodeAttr     0.000442s       S_OK    {parent_node_id=31657, node_name=config.lock, flags=0, mode=33188, node_id=504403158265505008, handle=0, size=240}
2024-07-10T14:51:35.110923Z       GetNodeAttr     0.000511s       S_OK    {parent_node_id=31657, node_name=config, flags=0, mode=33188, node_id=504403158265504888, handle=0, size=204}
2024-07-10T14:51:35.111627Z       RenameNode      0.000383s       S_ALREADY       {parent_node_id=31657, node_name=config.lock, new_parent_node_id=31657, new_node_name=config}
2024-07-10T14:51:41.823435Z       GetNodeAttr     0.000384s       S_OK    {parent_node_id=31657, node_name=config.lock, flags=0, mode=33188, node_id=504403158265505008, handle=0, size=240}
```
The problem was …

issue-1350: renamenode should work for files in the same shard

---

cloud/blockstore/apps/server_lightweight/ya.make

В аркадию приехал новый clang и появилась новая зависимость.
```
Error[-WBadDep]: in $B/cloud/blockstore/apps/server_lightweight/nbsd-lightweight: forbids direct or indirect PEERDIR dependency to module $B/build/internal/platform/clang_toolchain_info/internal-platform-clang_toolchain_info.pkg.fake via CHECK_DEPENDENT_DIRS
$B/cloud/blockstore/apps/server_lightweight/nbsd-lightweight -> $B/contrib/libs/cxxsupp/libcontrib-libs-cxxsupp.a
$B/contrib/libs/cxxsupp/libcontrib-libs-cxxsupp.a -> $B/contrib/libs/cxxsupp/libcxx/liblibs-cxxsupp-libcxx.a
$B/contrib/libs/cxxsupp/libcxx/liblibs-cxxsupp-libcxx.a -> $B/contrib/libs/cxxsupp/libcxxabi-parts/liblibs-cxxsupp-libcxxabi-parts.a
$B/contrib/libs/cxxsupp/libcxxabi-parts/liblibs-cxxsupp-libcxxabi-parts.a -> …
```

Fix arcadia build

---

cloud/blockstore/config/server.proto
cloud/blockstore/libs/daemon/common/bootstrap.cpp
cloud/blockstore/libs/endpoints_vhost/cont_io_with_timeout.h
cloud/blockstore/libs/endpoints_vhost/external_vhost_server.cpp
cloud/blockstore/libs/endpoints_vhost/external_vhost_server.h
cloud/blockstore/libs/endpoints_vhost/external_vhost_server_ut.cpp
cloud/blockstore/libs/endpoints_vhost/ya.make
cloud/blockstore/libs/server/config.cpp
cloud/blockstore/libs/server/config.h
cloud/blockstore/tests/.gitignore
cloud/blockstore/tests/external_endpoint/test.py
cloud/blockstore/tools/testing/fake-vhost-server/__main__.py
cloud/blockstore/vhost-server/options.cpp

1. на стороне NBS находим все запущенные external-vhost-server
2. при запуске нового external-vhost-server останвливаем старый, если он был
3. прогреваем файловый кэш чтобы новый external-vhost-server запускался быстрее
4. учитывается что external-vhost-server может не сразу начать обрабатывать сигналы, и делается несколько попыток получения статистики от него в первый раз https://github.com/ydb-platform/nbs/issues/1242
5. в external-vhost-server передается новый параметр - сколько он имеет право жить без родителя

Find old external-vhost-servers and terminate it when running new

---

cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp

Если диск еще не монтировался с ключом шифрования
показывать хэш ключа безопасно, его нельзя использовать для дешифровки, кроме того можно посмотреть в другом месте.

Show keyhash on monpage

---

cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/tablet/protos/tablet.proto
cloud/filestore/libs/storage/tablet/tablet_actor.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_loadstate.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_oplog.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_renamenode.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_unlinknode.cpp
cloud/filestore/libs/storage/tablet/tablet_database.cpp
cloud/filestore/libs/storage/tablet/tablet_database.h
cloud/filestore/libs/storage/tablet/tablet_private.h
cloud/filestore/libs/storage/tablet/tablet_schema.h
cloud/filestore/libs/storage/tablet/tablet_tx.h
cloud/filestore/libs/storage/tablet/ya.make
cloud/filestore/libs/storage/testlib/service_client.h

Implementing persistent OpLog - needed to retry leader->follower operations that haven't finished successfully. 
Main changes:
1. retrying errors in TUnlinkNodeInFollowerActor
2. recording Unlink ops to OpLog, deleting them upon successful completion
3. replaying OpLog ops upon tablet startup
#1350

issue-1350: OpLog - UnlinkNode

---

cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_createhandle.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_createnode.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_oplog.cpp
cloud/filestore/libs/storage/tablet/tablet_private.h
cloud/filestore/libs/storage/tablet/tablet_tx.h

Followup for https://github.com/ydb-platform/nbs/pull/1594
#1350

issue-1350: replaying CreateNode requests from OpLog upon tablet restart, retrying CreateNode requests happening upon CreateHandle requests, ut

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/core/pending_request.h
cloud/blockstore/libs/storage/disk_common/monitoring_utils.cpp
cloud/blockstore/libs/storage/disk_common/monitoring_utils.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_cms.cpp
cloud/blockstore/tests/infra-cms/test.py
example/nbs/nbs-storage.txt

Первым шагом я начинаю удалять девайсы у агента из DR при вызове REMOVE_HOST. При этом, если на хосте есть диск со сломанным девайсом - поведение не изменится и ни один девайс не будет удалён.
Если все девайсы были удалены, то после выключения агента мы полностью сотрём его из памяти.
По умолчанию поведение также не меняется.
Далее по плану у меня:
1) Удалять кеш у диск агента
2) Перевозить диски в "чистилище" 
3) Удалять девайсы по REMOVE_DEVICE

Cleanup agents from DR on REMOVE_HOST cms action

---

cloud/filestore/libs/storage/service/service_actor_createnode.cpp
cloud/filestore/libs/storage/service/service_ut.cpp

References #1350
Continuation of #1595

issue-1350: hard links for external modes should return correct node

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_mirror.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_readblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp

* resync range if scrubbing found a mismatch
* fix
* fix issues
* fix issues

Merge 23-3: resync range if scrubbing found a mismatch

---

cloud/filestore/libs/vfs_fuse/fs_ut.cpp

Поправил тест который проверяет вот это место https://github.com/ydb-platform/nbs/blob/main/cloud/filestore/libs/vfs_fuse/fs_impl_lock.cpp#L212
и сделал еще один тест про то что запросы прилетевшие в процессе остановки тоже не тригерят фатальные ошибки

fix fuse test

---

cloud/filestore/config/storage.proto
cloud/filestore/libs/diagnostics/critical_events.h
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/service/service_actor_listnodes.cpp
cloud/filestore/libs/storage/service/service_ut.cpp

Doing this under a feature flag to keep backwards-compatibility with old filestore-server versions and to be able to compare the performance of the batch and non-batch versions
#1350

issue-1350: GetNodeAttrBatch implementation in TListNodesActor

---

cloud/disk_manager/internal/pkg/services/pools/rebase_overlay_disk_task.go

#1577
Seems that we've already tried to fix this race earlier by [returning](https://github.com/ydb-platform/nbs/blob/main/cloud/disk_manager/internal/pkg/services/pools/rebase_overlay_disk_task.go#L67) NewInterruptExecutionError in case of "disk not found" error. But this was used in the wrong place.
It does not make sense for error returned by [storage.OverlayDiskRebasing](https://github.com/ydb-platform/nbs/blob/main/cloud/disk_manager/internal/pkg/services/pools/rebase_overlay_disk_task.go#L57). Indeed, [IsDiskNotFoundError](https://github.com/ydb-platform/nbs/blob/86d5c631e861bef09377512cd76f46655f61e6d7/cloud/disk_manager/internal/pkg/clients/nbs/client.go#L358) looks for errors from nbs client, not from storage.
We should handle error from …

[Disk Manager] fix disk not found error handling in rebase_overlay_disk task

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_secure_erase.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_writable_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_private.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_lifecycle.cpp
cloud/blockstore/libs/storage/disk_registry/testlib/test_env.h

Issue: #1395
Problem:
Erasing of hdd disks is significantly slower compare to erasing of nvme disks. Disk registry blocks next erase by setting SecureEraseInProgress flag while current erase is in progress. As a result we can delay erase of the next bunch of nvme disks despite of no nvme disks erase is in progress.
SecureErase is a background process which is regularly triggered by disk registry actor.
Solution:
1. Split SecureErase by pool name
2. Use different SecureEraseInProgress flags depend on the pool name.

issue-1395: run cleaning process per device pool

---

cloud/blockstore/libs/diagnostics/request_stats_ut.cpp

Problem:
Flaky ShouldFillTimePercentiles test
`[[bad]]assertion failed at cloud/blockstore/libs/diagnostics/request_stats_ut.cpp:383, virtual void NCloud::NBlockStore::NTestSuiteTRequestStatsTest::TTestCaseShouldFillTimePercentiles::Execute_(NUnitTest::TTestContext &): (200063 == p50->Val()) failed: (200063 != 200191) [[rst]]`
Reproducible on the developer vm after running stress
Analysis:
The most important thing here is how the duration of the request is [calculated](https://github.com/ydb-platform/nbs/blob/main/cloud/blockstore/libs/diagnostics/request_stats_ut.cpp#L36)
1. calculate requestStarted time via GetCycleCount() 
2. pass fake requestStarted time to requestStats.RequestCompleted by subtracting request.RequestTime(defined in the test) from requestStarted time
3. calculate …

NBSDUTY-33: fix ShouldFillTimePercentiles

---

cloud/blockstore/libs/storage/core/volume_model.cpp
cloud/blockstore/libs/storage/core/volume_model.h
cloud/blockstore/libs/storage/core/volume_model_ut.cpp

https://github.com/ydb-platform/nbs/issues/1634
При изменении размера диска рассчитывается необходимое каналов. Однако не всегда учитывается что общее количество каналов должно быть не больше 255.
В этом ПРе после рассчетов делается подрезка чтобы влезть в это ограничение. Алгоритм такой:
1. считаем сколько всего каналов должно получиться после досоздания 
2. рассчитываем для каждого типа канала его долю в этом общем количестве
3. начинаем отбирать по одному каналу у того типа, доля которого менее всего пострадает, если ему дадут создать меньше каналов чем он запросил.
4. повторяем пункт 3, пока количество каналов, что хотим создать, не совпадет количеством, которые можем создать

Fix channel count overflow

---

cloud/filestore/libs/storage/service/service_actor_destroyfs.cpp
cloud/filestore/libs/storage/service/service_ut.cpp

Problem:
DestroyFileStore for an already destroyed fs returns  NKikimrScheme::EStatus::StatusPathDoesNotExist instead of S_FALSE
Bug was introduced in https://github.com/ydb-platform/nbs/pull/1441 because DestroyFileStore actor and DescribeSessions actor are handling missing fs in different ways.

issue-1384: destruction of an already destroyed fs should return S_FALSE

---

cloud/filestore/libs/storage/service/service_actor_destroyfs.cpp
cloud/filestore/libs/storage/service/service_ut.cpp

cherry-pick: https://github.com/ydb-platform/nbs/pull/1659

merge to stable-23-3: issue-1384

---

cloud/storage/core/tools/common/go/configurator/configurator.go

`ya test -DAUTOCHECK=yes --style -F 'configurator.a.vet.txt::govet' cloud/storage/core/tools/common/go/configurator`
В нашей github репе эта команда не работает. Нужно разобраться и подлить недостающее.

Fix missed error check

---

cloud/filestore/libs/daemon/common/bootstrap.cpp
cloud/filestore/libs/daemon/common/bootstrap.h
cloud/filestore/libs/daemon/common/ya.make
cloud/filestore/libs/daemon/server/bootstrap.cpp
cloud/filestore/libs/daemon/vhost/bootstrap.cpp
cloud/filestore/libs/service_local/fs.cpp
cloud/filestore/libs/service_local/fs.h
cloud/filestore/libs/service_local/fs_data.cpp
cloud/filestore/libs/service_local/fs_lock.cpp
cloud/filestore/libs/service_local/index.cpp
cloud/filestore/libs/service_local/index.h
cloud/filestore/libs/service_local/lowlevel.cpp
cloud/filestore/libs/service_local/lowlevel.h
cloud/filestore/libs/service_local/service.cpp
cloud/filestore/libs/service_local/service.h
cloud/filestore/libs/service_local/service_ut.cpp
cloud/filestore/libs/service_local/service_ut_stress.cpp
cloud/filestore/libs/service_local/session.h
cloud/filestore/libs/service_local/ut/ya.make
cloud/filestore/libs/service_local/ut_stress/ya.make
util/system/file.h

ReadData and WriteData calls are now processed using libaio instead of pread/pwrite
This leads to the need to replace TFile usage by TFileHandle in LocalService (TFile is basically an intrusive ptr for TFileHandle + some convenience wrappers for TFileHandle's methods - all of this is not needed in LocalService) 
#1668

issue-1668: TLocalFileSystem::ReadDataAsync/WriteDataAsync 

---

cloud/blockstore/libs/endpoints_vhost/external_vhost_server.cpp

Когда vhost-server падает на старте, то его рестартуют без задержки. Если он не может подняться по каким-то причинам, то весь лог будет забит ошибками.
Я постепенно увеличиваю таймаут между рестартами до 30 секунд. Если он давно не падал (больше 60 секунд), то рестарт будет сделан сразу.

Use backoff delay when restart external-vhost-server

---

cloud/filestore/tests/loadtest/service-kikimr-newfeatures-test/nfs-storage.txt

issue-1350: GetNodeAttrBatchEnabled: true for multitablet filestore tests

---

cloud/filestore/libs/diagnostics/request_stats.cpp
cloud/filestore/libs/diagnostics/request_stats_ut.cpp
cloud/storage/core/libs/diagnostics/request_counters.cpp
cloud/storage/core/libs/diagnostics/request_counters.h

Unlike NBS we have a lot of different request types in Filestore. And we report a lot of metrics for each <requestType, fsId> pair which generates a lot of work for the monitoring systems that we use. Most of the filesystems never receive the majority of these request types. In this PR I'm not reporting any per-FS counters except Count and Errors/Fatal for the request types which have never been seen by this FS. It should radically decrease the total number of metrics that we report (we'll get rid of a lot of unnecessarily reported zeroes).
#1161

issue-1161: not initializing most of the per-filesystem request counters until we actually receive at least 1 request of the type

---

cloud/blockstore/vhost-server/backend_aio.cpp

MSAN не считает память, которую заполнили чтеним через AIO инициализированной.
```
==901720==WARNING: MemorySanitizer: use-of-uninitialized-value
warning: address range table at offset 0xc0 has a premature terminator entry at offset 0xd0
warning: address range table at offset 0xf0 has a premature terminator entry at offset 0x100
warning: address range table at offset 0x120 has a premature terminator entry at offset 0x130
#0 0x13e276a in NCloud::NBlockStore::IsAllZeroes(char const*, unsigned long) /-S/cloud/blockstore/libs/common/iovector.cpp:187:22
#1 0xae3b99 in NCloud::NBlockStore::NVHostServer::(anonymous namespace)::DoCryptoOperation<&NCloud::NBlockStore::IEncryptor::Decrypt> …
```

Fix MSAN wrong assumption for AIO reading

---

cloud/blockstore/libs/nbd/device.cpp

In case of not opened device we throw exception below in the code with not relevant message ["could not setup device block size"](https://github.com/ydb-platform/nbs/blob/13b2bfb36076128c189f3da0d09564a63d07494f/cloud/blockstore/libs/nbd/device.cpp#L189)
It's better to check `device.IsOpen()` and throw exception with correct error message

fix: throw exception if device is not open

---

cloud/blockstore/pylibs/ycp/ycp.py
cloud/disk_manager/test/acceptance/main.go
cloud/disk_manager/test/acceptance/test_runner/README.md
cloud/disk_manager/test/acceptance/test_runner/acceptance_test_runner.py
cloud/disk_manager/test/acceptance/test_runner/base_acceptance_test_runner.py
cloud/disk_manager/test/acceptance/test_runner/cleanup.py
cloud/disk_manager/test/acceptance/test_runner/eternal_acceptance_test_runner.py
cloud/disk_manager/test/acceptance/test_runner/lib/helpers.py
cloud/disk_manager/test/acceptance/test_runner/lib/test_cases.py
cloud/disk_manager/test/acceptance/test_runner/main.py
cloud/disk_manager/test/acceptance/test_runner/sync_acceptance_test_runner.py
cloud/disk_manager/test/acceptance/test_runner/tests/test.py

We want to run acceptace tests for disk registry based disks. Now acceptance tests have flag that specifies disk type, but we can not run tests for disk registry based based for 2 reasons:
1) We can not create images from dr based disks yet.
2) Names of resources created by tests consist of test type, disk size and disk block size (e.g. acceptance-test-disk-eternal-8tib-4kib-1720126075). These names do not contain disk type. This is crucial for eternal tests, because they reuse disks from previous runs and choose the disk to reuse according to its name.
This pr fixes both problems:
1) Add flag that skip all work with images (so we are going to use this flag test cases with dr based disks).
2) Change name format: add disk type to all names of disks and other resources.
Note: when this pr …

[Disk Manager] acceptance tests: support different types of disks, add flag to skip images

---

cloud/disk_manager/pkg/admin/private.go

не нужно, так как контекст выше содержит IAM для авторизации - так правильнее тут

[Disk Manager] do not need nbs creds in dm admin tool

---

cloud/tasks/runner.go

Когда раннер берёт таск на исполнение, он пишет об этом в лог. Но по сообщению не понятно, идёт ли речь о штатном исполнении или об отмене. Хотя эту информацию обычно можно восстановить из контекста, лучше писать об этом явно.

[Disk Manager] logs: write explicitly either task running or cancelling when starting execution

---

cloud/blockstore/tools/csi_driver/internal/driver/node.go
cloud/blockstore/tools/csi_driver/internal/driver/node_test.go

issue: #1588
CSI driver provides RPC_GET_VOLUME_STATS capability only in podMode when volume is mounted to the pod as a local folder.

issue-1588: Support RPC_GET_VOLUME_STATS capability in csi driver

---

cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_io.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_stats.cpp

Если физическое устройство ломается, то в логи падает много одинаковых ошибок. Достаточно писать ошибки уровня ERROR один раз, при нахождении такого сломанного устройства.

Remove repeated check-health errors when device broken

---

cloud/blockstore/tools/csi_driver/internal/driver/node.go

Otherwise we have ugly error messages like:
```
Failed to publish volume: %!w(*fmt.wrapError=&{failed to start NBS endpoint: ...
```

[CSI driver] error wrapping does not work with fmt.Sprintf

---

cloud/filestore/libs/storage/tablet/actors/tablet_adddata.cpp
cloud/filestore/libs/storage/tablet/actors/tablet_adddata.h
cloud/filestore/libs/storage/tablet/model/block.h
cloud/filestore/libs/storage/tablet/model/fresh_bytes.cpp
cloud/filestore/libs/storage/tablet/model/fresh_bytes.h
cloud/filestore/libs/storage/tablet/model/fresh_bytes_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_addblob.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
cloud/filestore/libs/storage/tablet/tablet_private.h
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
cloud/filestore/libs/storage/tablet/tablet_tx.h
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp
cloud/filestore/libs/storage/testlib/tablet_client.h
cloud/filestore/private/api/protos/tablet.proto

IndexTablet's AddData now accepts a list of unaligned data parts alongside the other data (BlobIds)
ServiceActor will cut off the unaligned head and tail for large unaligned writes, proceed with the usual GenerateBlobIds -> PutUserData -> AddData pipeline, adding those unaligned head and tail parts to the AddData request
The logic in ServiceActor will not be enabled unless a specific flag is set in StorageServiceConfig (we need to deploy all this code first and enable the flag only when we are sure that the IndexTablet part is deployed everywhere)
#1673

issue-1673: Unaligned requests support in ThreeStageWrite pipeline - IndexTablet part

---

cloud/filestore/libs/diagnostics/critical_events.h
cloud/filestore/libs/storage/tablet/model/block.h
cloud/filestore/libs/storage/tablet/tablet_actor_addblob.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp

Followup for https://github.com/ydb-platform/nbs/pull/1740 
#1673

issue-1673: AddData + UnalignedDataParts: using CommitId, generated in AddBlobTx (since the same CommitId is used for the blobs), adding some checks

---

cloud/disk_manager/internal/pkg/facade/private_service_test/private_service_test.go
cloud/disk_manager/internal/pkg/services/disks/delete_disk_task.go
cloud/disk_manager/internal/pkg/services/disks/delete_disk_task_test.go

https://github.com/ydb-platform/nbs/issues/1636
проблема была в том, что были одинаковые IdempotencyKeys у двух разных задач разного типа 
таким образом одна из них забывалась (releaseBaseDisk)
тут есть вопрос к тому что scheduler мог бы проверять, что нет задачи ДРУГОГО типа с ТАКИМ же IdempotencyKey

[Disk Manager] fix delete_disk_task

---

cloud/blockstore/libs/storage/disk_agent/recent_blocks_tracker.cpp
cloud/blockstore/libs/storage/disk_agent/recent_blocks_tracker.h

Продолжение NBS-4000
Чтобы было проще ловить отклоненные сообщения "из прошлого", пишу их в лог на стороне диск-агента.

Log rejected requests from the past on disk-agent side

---

cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.cpp

```
NBS_SERVER[747829]: 2024-08-09T17:38:53.818594Z :BLOCKSTORE_PARTITION ERROR: Unexpected event: (0x10620789) NCloud::NBlockStore::TResponseEvent<NCloud::NBlockStore::NStorage::TEvNonreplPartitionPrivate::TOperationCompleted, 274859913u>
```

fix unexpected event for partition nonrepl rdma actor

---

cloud/blockstore/libs/nvme/nvme.h
cloud/blockstore/libs/nvme/nvme_stub.cpp
cloud/blockstore/libs/nvme/nvme_stub.h
cloud/blockstore/libs/service_local/storage_aio.cpp
cloud/blockstore/libs/service_local/storage_aio_ut.cpp
cloud/blockstore/libs/service_local/storage_aio_ut_large.cpp
cloud/blockstore/libs/storage/disk_agent/testlib/test_env.cpp

* NBSNEBIUS-351: Erase devices using deallocate in 1GB chunks
Deallocating large device chunks (e.g., 93GB) on certain SSD models resulted in
incomplete erasure, leaving ~20 pages uncleared. This commit mitigates the issue
by deallocating in smaller 1GB chunks, ensuring complete device erasure.

NBSNEBIUS-351: Erase devices using deallocate in 1GB chunks (#1717)

---

cloud/filestore/libs/storage/tablet/tablet_ut_data_stress.cpp

see https://github-actions-s3.website.nemax.nebius.cloud/ydb-platform/nbs/Nightly-build-(ubsan)/10370766577/1/nebius-x86-64-ubsan/logs/cloud/filestore/libs/storage/tablet/ut_stress/test-results/unittest/chunk0/testing_out_stuff/TIndexTabletTest_Data_Stress.ShouldTruncateAndAllocateFiles.err

tablet stresstest should have less iterations under ubsan - otherwise we hit the timeout

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_mirrored_disk_migration.cpp

DiskRegistryNoScheduledNotification is triggered on DR's startup for any replica with non empty FinishedMigrations.

[NBS] fix false positive DiskRegistryNoScheduledNotification crit event

---

cloud/blockstore/tools/csi_driver/deploy/manifests/6-csi-daemonset.yaml

Default port 8774 is already in use by csi controller pod

issue-1657: set custom monitoring port in minikube manifest

---

cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/storage/tablet/subsessions.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_cleanupsessions.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_createsession.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_loadstate.cpp
cloud/filestore/libs/storage/tablet/tablet_private.h
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_sessions.cpp
cloud/filestore/libs/storage/tablet/tablet_tx.h
cloud/filestore/libs/storage/testlib/tablet_client.h

There is an object called "session" which corresponds to an active FS endpoint of a single VM - the session object stores that VM's locks and open file descriptors (file handles). A session exists in the leader tablet for each VM that has this FS attached and a session exists for each shard tablet as well. If a tablet restarts, it restores all sessions from persistent storage and launches a 5 minute timer waiting for a heartbeat (TCreateSessionRequest) from the client - if the heartbeat doesn't arrive, the session is deleted. If the leader restarts, each client reestablishes the connection to the leader and sends that heartbeat which causes all sessions - in the leader and in the shards - to be renewed. But if a shard restarts, the session in the shard won't receive a heartbeat until …

issue-1350: restoring follower sessions after follower restarts

---

cloud/blockstore/libs/endpoints/endpoint_manager.cpp
cloud/blockstore/libs/endpoints/service_endpoint_ut.cpp

#1788 
The most obvious solution is to extend `EndpointManager`'s life until `StopEndpoint` coroutine finishes

issue-1788: fix heap-use-after-free in TServiceEndpointTest.ShouldTimeoutFrozenRequest

---

cloud/blockstore/libs/storage/partition/part_actor_readblocks.cpp

Decided to mute those errors because they may easily happen if Blob Storage group write latency is slightly increased and disk has 'reads immediately follow writes' load pattern.
If those errors constitute a performance problem - it can be observed via 'max time' and other latency alerts

[Blockstore] make 'ReadBlocks transaction was interrupted' errors silent

---

cloud/blockstore/libs/client_rdma/rdma_client.cpp
cloud/blockstore/libs/endpoints_rdma/rdma_server.cpp
cloud/blockstore/libs/rdma/iface/protobuf.cpp
cloud/blockstore/libs/rdma/iface/protobuf.h
cloud/blockstore/libs/rdma/iface/protobuf_ut.cpp
cloud/blockstore/libs/rdma_test/client_test.cpp
cloud/blockstore/libs/rdma_test/server_test_async.cpp
cloud/blockstore/libs/service_local/storage_rdma.cpp
cloud/blockstore/libs/storage/disk_agent/rdma_target.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_common.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_checksumblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_writeblocks.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_zeroblocks.cpp
cloud/blockstore/tools/testing/rdma-test/storage_rdma.cpp
cloud/blockstore/tools/testing/rdma-test/target.cpp
cloud/storage/core/libs/common/block_data_ref.h

Убираю замаскированное небезопасное преобразование в виде с-style cast

Making an explicit unsafe conversion from TBlockDataRef to IOutputStream::TPart

---

cloud/filestore/apps/client/lib/command.cpp

Now filestore-client will fail if provided with a valid nfs-config.txt. Fixing error, introduced by #1687

[Filestore] parse `TClientAppConfig`, not `TClientConfig` in filestore-client

---

cloud/filestore/public/sdk/go/client/credentials.go

Make it the same as in blockstore:
https://github.com/ydb-platform/nbs/blob/6bc430c0f113d0815ed730dd40bae40a1d2e52fc/cloud/blockstore/public/sdk/go/client/credentials.go#L23
https://github.com/ydb-platform/nbs/blob/6bc430c0f113d0815ed730dd40bae40a1d2e52fc/cloud/blockstore/public/sdk/go/client/credentials.go#L91

[Filestore] fix incorrect auth header in GO SDK

---

cloud/storage/core/libs/aio/service.cpp
cloud/storage/core/libs/aio/service_ut.cpp

Fixing the following thing which may happen in our CI:
https://github-actions-s3.website.nemax.nebius.cloud/ydb-platform/nbs/Nightly-build/10481521148/1/nebius-x86-64/test_data/actions-runner/_work/nbs/nbs/cloud/blockstore/tests/loadtest/local-mirror/test-results/py3test/chunk4/testing_out_stuff/test.py__test_load[mirror3-resync]/stderr_pz3my8rw
```
VERIFY failed (2024-08-21T03:55:52.806960Z): unable to initialize context: Resource temporarily unavailable
cloud/storage/core/libs/aio/service.cpp:53
TAsyncIOContext(): requirement ret == 0 failed
NPrivate::InternalPanicImpl(int, char const*, char const*, int, int, int, TBasicStringBuf<char, std::__y1::char_traits<char> >, char const*, unsigned long)+663 (0x1044B4F7)
NPrivate::Panic(NPrivate::TStaticBuf const&, int, char const*, char const*, …
```

io_setup may return EAGAIN - it should be retried (for a reasonable time interval)

---

cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp
cloud/blockstore/libs/storage/volume/actors/shadow_disk_actor.cpp
cloud/blockstore/libs/storage/volume/actors/shadow_disk_actor.h

Related to #3
Вношу `TMigrationTimeoutCalculator` внтурь базового класса миграций `TNonreplicatedPartitionMigrationCommonActor`. 
Изменения логики нет.

Calculate migration bandwidth in the base migration class

---

cloud/filestore/libs/storage/service/service_actor_getnodeattr.cpp
cloud/filestore/libs/storage/service/service_actor_listnodes.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.cpp

Fix issues found by coverity:
service_actor_getnodeattr.cpp - use of moved object
service_actor_listnodes.cpp - use of moved object
tablet_actor.cpp - use after move

fix issues found by coverity

---

cloud/filestore/libs/storage/model/ut/ya.make
cloud/filestore/libs/storage/model/utils.h
cloud/filestore/libs/storage/model/utils_ut.cpp
cloud/filestore/libs/storage/model/ya.make
cloud/filestore/libs/storage/service/service_actor_listnodes.cpp
cloud/filestore/libs/storage/service/service_ut.cpp
cloud/filestore/libs/vfs_fuse/fs_impl_list.cpp

In multitablet filestores we first send ListNodesRequest to the leader, then send GetNodeAttr / GetNodeAttrBatch requests to the followers where the files are stored. If an UnlinkNode request happens between these two steps, GetNodeAttr / GetNodeAttrBatch will return ENOENT. Our current code detects this but does nothing and sends empty node attr for such nodes to the layer above it (vfs_fuse) which detects this and responds to the client with E_IO errors. This PR removes such nodes from the ListNodesResponse. NodeNotFoundInFollower is reported only if such nodes are still present in the leader fs (checked via a bunch of GetNodeAttr requests to the leader). E_IO is returned only if the resulting ListNodesResponse is empty and all the nodes are "lost" (not found in the followers and at the …

issue-1350: fixed ListNodes -> UnlinkNode -> GetNodeAttr race which lead to E_IO due to having empty node attrs in the listing results

---

cloud/blockstore/apps/client/lib/factory.cpp
cloud/blockstore/apps/client/lib/resize_device.cpp
cloud/blockstore/apps/client/lib/resize_device.h
cloud/blockstore/apps/client/lib/ya.make
cloud/blockstore/libs/endpoint_proxy/client/client.cpp
cloud/blockstore/libs/endpoint_proxy/client/client.h
cloud/blockstore/libs/endpoint_proxy/client/device_factory.cpp
cloud/blockstore/libs/endpoint_proxy/client/device_factory_ut.cpp
cloud/blockstore/libs/endpoint_proxy/server/server.cpp
cloud/blockstore/libs/endpoints/endpoint_manager.cpp
cloud/blockstore/libs/endpoints/endpoint_manager_ut.cpp
cloud/blockstore/libs/nbd/device.cpp
cloud/blockstore/libs/nbd/device.h
cloud/blockstore/libs/nbd/netlink_device.cpp
cloud/blockstore/libs/service/auth_scheme.cpp
cloud/blockstore/libs/service/request.h
cloud/blockstore/libs/service/request_helpers.h
cloud/blockstore/public/api/grpc/endpoint_proxy.proto
cloud/blockstore/public/api/grpc/service.proto
cloud/blockstore/public/api/protos/endpoints.proto
cloud/blockstore/tests/csi_driver/test.py
cloud/blockstore/tests/e2e-tests/test.py
cloud/blockstore/tests/e2e-tests/ya.make
cloud/blockstore/tests/python/lib/endpoint_proxy.py
cloud/blockstore/tests/python/lib/loadtest_env.py
cloud/blockstore/tests/python/lib/ya.make
cloud/blockstore/tests/ya.make
cloud/blockstore/tools/http_proxy/main_test.go
cloud/blockstore/tools/testing/chaos-monkey/monkey_test.go

issue: #1657
ResizeDevice command allows to resize mounted filesystem without restarting endpoint.
```
blockstore-client resizevolume --disk-id test-volume-12 --blocks-count 524288
blockstore-client resizedevice --sock /tmp/nbd12.sock --device-size 2147483648
resize2fs /dev/nbd12
```

issue-1657: resize nbd device

---

cloud/filestore/libs/storage/tablet/tablet_actor_addblob.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_allocatedata.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_createcheckpoint.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_createhandle.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_createnode.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_deletecheckpoint.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_destroyhandle.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_destroysession.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_removenodexattr.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_renamenode.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_setnodeattr.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_setnodexattr.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_truncate.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_unlinknode.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_writebatch.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_writedata.cpp
cloud/filestore/libs/storage/tablet/tablet_database.cpp
cloud/filestore/libs/storage/tablet/tablet_database.h
cloud/filestore/libs/storage/tablet/tablet_state_cache.h
cloud/filestore/libs/storage/tablet/tablet_tx.h

No actual changes, just some preliminary refactoring. Add the proxy, mentioned in this comment: https://github.com/ydb-platform/nbs/pull/1478#issue-2366706946
All transactions that can modity index tables are provided with args.IndexStateRequests, a place to store all modifying requests made in this transaction
References #1146

issue-1146: add dummy tablet database proxy + populate oplog in RW transactions

---

cloud/blockstore/apps/client/lib/command.cpp
cloud/blockstore/libs/client/bench/main.cpp
cloud/blockstore/libs/daemon/common/bootstrap.cpp
cloud/blockstore/libs/disk_agent/bootstrap.cpp
cloud/blockstore/libs/endpoint_proxy/server/bootstrap.cpp
cloud/blockstore/libs/logbroker/topic_api_impl/topic_api_ut.cpp
cloud/blockstore/libs/nbd/bench/bootstrap.cpp
cloud/blockstore/tests/fuzzing/common/starter.cpp
cloud/blockstore/tools/nbd/bootstrap.cpp
cloud/blockstore/tools/testing/eternal_tests/checkpoint-validator/bin/main.cpp
cloud/blockstore/tools/testing/eternal_tests/checkpoint-validator/lib/validator_ut.cpp
cloud/blockstore/tools/testing/eternal_tests/eternal-load/bin/test.cpp
cloud/blockstore/tools/testing/loadtest/lib/bootstrap.cpp
cloud/filestore/apps/client/lib/command.cpp
cloud/filestore/libs/daemon/common/bootstrap.cpp
cloud/filestore/tools/testing/loadtest/bin/bootstrap.cpp
cloud/storage/core/tools/analytics/cpu-wait-monitor/main.cpp
cloud/vm/blockstore/bootstrap.cpp

Сейчас в логах формат времени может отличаться:
2024-08-28-14-10-22:BLOCKSTORE_SERVER INFO: cloud/blockstore/libs/daemon/common/bootstrap.cpp:855: Started Monitoring
2024-08-28T07:10:22.059462Z:BLOCKSTORE_DISK_REGISTRY_PROXY INFO: Tablet client: 72075186224037888 (remote: [50000:7408084243596560056:8189])
В первом случае, когда время выглядит как «2024-08-28-14-10-22», это записано через BootstrapLogging https://github.com/ydb-platform/nbs/blob/main/cloud/blockstore/libs/daemon/common/bootstrap.cpp#L207
Во втором случае строки были записаны через логгер, созданный из Logging и выглядят как "2024-08-28T07:10:22.059462Z"
https://github.com/ydb-platform/nbs/blob/main/cloud/blockstore/libs/daemon/common/bootstrap.cpp#L709
Несмотря на то, что оба раза было выставлено UseLocalTimestamps = …

Make the date-time format consistent in logs

---

cloud/blockstore/libs/nbd/netlink_device.cpp
cloud/blockstore/tests/python/lib/endpoint_proxy.py

issue: #1657
1. fix proxy argument "--netlink" in e2e test
2. StartResult future doesn't contain any value as it was moved, so we need to remove this check and fail in message.Send

issue-1657: fix resize for netlink device

---

cloud/blockstore/libs/rdma/impl/client.cpp
cloud/blockstore/libs/rdma/impl/client_ut.cpp
cloud/blockstore/libs/rdma/impl/server.cpp
cloud/blockstore/libs/rdma/impl/test_verbs.cpp
cloud/blockstore/libs/rdma/impl/verbs.cpp
cloud/blockstore/libs/rdma/impl/verbs.h

* add more debug points to differentiate between states
* move non-essential messages to debug
* use RDMA_ logging macros in server
* resolve client's hostname
* clean up resources in destructor if endpoint wasn't stopped

improve rdma logging & clean up resources in destructor; issue-1020

---

cloud/blockstore/tests/e2e-tests/test.py

blockstore client asks to type the disk name as a confirmation to remove it.

issue-1657: confirm "destroy volume" in e2e test

---

contrib/restricted/libnl/ChangeLog.patch
contrib/restricted/libnl/lib/socket.c

```
/actions-runner/_work/nbs/nbs/contrib/restricted/libnl/lib/socket.c:114:19: runtime error: left shift of 545 by 22 places cannot be represented in type 'int'
warning: address range table at offset 0xf0 has a premature terminator entry at offset 0x100
warning: address range table at offset 0x6a0 has a premature terminator entry at offset 0x6b0
warning: address range table at offset 0x6d0 has a premature terminator entry at offset 0x6e0
#0 0x4a52963 in generate_local_port /actions-runner/_work/nbs/nbs/contrib/restricted/libnl/lib/socket.c:114:19
#1 0x4a52326 in _nl_socket_set_local_port_no_release /actions-runner/_work/nbs/nbs/contrib/restricted/libnl/lib/socket.c:346:10
#2 0x4a774fc in nl_connect …
```

libnl: fixed ub

---

cloud/disk_manager/internal/pkg/facade/interceptor.go
cloud/tasks/headers/headers.go
cloud/tasks/headers/headers_test.go
cloud/tasks/headers/tests/ya.make
cloud/tasks/headers/ya.make
cloud/tasks/runner.go
cloud/tasks/scheduler_impl.go
cloud/tasks/tracing/attributes.go
cloud/tasks/tracing/tracing_context.go
cloud/tasks/tracing/ya.make

https://github.com/ydb-platform/nbs/issues/1199
Traces will look like this (example for creating disk from snapshot):
```
<external span from grpc metadata>
CreateDisk
disks.CreateDiskFromSnapshot (gen 1)
disks.CreateDiskFromSnapshot (gen 2)
dataplane.TransferFromSnpashotToDisk (gen 1)
dataplane.TransferFromSnpashotToDisk (gen 2)
disks.CreateDiskFromSnapshot (gen 3)
```
Also, regular tasks will have their spans in separate traces.
For each task generation we start a new span. The disadvantage of this approach is huge amount of span if the task has many generations. Sampling can help here. I'm going to add sampling in next pull requests.

[Disk Manager] Tracing: Add spans for tasks

---

cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.cpp

Relates to #1303
```
NPrivate::InternalPanicImpl(int, char const*, char const*, int, int, int, TBasicStringBuf<char, std::__y1::char_traits<char> >, char const*, unsigned long)+663 (0x104974F7)
NPrivate::Panic(NPrivate::TStaticBuf const&, int, char const*, char const*, char const*, ...)+284 (0x1048D78C)
NCloud::HandleUnexpectedEvent(TAutoPtr<NActors::IEventHandle, TDelete>&, int)+158 (0x20893AAE)
2024-09-02T16:48:26.465900Z :BLOCKSTORE_PARTITION DEBUG: [vol0] Range [8192..9215] migrated
2024-09-02T16:48:26.465930Z :BLOCKSTORE_PARTITION DEBUG: [vol0] Schedule migrating next range after "0.150000s"
NCloud::NBlockStore::NStorage::TNonreplicatedPartitionMigrationCommonActor::StateZombie(TAutoPtr<NActors::IEventHandle, TDelete>&)+573 (0x208E3A7D) …
```

[Blockstore] ignore TEvRegisterTrafficSourceResponse in StateZombie

---

library/cpp/monlib/encode/prometheus/prometheus_encoder.cpp
library/cpp/monlib/encode/prometheus/prometheus_encoder_ut.cpp

- Don't erase first numerical character in sensor name in prometheus format (#1094)
- Removed assert on metrics without sensor label (prometheus format) (#1102)

Reapply monlib bugfixes (lost while merging ydb-24-1)

---

cloud/blockstore/libs/endpoint_proxy/server/server.cpp
cloud/blockstore/libs/endpoint_proxy/server/server_ut.cpp
cloud/blockstore/libs/endpoint_proxy/server/ut/ya.make
cloud/blockstore/libs/nbd/device.cpp

1. return error if nbd device failed to start
2. cleanup server state after "nbd device start" failure
3. log ioctl device errors

issue-1657: handle "start nbd device" error

---

cloud/disk_manager/internal/pkg/dataplane/create_snapshot_from_disk_task.go
cloud/disk_manager/internal/pkg/dataplane/create_snapshot_from_legacy_snapshot_task.go
cloud/disk_manager/internal/pkg/dataplane/create_snapshot_from_snapshot_task.go
cloud/disk_manager/internal/pkg/dataplane/create_snapshot_from_url_task.go
cloud/disk_manager/internal/pkg/dataplane/replicate_disk_task.go
cloud/disk_manager/internal/pkg/dataplane/transfer_from_disk_to_disk_task.go
cloud/disk_manager/internal/pkg/dataplane/transfer_from_snapshot_to_disk_task.go

There is a very unlikely (but possible) scenario which results in the task state having `t.state.Progress == 1` and `t.state.MilestoneChunkIndex != t.state.ChunkCount` which may cause a live lock in nemesis tests with the task being restarted but not making progress.
Example:
https://github-actions-s3.website.nemax.nebius.cloud/ydb-platform/nbs/Nightly-build/10674745634/1/nebius-x86-64/test_data/actions-runner/_work/nbs/nbs/cloud/disk_manager/internal/pkg/facade/image_service_nemesis_test/test-results/image_service_nemesis_test/chunk2/testing_out_stuff/
`cloud/disk_manager/internal/pkg/facade/image_service_nemesis_test/image_service_nemesis_test.TestImageServiceCreateRawImageFromURL`
Unfortunately, this hypothesis cannot be proven due to the lack of logs

[Snapshot] get rid of non-valuable but possibly buggy optimization which saves 1 task update when dataplane task is almost finished; better logging

---

cloud/blockstore/libs/nbd/netlink_device.cpp

- fix context leak when nl_socket_modify_cb fails
- use clojure instead of a static method as a socket callback
- move TNetlinkDevice methods outside of the class definition to reduce nesting
- use nl_send_auto + nl_wait_for_ack instead of nl_send_sync to differentiate between send and recv errors

nbd netlink refactoring

---

cloud/filestore/apps/client/lib/resize.cpp
cloud/filestore/libs/storage/service/service_actor_getnodeattr.cpp
cloud/filestore/tests/client/canondata/result.json
cloud/filestore/tests/client/canondata/test.test_resize/results.txt
cloud/filestore/tests/client/test.py
cloud/filestore/tests/python/lib/client.py

541968c8db244fe903dd398d9d70b66019c27786
f30724825fd2324eeab68e1ba5dacd767c62c8a8

[Filestore] merge-to-stable: allowing FS size decrease with a Force flag, Fix incorrect format string in service_actor_getnodeattr.cpp

---

cloud/blockstore/libs/storage/volume/volume_actor.cpp
cloud/blockstore/libs/storage/volume/volume_actor.h
cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
cloud/blockstore/libs/storage/volume/volume_actor_forward.cpp

Сейчас не все запросы отслеживаются вольюмом и соответсвенно не могут быть отменены.
Если запрос начали обрабатывать с трекингом блоков, то не запоминаем его в хэшмапе VolumeRequests
https://github.com/ydb-platform/nbs/blob/main/cloud/blockstore/libs/storage/volume/volume_actor_forward.cpp#L262
В этом ПРе делается подготовка к исправлению ошибки.

Refactor TVolumeRequest

---

cloud/blockstore/libs/endpoint_proxy/server/server.cpp

grpc::AddInsecureChannelFromFd takes ownership of closing socket. We need to duplicate socket to avoid calling close twice.

issue-1657: duplicate socket

---

cloud/blockstore/libs/storage/core/forward_helpers.h
cloud/blockstore/libs/storage/core/proto_helpers.cpp
cloud/blockstore/libs/storage/core/proto_helpers.h
cloud/blockstore/libs/storage/volume/partition_requests.h
cloud/blockstore/libs/storage/volume/volume_actor.h
cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
cloud/blockstore/libs/storage/volume/volume_actor_forward.cpp

1. отделяю обработку сообщений про чекпоинты в отдельный шаблонный метод. 
2. добавляю новых перегрузок для BuildRequestBlockRange
3. убираю дефолтную реализацию шаблона ToPartitionRequests.
4. переименовываю HandleRequest в HandleMultipartitionVolumeRequest, так как он зовется только для мультипартиционных вольюмов

Refactor volume request handling

---

cloud/blockstore/libs/storage/volume/multi_partition_requests.cpp
cloud/blockstore/libs/storage/volume/multi_partition_requests.h
cloud/blockstore/libs/storage/volume/partition_requests.cpp
cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
cloud/blockstore/libs/storage/volume/volume_actor_forward.cpp
cloud/blockstore/libs/storage/volume/ya.make

Оказалось что TPartitionRequestActor рассылает сообщения в несколько партишенов.
1. Переименовал его за это
2. Унес в cpp часть кода

Rename  TPartitionRequestActor -> TMultiPartitionRequestActor

---

cloud/filestore/libs/storage/tablet/tablet_actor.cpp
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_monitoring.cpp
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp

Adding information about backpressure state to the monpage for better observability:
---
---

[Filestore] add information about backpressure to the monpage

---

cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_stats.cpp

Если запрос отклоняется на стороне диска агента с этими ошибками, это уводит девайс в состоянии IO_ERROR.
Сделал чтобы некоторые типы ошибок не помечали девайс как сломанный.

Don't mark devices as broken on non io-related errors

---

cloud/blockstore/libs/endpoints/endpoint_manager.cpp
cloud/blockstore/tests/e2e-tests/test.py
cloud/blockstore/tools/csi_driver/internal/driver/node.go

issue: #1657
Discussion: https://github.com/ydb-platform/nbs/pull/1748#discussion_r1743430963
RefreshEndpoint was introduced to notify endpoints about new size of the volume: https://github.com/ydb-platform/nbs/blob/main/cloud/blockstore/libs/endpoints_vhost/vhost_server.cpp#L66
We can use it to resize nbd device instead of separate ResizeDevice method.
ResizeDevice will be removed in another PR.

issue-1657: resize device in "refresh endpoint" handler

---

cloud/blockstore/libs/service/device_handler.cpp
cloud/blockstore/libs/service/device_handler.h
cloud/blockstore/libs/service/device_handler_ut.cpp
cloud/blockstore/libs/vhost/server.cpp

Первая часть https://github.com/ydb-platform/nbs/issues/2000
Здесь делается разбиение запроса в обработчике TAlignedDeviceHandler.
Для Zero запросов уже было, сделано, я добавил для Read и Write

Split huge read and write requests in TAlignedDeviceHandler

---

cloud/blockstore/libs/endpoints_vhost/external_vhost_server.cpp

Откатываю обратно на TCondVar, т.к. здесь https://github.com/ydb-platform/nbs/blob/6edba2c/cloud/blockstore/libs/endpoints_vhost/external_vhost_server.cpp#L620 стреляет verify
https://github.com/ydb-platform/nbs/blob/6edba2c/library/cpp/coroutine/engine/impl.cpp#L375
```cpp
Thread 13241 (LWP 2698928):
#0 __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1 pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#2 google_breakpad::ExceptionHandler::SignalHandler (sig=11, info=0x7f0e5f5f8b30, uc=0x7f0e5f5f8a00) at src/client/linux/handler/exception_handler.cc +342
#3 <signal handler called>
#4 TRbGlobal<bool>::RebalanceForErase (z=0x574a5d9a8db0, root=<error reading variable>, leftmost=<error reading variable>, rightmost=<error reading variable>) at …
```

Switch coroutine wait to CondVar

---

cloud/blockstore/libs/storage/volume/volume_actor_forward.cpp
cloud/blockstore/libs/storage/volume/volume_ut.cpp

При реализации https://github.com/ydb-platform/nbs/pull/1475
был сделан баг, что запрос сохранялся в кэше для отслеживания повторных запросов, но не удалялся оттуда.
Перенес отклонение запроса выше, до его помещения в кэш DuplicateWriteAndZeroRequests

Fix invalid range request duplicates cache poisoning

---

cloud/filestore/libs/storage/tablet/tablet_actor_flush_bytes.cpp
cloud/filestore/libs/storage/tablet/tablet_private.h
cloud/filestore/libs/storage/tablet/tablet_tx.h
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp

References (and, hopefully, fixes) #652
The main problem is that FlushBytes acquires collect barrier, which is less than the last collect commit id:
---
1. Consider that there were the following sequence of writes:
```
Write(0,       256 KiB, 'a') -> Blob(commitId = 42)
Write(256 KiB, 256 KiB, 'b') -> Blob(commitId = 43)
Write(512 KiB, 1,       'f') -> FreshBytes(commitId = 44)
Write(0,       256 KiB, 'c') -> Blob(commitId = 45)
```
This will lead to the following file layout: `[ccccccc][bbbbbbb][f]`
2. After execution of the CollectGarbage, all three new blobs will get a KeepFlag and the last collect commit id will be equal to 44
```
CommitId:     41      42        43       44
Blob(a) Blob(b) FreshBytes Blob(c)
|
LastCollectCommitId
```
3. After execution of the Cleanup operation, the …

issue-652: do not acquire barriers from the past upon `FlushBytes`

---

cloud/blockstore/tests/external_endpoint/multiple_endpoints.py

Тест падает, т.к. 30 процессов не могут стартовать. На 27-28 процессе не хватает IO:
```
2024-09-16T02:06:50.608236Z :BLOCKSTORE_EXTERNAL_ENDPOINT ERROR: cloud/blockstore/libs/endpoints_vhost/external_vhost_server.cpp:505: [/home/github/.ya/build/build_root/92ii/0029f8/r3tmp/tmpu1hii7w7-id] bad json: VERIFY failed (2024-09-16T02:06:50.605952Z): io_setup
2024-09-16T02:06:50.608301Z :BLOCKSTORE_EXTERNAL_ENDPOINT ERROR: cloud/blockstore/libs/endpoints_vhost/external_vhost_server.cpp:505: [/home/github/.ya/build/build_root/92ii/0029f8/r3tmp/tmpu1hii7w7-id] bad json:   cloud/blockstore/vhost-server/backend_aio.cpp:179
2024-09-16T02:06:50.608307Z :BLOCKSTORE_EXTERNAL_ENDPOINT ERROR: cloud/blockstore/libs/endpoints_vhost/external_vhost_server.cpp:505: …
```

Fix local disks test

---

cloud/blockstore/libs/daemon/ydb/bootstrap.cpp
cloud/blockstore/tests/loadtest/local-emergency/test.py
cloud/blockstore/tests/python/lib/loadtest_env.py

issue-757: don't load configs from CMS in emergency mode

---

cloud/blockstore/apps/disk_agent/ya.make
cloud/blockstore/config/disk.proto
cloud/blockstore/libs/disk_agent/bootstrap.cpp
cloud/blockstore/libs/disk_agent/bootstrap.h
cloud/blockstore/libs/storage/disk_agent/model/config.cpp
cloud/blockstore/libs/storage/disk_agent/model/config.h
cloud/blockstore/libs/storage/disk_agent/model/device_scanner.cpp
cloud/blockstore/libs/storage/disk_agent/model/device_scanner.h
cloud/blockstore/libs/storage/disk_agent/storage_initializer.cpp
cloud/blockstore/tests/disk_agent_config/test.py
cloud/blockstore/tests/python/lib/daemon.py

Если на старте процесса выставлен флаг о возможном выключении регистрации в NodeBroker, то диск агент может стартануть в режиме пустышки:
1) Если он выключен в конфиге
2) Если нет девайсов ни в кеше, ни в конфиге в файле, ни в файловой системе с помощью дискавери.
Тут важный момент, что девайсы внутри CMS мы проигнорируем. Но кажется нас он уже не очень интересует.

Ability to disable node broker registration in the DA

---

cloud/blockstore/libs/daemon/ydb/config_initializer.cpp
cloud/blockstore/libs/daemon/ydb/config_initializer.h
cloud/blockstore/libs/disk_agent/config_initializer.cpp
cloud/blockstore/libs/disk_agent/config_initializer.h
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h

Пока что вынес код AdaptNodeRegistrationParams чтобы убрать копипасту . Изначальная задумка была вообще унести bootstrap код диск-агента в libs/daemon, но посмотрев на то что лежит там, я уже не уверен что это стоит вообще делать. В libs/daemon все же лежит код который так или иначе относится к различным вариантам nbsd, а disk-agent это все-таки немного другое и если его переновить туда же то рефакторить придется довольно много

issue-1946: remove duplicated code

---

cloud/filestore/apps/client/lib/ls.cpp
cloud/filestore/apps/client/lib/text_table.cpp
cloud/filestore/apps/client/lib/text_table.h
cloud/filestore/tests/client/canondata/result.json
cloud/filestore/tests/client/canondata/test.test_ls/results.txt
cloud/filestore/tests/client/canondata/test.test_write_ls_rm_ls/results.txt
cloud/filestore/tests/client/test.py

```
:~# filestore-client ls --filesystem nfs_eternal_4KiB_fio --path /
filestore-client "ls --filesystem nfs_eternal_4KiB_fio --path /" failed: (yexception) cloud/filestore/apps/client/lib/text_table.cpp:86: Failed to add row: column's size is not matching row's size
```

[Filestore] fix ls command in client without `--json` flag

---

cloud/storage/core/tools/testing/unstable-process/__main__.py

Sometimes our tests fail because they attempt to start daemons on occupied ports. Happens especially often for nemesis tests due to daemon restarts - some other process may capture a port between the restarts. Adding more logging to detect the offending processes.

unstable-process: logging open sockets upon process start failure

---

cloud/blockstore/libs/endpoints_vhost/external_vhost_server.cpp

Поймали вот такое зависание:
```
#0  0x00007f89aaa0e95d in syscall () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x000056004318b534 in AbslInternalSpinLockDelay_lts_20240116 (w=0x56005977c9c8 <tcmalloc::tcmalloc_internal::Static::transfer_cache_+1608>, value=9)
#2  0x000056004318b167 in absl::lts_20240116::base_internal::SpinLockDelay (w=0x9, value=128, loop=1, scheduling_mode=(unknown: 2246275520)) 
#3  absl::lts_20240116::base_internal::SpinLock::SlowLock (this=0x9) 
#4  0x0000560058b17e4a in absl::lts_20240116::base_internal::SpinLock::Lock (this=0x56005977c9c8 <tcmalloc::tcmalloc_internal::Static::transfer_cache_+1608>)
#5  absl::lts_20240116::base_internal::SpinLockHolder::SpinLockHolder (this=0x7f8985e36038, l=0x56005977c9c8 <tcmalloc::tcmalloc_internal::Static::transfer_cache_+1608>) …
```

Fix blockstore-vhost-server deadlock before execvp call

---

cloud/blockstore/libs/disk_agent/bootstrap.cpp
cloud/blockstore/libs/disk_agent/bootstrap.h
cloud/blockstore/libs/disk_agent/ya.make
cloud/blockstore/tests/disk_agent_config/test.py
cloud/blockstore/tests/python/lib/daemon.py
cloud/storage/core/libs/http/simple_http_server.cpp
cloud/storage/core/libs/http/simple_http_server.h
cloud/storage/core/libs/http/ya.make
cloud/storage/core/libs/ya.make

Чтобы мониторинг не удивлялся что диск агент не отвечает на пинги в monport, я прикрутил простой http сервер

Respond to HTTP requests while being in the deep idle state

---

cloud/blockstore/libs/daemon/ydb/bootstrap.cpp
cloud/blockstore/libs/storage/service/volume_session_actor_start.cpp
cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
cloud/blockstore/tests/loadtest/local-emergency/test.py
cloud/blockstore/tests/python/lib/loadtest_env.py
cloud/blockstore/tests/python/lib/nbs_runner.py
cloud/storage/core/libs/hive_proxy/hive_proxy_fallback_actor.cpp
cloud/storage/core/libs/hive_proxy/hive_proxy_ut.cpp
cloud/storage/core/libs/kikimr/node.cpp
ydb/tests/library/harness/kikimr_runner.py

* silence 'E_NOT_IMPLEMENTED Disk registry based disks can not handle GetChangedBlocks requests' error (#1972)
* issue-757: refactor local-emergency load-test making it actually turn on emergency mode; increment suggested generation upon external boot in fallback mode; minor tweaks (#2019)
* issue-757: don't load configs from CMS in emergency mode (#2042)
* issue-757: pass path as empty TMaybe<TString> instead of empty TString when registering node in Node Broker; spoil BS Controller config before restarting Kikimr after formatting static pdisks in local-emergency test (otherwise BS Controller would erase all the data from other non-static groups) (#2049)
#757

Merge to stable-23-3: making blockstore cluster survive after destruction of static BS group in local-emergency test

---

cloud/blockstore/libs/endpoints_vhost/external_vhost_server.cpp
cloud/blockstore/tests/external_endpoint/multiple_endpoints.py
cloud/blockstore/tests/python/lib/config.py
cloud/blockstore/vhost-server/main.cpp

Сильно упросил старт процесса и почнил корень зла - вызов SetValue() внутри потока, который обслуживает `blockstore-vhost-server`.
Таким образом у нас теперь всё работает на одном корутиновом потоке.

Simlify the vhost server spawn

---

cloud/blockstore/tools/csi_driver/internal/driver/node.go

Skip performance profile argument to automatically recalculate bw/iops quotes for resized volume

issue-1657: Skip perf profile to automatically recalculate quotes for resized volume

---

cloud/blockstore/libs/storage/partition_common/actor_read_blob.cpp
cloud/blockstore/tests/loadtest/local-emergency/test.py
ydb/tests/library/harness/kikimr_runner.py

* [Blockstore] partition/common/actor_read_blob.h should not include partition/part_events_private.h (#926)
* issue-757: move spoil_bs_controller_config and format_static_pdisks methods out from contrib/ydb (#2072)
#757

Merge to stable-23-3: issue-757: move spoil_bs_controller_config and format_static_pdisks methods out from contrib/ydb (#2072)

---

cloud/blockstore/tests/loadtest/local-emergency/test.py

issue-757: should not unmount volume (in local-emergency test) before static BS group destruction in order to make emergency unexpected

---

cloud/filestore/libs/vfs_fuse/file_ring_buffer.cpp

TEntryHeader is not aligned to a 4-byte boundary
without the packed attribute it may cause bus errors on ARM
#1541

issue-1541: fixed ubsan

---

cloud/blockstore/tests/python/lib/loadtest_env.py

Do not ask for password in sudo. If user does not have NOPASSWD for sudo, just fail.

[NBS]: Fix some tests local teardown hangs

---

cloud/blockstore/libs/encryption/encryption_client.cpp
cloud/blockstore/libs/encryption/encryption_client_ut.cpp

Зашифрованный диск нужно монтировать без указания ключа шифрования чтобы снять с него снимок, или наоборот налить из зашифрованного снимка шифрованный же диск.

Mount a volume encrypted with ENCRYPTION_AES_XTS without encryption

---

cloud/blockstore/libs/storage/ss_proxy/ss_proxy_actor.cpp
cloud/blockstore/libs/storage/ss_proxy/ss_proxy_actor_modifyscheme.cpp
cloud/blockstore/libs/storage/ss_proxy/ss_proxy_ut.cpp

To unlock the possibility of unification of the common part of these two implementations. 
Finally, we are going to move the common part to `cloud/storage` and add `PathDescriptionBackup` implementation on top of it - in order to re-use that for Filestore disaster recovery feature
#2100

issue-2100: make blockstore SS proxy error handling consistent with filestore SS proxy

---

cloud/filestore/libs/storage/tablet/tablet_actor_cleanup.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_collectgarbage.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_flush.cpp

issue-1285: fix missing `StartedTs` initialization for requestInfo in `Flush`, `CollectGarbage` and `Cleanup`

---

cloud/blockstore/libs/storage/ss_proxy/ss_proxy_actor.cpp
cloud/filestore/libs/storage/ss_proxy/ss_proxy_actor_modifyscheme.cpp

Follow-up for work started at #2101.
There are three possible error messages:
* `Wrong version in VolumeConfig` (blockstore)
* `Wrong version in Assign Volume` (blockstore)
* `Wrong version in config` (filestore)
We may use just `Wrong version in` in order to unify all of these messages.
#2100

issue-2100: make GetErrorFromPreconditionFailed function (of blockstore SS proxy) look the same as the corresponding function of filestore SS proxy

---

cloud/blockstore/libs/service_local/file_io_service_provider.cpp
cloud/blockstore/libs/service_local/file_io_service_provider.h
cloud/blockstore/libs/service_local/file_io_service_provider_ut.cpp
cloud/blockstore/libs/service_local/public.h
cloud/blockstore/libs/service_local/ut/ya.make
cloud/blockstore/libs/service_local/ya.make

issue-2086: introduce IFileIOServiceProvider

---

cloud/blockstore/config/server.proto
cloud/blockstore/libs/service_local/service_local.cpp
cloud/blockstore/tools/csi_driver/deploy/example/pvc-fs.yaml
cloud/blockstore/tools/csi_driver/deploy/manifests/4-storageclass.yaml
cloud/blockstore/tools/csi_driver/deploy/manifests/5-csi-deployment.yaml

issue: #1657
Support pvc resize with minikube/nbsd-lightweight
1. Update minikube manifests:
- Add csi-resizer sidecar to csi controller
- Allow to expand volume
- Increase pvc storage limit as it is not possible to expand volume beyond the limit
2. Fix volume resize in nbsd-lightweight. Old blocks count value was cached in several places: mounted volume, storage and storage adapter. Fixed by recreating storage/storage adapter.

issue-1657: resize pvc with nbsd-lightweight and minikube

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_get_agent_node_id.cpp
cloud/blockstore/libs/storage/protos/disk.proto
cloud/blockstore/libs/storage/service/service_actor_actions_get_disk_agent_node_id.cpp
cloud/blockstore/tests/client/test_with_multiple_agents.py

#2139
Добавил информации немного в ручку чтобы проще было синхронизировать blue-green для диск агента

Add agent state to DA node id response

---

cloud/blockstore/config/disk.proto
cloud/blockstore/libs/daemon/common/bootstrap.cpp
cloud/blockstore/libs/daemon/common/bootstrap.h
cloud/blockstore/libs/daemon/ydb/bootstrap.cpp
cloud/blockstore/libs/disk_agent/bootstrap.cpp
cloud/blockstore/libs/disk_agent/bootstrap.h
cloud/blockstore/libs/service_local/file_io_service_provider.cpp
cloud/blockstore/libs/service_local/file_io_service_provider.h
cloud/blockstore/libs/service_local/file_io_service_provider_ut.cpp
cloud/blockstore/libs/service_local/storage_aio.cpp
cloud/blockstore/libs/service_local/storage_aio.h
cloud/blockstore/libs/service_local/storage_aio_ut.cpp
cloud/blockstore/libs/service_local/storage_aio_ut_large.cpp
cloud/blockstore/libs/storage/disk_agent/model/config.cpp
cloud/blockstore/libs/storage/disk_agent/model/config.h
cloud/blockstore/libs/storage/disk_agent/testlib/test_env.cpp
cloud/blockstore/libs/storage/init/server/actorsystem.h
cloud/blockstore/tests/python/lib/config.py
cloud/blockstore/tests/python/lib/nonreplicated_setup.py

issue-2086: use multiple aio services

---

cloud/blockstore/tools/csi_driver/internal/driver/node.go

Kubernetes can trigger NodeGetVolumeStats each minute and it causes a lot of spam in our logs.

fix: remove NodeGetVolumeStats entry log

---

cloud/disk_manager/test/acceptance/test_runner/lib/helpers.py
cloud/disk_manager/test/acceptance/test_runner/lib/instance_policy.py

1. disable disk auto-detach to debug test after failure
2.  use wait_for_block_device_to_appear implementation from helpers

fix: acceptance test failure

---

cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_writeblocks.cpp

Сейчас типы TEvWriteBlocksLocalResponse и TEvWriteBlocksResponse совпадают, но не стоит их путать.

Fix wrong response type usage

---

cloud/filestore/config/storage.proto
cloud/filestore/libs/diagnostics/critical_events.h
cloud/filestore/libs/storage/core/config.cpp
cloud/filestore/libs/storage/core/config.h
cloud/filestore/libs/storage/tablet/tablet_actor.h
cloud/filestore/libs/storage/tablet/tablet_actor_allocatedata.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_createhandle.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_destroyhandle.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_destroysession.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_loadstate.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_renamenode.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_resetsession.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_setnodeattr.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_truncate.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_unlinknode.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_zerorange.cpp
cloud/filestore/libs/storage/tablet/tablet_database.cpp
cloud/filestore/libs/storage/tablet/tablet_database.h
cloud/filestore/libs/storage/tablet/tablet_database_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_schema.h
cloud/filestore/libs/storage/tablet/tablet_state.cpp
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
cloud/filestore/libs/storage/tablet/tablet_state_impl.h
cloud/filestore/libs/storage/tablet/tablet_state_nodes.cpp
cloud/filestore/libs/storage/tablet/tablet_tx.h
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp

Backpressure is enabled if LargeDeletionMarkerCount >= LargeDeletionMarkersThresholdForBackpressure.
The operations that directly generate LargeDeletionMarkers will be rejected:
* UnlinkNode
* Truncate
* SetNodeAttr
* ZeroRange
* AllocateData
* CreateHandle
The operations that may delete a node as a side effect will generate OrphanNodes and raise an AppCriticalEvent:
* DestroySession
* DestroyHandle
* RenameNode
* ResetSession
#1795

issue-1795: backpressure for LargeDeletionMarkers

---

cloud/tasks/runner_test.go

https://github-actions-s3.website.nemax.nebius.cloud/ydb-platform/nbs/PR-check/11012514227/1/nebius-x86-64/logs/cloud/tasks/tests/test-results/tests/testing_out_stuff/stderr
```
Difference found in argument 0:
--- Expected
+++ Actual
@@ -1,2 +1,2 @@
-(*tasks.executionContext)(*tasks.executionContext<0xc00086a000>)
+(*tasks.executionContext)(*tasks.executionContext<0xc00086a200>)
Diff: 0: FAIL:  (*tasks.executionContext=*tasks.executionContext<0xc00086a200>) != (*tasks.executionContext=*tasks.executionContext<0xc00086a000>) [recovered]
```

[Tasks] fix cloud/tasks/tests/tests.TestTryExecutingTask

---

cloud/filestore/libs/storage/api/tablet.h
cloud/filestore/libs/storage/service/service_actor.h
cloud/filestore/libs/storage/service/service_actor_actions.cpp
cloud/filestore/libs/storage/service/service_actor_actions_unsafe_node_ops.cpp
cloud/filestore/libs/storage/service/service_actor_actions_ut.cpp
cloud/filestore/libs/storage/service/ya.make
cloud/filestore/libs/storage/tablet/helpers.cpp
cloud/filestore/libs/storage/tablet/helpers.h
cloud/filestore/libs/storage/tablet/tablet_actor_unsafe_node_ops.cpp
cloud/filestore/libs/storage/tablet/tablet_tx.h
cloud/filestore/libs/storage/tablet/ya.make
cloud/filestore/private/api/protos/tablet.proto

issue-1795: implemented Unsafe{Delete,Update,Get}Node to use it in private api for manual interventions - e.g. to clean up OrphanNodes

---

cloud/storage/core/tests/recipes/access-service-new/__main__.py
cloud/storage/core/tools/testing/access_service_new/mock/main.go

> $S/cloud/storage/core/tools/testing/access_service_new/mock/main.go:30:2: "ST1003: struct field Id should be ID"
$S/cloud/storage/core/tools/testing/access_service_new/mock/main.go:30:2: "ST1003: if you believe this report is false positive, please silence it with //nolint:st1003 comment"
> cloud/storage/core/tests/recipes/access-service-new/__main__.py:58: [E302] expected 2 blank lines, found 1

Fix Arcadia sync #2

---

cloud/blockstore/libs/storage/partition_nonrepl/mirror_request_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_mirror.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_events_private.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_actor.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.h
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_mirror.cpp
cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_ut.cpp

Класс TMirrorRequestActor используется для двух задач:
1. для записи в 3 реплики для ssd-io3 диска. В таком режиме он должен превращать все ошибки от реплик в "ретрабельные", так как рано или поздно диск агент поднимется и mirroro-3 диски ломаться не умеют.
2. для наливки нового девайса, в этом случае у него две реплики, одна из которой делается наливка, а вторая куда льем. В таком режиме мы не обрабатывали ошибки и могли отдать в клиента E_IO когда проблема была у новой, наливаемой при миграции реплики.
Здесь делается так, что явно указывается какая реплика является "follower". Если такой реплики нет, то все реплики равнозначные и работа идет по сценарию 1.
Если такая реплика есть, то у нас второй сценарий и поведение чуть меняется относительно того что было:
- если получили фатальную …

Handle migration partition non-retriable errors separately

---

cloud/blockstore/tools/csi_driver/internal/driver/node.go
cloud/blockstore/tools/csi_driver/internal/driver/node_test.go

Previously endpoints were started on NodePublish phase, this breaks hotplug of multiple disks to the same VM (causes recreation of endpoints when helpler pod chandges, and ends up in deadlock attemptiong to create new endpoint before the old wan was stopped).
This commit splits volume mount between NodeStage and NodePublish phases. So endpoint is started in NodeStage, and NodePublish just creates mount to requested pod. With this split change of hotplug pod doesn't cause endpoint stop (because it doesn't trigger NodeUnpublish) but intead results in remounts, avoiding deadlock and reconnects.
What is unclear:
Decided that only vhost endpoints (NBS and NFS) should use new scheme
We don't use podId at all, use instead instanceId from volume attributes, if it is not provided then use old …

[CSI driver] Implementation of staged mount for vhost block and FS volumes in VM mode

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_checkpoint.cpp

Когда происходит изменение диска нужно изменить и размер теневого диска тоже, чтобы если в этот момент идет миграция, то записи пользователей могли проходить, а не падать с ошибкой E_ARGUMENT, что приводит к поломке NRD и залипанию mirror-диска.
Т.е. фикс чинит проблему, когда пользователь изменил размер диска в процессе создания снимка.

Resize the shadow disk when the size of the source disk changes

---

cloud/disk_manager/test/acceptance/test_runner/lib/helpers.py
cloud/disk_manager/test/acceptance/test_runner/lib/instance_policy.py

revert to previous wait_for_block_device_to_appear implementation https://github.com/ydb-platform/nbs/commit/98ac178cc7fc1cf886f38dae7ae5367780629686#diff-536ed3f8ea3b7c4f96c4e0fa2c894a1ee506c2da759d2ee1c77a334199779477

fix: revert wait_for_block_device_to_appear implementation

---

cloud/blockstore/tools/csi_driver/internal/driver/node.go

Partially revert https://github.com/ydb-platform/nbs/pull/2006/files#diff-021fd610a4ef17348cd72682382ac75500e3207f4f055627a06300ba7c962f9e and use previous implementation of NodeExpandVolume  as we have not deployed new nbs.

revert NodeExpandVolume implementation

---

cloud/filestore/libs/storage/tablet/tablet_ut_nodes.cpp

References #1146
Through the unittest enforces that RO transaction can not observe stale data

issue-1146: enforce that RO tx can not read data not commited yet by RW tx

---

cloud/filestore/tests/auth/lib/__init__.py

New auth test failed in our internal CI (for some reason ya.make ignored test's depends and `cloud/storage/core/tools/testing/access_service/mock/accessservice-mock` was not found. I could not reproduce the issue even on the CI vm itself with CI vm's configuration, but just to be safe, there's an ironclad fix.

[Test]: Fix new auth test

---

contrib/ydb/core/cms/console/configs_dispatcher.cpp

It turned out that config dispatcher can apply configs from cms without checking allow and lists provided by NBS/Filestore code.
Source pr: https://github.com/ydb-platform/ydb/pull/9917

cheery pick ydb commit to fix problem with unconditional configs loading

---

cloud/storage/core/libs/user_stats/user_stats_actor.cpp
cloud/storage/core/libs/user_stats/user_stats_actor.h

* Added prometheus format to user stats
* use "name" instead "sensor" for counter name
* remove timestamp
---------

[merge to stable-23-3] Added prometheus format to user stats (#2193)

---

cloud/filestore/libs/storage/tablet/tablet_actor_createhandle.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_nodes.cpp

Extra safety measure - if the handle that we found in DupCache doesn't exist, don't return it - drop this DupCache entry.
#2033

issue-2033: not returning stale handles from DupCache for CreateHandle requests

---

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_update_cms_device_state.cpp
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_update_cms_host_state.cpp

Fixes cases like this:
```
UpdateCmsHost result: Host=localhost Error=E_TRY_AGAIN time remaining: 0.025766s Timeout=0 AffectedDisks=[]
```

NBSDUTY-111: round up Timeout to seconds

---

cloud/disk_manager/pkg/admin/filesystem.go
cloud/disk_manager/pkg/admin/placement_group.go

Added aliases for filesystem and placement_group commands (similarly to disks, tasks and other commands).

Add aliases for disk manager admin commands

---

cloud/storage/core/libs/common/context.cpp

```
VERIFY failed (2024-10-01T09:10:30.509721Z): Request was not postponed.
cloud/storage/core/libs/common/context.cpp:95
Advance(): requirement start != 0 failed
2024-10-01T09:10:30.510683Z :BLOCKSTORE_PARTITION DEBUG: [72075186224037889] Complete ZeroBlocks (gen: 4, step: 8)
BackTrace(void**, unsigned long)+29 (0x36B9A42D)
FormatBackTrace(IOutputStream*)+32 (0x36B9A900)
PrintBackTrace()+17 (0x36B9A951)
NPrivate::InternalPanicImpl(int, char const*, char const*, int, int, int, TBasicStringBuf<char, std::__y1::char_traits<char> >, char const*, unsigned long)+995 (0x36BF67E3)
NPrivate::Panic(NPrivate::TStaticBuf const&, int, char const*, char const*, char const*, ...)+418 (0x36BE9A62)
NCloud::TCallContextBase::Advance(unsigned long)+222 (0x3747BBEE)
??+0 (0x3862C5C2)
??+0 (0x3866C7A4)
??+0 …
```

Adding a debug assert to debug the case when PostponeTsCycles is zero upon Advance()

---

cloud/blockstore/tests/csi_driver/test.py

Move csi driver log to the test folder to avoid loosing logs after running the next test from the suite.

fix: csi driver log path

---

cloud/blockstore/config/storage.proto
cloud/blockstore/libs/diagnostics/critical_events.h
cloud/blockstore/libs/storage/core/config.cpp
cloud/blockstore/libs/storage/core/config.h
cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_notify.cpp
cloud/blockstore/libs/storage/volume/testlib/test_env.cpp
cloud/blockstore/libs/storage/volume/testlib/test_env.h
cloud/blockstore/libs/storage/volume/volume_actor.h
cloud/blockstore/libs/storage/volume/volume_actor_allocatedisk.cpp
cloud/blockstore/libs/storage/volume/volume_actor_read_history.cpp
cloud/blockstore/libs/storage/volume/volume_actor_read_meta_history.cpp
cloud/blockstore/libs/storage/volume/volume_events_private.h
cloud/blockstore/libs/storage/volume/volume_tx.h
cloud/blockstore/libs/storage/volume/volume_ut.cpp
cloud/blockstore/libs/storage/volume/ya.make

#2145
В случае реалокации диска во время blue-green диск агента, теперь не пишется история и не сбрасывается индекс миграции. 
Возможно в будущем доделаю, чтобы partition вообще не рестартовал. Но по-простому там не получилось.

Add possibility to do lite reallocations

---

cloud/storage/core/libs/common/persistent_table.cpp
cloud/storage/core/libs/common/persistent_table.h
cloud/storage/core/libs/common/persistent_table_ut.cpp
cloud/storage/core/libs/common/ut/ya.make
cloud/storage/core/libs/common/ya.make

Implementation of records table on top of memory mapped file.
This will be used to recover inodes and file descriptors in later PRs
#2190

issue-2190: persistent table data structure

---

cloud/filestore/libs/storage/tablet/tablet_actor_compaction.cpp

issue-1285: fix missing StartedTs initialization for requestInfo in `Compaction`

---

cloud/tasks/config/config.proto
cloud/tasks/runner.go
cloud/tasks/runner_test.go
cloud/tasks/tracing/init.go
cloud/tasks/tracing/sampling.go
cloud/tasks/tracing/ya.make

#1199
- spans for task generations with id <= MaxSampledGeneration will be sampled (i.e. these spans will be sent to backend). Spans for tasks generations with greater id will not be sapmpled
- added request_id attribute to task spans.

[Disk Manager] tracing: add sampling of tasks generations

---

cloud/blockstore/tests/python/lib/loadtest_env.py

Move dmesg log to the test folder to avoid loosing logs after running the next test from the suite.

test: move dmesg log to test directory

---

contrib/ydb/tests/library/harness/kikimr_runner.py

Replace slash in the test name to fix output directory for tests parametrized with some path.

fix: replace slash in the test name

---

cloud/blockstore/libs/storage/disk_agent/actors/io_request_parser.cpp
cloud/blockstore/libs/storage/disk_agent/actors/session_cache_actor.cpp

Otherwise we get activity=='-' for these actors in monitoring whereas the default value for activity is the name of the actor (which is good)

deleting explicit ActivityType setting - 1. it's broken 2. the default value is better anyway

---

cloud/blockstore/apps/client/lib/command.cpp
cloud/blockstore/config/diagnostics.proto
cloud/blockstore/libs/daemon/common/bootstrap.cpp
cloud/blockstore/libs/diagnostics/config.cpp
cloud/blockstore/libs/diagnostics/config.h
cloud/blockstore/libs/diagnostics/request_stats.cpp
cloud/blockstore/libs/diagnostics/request_stats.h
cloud/blockstore/libs/diagnostics/request_stats_ut.cpp
cloud/blockstore/libs/diagnostics/server_stats_ut.cpp
cloud/blockstore/libs/diagnostics/stats_helpers.cpp
cloud/blockstore/libs/diagnostics/stats_helpers.h
cloud/blockstore/libs/diagnostics/volume_stats.cpp
cloud/blockstore/libs/endpoints_vhost/external_endpoint_stats_ut.cpp
cloud/blockstore/libs/service_local/compound_storage_ut.cpp
cloud/blockstore/libs/service_local/storage_spdk_ut.cpp
cloud/blockstore/tools/nbd/bootstrap.cpp
cloud/blockstore/tools/testing/loadtest/lib/bootstrap.cpp
cloud/filestore/config/diagnostics.proto
cloud/filestore/libs/diagnostics/config.cpp
cloud/filestore/libs/diagnostics/config.h
cloud/filestore/libs/diagnostics/request_stats.cpp
cloud/storage/core/libs/diagnostics/histogram_counter_options.h
cloud/storage/core/libs/diagnostics/histogram_types.h
cloud/storage/core/libs/diagnostics/request_counters.cpp
cloud/storage/core/libs/diagnostics/request_counters.h
cloud/storage/core/libs/diagnostics/request_counters_ut.cpp
cloud/vm/blockstore/bootstrap.cpp

This pull request adds options to report histograms as either single or multiple counters, providing more flexibility in how monitoring data is collected and reported. Single historgram counter with "le" label makes it possible to calculate quantiles in Grafana monitoring system.
There are a several places in project that report histograms, this PR changes only some of them (specifically `THistBase` class).
The main changes: 
* Added new configuration options `ReportHistogramAsMultipleCounters` and `ReportHistogramAsSingleCounter` to the diagnostics configuration files (diagnostics.proto) and support them in NBS and Filestore
* Updated the `THistBase`, `TRequestCounters` and other related classes to handle the new histogram counter options
* Added unit tests to verify the new histogram …

Added possibility to report histograms as single-counter as well as multiple-counters in TRequestCounters::TStatCounters

---

cloud/filestore/libs/storage/tablet/tablet_actor_addblob.cpp
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp

issue-1922: properly tracking BlobsCount to guarantee the BlobsCount <= real blob count in range property

---

cloud/storage/core/libs/common/error.cpp

#2274
Повод для изменений: у нас сломался SSD у одной из реплик mirror3 диска. DR не менял состояние девайса на сломанное, т.к. `EIO` ошибка считается ретрабельной. В итоге диск завис в нерабочем состоянии до ручного рестарта диск агента со сломанным SSD.

EIO is now non retriable error

---

cloud/filestore/tests/loadtest/service-kikimr-localdb-compaction-test/test.py

Test failed here: https://github-actions-s3.website.nemax.nebius.cloud/ydb-platform/nbs/Nightly-build-(asan)/11285116769/1/nebius-x86-64-asan/summary/ya-test.html#FAIL
```
2024-10-11T03:31:59.748139Z :NFS_SERVER INFO: cloud/filestore/libs/daemon/common/bootstrap.cpp:317: CgroupStatsFetcher initialized
Failed to set up IC listener on port 22170 errno# 98 (Address already in use)
```
This commit will hep debug failure to start filestore in case of

[Filestore] dump `ss -tpn` upon completion for debugging `service-kikimr-localdb-compaction-test` failure

---

cloud/blockstore/tests/csi_driver/test.py
cloud/blockstore/tools/csi_driver/client/main.go
cloud/blockstore/tools/csi_driver/internal/driver/node.go
cloud/blockstore/tools/csi_driver/internal/mounter/iface.go
cloud/blockstore/tools/csi_driver/internal/mounter/mock.go
cloud/blockstore/tools/csi_driver/internal/mounter/mounter.go

issue: #1657
Use mount-utils.Resize to support resize of ext4 and xfs

issue-1657: use mount-utils to resize fs

---

cloud/blockstore/tests/csi_driver/test.py
cloud/blockstore/tools/csi_driver/internal/driver/node.go
cloud/blockstore/tools/csi_driver/internal/driver/node_test.go
cloud/blockstore/tools/csi_driver/stage-publish-unpublish-unstage-flow.md

Problem:
-------
CSI Driver implementation violates CSI specification in terms of stage/publish/unstage/unpublish volumes.
At this moment StageVolume step is completely ignored and start endpoint/mounting volumes happens at PublishVolume step. As a result CSI Driver doesn't support ReadWriteOnce access mode in the correct way and only one pod on the same node can mount the volume, however it should be allowed to mount the same volume into multiple pods on the same node.
According to CSI Driver specification:
1. NodeStageVolume should mount the volume to the staging path
2. NodePublishVolume should mount the volume to the target path
3. NodeUnpublishVolume should unmount the volume from the target path
4. NodeUnstageVolume should unmount the volume from the staging path
As we already have …

Implement (un)stage/(un)publish volume according csi spec for mount mode

---

cloud/filestore/libs/daemon/common/bootstrap.cpp

samplingRate was bool, and we were always getting a probability of tracing requests as 1

fix slow requests sampling rate

---

cloud/blockstore/tests/csi_driver/test.py
cloud/blockstore/tools/csi_driver/internal/mounter/mounter.go

1. log output of "blockdev --getsize64"
2. move unpublish/unstage/delete volume commands to cleanup function
3. add 1 second pause before cleanup to distingiush dmesg log before and after test failure

NBSDUTY-123: log blockdev output & fix cleanup for csi tests

---

cloud/filestore/libs/storage/tablet/model/compaction_map.cpp
cloud/filestore/libs/storage/tablet/model/compaction_map.h
cloud/filestore/libs/storage/tablet/model/compaction_map_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_addblob.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_compaction.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_delete_zero_compaction_ranges.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_write_compactionmap.cpp
cloud/filestore/libs/storage/tablet/tablet_database.cpp
cloud/filestore/libs/storage/tablet/tablet_database.h
cloud/filestore/libs/storage/tablet/tablet_database_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_schema.h
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
cloud/filestore/private/api/protos/tablet.proto

Will properly calculate GarbageBlocksCount (upon writes and compactions) in the next (2nd) PR.
Will use GarbageBlocksCount to order CompactionRanges for Garbage-based Compaction in the 3rd PR.
#2137

issue-2137: support for GarbageBlocksCount in CompactionMap

---

contrib/ydb/core/log_backend/log_backend_build.cpp
contrib/ydb/core/protos/config.proto

Now with the `SysLogToStdErr` option from `TLogConfig` enabled, logs are duplicated in stderr. 
This option `SysLogToStdErr` existed but was not used in any way before. This functionality is necessary to write logs both to a local file and to stderr (in order to support cloud logging in kubernetes)

Enable duplicating logs to stderr

---

cloud/filestore/libs/diagnostics/events/profile_events.ev
cloud/filestore/libs/storage/tablet/model/mixed_blocks.cpp
cloud/filestore/libs/storage/tablet/model/mixed_blocks.h
cloud/filestore/libs/storage/tablet/profile_log_events.cpp
cloud/filestore/libs/storage/tablet/profile_log_events.h
cloud/filestore/libs/storage/tablet/profile_log_events_ut.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_addblob.cpp
cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
cloud/filestore/libs/storage/tablet/tablet_state.h
cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp
cloud/filestore/libs/storage/tablet/tablet_ut_data_stress.cpp
cloud/filestore/libs/storage/testlib/test_env.h
cloud/filestore/private/api/protos/tablet.proto
cloud/filestore/tools/analytics/libs/event-log/request_printer.cpp

Follow-up for https://github.com/ydb-platform/nbs/pull/2301
Will use GarbageBlocksCount to order CompactionRanges for Garbage-based Compaction in the 3rd PR.
#2137

issue-2137: calculating GarbageBlocksCount stats in CompactionMap

---

cloud/blockstore/config/disk.proto
cloud/blockstore/config/rdma.proto
cloud/blockstore/libs/disk_agent/config_initializer.cpp
cloud/blockstore/libs/rdma/iface/config.h
cloud/blockstore/libs/rdma_test/rdma_test_environment.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_init.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_state.cpp
cloud/blockstore/libs/storage/disk_agent/disk_agent_state.h
cloud/blockstore/libs/storage/disk_agent/disk_agent_state_ut.cpp
cloud/blockstore/libs/storage/disk_agent/model/config.h
cloud/blockstore/libs/storage/disk_agent/rdma_target.cpp
cloud/blockstore/libs/storage/disk_agent/rdma_target.h

Also move DiskAgent.RdmaTarget to RdmaConfig.DiskAgentTarget for convenience

configure rdma target thread pool size; issue-2267

---

cloud/blockstore/libs/storage/volume/multi_partition_requests.h
cloud/blockstore/libs/storage/volume/volume_actor.cpp
cloud/blockstore/libs/storage/volume/volume_actor.h
cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
cloud/blockstore/libs/storage/volume/volume_actor_forward.cpp
cloud/blockstore/libs/storage/volume/volume_actor_forward_trackused.cpp
cloud/blockstore/libs/storage/volume/volume_events_private.h
cloud/blockstore/libs/storage/volume/volume_ut.cpp

Раньше не всегда запросы, которые отправлялись в партишен, сохранялись в акторе вольюма в векторе VolumeRequests. Это работало только если паришен был один, и не происходило отслеживание записанных блоков.
Сейчас сохранение происходит во всех случаях. А значит, если таблетка вольюма умирает, то и E_REJECTED будет отправляться всегда https://github.com/ydb-platform/nbs/blob/main/cloud/blockstore/libs/storage/volume/volume_actor.cpp#L531
Поведение стало консистентным.

Always respond with E_REJECT when killing a volume tablet actor

---

cloud/filestore/libs/vfs_fuse/file_ring_buffer.cpp
cloud/filestore/libs/vfs_fuse/file_ring_buffer_ut.cpp

issue-1541: fixed TFileRingBuffer validation for the case when slack space is smaller than TEntryHeader

---

cloud/filestore/tests/recipes/service-kikimr.inc

Arcadia trunk tests crash if --bs-cache-file-path is passed to kikimr but NFS_BS_CACHE_FILE_PATH is not set in the environment

should not pass --bs-cache-file-path if NFS_BS_CACHE_FILE_PATH is not set

---

cloud/filestore/config/server.proto
cloud/filestore/libs/diagnostics/critical_events.h
cloud/filestore/libs/service_local/config.cpp
cloud/filestore/libs/service_local/config.h
cloud/filestore/libs/service_local/fs.cpp
cloud/filestore/libs/service_local/fs.h
cloud/filestore/libs/service_local/fs_attrs.cpp
cloud/filestore/libs/service_local/fs_data.cpp
cloud/filestore/libs/service_local/fs_node.cpp
cloud/filestore/libs/service_local/fs_session.cpp
cloud/filestore/libs/service_local/index.h
cloud/filestore/libs/service_local/index_ut.cpp
cloud/filestore/libs/service_local/service.cpp
cloud/filestore/libs/service_local/service_ut.cpp
cloud/filestore/libs/service_local/session.h
cloud/filestore/libs/service_local/ut/ya.make
cloud/filestore/libs/service_local/ya.make
cloud/filestore/tests/fio/qemu-local-noserver-test/ya.make

[Filestore] issue-2190: support reconnect for local file system

---

cloud/disk_manager/internal/pkg/dataplane/create_snapshot_from_url_task.go
cloud/disk_manager/internal/pkg/dataplane/url/common/errors.go
cloud/disk_manager/internal/pkg/dataplane/url/common/http_client.go

Wrong ETag error occurs during creation image from url if data from source url changed during image creation. This error shoudl not be internal.

[Disk Manager] return detailed error with aborted status on wrong etag

---

cloud/filestore/tools/testing/fs_posix_compliance/suite/tests/chown/00.t

Failed here: https://github-actions-s3.website.nemax.nebius.cloud/ydb-platform/nbs/Nightly-build/11395477455/1/nebius-x86-64/summary/ya-test.html#FAIL

[Filestore] add more debug information for posix_compliance test (chown.00.137)

---

doc/blockstore/storage/dynamic_io_mirroring_proposal.md

Related to #3 
https://github.com/ydb-platform/nbs/blob/users/komarevtsev-d/issue-3/doc-proposal/0/doc/blockstore/storage/dynamic_io_mirroring_proposal.md

Dynamic IO mirroring in mirror disks proposal
