cloud/blockstore/tests/csi_driver/e2e_tests_part1/test.py, cloud/blockstore/tools/csi_driver/internal/driver/node.go
Remove endpoint directory in NodeUnstageVolume. For old format endpoints directory removing happens in NodeUnpublishVolume https://github.com/ydb-platform/nbs/blob/main/cloud/blockstore/tools/csi_driver/internal/driver/node.go#L1049
=> csi-driver: remove endpoint dir after stopping nbs endpoint

cloud/blockstore/libs/nbd/server.cpp, cloud/blockstore/libs/nbd/server_ut.cpp
issue: #2364 
Problem:
Start endpoint returns E_FAIL if bind socket fails with "Directory not found" error
bind throws TSystemError: [nbs/library/cpp/coroutine/listener/listen.cpp at main · ydb-platform/nbs](https://github.com/ydb-platform/nbs/blob/main/library/cpp/coroutine/listener/listen.cpp#L83)
nbd server calls bind inside of SafeExecute: [nbs/cloud/blockstore/libs/nbd/server.cpp at main · ydb-platform/nbs](https://github.com/ydb-platform/nbs/blob/main/cloud/blockstore/libs/nbd/server.cpp#L315)
SafeExecute converts system error to E_FAIL: [nbs/cloud/storage/core/libs/common/error.h at main · ydb-platform/nbs](https://github.com/ydb-platform/nbs/blob/main/cloud/storage/core/libs/common/error.h#L441)
Solution:
Throw exception with E_NOT_FOUND error if directory doesn't exist before …
=> issue-2364: return E_NOT_FOUND when unix socket path doesn't exist

cloud/filestore/libs/storage/core/config.cpp, cloud/filestore/libs/storage/tablet/tablet_ut_counters.cpp
Previous (40 KiB) value did not show good compression ratio on real data, so increase a little bit
#9
=> issue-9: increase default BlobCompressionChunkSize to 80 KiB

cloud/blockstore/libs/storage/volume/volume_actor_allocatedisk.cpp, cloud/blockstore/libs/storage/volume/volume_actor_updateconfig.cpp, cloud/blockstore/libs/storage/volume/volume_ut.cpp
If an allocation error occurs during a volume configuration update, the volume stores inconsistent data in Meta (non-empty replicas containing empty device lists).
=> [Blockstore] handle disk allocation errors when updating the volume config

cloud/filestore/libs/storage/tablet/tablet_actor_addblob.cpp, cloud/filestore/libs/storage/tablet/tablet_ut_data_stress.cpp
This PR addresses the following line from #2388 : 
> if some range contains a lot of data logically (due to hash collisions) we should permanently increase Compaction/Cleanup thresholds for that range
Suppose CompactionThreshold is 10 and due to hash collisions the data in that range needs to be stored in >= 10 blobs (due to the MaxBlobSize limit). Then every 
new write will cause a new Compaction iteration because BlobsCount for that range will get >= CompactionThreshold upon every new write which is not the desired behaviour. We store the data in multiple blobs only because of BlobStorage limitations. Logically we want to treat that data as a single blob - we want to perform a Compaction iteration triggered by the "BlobsCount >= CompactionThreshold" condition only when we have a chance …
=> issue-2388: counting all MixedBlobs generated by a single Compaction run as a single logical blob in CompactionMap range stats

cloud/blockstore/config/storage.proto, cloud/blockstore/libs/diagnostics/critical_events.h, cloud/blockstore/libs/storage/core/config.cpp, cloud/blockstore/libs/storage/core/config.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_cms.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_purge_host_cms.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_secure_erase.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_update_cms_host_state.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_private.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_cms.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_suspend.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_tx.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_cms.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_pools.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_suspend.cpp, cloud/blockstore/libs/storage/disk_registry/model/device_list.cpp, cloud/blockstore/libs/storage/disk_registry/model/device_list.h, cloud/blockstore/libs/storage/disk_registry/model/device_list_ut.cpp, cloud/blockstore/libs/storage/disk_registry/testlib/test_env.cpp, cloud/blockstore/libs/storage/disk_registry/testlib/test_state.cpp, cloud/blockstore/libs/storage/disk_registry/ya.make, cloud/blockstore/public/api/protos/cms.proto, cloud/blockstore/public/sdk/go/client/safe_client.go, cloud/blockstore/tests/infra-cms/test.py, cloud/blockstore/tests/local_ssd/test.py, example/nbs/nbs-storage.txt
#2261 
1) Удалил из storage конфига `CleanupDRConfigOnCMSActions` с включением по дефолту
2) Добавил новый параметр `DiskRegistryAlwaysAllocatesLocalDisks`. При включении он изменяет поведение ручек RemoveHost, QueryAvailableStorage и аллокации локальных дисков:
- RemoveHost перестаёт удалять девайсы из конфига агента
- QueryAvailableStorage отдает локальные девайсы даже когда агент в warning
- Можно создать локальный диск из девайсов которые находятся на warning агенте
3) Добавил новую ручку PurgeHost. Она дергает RemoveHost + удаляет девайсы из агента (если нет affectedDisks)   и вводит локальные девайсы в suspend. То есть пока `DiskRegistryAlwaysAllocatesLocalDisks` выключен, RemoveHost делает то то же самое что и PurgeHost. После включения удалением будет заниматься только PurgeHost.
=> Add PURGE_HOST cms action

cloud/blockstore/libs/endpoints/endpoint_manager.cpp, cloud/blockstore/libs/endpoints/endpoint_manager_ut.cpp, cloud/blockstore/tools/csi_driver/internal/driver/node.go
issue: #2270
1. return E_ARGUMENT error if nbd device name is missing or empty and UseFreeNbdDeviceFile is missing or False
2. remove nbd device name checks if StartEndpoint succeeded
=> issue-2270: return error if nbd device name is missing

cloud/blockstore/tools/csi_driver/internal/driver/node.go, cloud/blockstore/tools/csi_driver/internal/driver/node_test.go, cloud/blockstore/tools/csi_driver/stage-publish-unpublish-unstage-flow.md
After merge of  #1982 using single FS share by multiple VMs on the same host was broken. Also testing showed that quickly unplugging disk from a VM and hotplugging to other VM on the same host doesn't work as expected.
These problems have same root cause: Kubernetes treats different PVs that have same `volumeHandle` as referring to the same volume. And we used NBS disk/filesystem ID as a `volumeHandle`, so when we the volume has been already staged on the host scheduling a VM with different PV/PVC but same `volumeHandle` on this host resulted only in `NodePublish` call (mount to pod) but not `NodeStage` call (start endpoint).
This breaks VM scenarios because only one qemu process can work with vhost-socket simultaneously, so each VM requires its own endpoint to be started.
This PR …
=> Support per-VM volumes

cloud/blockstore/libs/storage/volume/volume_actor_forward.cpp, cloud/blockstore/libs/storage/volume/volume_ut.cpp, example/7-run_qemu.sh, example/nbs/nbs-storage.txt
Исправлена опечатка при передаче параметра. 
Вместо идентификатора запроса передавался идентификатор партишена.
Это влияло на отслеживание запросов "из прошлого": в диска-агент стали приходить одинаковые идентификаторы и он начал отклонять запросы.
=> Fix request id for encrypted volume

cloud/filestore/tools/analytics/profile_tool/lib/CMakeLists.darwin-x86_64.txt, cloud/filestore/tools/analytics/profile_tool/lib/CMakeLists.linux-aarch64.txt, cloud/filestore/tools/analytics/profile_tool/lib/CMakeLists.linux-x86_64.txt, cloud/filestore/tools/analytics/profile_tool/lib/CMakeLists.windows-x86_64.txt, cloud/filestore/tools/analytics/profile_tool/lib/factory.cpp, cloud/filestore/tools/analytics/profile_tool/lib/factory_ut.cpp, cloud/filestore/tools/analytics/profile_tool/lib/mask.cpp, cloud/filestore/tools/analytics/profile_tool/lib/mask.h, cloud/filestore/tools/analytics/profile_tool/lib/ya.make, library/cpp/getopt/last_getopt_demo/demo.cpp, library/cpp/getopt/small/last_getopt_opt.h, library/cpp/getopt/small/last_getopt_opts.cpp
* [Filestore] Implement a tool which replays filestore-vhost's profile log - Tool for removing sensitive data (#1733)
commit https://github.com/ydb-platform/nbs/commit/02f6d18f9973b6ff9455f8f1b232d6656b9ba056
=> [Filestore] Implement a tool which replays filestore-vhost's profile log - Tool for removing sensitive data (#2284)

cloud/filestore/config/storage.proto, cloud/filestore/libs/service/filestore.h, cloud/filestore/libs/storage/core/config.cpp, cloud/filestore/libs/storage/core/config.h, cloud/filestore/libs/storage/core/model.cpp, cloud/filestore/libs/storage/core/model.h, cloud/filestore/libs/storage/core/model_ut.cpp, cloud/filestore/libs/storage/service/service_actor_createfs.cpp, cloud/filestore/libs/storage/service/service_ut.cpp, cloud/filestore/libs/storage/tablet/protos/tablet.proto, cloud/filestore/libs/storage/tablet/tablet_actor_createsession.cpp, cloud/filestore/libs/storage/tablet/tablet_actor_updateconfig.cpp, cloud/filestore/libs/storage/tablet/tablet_state.cpp, cloud/filestore/libs/storage/tablet/tablet_state.h, cloud/filestore/public/api/protos/const.proto
Shard creation and configuration is deliberately done NOT in the tablet code. Even though an implementation like this one leaves a possibility to produce incompletely created filesystems if the client doesn't retry errors it's not a real issue for our production clients (and even if it happens the impact will be insignificant). The upside is that such an implementation leaves no way to make a critical bug which would result in uncontrollable recursive tablet creation (fork bomb-style bug). 
Support for automatic shard creation upon filesystem resize and automatic shard deletion upon filesystem destruction will be implemented in the next PRs.
#1932
=> issue-1932: automatic filesystem shard configuration upon filesystem creation

contrib/libs/fuse/include/fuse_common.h, contrib/libs/fuse/include/fuse_kernel.h, contrib/libs/fuse/lib/fuse_lowlevel.c
original flag was added in upstream libfuse [here](https://github.com/libfuse/libfuse/commit/8bb62a632caa4269bb6436cae67307404882b936)
=> issue-1751: add WRITEBACK_CACHE flag to fuse contrib

cloud/blockstore/config/storage.proto, cloud/blockstore/libs/storage/core/config.cpp, cloud/blockstore/libs/storage/core/config.h, cloud/blockstore/libs/storage/partition_nonrepl/config.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_checksumblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_readblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_readblocks_local.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_stats.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_writeblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_zeroblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_events_private.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/resync_range_ut.cpp, cloud/storage/core/libs/actors/helpers.h
https://github.com/ydb-platform/nbs/issues/720
Делаю так, чтобы если связанность между NBS и DA восстановилась - запросы начинали выполняться, даже если диск уже успел уйти в ошибку и отдать клиенту E_IO/E_IO_SILENT. 
1. таймаут теперь отслеживается точно. Внутри каждого запроса взводится свой таймер.
2. немного поменял логику вычисления таймаута, если последний запрос завершился таймаутом. Теперь это максимальное время последних 10 запросов + сколько мы уже наблюдаем таймауты к девайсу  + backoff.  Отличие в том, что backoff не увеличивается, как раньше, а константный - 0.5 сек по дефолту. Т.е. таймауты будут : 1, 1.5, 3, 6, 12, 24,  и т.д. до достижения верхнего лимита, что сейчас 30 сек.
=> Always retry request after DA timeout

cloud/blockstore/pylibs/common/ssh_client.py
Add `check=True` option to `exec_command` so that we throw an exception on exit code 1
=> NOTICKET: Add check=True option to exec_command 

cloud/filestore/config/filesystem.proto, cloud/filestore/config/server.proto, cloud/filestore/config/storage.proto, cloud/filestore/libs/service_local/config.cpp, cloud/filestore/libs/service_local/config.h, cloud/filestore/libs/service_local/fs_session.cpp, cloud/filestore/libs/storage/core/config.cpp, cloud/filestore/libs/storage/core/config.h, cloud/filestore/libs/storage/tablet/tablet_actor_createsession.cpp, cloud/filestore/libs/vfs_fuse/config.cpp, cloud/filestore/libs/vfs_fuse/config.h, cloud/filestore/libs/vfs_fuse/loop.cpp, cloud/filestore/public/api/protos/fs.proto
Pass FUSE_CAP_WRITEBACK_CACHE to fuse client when GuestWritebackCacheEnabled
flag is set. This flag ensures that individual write request may be buffered and
merged in the kernel of the filesystem client
=> [Filestore] issue-1751: support guest writeback cache

cloud/storage/core/libs/grpc/init.cpp
Will turn it on again once the issue with exit(1) is fixed https://github.com/ydb-platform/nbs/blob/50a2e91348f2dd5264c66432b307928682fc511d/contrib/ydb/core/driver_lib/run/kikimr_services_initializers.cpp#L786
Otherwise the check may fail during initialization
=> Temporarily turn off the check in ~TGrpcState()

cloud/blockstore/tests/csi_driver/e2e_tests_part1/test.py, cloud/blockstore/tests/csi_driver/lib/csi_runner.py
Problem:
hardcoded 1ms retry timeout was removed here: https://github.com/ydb-platform/nbs/pull/2428
As a result `test_nbs_csi_driver_mounted_disk_protected_from_deletion` hangs for 5 minutes trying to destroy mounted volume.
Solution:
Add optional `retry_timeout` parameter and set it only for specific tests.
=> NBSDUTY-146: add optional retry timeout parameter

cloud/blockstore/libs/storage/init/disk_agent/actorsystem.cpp, cloud/blockstore/libs/storage/init/server/actorsystem.cpp, cloud/blockstore/tests/config_dispatcher/test.py, cloud/blockstore/tests/config_dispatcher/ya.make, cloud/filestore/libs/storage/init/actorsystem.cpp, cloud/storage/core/libs/kikimr/config_dispatcher_helpers.cpp, cloud/storage/core/libs/kikimr/config_dispatcher_helpers.h, cloud/storage/core/libs/kikimr/config_dispatcher_helpers_ut.cpp, contrib/ydb/core/cms/console/configs_dispatcher.cpp, contrib/ydb/core/cms/console/console_configs_subscriber.cpp, contrib/ydb/core/cms/console/console_configs_subscriber.h, contrib/ydb/core/cms/console/log_settings_configurator_ut.cpp
#370 
Currently nbs server and disk agent could be configured to run without tenant slot broker(actually they could be configured to run without local service which is managed by tenant slot broker). In this case configs dispatcher stucks in init state because it depends on tenant slot broker. Here i cherry-pick commit from ydb to allow configs dispatcher explicit configuration providing tenant name and node type.
=> issue-370: cherry-pick ydb commit to configure configs dispatcher without tenant slot broker + adopt blockstore/filestore code

cloud/blockstore/tests/csi_driver/e2e_tests_part2/test.py, cloud/blockstore/tools/csi_driver/internal/driver/node.go, cloud/blockstore/tools/csi_driver/internal/driver/node_test.go
issue: #2091 
Add grpid option to have volume_mount_group as GID for newly created files and directories.
doc: https://github.com/container-storage-interface/spec/blame/master/spec.md#L947
=> issue-2091: set grpid option

cloud/filestore/libs/storage/service/service_actor_readdata.cpp, cloud/filestore/libs/storage/tablet/tablet_actor.h, cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp, cloud/filestore/libs/storage/tablet/tablet_actor_monitoring.cpp, cloud/filestore/libs/storage/tablet/tablet_state.h, cloud/filestore/libs/storage/tablet/tablet_state_cache.cpp, cloud/filestore/libs/storage/tablet/tablet_state_cache.h, cloud/filestore/libs/storage/tablet/tablet_state_nodes.cpp, cloud/filestore/libs/storage/tablet/tablet_ut_cache.cpp
f0e639feb85aa40ebe4d4f8f8f822872a9c901c3
9a583b72e8df557f98a8f609df0f094df9c58351
=> [Filestore merge-to-stable] issue-1146: add monitoring for in-memory state cache sizes and exhaustiveness, get rid of multi-line log lines

cloud/disk_manager/internal/pkg/clients/nbs/client.go, cloud/disk_manager/internal/pkg/clients/nbs/factory.go, cloud/tasks/errors/errors.go, cloud/tasks/errors/errors_test.go, cloud/tasks/tracing/attributes.go, cloud/tasks/tracing/init.go
- Some errors in disk manager have stacktrace, but it might be too unwieldy write it in span/events in traces. In this pr we don't wrte stacktrace in traces, but still write it in logs.
- Sometimes errors chains have both retriable and non-retriable errors. In this pr we stop printing retriable errors created over non-retriabe errors.
example 1:
[Errors from ydb](https://github.com/ydb-platform/nbs/blob/main/cloud/tasks/persistence/ydb.go#L612). Here retriable error might wrap non-retriable error. In this case error message looks like this:
```
Retriable error <...> Non retriable error <...>
```
This is confusing, because the word 'retriable' goes first, but the error is actually non-retryable.
We get rid of such messages.
example 2:
[Too many retriable errors for …
=> [Disk Manager] do not print stacktrace in error in traces, do not print retriable errors above non-retriable errors in logs and traces

cloud/blockstore/libs/diagnostics/critical_events.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_writeblocks.cpp, cloud/blockstore/libs/storage/volume/volume_actor_forward.cpp, cloud/blockstore/libs/storage/volume/volume_ut.cpp
The added ut is useful but unfortunately it doesn't reproduce the problem it was intended to reproduce due to TString's COW. But I made the code safer just in case.
#2421
=> issue-2421: safer code + extra ut for use-intermediate-write-buffer volume tag

cloud/blockstore/libs/storage/volume/volume_ut_checkpoint.cpp
use std::popcount() from C++20 standard
___
В С++20 появилась стандартная реализация [popcount](https://en.cppreference.com/w/cpp/numeric/popcount)
Бонусом - она является constexpr
Нужно перейти на неё
___
сравнение перфа:
TLTR:
хуже для 8-ми битных (но их использование я не нашёл)
лучше для 16-ти битных 17.9G -> 19.7G (у нас используется)
одинаково для 32 и 64 битных
=> [Blockstore] PopCount => std::popcount

cloud/filestore/libs/storage/service/service_actor_destroyfs.cpp, cloud/filestore/libs/storage/service/service_ut.cpp
The actual intention is to just ignore this destruction request since for the systems above filestore filesystems listed in DenyList exist elsewhere (e.g. in a different cloud cluster under a different id).
#2216
=> issue-2216: DestroyFileStoreRequest for filestores from DenyList should result in S_FALSE, not E_ARGUMENT

cloud/filestore/libs/service_local/fs.cpp, cloud/filestore/libs/service_local/fs.h, cloud/filestore/libs/service_local/fs_session.cpp, cloud/filestore/libs/service_local/index.cpp, cloud/filestore/libs/service_local/index.h, cloud/filestore/libs/service_local/public.h, cloud/filestore/libs/service_local/session.h
#2461 
Previously, the node index was shared between all sessions belonging to the same
local filesystem. A shared index can reduce memory consumption and require fewer
open file descriptors. However, synchronizing the shared index makes the code
more complex and error-prone.
We already implemented per-session node state, which needs to be restored during
reconnect. This change aligns better with the per-session state design.
=> [Fielstore] issue-2461: simplify the local file store index by making it per session.

cloud/blockstore/libs/diagnostics/critical_events.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut.cpp
#2074
Only unoccupied devices are cleared, devices with user disks will still be put into error state without cleanup.
=> issue-2074: clean an unoccupied device if its configuration has been changed

cloud/filestore/libs/storage/tablet/tablet_ut_cache_stress.cpp, cloud/filestore/libs/storage/tablet/ut_cache_stress/ya.make
References #1146
Fixes after #2303
=> issue-1146: make ut_cache stress test use less iterations while being executed under tsan/ubsan/asan alike other ut tests

cloud/filestore/libs/storage/tablet/protos/tablet.proto, cloud/filestore/libs/storage/tablet/tablet_actor_monitoring.cpp, cloud/filestore/libs/storage/tablet/tablet_state_sessions.cpp
#1861 
- **[Filestore] issue-1861: show client hostname in list of active sessions**
- **[Filestore] issue-1861: show recovery timestamp in list of active session**
=> [Filestore] issue-1861: show client hostname and recovery timestamp in list of active sessions

contrib/ydb/core/base/blobstorage.h, contrib/ydb/core/blobstorage/dsproxy/dsproxy.h, contrib/ydb/core/blobstorage/dsproxy/dsproxy_impl.h, contrib/ydb/core/blobstorage/dsproxy/dsproxy_put.cpp, contrib/ydb/core/blobstorage/dsproxy/dsproxy_put_impl.cpp, contrib/ydb/core/blobstorage/dsproxy/dsproxy_put_impl.h, contrib/ydb/core/blobstorage/dsproxy/dsproxy_request.cpp, contrib/ydb/core/blobstorage/dsproxy/dsproxy_state.cpp
Support uniform Deadline handling for all DS proxy requests
* Improvement
DS proxy now handles Deadline fields for all requests and aborts them on timer. Timer is checked once per second for all pending requests.
=> Support uniform Deadline handling for all DS proxy requests (merge from ydb/main #5019)

cloud/tasks/storage/storage_ydb_impl.go
#2438
Can not write `request` to error as uninterpreted bytes, because this error will be send to ydb (in `error_message` field of task state) as utf8 field https://github.com/ydb-platform/nbs/blob/main/cloud/tasks/storage/common.go#L154, but `request` is not utf8-encoded. So ydb can not parse this error message.
So we write `request` in base64 endocing.
Now this error message looks like this:
```
error:{code:2  message:"Non retriable error, Silent=false: cannot create task with request=CitUZXN0SW1hZ2VTZXJ2aWNlQ3JlYXRlSW1hZ2VGcm9tSW1hZ2VfaW1hZ2UxEgZ6b25lLWEYAQ==, because task with same id=28f44fe0-aea1-4b82-9a4d-5f87131a16f7,\n\t\t\t\t but different request=CitUZXN0SW1hZ2VTZXJ2aWNlQ3JlYXRlSW1hZ2VGcm9tSW1hZ2VfaW1hZ2UxEgZ6b25lLWEYASCAgIAU already exists
```
=> [Disk Manager] write task request to error in base64 encoding

cloud/blockstore/libs/storage/volume/model/checkpoint.cpp, cloud/blockstore/libs/storage/volume/model/checkpoint.h, cloud/blockstore/libs/storage/volume/volume_actor.cpp, cloud/blockstore/libs/storage/volume/volume_actor.h, cloud/blockstore/libs/storage/volume/volume_actor_allocatedisk.cpp, cloud/blockstore/libs/storage/volume/volume_actor_change_storage_config.cpp, cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp, cloud/blockstore/libs/storage/volume/volume_actor_resync.cpp, cloud/blockstore/libs/storage/volume/volume_actor_startstop.cpp, cloud/blockstore/libs/storage/volume/volume_actor_updateconfig.cpp, cloud/blockstore/libs/storage/volume/volume_actor_updatestartpartitionsneeded.cpp, cloud/blockstore/libs/storage/volume/volume_actor_updatevolumeparams.cpp, cloud/blockstore/libs/storage/volume/volume_events_private.h, cloud/blockstore/libs/storage/volume/volume_ut_checkpoint.cpp
https://github.com/ydb-platform/nbs/issues/2136
Сделал чтобы сначала останавливался партишен с теневым диском, и только потом запускается процесс деаллокации теневого диска.
Иначе если чекопоинт удаляется в процессе наливки диска, то актор теневого диска мог слать команды на запись блоков в уже освобожденный девайс, который находился в процессе зачистки.
=> Destroy shadow disk actor before shadow disk deallocation

cloud/filestore/libs/storage/core/config.cpp
10% garbage threshold seems completely reasonable. Right now after all the recent improvements in Compaction the rate of Compactions in real clusters with 20% threshold is really small. We can afford increasing that rate a bit in exchange for storing less garbage. 
#2137
=> issue-2137: changing default value for GarbageCompactionThresholdAverage 20 -> 10

cloud/blockstore/config/storage.proto, cloud/blockstore/libs/storage/core/config.cpp, cloud/blockstore/libs/storage/core/config.h, cloud/blockstore/libs/storage/core/disk_counters.h, cloud/blockstore/libs/storage/partition/part_actor_compaction.cpp, cloud/blockstore/libs/storage/partition/part_actor_readblob.cpp, cloud/blockstore/libs/storage/partition/part_ut.cpp, cloud/blockstore/libs/storage/partition/ya.make, cloud/blockstore/libs/storage/partition2/part2_actor_compaction.cpp, cloud/blockstore/libs/storage/partition2/part2_actor_readblob.cpp, cloud/blockstore/libs/storage/partition2/part2_events_private.h, cloud/blockstore/libs/storage/partition2/part2_ut.cpp, cloud/blockstore/libs/storage/partition2/ya.make, cloud/blockstore/libs/storage/partition_common/actor_read_blob.cpp, cloud/blockstore/libs/storage/partition_common/actor_read_blob.h, cloud/blockstore/libs/storage/partition_common/events_private.h, contrib/ydb/core/blobstorage/dsproxy/dsproxy_request.cpp
=> issue-2489: limit async get duration

cloud/disk_manager/internal/pkg/facade/disk_service_nemesis_test/ya.make, cloud/disk_manager/internal/pkg/facade/disk_service_test/disk_relocation_test.go, cloud/disk_manager/internal/pkg/facade/disk_service_test/disk_service_test.go, cloud/disk_manager/internal/pkg/facade/disk_service_test/ya.make, cloud/disk_manager/internal/pkg/services/disks/config/config.proto, cloud/disk_manager/internal/pkg/services/disks/service.go, cloud/disk_manager/test/recipe/__main__.py, cloud/disk_manager/test/recipe/disk_manager_launcher.py
Added flag `DisableDiskRegistryBasedDisks` to disable DiskRegistry-based disk.
Added parameter `DiskRegistryBasedDisksFolderIdAllowList` to enable DiskRegistry-based disks for specific folders.
=> [Disk Manager] add ability to disable DiskRegistry-based disks; add ability to enable DiskRegistry-based disks for specific folders

cloud/blockstore/apps/client/README.md, cloud/blockstore/apps/client/lib/command.cpp, cloud/blockstore/apps/client/lib/command.h, cloud/blockstore/tests/loadtest/local-auth/test.py, cloud/filestore/apps/client/lib/command.cpp, cloud/filestore/apps/client/lib/command.h, cloud/filestore/tests/auth/lib/__init__.py, cloud/filestore/tests/auth/new/test.py, cloud/filestore/tests/auth/new/ya.make, cloud/filestore/tests/python/lib/client.py, cloud/filestore/tests/recipes/service-kikimr.inc, cloud/filestore/tests/recipes/service-kikimr/__main__.py
* Add a server-unix-socket-path argument for blockstore and filestore clients.
* Add option to listen on the unix socket in the filestore recipe.
* Add tests which check that the unix socket server does not require authorization.
=> [NBS, Filestore]: Add unix socket path to blockstore and filestore clients

cloud/blockstore/config/storage.proto, cloud/blockstore/libs/diagnostics/critical_events.h, cloud/blockstore/libs/storage/core/config.cpp, cloud/blockstore/libs/storage/core/config.h, cloud/blockstore/libs/storage/model/requests_in_progress.h, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_mirror.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_readblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_events_private.h, cloud/blockstore/libs/storage/partition_nonrepl/ut_env.h
If MirrorReadReplicaCount > 1, we read data from one of the replicas and we request checksums from the remaining replicas. If some of the checksums differ, we return E_REJECTED. For m3 disks and MirrorReadReplicaCount=2 one of the next retries will return S_OK if at least 2 replicas contain the same data. If data is different in all replicas, nothing can be done automatically and read request will hang (will be retried until someone manually fixes the discrepancy). 
If such a discrepancy upon read is detected, MirroredDiskChecksumMismatchUponRead critical event is raised if there were no concurrent writes whose ranges overlap the range of the read request.
In case of a 2/3 read and a discrepancy in checksums we could write some code to read the 3rd replica and, if the data in it matches …
=> issue-2077: read N/M for mirrored disks (1 ReadBlocks + N-1 ChecksumBlocks)

cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
Недавно добавленный `DiskRegistryCleanupAgentConfigError` начал загораться. Для этого достаточно позвать два раза `REMOVE_HOST`
=> Do not raise crit event when agent is not found

cloud/disk_manager/internal/pkg/facade/image_service_test/image_service_test.go, cloud/disk_manager/internal/pkg/resources/images.go, cloud/disk_manager/internal/pkg/resources/images_test.go, cloud/disk_manager/internal/pkg/resources/mocks/storage_mock.go, cloud/disk_manager/internal/pkg/resources/snapshots.go, cloud/disk_manager/internal/pkg/resources/snapshots_test.go, cloud/disk_manager/internal/pkg/resources/storage.go, cloud/disk_manager/internal/pkg/services/images/common.go, cloud/disk_manager/internal/pkg/services/images/create_image_from_disk_task.go, cloud/disk_manager/internal/pkg/services/images/create_image_from_image_task.go, cloud/disk_manager/internal/pkg/services/images/create_image_from_snapshot_task.go, cloud/disk_manager/internal/pkg/services/images/create_image_from_url_task.go, cloud/disk_manager/internal/pkg/services/snapshots/create_snapshot_from_disk_task.go, cloud/disk_manager/internal/pkg/services/snapshots/delete_snapshot_task.go
#2438
Fix for the issue.
If imageMeta.size == 0, then the image is already deleted, and there is no reason to schedule retire base disks task.
=> [Disk Manager] fix delete image idempotency: do not schedule retire base disks if image was not found in database

cloud/blockstore/libs/storage/core/forward_helpers.h, cloud/blockstore/libs/storage/partition_common/get_device_for_range_companion.cpp, cloud/blockstore/libs/storage/partition_common/get_device_for_range_companion.h, cloud/blockstore/libs/storage/partition_common/ya.make, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_get_device_for_range.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor_readblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_events_private.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/ya.make, cloud/blockstore/libs/storage/volume/actors/shadow_disk_actor.cpp
https://github.com/ydb-platform/nbs/issues/2368
Первая часть задачи про то чтобы сделать копирование данных между диск-агентами напрямую.
Здесь сделано новое сообщение, которое умеют обрабатывать все типы нереплицированных партишенов, где они отвечают в какой девайс попадает данный диапазон. Если таких девайсов несколько (диапаон на границе двух устройств), или сейчас невозможно читать из конкретного девайса, так как идет синхронизация, то отвечают E_ABORTED.
=> Introduce GetDeviceForRange method and companion for it

cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_base_request.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_ut.cpp
После https://github.com/ydb-platform/nbs/pull/2359 запросы к диску всегда пытаются отправляться в DA. Раньше же ошибка создавалась внутри партишиона и флаг выставлялся при вызове `PartConfig->MakeError()`
=> Fix missing hw problems flag in the nonrepl partition response

cloud/blockstore/libs/daemon/ydb/bootstrap.cpp, cloud/blockstore/libs/storage/volume_balancer/volume_balancer_actor.cpp, cloud/blockstore/libs/storage/volume_balancer/volume_balancer_actor.h, cloud/blockstore/libs/storage/volume_balancer/volume_balancer_ut.cpp, cloud/filestore/libs/daemon/common/bootstrap.cpp, cloud/filestore/libs/storage/service/service_actor.cpp, cloud/filestore/libs/storage/service/service_actor.h, cloud/filestore/libs/storage/service/service_actor_update_stats.cpp, cloud/storage/core/libs/diagnostics/cgroup_stats_fetcher.cpp, cloud/storage/core/libs/diagnostics/cgroup_stats_fetcher.h, cloud/storage/core/libs/diagnostics/cgroup_stats_fetcher_ut.cpp
issue: #1444
refactoring. As we plan to add[ new StatsFetcher implementation](https://github.com/ydb-platform/nbs/pull/1630) it is more convenient to set CpuWaitFailure counter in blockstore/filestore actors.
=> issue-1444: create CpuWaitFailure counter in filestore/blockstore actors

cloud/filestore/libs/server/server.cpp, cloud/filestore/libs/server/server_ut.cpp, cloud/filestore/tests/auth/lib/__init__.py, cloud/filestore/tests/auth/new/server/test.py
issue: #2570
At this moment only nfs-vhost server handles UDS request(https://github.com/ydb-platform/nbs/issues/380). Using the same ValidateRequest implementation as for vhost to handle requests from uds
=> [Filestore] Enable unix socket support in NFS server

cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_checkpoint.cpp
Исправляется недоделки:
1. DiskRegistry больше не пытается делать миграции устройств теневых дисков.
2. DiskRegistry при нотификации об изменении конфига теневого диска теперь идет в диск источника. Это нужно если например NodeId дискагента под теневым диском поменялся. https://github.com/ydb-platform/nbs/issues/2609
=> Fix shadow disk notification

cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_base_request.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_common.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_checksumblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_readblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_readblocks_local.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_writeblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_zeroblocks.cpp
Немного лучшее исправление https://github.com/ydb-platform/nbs/pull/2596
Все ответы на чтение/запись/зануление от диск-агента должны дополнительно обрабатываться:
1. выставляться флаг EF_SILENT
2. выставляться флаг EF_HW_PROBLEMS_DETECTED
3. ошибка авторизации заменяться на E_REJECT + отсылаться сообщение TEvVolume::TEvReacquireDisk
Сделал чтобы все это происходило не отдельными вызовами ProcessError() + AugmentErrorFlags(), а одним ProcessError().
=> Always call AugmentErrorFlags in ProcessError

cloud/filestore/libs/storage/service/service_actor_statfs.cpp, cloud/filestore/libs/storage/service/service_ut.cpp, cloud/filestore/libs/storage/tablet/tablet_actor.h, cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp, cloud/filestore/libs/storage/tablet/tablet_private.h, cloud/filestore/libs/storage/tablet/tablet_ut_counters.cpp, cloud/filestore/private/api/protos/tablet.proto
will use these aggregated metrics to:
* implement cheap ENOSPC checks taking aggregated space usage into account
* report aggregated space usage in main tablet monitoring metrics
#2559
=> issue-2559: aggregating shard stats in background

cloud/filestore/tests/recipes/service-kikimr/__main__.py, cloud/filestore/tests/recipes/service-local/__main__.py, cloud/filestore/tests/recipes/vhost/__main__.py
In order to better diagnose "address already in use" problem
=> Output 'ss -tpna' when stopping filestore recipes

cloud/filestore/libs/storage/tablet/shard_request_actor.h, cloud/filestore/libs/storage/tablet/tablet_actor.cpp, cloud/filestore/libs/storage/tablet/tablet_actor.h, cloud/filestore/libs/storage/tablet/tablet_actor_createsession.cpp, cloud/filestore/libs/storage/tablet/tablet_actor_destroysession.cpp, cloud/filestore/libs/storage/tablet/tablet_actor_resetsession.cpp, cloud/filestore/libs/storage/tablet/tablet_private.h
Will presumably fix hangups like this: https://github-actions-s3.website.nemax.nebius.cloud/ydb-platform/nbs/Nightly-build-(tsan)/12151536344/1/nebius-x86-64-tsan/test_data/actions-runner/_work/nbs/nbs/cloud/filestore/tests/fio_index/qemu-kikimr-multishard-nemesis-test/test-results/py3test/chunk2/testing_out_stuff/filestore-server.err
And making this code consistent with the other code that spawns one-shot actors
=> tracking ShardRequestActors to kill them upon tablet shutdown

cloud/blockstore/libs/storage/api/disk_agent.h, cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_direct_copy.cpp, cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_ut.cpp, cloud/blockstore/libs/storage/disk_agent/testlib/test_env.cpp, cloud/blockstore/libs/storage/disk_agent/testlib/test_env.h
Использование параметра по-умолчанию в MakeDiskAgentServiceId() это плохая идея, потому что приводит к неконсистентности:  когда при формировании ActorId через правильный NodeId получается ActorId, под которым никого нет, так как DiskAgent зарегистрировали с NodeId = 0.
Эта происходило в тестах blockstore/libs/storage/disk_agent/disk_agent_actor_ut.cpp
После этого исправления исчез костыль из боевого кода.
=> Fix inconsistency in obtaining ActorId for DiskAgent

cloud/filestore/libs/storage/tablet/tablet_schema.h
In the light of the growth of number of nodes it is reasonable to enable a three-stage compaction policy for Nodes and NodeRefs tables
References #688
=> issue-688 Followup: enable new compaction policy for Nodes and NodeRefs table

cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
=> issue-2559: background shard stats aggregation shouldn't get stuck in case of GetStorageStats errors from shards

cloud/blockstore/libs/storage/disk_agent/disk_agent_actor.cpp
#1950
Need DisableConcreteAgent event in integration test for Disk Manager in order to enforce shadow disk failure.
=> [Disk Agent] handle disable concrete agent event in disk agent actor

cloud/blockstore/libs/storage/volume/volume_actor_change_storage_config.cpp, cloud/blockstore/libs/storage/volume/volume_actor_loadstate.cpp, cloud/blockstore/libs/storage/volume/volume_database.cpp, cloud/blockstore/libs/storage/volume/volume_database_ut.cpp
`TVolumeDatabase::ReadStorageConfig` always sets `storageConfig` to Defined, because it only checks the iterator for validity (it should also check for `HaveValue`). It results that the Volume always creates a copy of the Config when loading a state. Because of this, it is not possible to change the configuration of the Volume via ICB.
=> [Blockstore] do not change Config if it is equal to the global config

cloud/filestore/libs/storage/tablet/tablet_actor.cpp
=> [Filestore] fix `qemu-kikimr-multishard-tablets-restart-test` test: handle TFlushResponse in the zombie state

cloud/blockstore/config/storage.proto, cloud/blockstore/libs/daemon/ydb/bootstrap.cpp, cloud/blockstore/libs/daemon/ydb/config_initializer.cpp, cloud/blockstore/libs/root_kms/impl/client.cpp, cloud/blockstore/libs/storage/core/config.cpp, cloud/blockstore/libs/storage/core/config.h, cloud/blockstore/libs/storage/core/proto_helpers.cpp, cloud/blockstore/libs/storage/init/server/actorsystem.cpp, cloud/blockstore/libs/storage/init/server/actorsystem.h, cloud/blockstore/libs/storage/service/service.cpp, cloud/blockstore/libs/storage/service/service.h, cloud/blockstore/libs/storage/service/service_actor.cpp, cloud/blockstore/libs/storage/service/service_actor.h, cloud/blockstore/libs/storage/service/service_actor_create.cpp, cloud/blockstore/libs/storage/service/service_events_private.h, cloud/blockstore/libs/storage/testlib/test_env.cpp, cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp, cloud/blockstore/tests/encryption_at_rest/test.py, cloud/blockstore/tests/encryption_at_rest/ya.make, cloud/blockstore/tests/loadtest/local-nonrepl/test.py, cloud/blockstore/tests/loadtest/local-nonrepl/ya.make.inc, cloud/blockstore/tests/python/lib/nbs_runner.py, cloud/blockstore/tests/ya.make
Create DiskRegistry-based disks with encription at rest (if enabled in configs)
#176
=> issue-176: encryption at rest

cloud/blockstore/config/storage.proto, cloud/blockstore/libs/storage/core/config.cpp, cloud/blockstore/libs/storage/core/config.h, cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_direct_copy.cpp, cloud/blockstore/libs/storage/partition_common/get_device_for_range_companion.cpp, cloud/blockstore/libs/storage/partition_common/get_device_for_range_companion.h, cloud/blockstore/libs/storage/partition_nonrepl/direct_copy_range.cpp, cloud/blockstore/libs/storage/partition_nonrepl/direct_copy_range.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_events_private.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/ut/ya.make, cloud/blockstore/libs/storage/partition_nonrepl/ya.make, cloud/blockstore/libs/storage/testlib/disk_agent_mock.h, example/nbs/nbs-storage.txt
Продолжение https://github.com/ydb-platform/nbs/issues/2368
Склеиваю все вместе.
1. Новый актор TDirectCopyRangeActor который ходит в партишены c запросом TGetDeviceForRangeRequest, получает девайсы и затем отправляет запрос TEvDirectCopyBlocksRequest с полученной информацией в ДискаАгента
2. TNonreplicatedPartitionMigrationCommonActor учится использовать TDirectCopyRangeActor для копирования данных под флагом
=> Use direct copy in TNonreplicatedPartitionMigrationCommonActor

cloud/blockstore/libs/common/block_range.cpp, cloud/blockstore/libs/common/block_range.h
TBlockRange теперь печатается одинаково, что через DescribeRange(), что через operator<<
=> Print TBlockRange the same way

cloud/blockstore/tests/csi_driver/csi_sanity_tests/test.py, cloud/blockstore/tests/csi_driver/e2e_tests_part1/test.py, cloud/blockstore/tests/csi_driver/e2e_tests_part2/test.py, cloud/blockstore/tools/csi_driver/client/main.go, cloud/blockstore/tools/csi_driver/internal/driver/node.go
issue: #2654
disk manager resizes volumes in [VM mode](https://github.com/ydb-platform/nbs/blob/main/doc/k8s/kubevirt.svg) however we must refresh nbs endpoint in csi driver.
=> [CSI] Support volume resize in vm mode

cloud/blockstore/public/sdk/go/client/session.go, cloud/blockstore/public/sdk/go/client/session_test.go
Test failed in pr https://github.com/ydb-platform/nbs/pull/2519
The reason of failure is a race condition in blockstore go SDK. Namely, the volume might be remounted after it was unmounted, but before session is closed. This might cause mount conflict on the next mount of the volume.
Bad scenario in more details:
- Start volume unmount.
- While unmounting, tick of the remounter happens. Remounter starts waiting on the mutex https://github.com/ydb-platform/nbs/blob/main/cloud/blockstore/public/sdk/go/client/session.go#L480
- Finish unmount.
- Remounter remounts volume.
=> [GO SDK] fix race condition in remounter

cloud/blockstore/libs/storage/partition2/part2_actor.cpp, cloud/blockstore/libs/storage/partition2/part2_actor.h
Тест падал потому что на момент его окончания была "висящая" операция compaction и поскольку не вызывался обычный код убивания таблетки (а просто деструктор, который ничего не делал)
=> fix memory leak in partition2 tests

cloud/filestore/config/storage.proto, cloud/filestore/libs/storage/core/config.cpp, cloud/filestore/libs/storage/core/config.h, cloud/filestore/libs/storage/tablet/model/shard_balancer.cpp, cloud/filestore/libs/storage/tablet/model/shard_balancer.h, cloud/filestore/libs/storage/tablet/model/shard_balancer_ut.cpp, cloud/filestore/libs/storage/tablet/model/ut/ya.make, cloud/filestore/libs/storage/tablet/tablet_actor.h, cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp, cloud/filestore/libs/storage/tablet/tablet_actor_createhandle.cpp, cloud/filestore/libs/storage/tablet/tablet_actor_createnode.cpp, cloud/filestore/libs/storage/tablet/tablet_actor_monitoring.cpp, cloud/filestore/libs/storage/tablet/tablet_private.h, cloud/filestore/libs/storage/tablet/tablet_state.cpp, cloud/filestore/libs/storage/tablet/tablet_state.h, cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
If we have shards with FreeSpace >= ShardBalancerDesiredFreeSpaceReserve, we choose among them in a round robin manner
If not - we choose among shards with FreeSpace >= ShardBalancerMinFreeSpaceReserve in a round robin manner
If all shards have less than ShardBalancerMinFreeSpaceReserve free space, we return ENOSPC
#2559
=> issue-2559: actual ShardBalancer implementation

cloud/disk_manager/internal/pkg/services/images/delete_image_task_test.go, cloud/disk_manager/internal/pkg/services/images/tests/ya.make, cloud/disk_manager/internal/pkg/services/images/ya.make
#2438
Checks that retire base disks is scheduled correctly (there was a bug that was fixed here https://github.com/ydb-platform/nbs/pull/2497).
=> Add unit test on delete image task

cloud/blockstore/libs/storage/core/config.cpp, cloud/blockstore/libs/storage/core/config.h, cloud/blockstore/libs/storage/core/config_ut.cpp, cloud/blockstore/libs/storage/core/ut/ya.make, cloud/blockstore/libs/storage/volume/volume_actor_change_storage_config.cpp, cloud/blockstore/libs/storage/volume/volume_actor_loadstate.cpp, cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp
Fixed overriding of configs via ChangeStorageConfig action: the configuration patch had no effect because it was applied only to the internal protobuf, not to all fields of TStorageConfig.
=> [Blockstore] fix storage config overriding

cloud/blockstore/apps/server_lightweight/ya.make
```
Error[-WBadDep]: in $B/cloud/blockstore/apps/server_lightweight/nbsd-lightweight: forbids direct or indirect PEERDIR dependency to module $B/yql/essentials/public/issue/protos/libpublic-issue-protos.a via CHECK_DEPENDENT_DIRS
$B/cloud/blockstore/apps/server_lightweight/nbsd-lightweight -> $B/cloud/blockstore/libs/daemon/local/liblibs-daemon-local.a
$B/cloud/blockstore/libs/daemon/local/liblibs-daemon-local.a -> $B/cloud/blockstore/libs/daemon/common/liblibs-daemon-common.a
$B/cloud/blockstore/libs/daemon/common/liblibs-daemon-common.a -> $B/cloud/blockstore/libs/endpoints/libblockstore-libs-endpoints.a
$B/cloud/blockstore/libs/endpoints/libblockstore-libs-endpoints.a -> $B/contrib/ydb/core/protos/libydb-core-protos.a
$B/contrib/ydb/core/protos/libydb-core-protos.a -> …
```
=> Fix arcadia sync

cloud/filestore/libs/vfs_fuse/fs_impl_data.cpp, cloud/filestore/libs/vfs_fuse/fs_ut.cpp, cloud/filestore/libs/vhost/request.h
When working with writeback cache on client we need to additionally allow  reads
for files which are open with write-only flag similar to virtiofsd
https://gitlab.com/virtio-fs/virtiofsd/blob/main/src/passthrough/mod.rs#L606
#1751
=> [Filestore] issue-1751: allow read when guest writeback cache enabled

cloud/blockstore/tools/csi_driver/internal/driver/node.go
issue: #2720
sci spec: https://github.com/container-storage-interface/spec/blob/master/spec.md#nodeexpandvolume-errors
=> issue-2720: return non-retryable error after resize2fs failure

cloud/filestore/libs/storage/service/service_ut_sharding.cpp, cloud/filestore/libs/storage/tablet/tablet_actor_createnode.cpp, cloud/filestore/libs/storage/tablet/tablet_actor_listnodes.cpp, cloud/filestore/libs/storage/tablet/tablet_private.h, cloud/filestore/libs/storage/tablet/tablet_state.h, cloud/filestore/libs/storage/tablet/tablet_state_impl.h, cloud/filestore/libs/storage/tablet/tablet_state_nodes.cpp
=> [Filestore] issue-2171: Avoid listing nodes with pending create on shards

cloud/blockstore/tools/csi_driver/internal/driver/node.go, cloud/blockstore/tools/csi_driver/internal/driver/node_test.go, cloud/blockstore/tools/csi_driver/internal/mounter/iface.go, cloud/blockstore/tools/csi_driver/internal/mounter/mock.go, cloud/blockstore/tools/csi_driver/internal/mounter/mounter.go
issue: #2727 
formatAndMount [implementation](https://github.com/kubernetes/mount-utils/blob/master/mount_linux.go#L555):
1. check that fs already exists
2. if fs doesn't exist:
- make fs
- mount fs
3. if fs exists:
- check that required fs type is the same as existing fs type
- check and repair fs
- mount fs
=> issue-2727: use mount-utils/FormatAndMount to check and repair FS before mounting

cloud/blockstore/libs/diagnostics/critical_events.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_migration.cpp
=> issue-2715: add critical events for double migration

contrib/ydb/core/driver_lib/run/kikimr_services_initializers.cpp, contrib/ydb/core/protos/config.proto, contrib/ydb/library/actors/dnsresolver/dnsresolver.cpp, contrib/ydb/library/actors/dnsresolver/dnsresolver.h
https://github.com/ydb-platform/ydb/pull/4123
=> Backport 'Allow to set "force tcp" and "keep-socket" options for dns resolver' from ydb-platform/ydb

cloud/blockstore/libs/storage/disk_agent/actors/device_health_check_actor.cpp, cloud/blockstore/libs/storage/disk_agent/actors/device_health_check_actor.h, cloud/blockstore/libs/storage/disk_agent/actors/ya.make, cloud/blockstore/libs/storage/disk_agent/disk_agent_actor.cpp, cloud/blockstore/libs/storage/disk_agent/disk_agent_actor.h, cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_init.cpp, cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_register.cpp, cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_stats.cpp, cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_ut.cpp, cloud/blockstore/libs/storage/disk_agent/disk_agent_state.cpp, cloud/blockstore/libs/storage/disk_agent/disk_agent_state.h, cloud/blockstore/libs/storage/disk_agent/disk_agent_state_ut.cpp, cloud/blockstore/libs/storage/disk_agent/model/device_client.cpp, cloud/blockstore/libs/storage/disk_agent/model/device_client.h, cloud/blockstore/libs/storage/disk_agent/testlib/test_env.cpp
Device health checking was moved to TDeviceHealthCheckActor.
Health check is only performed for enabled devices to reduce noisy error log messages:
```
2024-12-10T14:37:37.223534Z :BLOCKSTORE_DISK_AGENT ERROR: cloud/blockstore/libs/storage/disk_agent/disk_agent_state.cpp:557: [foo/check-health] Device disabled. Drop request.
2024-12-10T14:37:37.232994Z :BLOCKSTORE_DISK_AGENT_WORKER INFO: The device "foo" broke down. E_IO cloud/blockstore/libs/storage/disk_agent/disk_agent_state.cpp:566: Device disabled
```
To handle actual list of devices TDeviceHealthCheckActor is restarted every time when Disk Agent is registered in Disk Registy.
=> [Blockstore] Do not check health of disabled devices

cloud/blockstore/config/storage.proto, cloud/blockstore/libs/storage/core/config.cpp, cloud/blockstore/libs/storage/core/config.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut.cpp
При большом количестве групп размещения, подсчет статистики, сколько групп уже полны - занимает непозволительно много времени. 
До того как сделали оптимально, делаю флаг для выключения.
=> Disable FullPlacementGroupCount calculation

cloud/blockstore/tools/csi_driver/internal/driver/node.go, cloud/blockstore/tools/csi_driver/internal/driver/node_test.go, cloud/blockstore/tools/csi_driver/internal/mounter/iface.go, cloud/blockstore/tools/csi_driver/internal/mounter/mock.go, cloud/blockstore/tools/csi_driver/internal/mounter/mounter.go
issue: #2727
In this [pr](https://github.com/ydb-platform/nbs/pull/2728/files#diff-021fd610a4ef17348cd72682382ac75500e3207f4f055627a06300ba7c962f9eL785) I removed makeFilsystemIfNeeded call. Inside it calls IsFilesystemExisted and checks existence of block device. It's important because startEndpoint is an async function and in some cases block device is not available immediately. Kubelet will retry NodeStageVolume call if block device is not avaiable.
I moved this logic to separate function HasBlockDevice and added comment to avoid removing of this logic again.
=> issue-2727: check block device before mounting FS

contrib/ydb/core/protos/filestore_config.proto, contrib/ydb/core/tx/schemeshard/schemeshard_info_types.h, contrib/ydb/core/tx/schemeshard/schemeshard_path_element.cpp, contrib/ydb/core/tx/schemeshard/schemeshard_path_element.h, contrib/ydb/core/tx/schemeshard/user_attributes.cpp, contrib/ydb/core/tx/schemeshard/user_attributes.h, contrib/ydb/core/tx/schemeshard/ut_filestore_reboots/ut_filestore_reboots.cpp
Manually applied https://github.com/ydb-platform/ydb/pull/12693 because of conflicts.
Tests were run locally:
```
root@bh2qurg7qaaevd7tte2i:~/reps/nbs_stable/contrib/ydb/core/tx/schemeshard# ~/reps/nbs_stable/ya make -tt ut_filestore_reboots/ -F=*CheckFileStoreSSDLimits*
------- [TM] {debug, default-linux-x86_64} contrib/ydb/core/tx/schemeshard/ut_filestore_reboots/unittest >> TFileStoreWithReboots::CheckFileStoreSSDLimits
Test command err:
No Keys in KeyConfig! Encrypted group DsProxies will not start
Leader for TabletID 8751008 is [0:0:0] sender: [1:101:2042] recipient: [1:95:12303]
IGNORE Leader for TabletID 8751008 is [0:0:0] sender: [1:101:2042] recipient: [1:95:12303]
Leader for TabletID 8751008 is [1:110:12290] sender: [1:112:2042] recipient: [1:95:12303] …
```
=> Backport https://github.com/ydb-platform/ydb/pull/12693

cloud/blockstore/config/storage.proto, cloud/blockstore/libs/diagnostics/critical_events.h, cloud/blockstore/libs/storage/core/config.cpp, cloud/blockstore/libs/storage/core/config.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_loadstate.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_private.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_lifecycle.cpp
#2752
If the percentage of agents that did not reconnect after Disk Registry' reboot is higher than DiskRegistryInitialAgentRejectionThreshold, then the rejection of such agents does not occur - we assume a connectivity failure in the cluster.
=> [Blockstore] preventing the rejection of a significant fraction of Disk Agents in the cluster

cloud/blockstore/libs/storage/service/service_actor.h, cloud/blockstore/libs/storage/service/service_actor_forward.cpp, cloud/blockstore/libs/storage/service/service_actor_writeblocks.cpp
issue: #2605
remove redundant validation of blocks count for remote requests
=> issue-2605: remove blocks count validation for remote requests

cloud/filestore/libs/service_local/fs_attrs.cpp, cloud/filestore/libs/service_local/lowlevel.cpp
=> [Filestore] issue-2783: fix local filestore chown to work when one of uid/gid is not provided

cloud/storage/core/libs/endpoints/keyring/ut/ya.make
Run all keyring unit tests in the one vm to speedup tests execution. Time execution is approximately 40s vs 170s on my developer VM.
=> test: set split factor to 1 for keyring tests

cloud/storage/core/libs/auth/authorizer.cpp, cloud/storage/core/libs/auth/authorizer_ut.cpp
`TicketParser` can return fatal error with empty ticket, for example [there](https://github.com/ydb-platform/nbs/blob/b5c6c7763e995162f75752ded679be85c53d1662/contrib/ydb/core/security/ticket_parser_impl.h#L1097). 
That will cause a crash:
```
VERIFY failed (2025-01-03T17:18:07.587479Z): 
cloud/storage/core/libs/auth/authorizer.cpp:256
HandleParseTicketResult(): requirement Token == msg->Ticket failed
NPrivate::InternalPanicImpl(int, char const*, char const*, int, int, int, TBasicStringBuf<char, std::__y1::char_traits<char> >, char const*, unsigned long)+557 (0x5597D1AFA02D)
NPrivate::Panic(NPrivate::TStaticBuf const&, int, char const*, char const*, char const*, ...)+268 (0x5597D1AF04CC)
??+0 (0x5597E333D2B6)
NActors::TGenericExecutorThread::TProcessingResult …
```
=> Authorizer should not crash when TicketParser returns fatal error with empty ticket in result

cloud/blockstore/libs/storage/volume/volume_state.cpp, cloud/blockstore/libs/storage/volume/volume_state.h, cloud/blockstore/libs/storage/volume/volume_state_ut.cpp, cloud/blockstore/tests/encryption_at_rest/test.py
#176
Tracking of used blocks should be disabled in case of volumes with encryption at rest: assume that unencrypted blocks are completely filled with zeros.
=> issue-176: disable used block tracking

cloud/filestore/libs/storage/service/service_ut_sharding.cpp, cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp, cloud/filestore/private/api/protos/tablet.proto
=> issue-2674: directory sharding - shard->shard stats aggregation fixes + ut

cloud/filestore/libs/storage/tablet/tablet_actor.cpp, cloud/filestore/libs/storage/tablet/tablet_actor.h, cloud/filestore/libs/storage/tablet/tablet_actor_loadstate.cpp, cloud/filestore/libs/storage/tablet/tablet_actor_loadstate_noderefs.cpp, cloud/filestore/libs/storage/tablet/tablet_private.h, cloud/filestore/libs/storage/tablet/tablet_tx.h, cloud/filestore/libs/storage/tablet/tablet_ut_cache.cpp
References #1146
Fixes after https://github.com/ydb-platform/nbs/pull/2241
Earlier LoadNodeRefs executed transaction that upon completion immediately executed transaction for the next batch. In this approach there were no gaps allowing for a concurrent operation to complete. In this PR this issue is resolved by sending messages to trigger another batch loading
=> issue-1146: allow other operations to complete during noderefs loading

cloud/filestore/apps/client/lib/command.cpp, cloud/filestore/apps/client/lib/command.h, cloud/filestore/apps/client/lib/diff.cpp, cloud/filestore/apps/client/lib/factory.cpp, cloud/filestore/apps/client/lib/ln.cpp, cloud/filestore/apps/client/lib/ya.make, cloud/filestore/libs/storage/api/service.h, cloud/filestore/tests/client_sharded_dir/canondata/test.test_nonsharded_vs_sharded_fs/results.txt, cloud/filestore/tests/client_sharded_dir/test.py, cloud/filestore/tests/python/lib/client.py
=> issue-2674: filestore-client ln command + support for RenameNode, UnlinkNode + basic support for RenameNode in filesystems with directories in shards

cloud/storage/core/libs/common/error.h, doc/blockstore/diagnostics/result-codes.md
Fix issues from https://github.com/ydb-platform/nbs/pull/2766
=> [NBS] Document result codes

cloud/filestore/libs/storage/tablet/tablet_actor.cpp, cloud/filestore/libs/storage/tablet/tablet_actor.h, cloud/filestore/libs/storage/tablet/tablet_actor_loadstate.cpp, cloud/filestore/libs/storage/tablet/tablet_actor_loadstate_nodes.cpp, cloud/filestore/libs/storage/tablet/tablet_database.cpp, cloud/filestore/libs/storage/tablet/tablet_database.h, cloud/filestore/libs/storage/tablet/tablet_private.h, cloud/filestore/libs/storage/tablet/tablet_state_cache.cpp, cloud/filestore/libs/storage/tablet/tablet_state_cache.h, cloud/filestore/libs/storage/tablet/tablet_state_iface.h, cloud/filestore/libs/storage/tablet/tablet_tx.h, cloud/filestore/libs/storage/tablet/tablet_ut_cache.cpp, cloud/filestore/libs/storage/tablet/ya.make
References #1146 
Similar to #2241: Upon the filestore index tablet startup load not only NodeRefs table to the in-memory cache, but Nodes table as well
=> issue-1146: load nodes upon the tablet startup as well

cloud/blockstore/libs/diagnostics/volume_stats_ut.cpp, cloud/storage/core/libs/diagnostics/request_counters_ut.cpp
Test fails due to long timer initialization resulting in erroneous measurement of the request times
https://github.com/ydb-platform/nbs/blob/aaac99648c06e24c3f158b8373c97e7381a79edd/util/system/hp_timer.cpp#L105
#2830
=> NBSDUTY-214: fix ShouldReportSufferMetrics test (add warmup timer)

cloud/filestore/libs/service_local/fs_node.cpp
#2819 
Some proprietary file systems report the links count incorrectly as 1
=> [Filestore] issue-2819: Forget deleted directory node if it has <= 2 links

.github/actions/nebius_threads_calculator/action.yaml
we want to see if reducing number of parallel tests during nightly run will help get rid off timeouts in tests for example [here](https://github-actions-s3.storage.eu-north1.nebius.cloud/ydb-platform/nbs/Nightly-build/12738760869/1/nebius-x86-64/summary/ya-test.html#FAIL)
=> reduce number of tests threads in nightly to avoid disk pressure that can lead to timeouts

cloud/blockstore/tools/csi_driver/internal/driver/node.go, cloud/blockstore/tools/csi_driver/internal/driver/node_test.go
issue: #2801
All Start/StopEndpoint requests are landed into the same queue: [nbs/cloud/blockstore/libs/storage/service/volume_session_actor_mount.cpp at main · ydb-platform/nbs](https://github.com/ydb-platform/nbs/blob/main/cloud/blockstore/libs/storage/service/volume_session_actor_mount.cpp#L1020) . NBS handles only one request at the same time.
StartEndpoint request from csi driver can fail by timeout however request in the queue will retry to start endpoint longer time. It leads to hanging delete volume operation as csi driver doesn’t send stop endpoint request(NodeVolume publish fails so we don’t need to send NodeUnpublishVolume).
Solution:
Send StopEndpoint request(in NodePublishVolume/NodeStageVolume) if StartEndpoint request fails with GRPC timeout error.
=> [CSI] trigger StopEndpoint if StartEndpoint has failed with GRPC Timeout error

cloud/filestore/libs/diagnostics/critical_events.h, cloud/filestore/libs/storage/api/tablet.h, cloud/filestore/libs/storage/service/service_actor_alterfs.cpp, cloud/filestore/libs/storage/service/service_actor_createfs.cpp, cloud/filestore/libs/storage/tablet/protos/tablet.proto, cloud/filestore/libs/storage/tablet/protos/ya.make, cloud/filestore/libs/storage/tablet/tablet_actor.cpp, cloud/filestore/libs/storage/tablet/tablet_actor.h, cloud/filestore/libs/storage/tablet/tablet_actor_createnode.cpp, cloud/filestore/libs/storage/tablet/tablet_actor_oplog.cpp, cloud/filestore/libs/storage/tablet/tablet_actor_renamenode.cpp, cloud/filestore/libs/storage/tablet/tablet_actor_renamenode_destination.cpp, cloud/filestore/libs/storage/tablet/tablet_actor_renamenode_source.cpp, cloud/filestore/libs/storage/tablet/tablet_actor_request.cpp, cloud/filestore/libs/storage/tablet/tablet_actor_unlinknode.cpp, cloud/filestore/libs/storage/tablet/tablet_actor_updateconfig.cpp, cloud/filestore/libs/storage/tablet/tablet_private.h, cloud/filestore/libs/storage/tablet/tablet_state.h, cloud/filestore/libs/storage/tablet/tablet_state_sessions.cpp, cloud/filestore/libs/storage/tablet/tablet_tx.h, cloud/filestore/libs/storage/tablet/ya.make, cloud/filestore/private/api/protos/tablet.proto, cloud/filestore/tests/client_sharded_dir/canondata/test.test_nonsharded_vs_sharded_fs/results.txt, cloud/filestore/tests/client_sharded_dir/test.py
TODOs:
* DupCache for RenameNodeInDestination
* RenameNodeInDestination request replay from OpLog upon tablet start
* uts for non-happy path
* implement NodeType checks (via extra GetNodeAttr calls)
Happy path works (tested via https://github.com/ydb-platform/nbs/blob/83fa5e20b14073610e49f9ae722d85cef756ec75/cloud/filestore/tests/client_sharded_dir/test.py#L144)
#2674
=> issue-2674: cross-shard RenameNode implementation

cloud/blockstore/libs/.gitignore, cloud/blockstore/libs/storage/disk_registry/benchmark/ya.make, cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_restore_state.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_benchmark.cpp, cloud/blockstore/libs/storage/disk_registry/ya.make, cloud/blockstore/tests/.gitignore, cloud/blockstore/tests/recipes/disk-registry-state/__main__.py, cloud/blockstore/tests/recipes/disk-registry-state/recipe.inc, cloud/blockstore/tests/recipes/disk-registry-state/ya.make, cloud/blockstore/tests/recipes/ya.make, cloud/blockstore/tools/.gitignore, cloud/blockstore/tools/testing/disk-registry-state-generator/main.cpp, cloud/blockstore/tools/testing/disk-registry-state-generator/ya.make, cloud/blockstore/tools/testing/ya.make
Сделал бенчмарки для DiskRegistry.
Пока только:
- публикация счетчиков (из-за чего у нас был инцидент)
-  создание/удаление Nonrepl дисков разного размера
-  создание/удаление Mirror дисков разного размера
Перед запуском теста через утилиту создается бэкап DR. Бэкап чем-то напоминает один из кластеров. Утилита запускается через рецепт.
Анонимизрованный бэкап тоже бы подошел, но генерация стейта позволит отвечать на вопрос: "что будет когда кластер вырастет до размера Х".
```
----------------------------------------------------------------------------
Benchmark                                  Time             CPU   Iterations
----------------------------------------------------------------------------
PublishCounters_All                869476645 ns    869360580 ns            1 …
```
=> Disk registry benchmarks

cloud/blockstore/config/storage.proto, cloud/blockstore/libs/storage/core/config.cpp, cloud/blockstore/libs/storage/core/config.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_agent_state.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_device_state.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp, cloud/blockstore/libs/storage/disk_registry/ya.make, cloud/blockstore/tests/monitoring/test.py, cloud/blockstore/tests/python/lib/client.py
#2732 
Change agent state:
Change device state:
=> [NBS] Issue 2732: add change device/agent state buttons

cloud/blockstore/libs/endpoint_proxy/server/server.cpp, cloud/blockstore/libs/endpoints_nbd/nbd_server.cpp, cloud/blockstore/libs/nbd/bench/bootstrap.cpp, cloud/blockstore/libs/nbd/error_handler.cpp, cloud/blockstore/libs/nbd/error_handler.h, cloud/blockstore/libs/nbd/netlink_device.cpp, cloud/blockstore/libs/nbd/public.h, cloud/blockstore/libs/nbd/server.cpp, cloud/blockstore/libs/nbd/server_handler.cpp, cloud/blockstore/libs/nbd/server_handler.h, cloud/blockstore/libs/nbd/server_handler_ut.cpp, cloud/blockstore/libs/nbd/server_ut.cpp, cloud/blockstore/libs/nbd/ya.make, cloud/blockstore/tools/nbd/bootstrap.cpp, cloud/blockstore/tools/testing/nbd-test/target.cpp
For now implementing only for endpoint proxy, because it's our primary use case
=> reconfigure nbd device on disconnect from the kernel #2791

cloud/blockstore/tests/csi_driver/e2e_tests_part2/test.py, cloud/blockstore/tools/csi_driver/deploy/manifests/4-storageclass.yaml, cloud/blockstore/tools/csi_driver/internal/driver/node.go, cloud/blockstore/tools/csi_driver/internal/driver/node_test.go
issue: #2795
This reverts commit d37133329aec595df091c42cd009538a3c00aada.
The removal of the VOLUME_MOUNT_GROUP capability is not possible at this time, as we must first migrate to the new storage classes.
=> Revert "[CSI] remove VOLUME_MOUNT_GROUP capability (#2739)"

cloud/filestore/libs/storage/api/service.h, cloud/filestore/libs/storage/service/service_actor.cpp, cloud/filestore/libs/storage/service/service_actor.h, cloud/filestore/libs/storage/service/service_actor_update_stats.cpp, cloud/filestore/libs/storage/service/service_state.cpp, cloud/filestore/libs/storage/service/service_state.h, cloud/filestore/libs/storage/service/service_ut.cpp, cloud/filestore/libs/storage/tablet/tablet_actor.cpp, cloud/filestore/libs/storage/tablet/tablet_actor_updateconfig.cpp, cloud/filestore/libs/storage/tablet/tablet_ut.cpp, cloud/filestore/libs/storage/testlib/service_client.h
=> add fs and tablets counters

cloud/filestore/libs/diagnostics/critical_events.h, cloud/filestore/libs/storage/service/service_ut_sharding.cpp, cloud/filestore/libs/storage/tablet/model/node_index_cache.cpp, cloud/filestore/libs/storage/tablet/model/node_index_cache.h, cloud/filestore/libs/storage/tablet/model/node_ref.cpp, cloud/filestore/libs/storage/tablet/model/node_ref.h, cloud/filestore/libs/storage/tablet/model/ya.make, cloud/filestore/libs/storage/tablet/tablet_actor_oplog.cpp, cloud/filestore/libs/storage/tablet/tablet_actor_renamenode.cpp, cloud/filestore/libs/storage/tablet/tablet_actor_renamenode_source.cpp, cloud/filestore/libs/storage/tablet/tablet_actor_unlinknode.cpp, cloud/filestore/libs/storage/tablet/tablet_state.h, cloud/filestore/libs/storage/tablet/tablet_state_impl.h, cloud/filestore/libs/storage/tablet/tablet_state_nodes.cpp
=> issue-2674: locking NodeRefs for modification upon RenameNode and UnlinkNode ops

cloud/tasks/tasks_tests/tasks_test.go
Test on inflight tasks limit should check the number of inflight tasks. This is not the same at the number of tasks in status 'running' because a task can be running but not inflight.
=> [Disk Manager] check number of inflight tasks properly in test

cloud/blockstore/libs/storage/volume/volume_actor_allocatedisk.cpp, cloud/blockstore/libs/storage/volume/volume_ut.cpp
=> Do the lite reallocation when only IOModeTs is changed

cloud/blockstore/libs/storage/volume/volume_state_ut.cpp
Тест не работал, потому что емкость контейнера TCachedVolumeMountHistory была равна нулю.
=> Fix ShouldCacheLimitedNumberOfRecords test

cloud/blockstore/libs/diagnostics/profile_log.cpp, cloud/blockstore/libs/diagnostics/profile_log_ut.cpp, cloud/filestore/libs/diagnostics/profile_log.cpp, cloud/filestore/libs/diagnostics/profile_log_ut.cpp
To avoid losing up to 15 seconds of logs on server exit or soft crash
=> Flush profile logs on destruct

cloud/blockstore/config/storage.proto, cloud/blockstore/libs/storage/core/compaction_map.cpp, cloud/blockstore/libs/storage/core/compaction_map.h, cloud/blockstore/libs/storage/core/compaction_map_ut.cpp, cloud/blockstore/libs/storage/core/config.cpp, cloud/blockstore/libs/storage/core/config.h, cloud/blockstore/libs/storage/partition/part_actor_compaction.cpp, cloud/blockstore/libs/storage/partition/part_ut.cpp, cloud/blockstore/tests/loadtest/local-newfeatures/test.py
Добавляются новые параметры для управления batch compaction:
- GarbageCompactionRangeCountPerRun - сколько ренджей обрабатывать за один компакшн в режиме garbage compaction;
- ForceCompactionRangeCountPerRun - сколько ренджей обрабатывать за один компакшн по команде от оператора (force).
Эти параметры учитываются только если BatchCompactionEnabled == true, т.е. batch compaction включен.
=> Add GarbageCompactionRangeCountPerRun and ForcedCompactionRangeCountPerRun parameters to batch compaction feature

.github/scripts/nebius-manage-vm.py, .github/scripts/shell-extractor.py
Fix errors like that https://github.com/ydb-platform/nbs/actions/runs/12913143995/job/36009721975
=> chore: fix flake8 build

cloud/filestore/libs/storage/tablet/model/read_ahead.cpp, cloud/filestore/libs/storage/tablet/model/read_ahead_ut.cpp
typo fix causing entire cache eviction: `hashmap.clear(size_t)` is a clear with a downsize hint
=> Filestore: readahead cache invalidation should not evict all nodes

cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut.cpp
=> issue-2917: don't discard Disk Agent stats with unknown devices

cloud/blockstore/libs/storage/disk_registry/actors/restore_validator_actor.cpp, cloud/blockstore/libs/storage/disk_registry/actors/restore_validator_actor_ut.cpp, cloud/blockstore/libs/storage/volume/actors/shadow_disk_actor.cpp, cloud/blockstore/libs/storage/volume/volume_ut_checkpoint.cpp
When restoring from backup, shadow disks are deleted, this is normal, since the backup may be old.
1. corrected the warning message
2. The shadow disk in the volume will immediately go into error state as soon as there disk registry restarted
=> FIx restoration shadow disk from backup

cloud/filestore/libs/daemon/vhost/bootstrap.cpp, cloud/filestore/libs/service_local/config.cpp, cloud/filestore/libs/service_local/service.cpp, cloud/filestore/libs/vfs_fuse/loop.cpp, cloud/storage/core/libs/aio/service.cpp, cloud/storage/core/libs/aio/service.h
#2806 
Additionally dispatch async read/write into thread pool and increase default
number of worker threads to 8
=> [Filestore] issue-2806: support multiple aio engines in local filestore

cloud/filestore/libs/service_local/index.h, cloud/filestore/libs/service_local/index_ut.cpp
=> [Filestore] issue-2865: discard deleted nodes when recovering existing local filestore session

cloud/filestore/libs/storage/model/ut/ya.make
`Error[-WBadDir]: in $S/cloud/filestore/libs/storage/model/ut/ya.make: DEPENDS to missing directory: $S/cloud/filestore/libs/storage/model/ut/ut`
=> [Filestore] Remove unused  RECURSE_FOR_TESTS

contrib/libs/grpc/src/core/lib/iomgr/tcp_client_posix.cc
backport https://github.com/grpc/grpc/pull/35064
probably related to e2e tests failures: https://github-actions-s3.storage.eu-north1.nebius.cloud/ydb-platform/nbs/PR-check/13010898098/1/nebius-x86-64/test_data/actions-runner/_work/nbs/nbs/cloud/blockstore/tests/csi_driver/e2e_tests_part1/test-results/py3test/testing_out_stuff/test.py__test_publish_volume_twice_on_the_same_node[mount-True]/ydbd_output.log
=> issue-2765: backport grpc pr #35064

cloud/blockstore/libs/storage/partition/part_actor_readblob.cpp, cloud/blockstore/libs/storage/partition/part_actor_writeblob.cpp, cloud/blockstore/libs/storage/partition2/part2_actor_readblob.cpp, cloud/blockstore/libs/storage/partition2/part2_actor_writeblob.cpp
Increase logging verbosity: include group ID in (Read|Write)Blob logs
This is useful when multiple partition tablets fail due to corresponding groups failure because it allows to indicate number of unique failing groups
=> [NBS] Increase logging verbosity: include group ID

cloud/blockstore/libs/storage/partition/part_ut.cpp
If we write blocks not exceeded threshold and batching mode is enabled part of data can be written to mixed channel directly so need to check this scenario in UTs.
=> Improve UTs to check mixed/fresh blocks when write batching is enabled; add ShouldBatchSmallWritesToFreshChannelIfThresholdNotExceeded test

cloud/blockstore/config/disk.proto, cloud/blockstore/libs/storage/core/proto_helpers.cpp, cloud/blockstore/libs/storage/core/proto_helpers.h, cloud/blockstore/libs/storage/disk_agent/actors/io_request_parser.cpp, cloud/blockstore/libs/storage/disk_agent/actors/io_request_parser.h, cloud/blockstore/libs/storage/disk_agent/disk_agent_actor.cpp, cloud/blockstore/libs/storage/disk_agent/disk_agent_actor.h, cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_init.cpp, cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_io.cpp, cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_ut.cpp, cloud/blockstore/libs/storage/disk_agent/disk_agent_private.h, cloud/blockstore/libs/storage/disk_agent/disk_agent_state.cpp, cloud/blockstore/libs/storage/disk_agent/disk_agent_state.h, cloud/blockstore/libs/storage/disk_agent/hash_table_storage.cpp, cloud/blockstore/libs/storage/disk_agent/model/config.cpp, cloud/blockstore/libs/storage/disk_agent/model/config.h, cloud/blockstore/libs/storage/disk_agent/testlib/test_env.cpp, cloud/blockstore/tests/python/lib/config.py, cloud/blockstore/tests/python/lib/nonreplicated_setup.py
#2277
Aio has a buffer alignment requirement. To meet this requirement, TStorageAdapter [allocates an additional buffer and copies the data from the request into it](https://github.com/ydb-platform/nbs/blob/main/cloud/blockstore/libs/service/storage.cpp#L434-L442). The copying takes place in a single TDiskAgentActor thread, which creates scalability issues.
In order to improve scalability, the allocation and copying of data has been moved to the IORequestParserActor.
=> issue-2277: move copying of the request buffer to TIORequestParserActor

cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_migration.cpp
=> Issue 2404: mv WrongMigratedDeviceOwnership critical event to AddMigration Function

cloud/blockstore/tools/testing/eternal_tests/eternal-load/lib/ut/ya.make
```
2025-02-03 11:02:17,774 - INFO - ya.test - pytest_runtest_setup: ####################################################################################################
2025-02-03 11:02:17,775 - INFO - ya.test - pytest_runtest_setup: test_load_fails
2025-02-03 11:02:17,775 - INFO - ya.test - pytest_runtest_setup: ####################################################################################################
2025-02-03 11:02:17,775 - INFO - ya.test - pytest_runtest_setup: Test setup
2025-02-03 11:02:17,777 - INFO - ya.test - pytest_runtest_call: Test call (class_name: test.py, test_name: test_load_fails)
2025-02-03 11:02:17,778 - DEBUG - ya.test - get_binary: Binary was found by /home/github/.ya/build/build_root/m4op/00084b/cloud/blockstore/tools/testing/eternal_tests/eternal-load/bin …
```
=> Make eternal_tests/eternal-load/lib/ut medium as it uses local disk and sometimes hits the 30 sec deadline

cloud/blockstore/libs/service_local/ut/ya.make
```
Traceback (most recent call last):
File "library/python/testing/yatest_common/yatest/common/process.py", line 384, in wait
wait_for(
File "library/python/testing/yatest_common/yatest/common/process.py", line 764, in wait_for
raise TimeoutError(truncate(message, MAX_MESSAGE_LEN))
yatest.common.process.TimeoutError: 180 second(s) wait timeout has expired: Command '['/home/github/.ya/tools/v4/5571992960/test_tool3', 'run_ut', '@/home/github/.ya/build/build_root/6c7f/000e44/cloud/blockstore/libs/service_local/ut/test-results/unittest/chunk0/testing_out_stuff/test_tool.args']' stopped by 180 seconds timeout
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "devtools/ya/test/programs/test_tool/run_test/run_test.py", line 1732, in …
```
=> Replace 180 sec timeout for TAioStorageTest with default 600 sec timeout as the test uses disk and sometimes hits the deadline

cloud/disk_manager/internal/pkg/facade/snapshot_service_test/snapshot_service_test.go, cloud/disk_manager/internal/pkg/facade/testcommon/common.go
https://github.com/ydb-platform/nbs/issues/2008
Turning off some checkpoint disk manager checks that would be influenced by future changes in StatVolume logic
=> [Disk Manager] Turn off disk manager tests influenced by StatVolume

cloud/blockstore/libs/storage/volume/volume_actor_statvolume.cpp, cloud/blockstore/libs/storage/volume/volume_ut_checkpoint.cpp
https://github.com/ydb-platform/nbs/issues/2008 — Исправлено поведение StatVolume. Теперь он возвращает и чекпоинты с данными, и чекпоинты без данных
=> [Blockstore] StatVolume should return checkpoints without data

cloud/filestore/libs/storage/core/model.cpp, cloud/filestore/libs/storage/core/model_ut.cpp, cloud/filestore/libs/storage/service/service_ut_sharding.cpp
References #1932
Currently a shard of 5TiB is created per each 4TiB in the filesystem (rounding the number of shards down). So if the filesystem is the size of 7TiB, only one shard of size 5TiB will be created. In this PR rounding down is replaced with rounding up.
=> issue-1932: use ceil instead of floor for calculating shards count

cloud/blockstore/libs/storage/init/disk_agent/actorsystem.cpp, cloud/blockstore/libs/storage/init/server/actorsystem.cpp, cloud/filestore/libs/storage/init/actorsystem.cpp, cloud/storage/core/libs/hive_proxy/hive_proxy.cpp, cloud/storage/core/libs/hive_proxy/hive_proxy.h, cloud/storage/core/libs/hive_proxy/hive_proxy_actor.cpp, cloud/storage/core/libs/hive_proxy/hive_proxy_actor.h, cloud/storage/core/libs/hive_proxy/hive_proxy_ut.cpp, cloud/storage/core/libs/hive_proxy/ya.make
=> issue-2969: add hive reconnect time counter

cloud/blockstore/tools/testing/eternal_tests/eternal-load/bin/tests/test.py
```
2025-02-05 01:52:08,814 - INFO - ya.test - pytest_collection_modifyitems: Modulo 0 tests are: [[<Function test_load_fails>]]
2025-02-05 01:52:08,817 - INFO - ya.test - pytest_runtest_setup: ####################################################################################################
2025-02-05 01:52:08,817 - INFO - ya.test - pytest_runtest_setup: test_load_fails
2025-02-05 01:52:08,817 - INFO - ya.test - pytest_runtest_setup: ####################################################################################################
2025-02-05 01:52:08,817 - INFO - ya.test - pytest_runtest_setup: Test setup
2025-02-05 01:52:08,818 - INFO - ya.test - pytest_runtest_call: Test call (class_name: test.py, test_name: test_load_fails)
2025-02-05 01:52:08,819 - DEBUG - ya.test - get_binary: …
```
=> Fix eternal_tests/eternal-load/bin/tests/test_load_fails: don't use 30 sec timeout when running eternal-load, use default suite timeout instead

cloud/blockstore/apps/client/lib/command_ut.cpp, cloud/blockstore/apps/client/lib/read_blocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_readblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor_readblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/ut_env.h, cloud/blockstore/public/api/protos/headers.proto
In order to provide better diagnostics for checksum mismatches in replicas, I want to add the ability for blockstore-client to read certain replica and compare it further in scripts
=> issue-2722: add ability to read from certain replica of mirrored disk

cloud/filestore/libs/storage/service/service_actor_readdata.cpp
=> fix issues found by coverity and delete some useless std::move

cloud/blockstore/libs/encryption/encryption_client.cpp, cloud/blockstore/libs/encryption/encryption_client_ut.cpp, cloud/blockstore/libs/encryption/encryption_key.cpp, cloud/blockstore/libs/encryption/encryption_key_ut.cpp, cloud/blockstore/libs/encryption/encryption_service_ut.cpp, cloud/blockstore/libs/storage/service/service_actor_create.cpp, cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp, cloud/blockstore/libs/storage/volume/volume_state.cpp, cloud/blockstore/libs/storage/volume/volume_state_ut.cpp, cloud/blockstore/public/api/protos/encryption.proto, cloud/blockstore/public/sdk/python/client/safe_client.py, cloud/blockstore/public/sdk/python/client/ya.make, cloud/blockstore/tests/encryption_at_rest/test.py, cloud/blockstore/vhost-server/server_ut.cpp
#176
Now one can create a disk with encryption at rest by specifying `ENCRYPTION_AT_REST` mode in the create request.
=> issue-176: create an encrypted disk via EncryptionSpec

cloud/filestore/libs/storage/tablet/tablet_actor_renamenode.cpp
Разобрались что вызов UnlockNodeRef после вызова транзакции не нужен
=> fix coverity issue

cloud/filestore/tests/recipes/vhost-endpoint.inc, cloud/filestore/tests/recipes/vhost-endpoint/__main__.py, cloud/storage/core/tools/testing/qemu/lib/common.py, cloud/storage/core/tools/testing/qemu/lib/recipe.py
=> issue-1751: add ability to run several qemu with mounted filestore in test recipes; extract ssh client to lib from qemu recipe

.clang-format
С такими настройками clang format не портит необратимо наши макросы xxx()
=> Fix clang format for xxx macros

cloud/blockstore/libs/endpoints/endpoint_manager.cpp, cloud/blockstore/tests/e2e-tests/test.py
issue: #3017
blockstore-server must restore endpoints despite of missing endpoint directory. e.g. directory can be removed after host reboot if directory was mounted as tmpfs.
=> issue-3017: restore endpoints despite of missing socket directory

cloud/disk_manager/internal/pkg/clients/nbs/tests/ya.make
Tests on blockstore client might run out of devices and fail with E_DISK_ALLOCATION_FAILED.
In order to prevent this, incresae number of disk agents used in these tests.
=> [Disk Manager] use more disk agents in blockstore client tests

cloud/storage/core/libs/grpc/init.cpp, cloud/storage/core/libs/grpc/init_ut.cpp
A race condition occurs during gRPC shutdown when using a [dedicated](https://github.com/ydb-platform/nbs/blob/main/contrib/libs/grpc/src/core/lib/surface/init.cc#L200-L203) thread: the [TTempBufManager](https://github.com/ydb-platform/nbs/blob/main/util/memory/tempbuf.cpp#L152-L163) singleton (used by the logger: [TLog](https://github.com/ydb-platform/nbs/blob/main/library/cpp/logger/log.h#L98), [TLogElement](https://github.com/ydb-platform/nbs/blob/main/library/cpp/logger/element.h#L14), [TTempBufOutput](https://github.com/ydb-platform/nbs/blob/main/util/stream/tempbuf.h#L7), [TTempBuf](https://github.com/ydb-platform/nbs/blob/main/util/memory/tempbuf.cpp#L174)) may be deleted or in the process of deletion.
<details><summary>Logs</summary>
2025-02-12T03:31:34.221545Z :GRPC INFO: …
=> Fix race condition during gRPC shutdown

cloud/blockstore/libs/daemon/ydb/bootstrap.cpp, cloud/blockstore/libs/storage/init/server/actorsystem.cpp, cloud/blockstore/libs/storage/init/server/actorsystem.h, cloud/storage/core/libs/hive_proxy/hive_proxy_ut.cpp
#2947 показалось странным, что временный сервер тоже бэкапит информацию о таблетках. Плюс это может помешать во время рестарта при прогреве соедений в задачке #2947
#2100
=> issue-2947: don't backup tablet info in temporary server

cloud/disk_manager/internal/pkg/dataplane/url/common/http_client_test.go
```
2025-02-14T02:09:00.903Z	DEBUG	common/http_client.go:191	Sending http get header request to "http://127.0.0.1:42951"	{"SYSLOG_IDENTIFIER": "disk-manager"}
2025-02-14T02:09:00.903Z	DEBUG	go-retryablehttp/client.go:597	performing request, [method HEAD url http://127.0.0.1:42951]:	{"SYSLOG_IDENTIFIER": "disk-manager", "SYSLOG_IDENTIFIER": "disk-manager"}
2025-02-14T02:09:00.905Z	ERROR	go-retryablehttp/client.go:654	request failed, [error Head "http://127.0.0.1:42951": context deadline exceeded (Client.Timeout exceeded while awaiting headers) method HEAD url http://127.0.0.1:42951]:	{"SYSLOG_IDENTIFIER": "disk-manager", "SYSLOG_IDENTIFIER": "disk-manager"}
2025-02-14T02:09:00.905Z	DEBUG	go-retryablehttp/client.go:698	retrying request, [request HEAD http://127.0.0.1:42951 timeout 1ms …
```
=> Fix cloud/disk_manager/internal/pkg/dataplane/url/common.TestHTTPClientTimeout

cloud/blockstore/libs/storage/core/compaction_map.cpp
Benchmark results for disk with size 100_TB
before changes:
| Benchmark | Time | CPU |
|--------|--------|--------|
| BenchmarkUpdate_100_TB | 1.3232e+10 ns | 1.3232e+10 ns |
after changes:
| Benchmark | Time | CPU |
|--------|--------|--------|
| BenchmarkUpdate_100_TB | 7694792291 ns | 7694446694 ns |
As next step need to think about asynchronous loading compaction map.
=> Fill GarbageByScore, GroupByGarbageBlockCount once when compaction map is loaded

cloud/blockstore/libs/storage/volume/volume_ut_checkpoint.cpp, cloud/disk_manager/internal/pkg/dataplane/snapshot/storage/mocks/storage_mock.go, cloud/disk_manager/internal/pkg/dataplane/snapshot/storage/storage.go, cloud/disk_manager/internal/pkg/dataplane/snapshot/storage/storage_legacy.go, cloud/disk_manager/internal/pkg/dataplane/snapshot/storage/storage_ydb.go, cloud/disk_manager/internal/pkg/dataplane/snapshot/storage/storage_ydb_impl.go, cloud/disk_manager/internal/pkg/dataplane/snapshot/storage/storage_ydb_test.go, cloud/disk_manager/internal/pkg/facade/image_service_test/image_service_test.go, cloud/disk_manager/internal/pkg/facade/snapshot_service_test/snapshot_service_test.go, cloud/disk_manager/internal/pkg/facade/testcommon/common.go
https://github.com/ydb-platform/nbs/issues/2008 — Fixed Dm tests, that depend on StatVolume.
=> [Disk Manager] Fix disk manager tests after updating StatVolume behaviour

cloud/blockstore/libs/storage/model/requests_in_progress.h, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_mirror.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_readblocks.cpp
Для задачи #2854 в пре #2943 нужно распиливать один запрос на несколько и посылать обратно в TMirrorPartitionActor, чтобы распиливать запросы надо сделать так, чтобы идентификация запроса происходила не по кукам
=> issue-2854: rm request ident by cookie at part mirror actor

cloud/filestore/tests/fio_index/qemu-kikimr-multishard-tablets-restart-test/ya.make
For failure like this: https://github-actions-s3.storage.eu-north1.nebius.cloud/ydb-platform/nbs/Nightly-build-(ubsan)/13191220677/1/nebius-x86-64-ubsan/summary/ya-test.html#FAIL
=> [Filestore] increase verbosity of fio_index/qemu-kikimr-multishard-tablets-restart-test

cloud/storage/core/libs/hive_proxy/hive_proxy_ut.cpp
ShouldRejectLookupEventsOnPipeReset test frequently flaps
`[fail] THiveProxyTest::ShouldRejectLookupEventsOnPipeReset [default-linux-x86_64-relwithdebinfo] (0.27s)
assertion failed at cloud/storage/core/libs/hive_proxy/hive_proxy_ut.cpp:1491, virtual void NCloud::NStorage::NTestSuiteTHiveProxyTest::TTestCaseShouldRejectLookupEventsOnPipeReset::Execute_(NUnitTest::TTestContext &): (receivedlookupCount == 2) failed: (3 != 2) 
Get at /-S/util/generic/ptr.h:579:16
~TStringBuilder at /-S/util/string/builder.h:8:11
NCloud::NStorage::NTestSuiteTHiveProxyTest::TCurrentTest::Execute()::'lambda'()::operator()() const at /-S/cloud/storage/core/libs/hive_proxy/hive_proxy_ut.cpp:0:1
~__value_func at /-S/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:395:16
UnRef at …
=> fix flapping test

cloud/filestore/libs/server/server_ut.cpp
Not enough logs:
```
2025-02-20T01:40:21.749759Z :NFS_SERVER INFO: cloud/filestore/libs/server/server.cpp:1197: Start listening on insecure localhost:8872
2025-02-20T01:40:21.749810Z :NFS_SERVER INFO: cloud/filestore/libs/server/server.cpp:1203: Listen on (secure control) localhost:21571
2025-02-20T01:40:22.417055Z :NFS_CLIENT INFO: cloud/filestore/libs/client/client.cpp:755: Connect to localhost:8872
2025-02-20T01:40:22.417926Z :NFS_CLIENT INFO: cloud/filestore/libs/client/client.cpp:755: Connect to localhost:21571
2025-02-20T01:40:22.901876Z :NFS_SERVER INFO: cloud/filestore/libs/server/server.cpp:1258: Shutting down
2025-02-20T01:40:22.908179Z :NFS_CLIENT INFO: cloud/filestore/libs/client/client.cpp:630: Shutting down
2025-02-20T01:40:22.909100Z :NFS_CLIENT INFO: …
```
=> [Filestore] add gRPC logs for TServerTest to investigate problem with ShouldHandleAuthRequestsWithMultipleCertificates test

cloud/disk_manager/internal/pkg/clients/nbs/tests/client_test.go, cloud/disk_manager/test/recipe/nbs_launcher.py
Add test for methods of blockstore clients concerning placements groups.
Also add ability to check errors from blockstore clients more strictly.
This should unblock the pr https://github.com/ydb-platform/nbs/pull/2980#discussion_r1952452737
=> [Disk Manager] add tests on placement groups for blockstore client

cloud/blockstore/libs/daemon/common/bootstrap.cpp, cloud/blockstore/libs/endpoint_proxy/server/bootstrap.cpp, cloud/blockstore/libs/endpoint_proxy/server/options.cpp, cloud/blockstore/libs/endpoint_proxy/server/options.h, cloud/blockstore/libs/endpoint_proxy/server/server.cpp, cloud/blockstore/libs/endpoint_proxy/server/server.h, cloud/blockstore/libs/endpoint_proxy/server/server_ut.cpp, cloud/blockstore/libs/nbd/netlink_device.cpp, cloud/blockstore/libs/nbd/netlink_device.h, cloud/blockstore/tests/python/lib/endpoint_proxy.py, cloud/blockstore/tools/nbd/bootstrap.cpp, cloud/storage/core/libs/netlink/message.cpp, cloud/storage/core/libs/netlink/message.h, cloud/storage/core/libs/netlink/socket.cpp, cloud/storage/core/libs/netlink/socket.h
issue: #2869
1. Implement NetlinkDevice without using libnl
2. Add WithoutLibnl option to endpoint_proxy
=> issue-2869: implement netlink_device without libnl

cloud/blockstore/libs/storage/volume/volume_actor.cpp
TEvAcquireDiskIfNeeded is [scheduled](https://github.com/ydb-platform/nbs/blob/main/cloud/blockstore/libs/storage/volume/volume_actor_addclient.cpp#L140-L143) every 4s, there is a chance that the volume gets TEvAcquireDiskIfNeeded already in a zombie state:
```
VERIFY failed (2025-02-23T03:22:35.229069Z): [BLOCKSTORE_VOLUME] Unexpected event: (0x10620144) NCloud::NBlockStore::TRequestEvent<NCloud::NBlockStore::NStorage::TEvVolumePrivate::TAcquireDiskIfNeeded, 274858308u>
cloud/storage/core/libs/actors/helpers.cpp:39
HandleUnexpectedEvent(): requirement false failed
```
=> ignore TEvVolumePrivate::TEvAcquireDiskIfNeeded in zombie state

cloud/disk_manager/internal/pkg/clients/nbs/client.go, cloud/disk_manager/internal/pkg/clients/nbs/tests/client_test.go
Before this fix, all error from blockstore with codes E_PRECONDITION_FAILED and E_RESOURCE_EXHAUSTED were treated as public. This is too wide range of errors to treat them all as public.
=> [Disk Manager] errors from blockstore should be internal by default

cloud/blockstore/config/storage.proto, cloud/blockstore/libs/daemon/common/bootstrap.cpp, cloud/blockstore/libs/daemon/common/bootstrap.h, cloud/blockstore/libs/daemon/local/bootstrap.cpp, cloud/blockstore/libs/daemon/local/bootstrap.h, cloud/blockstore/libs/daemon/ydb/bootstrap.cpp, cloud/blockstore/libs/daemon/ydb/bootstrap.h, cloud/blockstore/libs/storage/core/config.cpp, cloud/blockstore/libs/storage/core/config.h, cloud/blockstore/libs/storage/ss_proxy/path_description_backup.cpp, cloud/storage/core/libs/api/hive_proxy.h, cloud/storage/core/libs/hive_proxy/hive_proxy_actor.cpp, cloud/storage/core/libs/hive_proxy/hive_proxy_events_private.h, cloud/storage/core/libs/hive_proxy/hive_proxy_fallback_actor.cpp, cloud/storage/core/libs/hive_proxy/hive_proxy_ut.cpp, cloud/storage/core/libs/hive_proxy/tablet_boot_info_backup.cpp, cloud/storage/core/libs/hive_proxy/tablet_boot_info_backup.h, cloud/storage/core/libs/ss_proxy/path_description_backup.cpp
#2947
Провели пару замеров на проде и прогрев соеденений дал улучшение в пару секунд для максимального летенси на пользовательской стороне во время рестарта. 
Уже есть тест cloud/blockstore/tests/loadtest/local-emergency/test.py который делает BackupTabletBootInfos и затем рестартит nbs, поэтому наш случай уже покрыт тестами.
=> issue-2947: add BS group connections warmup on process startup

cloud/filestore/libs/storage/tablet/model/blob.h, cloud/filestore/libs/storage/tablet/rebase_logic.cpp, cloud/filestore/libs/storage/tablet/rebase_logic.h, cloud/filestore/libs/storage/tablet/rebase_logic_ut.cpp, cloud/filestore/libs/storage/tablet/tablet_actor.cpp, cloud/filestore/libs/storage/tablet/tablet_actor_addblob.cpp, cloud/filestore/libs/storage/tablet/tablet_state.h, cloud/filestore/libs/storage/tablet/tablet_state_data.cpp, cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp
The amount of garbage blocks in filesystem statistics consistently exceeds the garbage compaction threshold.
It was found that the deletion of blocks in a range does not result in marking the deleted blocks as garbage, therefore such ranges have zero score and are not subject for compaction.
#3061
The issue is resolved in this PR by the following approach:
1. Garbage block count is now increased in the cleanup operation.
2. The condition `compactionScore > 1` was removed for blocks to be compacted by garbage threshold.
=> [Filestore] issue-3061: blocks with garbage should be compacted after cleanup

cloud/storage/core/libs/diagnostics/task_stats_fetcher.cpp
cpu_delay_total is cumulative delay in nanoseconds: https://github.com/torvalds/linux/blob/master/Documentation/accounting/taskstats-struct.rst?plain=1#L106
=> issue-1444: fix conversion from nanoseconds

cloud/filestore/libs/storage/tablet/tablet_actor.cpp
Same as https://github.com/ydb-platform/nbs/pull/2653
Failure seen here: https://github-actions-s3.storage.eu-north1.nebius.cloud/ydb-platform/nbs/PR-check/13508037474/1/nebius-x86-64/summary/ya-test.html#FAIL
=> [Filestore] fix qemu-kikimr-multishard-tablets-restart-test test: handle TFlushBytesResponse in the zombie state

cloud/storage/core/libs/diagnostics/task_stats_fetcher.cpp
Specify tgid attribute to request stats for all threads
https://docs.kernel.org/accounting/taskstats.html
> To get statistics during a task's lifetime, userspace opens a unicast netlink socket (NETLINK_GENERIC family) and sends commands specifying a pid or a tgid. The response contains statistics for a task (if pid is specified) or the sum of statistics for all tasks of the process (if tgid is specified).
=> issue-1444: request stats for tgid

cloud/blockstore/libs/storage/volume/volume_ut.cpp, cloud/blockstore/public/api/protos/headers.proto
https://github.com/ydb-platform/nbs/issues/3058
В поле VolumeRequestId должно ехать два uint32: поколение таблетки волума и номер запроса. Из-за опечатки поколение таблетки отбрасывалось и становилось нулём.
=> [NBS] Fix NRD strict write ordering feature

cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_migration.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_mirrored_disks.cpp
=> Issue 2973: add different notification levels to publish migration states for mirror disks

cloud/blockstore/libs/storage/core/compaction_map.cpp, cloud/blockstore/libs/storage/core/compaction_map.h, cloud/blockstore/libs/storage/core/compaction_map_ut.cpp, cloud/blockstore/libs/storage/partition/part_actor_compaction.cpp, cloud/blockstore/libs/storage/partition/part_actor_compactrange.cpp, cloud/blockstore/libs/storage/partition/part_events_private.h, cloud/blockstore/libs/storage/partition/part_state.h, cloud/blockstore/libs/storage/partition/part_ut.cpp
The value of processed ranges for monitoring, as well as the index of the next range, were incremented by 1 instead of ForcedCompactionRangeCountPerRun. As a result, we were processing each range several times and displaying incorrect values in the monitoring.
=> Fixed the use of the parameter ForcedCompactionRangeCountPerRun

cloud/blockstore/libs/endpoints/endpoint_manager.cpp, cloud/filestore/libs/endpoint/endpoint_manager.cpp, cloud/filestore/libs/endpoint/endpoint_manager_ut.cpp
1. create all directories for socket
2. skip exist check as Mkdirs has the same check inside.
=> issue-3017: create all directories for unix socket before restoring endpoint

cloud/filestore/libs/storage/tablet/tablet_actor_addblob.cpp, cloud/filestore/libs/storage/tablet/tablet_ut_counters.cpp, cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp, cloud/filestore/libs/storage/tablet/tablet_ut_data_stress.cpp
Incrementing GarbageBlocksCount when writing new data unnecessary triggers compaction operation.
https://github.com/ydb-platform/nbs/issues/3061
=> [Filestore] Do not increment garbage blocks count when writing new blobs

cloud/blockstore/libs/service_local/compound_storage.cpp, cloud/blockstore/libs/storage/partition_nonrepl/config.h, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_readblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_split_read_blocks_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_split_request_helpers.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_split_request_helpers.h, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_split_request_helpers_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_state.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_state.h, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/ut/ya.make, cloud/blockstore/libs/storage/partition_nonrepl/ya.make, cloud/blockstore/tests/loadtest/local-mirror/local-mirror2-split-read-column.txt, cloud/blockstore/tests/loadtest/local-mirror/local-mirror2-split-read-cross.txt, cloud/blockstore/tests/loadtest/local-mirror/test.py, cloud/blockstore/tools/testing/loadtest/lib/control_plane_action_runner.cpp, cloud/blockstore/tools/testing/loadtest/lib/control_plane_action_runner.h, cloud/blockstore/tools/testing/loadtest/protos/loadtest.proto, cloud/storage/core/libs/common/sglist_block_range.cpp, cloud/storage/core/libs/common/sglist_block_range.h, cloud/storage/core/libs/common/ya.make
#2854 
На самом деле проблема возникает в следующей конфигурации
```
┌───────────────────────────────┐
│ uuid-1 (Fresh)   │ uuid-3           
│──────────────────┼────────────│
│ uuid-2 (Fresh)   │ uuid-4   
└───────────────────────────────┘
```
Это происходит из-за  изменений в ReplicasInfo, которые происходят при налитии свежих девайсов в этой функции https://github.com/ydb-platform/nbs/blob/8dd237560b9179b8f6c238d51c70cc2fa12eaf1d/cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_state.cpp#L129
Из-за этого в тестах TMirrorPartitionTest::ShouldTryToSplitReadRequest
и в https://github.com/ydb-platform/nbs/blob/9686d14430d09ce06590bf2cafe60679f7547742/cloud/blockstore/tests/loadtest/local-mirror/test.py#L87-L103
Пришлось перебрать разные топологии свежих девайсов из-за изменений …
=> Issue 2854: add split read request in mirror partition by device borders

cloud/blockstore/libs/storage/partition_nonrepl/config.h, cloud/blockstore/libs/storage/partition_nonrepl/lagging_agents_replica_proxy_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/migration_timeout_calculator_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_lagging_devices_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_state_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/resync_range_ut.cpp, cloud/blockstore/libs/storage/volume/actors/shadow_disk_actor.cpp, cloud/blockstore/libs/storage/volume/volume_actor_lagging_agents.cpp, cloud/blockstore/libs/storage/volume/volume_actor_startstop.cpp
#3
Изменений в логике нет. 
Переделываю инициализацию `TNonreplicatedPartitionConfig` через структуру чтобы не править все конструирования в кодовой базе при добавлении параметра
=> Initialize PartConfig with params struct

cloud/filestore/config/storage.proto, cloud/filestore/libs/storage/core/config.cpp, cloud/filestore/libs/storage/core/config.h, cloud/filestore/libs/storage/tablet/tablet_actor.cpp, cloud/filestore/libs/storage/tablet/tablet_actor_setnodeattr.cpp, cloud/filestore/libs/storage/tablet/tablet_actor_truncate.cpp, cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp, cloud/filestore/tests/common_configs/nfs-storage-newfeatures-patch.txt, doc/filestore/design/storage/config.md
Initially, the condition for running cleanup was based on the average number of deletion markers per used range without taking sparsity into account. It could lead to the situation when the ranges are not cleaned because the number of deletion markers is low despite the fact that the ratio between the number of deletion markers and the number of used blocks is very high.
The new condition is based on the average number of deletion markers per used block. For the compatibility with the old condition, the number of blocks is converted to the number of ranges taking the assumption that the ranges are fully filled.
Also, a condition for running cleanup is added after truncation operations.
https://github.com/ydb-platform/nbs/issues/3061
=> [Filestore] Change cleanup trigger condition based on UsedBlocks instead of UsedRanges

cloud/disk_manager/test/recipe/__main__.py, cloud/disk_manager/test/recipe/common.py, cloud/disk_manager/test/recipe/ya.make, cloud/disk_manager/test/snapshot_migration_test/test.py
Should handle exception when search for ydb binary path with yatest_common.binary_path.
```
yatest_lib.ya.TestMisconfigurationException: Cannot find binary '['cloud/storage/core/tools/testing/ydb/bin/ydbd']': make sure it was added in the DEPENDS section
```
This binary should not be found if we build without OPENSOURCE option https://github.com/ydb-platform/nbs/blob/main/cloud/disk_manager/test/snapshot_migration_test/ya.make#L62. The problem was the following: yatest_common.binary_path might throw exception instead of returning None.
=> [Disk Manager] fix ydb binary path

cloud/blockstore/libs/storage/partition_nonrepl/config.h, cloud/blockstore/libs/storage/partition_nonrepl/lagging_agents_replica_proxy_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_lagging_devices_ut.cpp, cloud/blockstore/libs/storage/volume/volume_actor.h, cloud/blockstore/libs/storage/volume/volume_actor_lagging_agents.cpp, cloud/blockstore/libs/storage/volume/volume_actor_startstop.cpp
=> Pass lagging devices toggle to nonrepl partition

cloud/blockstore/tools/csi_driver/internal/driver/node.go
It's not possible to receive success response with empty device name if request contains "UseFreeNbdDevice" parameter
=> issue-2270: remove device name checks

cloud/disk_manager/internal/pkg/facade/disk_service_test/disk_service_test.go
In line 665, we create another 'err' variable because of ':='. So the value of err from line 668 was never checked.
=> [Disk Manager] fix error check in disk service test

cloud/blockstore/config/storage.proto, cloud/blockstore/libs/storage/core/config.cpp, cloud/blockstore/libs/storage/core/config.h, cloud/blockstore/libs/storage/core/proto_helpers.cpp, cloud/blockstore/libs/storage/core/proto_helpers.h, cloud/blockstore/libs/storage/core/proto_helpers_ut.cpp, cloud/blockstore/libs/storage/volume/volume_actor_throttling.cpp
#3129 
Filesystem can be mounted with discard option:
```
discard
If set, causes discard/TRIM commands to be issued to the block
device when blocks are freed. This is useful for SSD devices
and sparse/thinly-provisioned LUNs.
```
As a result, we see spikes in zero block requests, leading to throttling of all write requests and causing users to experience disk hangs.
In this pull request I introduced config parameter to disable throttling of zero blocks requests.
=> issue-3129: Add flag to enable/disable throttling of zero block requests

cloud/blockstore/tools/csi_driver/cmd/nbs-csi-driver/main.go, cloud/blockstore/tools/csi_driver/internal/driver/controller.go, cloud/blockstore/tools/csi_driver/internal/driver/driver.go, cloud/blockstore/tools/csi_driver/internal/driver/helper.go, cloud/blockstore/tools/csi_driver/internal/driver/node.go, cloud/blockstore/tools/csi_driver/internal/driver/node_test.go, cloud/blockstore/tools/csi_driver/internal/driver/ya.make
https://github.com/ydb-platform/nbs/issues/3129
=> [CSI] Enable discard mount option only for YDB-based disks

cloud/filestore/libs/service/request.cpp
=> Issue 3127: fixing log truncation

cloud/blockstore/libs/storage/volume/volume_database.cpp
Баг в  https://github.com/ydb-platform/nbs/pull/3147
```
=================================================================
==217357==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7f6a2a7e8740 at pc 0x000025757d75 bp 0x7ffce022e490 sp 0x7ffce022e488
READ of size 8 at 0x7f6a2a7e8740 thread T0
warning: address range table at offset 0x30 has a premature terminator entry at offset 0x40
warning: address range table at offset 0x60 has a premature terminator entry at offset 0x70
warning: address range table at offset 0x90 has a premature terminator entry at offset 0xa0
warning: address range table at offset 0xc0 has a premature terminator entry at offset 0xd0
warning: address range table at …
```
=> Fix use-after-free

cloud/blockstore/libs/storage/partition_nonrepl/config.h, cloud/blockstore/libs/storage/partition_nonrepl/migration_timeout_calculator.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_base_request.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_base_request.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_checksumblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_readblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_readblocks_local.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_writeblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_zeroblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_ut.cpp
#3
В этом ПРе партишн отслеживает что девайс долго не отвечал и делает запрос в Volume `TEvDeviceTimeoutedRequest`.
Когда Volume ответил что агент недоступен, партишн отменяет все активные запросы. Скорее всего они и так не ответят. А поретраив мы быстрее их завершим об другие реплики.
=> Allow nonreplicated partition to timeout devices

cloud/filestore/tests/recipes/service-kikimr/__main__.py
The tests for _cloud/filestore/tests/auth/new/vhost_, _cloud/filestore/tests/auth/old/vhost_ and _cloud/filestore/tests/endpoints_, as well as other tests, failed because the JSON parser expected a string from the NFS_RESTART_INTERVAL value.
```
RecipeStartUpError: vhost-recipe-3 failed
Stderr tail:estore/tests/recipes/vhost/__main__.py", line 149, in start
wait_for_filestore_vhost(filestore_vhost, vhost_configurator.port)
File "contrib/python/retrying/py3/retrying.py", line 56, in wrapped_f
return Retrying(*dargs, **dkw).call(f, *args, **kw)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "contrib/python/retrying/py3/retrying.py", line 257, in call
return attempt.get(self._wrap_exception)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "contrib/python/retrying/py3/retrying.py", line 301, in get …
```
=> [Filestore] vhost bug fix

contrib/ydb/library/yql/minikql/comp_nodes/ut/ya.make.inc, contrib/ydb/library/yql/minikql/comp_nodes/ya.make.inc, contrib/ydb/library/yql/minikql/perf/mprefetch/ya.make
-mprfchw makes unused compiled param warning -> error when building for arm
=> Fix build for arm

contrib/libs/ibdrv/symbols.cpp
Actual names depend on arch:
/usr/lib/x86_64-linux-gnu/libibverbs.so.1
/usr/lib/x86_64-linux-gnu/librdmacm.so.1
/usr/lib/x86_64-linux-gnu/libmlx5.so.1
/usr/lib/aarch64-linux-gnu/libibverbs.so.1
/usr/lib/aarch64-linux-gnu/librdmacm.so.1
/usr/lib/aarch64-linux-gnu/libmlx5.so.1
=> Fix dynamic libs names

cloud/blockstore/config/storage.proto, cloud/blockstore/libs/daemon/ydb/bootstrap.cpp, cloud/blockstore/libs/disk_agent/bootstrap.cpp, cloud/blockstore/libs/storage/core/config.cpp, cloud/blockstore/libs/storage/core/config.h, cloud/filestore/config/storage.proto, cloud/filestore/libs/daemon/common/bootstrap.cpp, cloud/filestore/libs/storage/core/config.cpp, cloud/filestore/libs/storage/core/config.h, cloud/storage/core/libs/kikimr/node.cpp, cloud/storage/core/libs/kikimr/node.h, cloud/storage/core/libs/kikimr/options.cpp, cloud/storage/core/libs/kikimr/options.h
1. Add argument `--node-broker-secure-port`.
2. Enable setting `UseNodeBrokerSsl` not only from command line arguments but also from config file.
=> [Blockstore, Filestore] Enable turning on secure connection to node broker via config file

cloud/disk_manager/internal/pkg/facade/snapshot_service_test/snapshot_service_test.go, cloud/disk_manager/internal/pkg/facade/testcommon/common.go
One of the tests affected by https://github.com/ydb-platform/nbs/issues/2008 was not correct.
One of it's flaps: https://github.com/ydb-platform/nbs/actions/runs/13579009298
Also changed WaitForCheckpointsDoNotExist method for better testing
=> [Disk Manager] Fix flappy test for snapshot service

cloud/storage/core/libs/netlink/message.h
According to netlink specification we should send raw C structure to the kernel however the structure contains paddings(again it's according to netlink specification) which cause the uninitialized bytes warning from memory sanitizer.
Solution: use memset to initialize all bytes of the structure.
=> fix: uninitialized bytes warning

cloud/blockstore/libs/storage/stats_service/stats_service_actor_solomon.cpp, cloud/blockstore/libs/storage/stats_service/stats_service_actor_ydb.cpp, cloud/blockstore/libs/storage/stats_service/stats_service_state.h, cloud/blockstore/libs/ydbstats/ydbrow.h
Add volume tablet id to ydb perfstats tables. This provides convenient way go resolve volume tablet id into disk id.
=> [blockstore] upload volume tablet id to ydb-stats

cloud/filestore/apps/client/lib/app.cpp
Reverting this: https://github.com/ydb-platform/nbs/pull/2632#pullrequestreview-2482291564
Allows to use just `filestore-client listfilestores` command without specifying other arguments
=> [Filestore] fix client not working for single-argument commands

cloud/blockstore/libs/storage/partition/part_actor.cpp, cloud/blockstore/libs/storage/partition2/part2_actor.cpp
```
VERIFY failed (2025-03-20T00:37:43.804917Z): [BLOCKSTORE_PARTITION] Unexpected event: (0x106207EB) NCloud::NBlockStore::TResponseEvent<NCloud::NBlockStore::NStorage::TEvPartitionCommonPrivate::TOperationCompleted, 274860011u>
cloud/storage/core/libs/actors/helpers.cpp:53
HandleUnexpectedEvent(): requirement false failed
2025-03-20T00:37:43.805066Z :BLOCKSTORE_BOOTSTRAPPER ERROR: [72075186224037888] Tablet failed: ReasonPill (gen: 4, attempts: 1, threshold: 1)
2025-03-20T00:37:43.805075Z :BLOCKSTORE_BOOTSTRAPPER INFO: [72075186224037888] Exiting tablet (reason: ReasonPill)
2025-03-20T00:37:43.809315Z :BS_PROXY_PUT NOTICE: [5766328155169d5f] SendReply putResult# TEvPutResult {Id# [72075186224037888:4:6:6:0:4096000:0] Status# BLOCKED StatusFlags# { } ErrorReason# "Got VPutResult status# …
```
=> [Blockstore] ignore TEvPartitionCommonPrivate::TEvTrimFreshLogCompleted in StateZombie

cloud/blockstore/libs/storage/volume/volume_actor.cpp
Fixes `TestAlterPlacementGroupMembershipFailureBecauseDiskIsInAnotherGroup`:
https://github-actions-s3.storage.eu-north1.nebius.cloud/ydb-platform/nbs/PR-check/13977198773/1/nebius-x86-64/summary/ya-test.html#FAIL
```
VERIFY failed (2025-03-20T19:16:47.329823Z): [BLOCKSTORE_VOLUME] Unexpected event: (0x10620142) NCloud::NBlockStore::TRequestEvent<NCloud::NBlockStore::NStorage::TEvVolumePrivate::TAllocateDiskIfNeeded, 274858306u>, void NCloud::NBlockStore::NStorage::TVolumeActor::StateZombie(TAutoPtr< ::NActors::IEventHandle> &)
cloud/storage/core/libs/actors/helpers.cpp:70
HandleUnexpectedEvent(): requirement false failed
```
=> Ignore TEvVolumePrivate::TAllocateDiskIfNeeded in StateZombie

cloud/blockstore/libs/server/server_ut.cpp
fix flaky server tests:
https://github-actions-s3.storage.eu-north1.nebius.cloud/ydb-platform/nbs/Nightly-build-(msan)/13962498973/1/nebius-x86-64-msan/summary/ya-test.html#FAIL
`2025-03-20T06:27:16.748689Z :GRPC ERROR: contrib/libs/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc:1061: UNKNOWN:No address added out of total 2 resolved for 'localhost:9767' {created_time:"2025-03-20T06:27:16.748483632+00:00", children:[UNKNOWN:Unable to configure socket {fd:9, created_time:"2025-03-20T06:27:16.748393906+00:00", children:[UNKNOWN:Address already in use {created_time:"2025-03-20T06:27:16.748354331+00:00", errno:98, os_error:"Address already in use", syscall:"bind"}]}, UNKNOWN:Unable to configure socket {fd:9, created_time:"2025-03-20T06:27:16.748460719+00:00", …
=> fix: use port manager to get data port

cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_common.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_common.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_common_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_ut.cpp
Исправление бага когда данные писались с не правильным смещением.
1. вольюм должен мигрировать
2. этот девайс должен быть не первым
3. пользователь, пока идет миграция, должен записать запрос, попадающий на границу двух девайсов, так чтобы слева(с адресом меньше) был девайс который НЕ мигрирует, а справа девайс который мигрирует.
Проблема была в том, что не учитывалось что в конфиге миграционного партишена есть только те устройства, на которые идет миграция. Остальных девайсов нет, и нужно пропускать записи на них, а если запись бьется на два девайса, то нужно учитывать это при формировании буфера для запроса TEvWriteDeviceBlocksRequest. Ситуация, когда первого девайса нет, а второй есть - обрабатывалась не правильно.
=> Fix multidevice write when migration running

cloud/blockstore/libs/diagnostics/critical_events.h, cloud/blockstore/libs/endpoints_nbd/nbd_server.cpp, cloud/blockstore/libs/endpoints_vhost/vhost_server.cpp, cloud/blockstore/libs/nbd/server_handler.cpp, cloud/blockstore/libs/nbd/server_handler.h, cloud/blockstore/libs/service/aligned_device_handler.cpp, cloud/blockstore/libs/service/aligned_device_handler.h, cloud/blockstore/libs/service/device_handler.cpp, cloud/blockstore/libs/service/device_handler.h, cloud/blockstore/libs/service/device_handler_ut.cpp, cloud/blockstore/libs/service/storage_ut.cpp, cloud/blockstore/libs/service/unaligned_device_handler.cpp, cloud/blockstore/libs/service/unaligned_device_handler.h, cloud/blockstore/libs/vhost/server.cpp, cloud/blockstore/libs/vhost/server.h, cloud/storage/core/libs/common/media.cpp, cloud/storage/core/libs/common/media.h
Сделал чтобы  зажигались крит-эвенты, если мы все-таки отвечаем гостю ошибкой.
Если диск надежный и не должен ломаться, то зажигаем ErrorWasSentToTheGuestForReliableDisk на все ошибки.
Для нереплицирванных дисков зажигается один раз и ErrorWasSentToTheGuestForNonReliableDisk
=> Report critical event when error replied to guest

cloud/blockstore/libs/client/durable.cpp, cloud/blockstore/libs/client/durable.h, cloud/blockstore/libs/client/durable_ut.cpp, cloud/filestore/libs/client/durable.cpp, cloud/filestore/libs/client/durable.h, cloud/filestore/libs/client/durable_ut.cpp, cloud/storage/core/protos/error.proto
Добавил флаг, который поможет мне в реализации #3. Там есть два места в которых можно будет использовать этот флаг:
1) если девайс был признан лагающим, то мы можем отклонить запросы касающиеся этих девайсов, т.к. они наверняка затаймаутятся. А ретрай перевыполнит их на здоровых репликах. 
2) Когда девайс ожил после лагания, мы не можем сразу начинать миграцию, т.к. есть запросы на запись в полёте. Возникает гонка из-за которой мы можем прочитать то что было на диске до записи. Здесь этот флаг бы тоже помог чтобы отклонить все такие запросы. (Этот пункт под вопросом, можно решить иначе проблему)
В filestore добавил чтобы было симметрично.
=> Proto flag for instant retries

cloud/tasks/scheduler_impl.go, cloud/tasks/tasks_tests/tasks_test.go
Fix for TestTasksInflightLimit faulure:
```
tasks_test.go:837: 
Error Trace:	/-S/cloud/tasks/tasks_tests/tasks_test.go:837
Error:      	Received unexpected error:
Non retriable error, Silent=false: scheduler.WaitTaskSync timed out
goroutine 793 [running]:
runtime/debug.Stack()
/-S/contrib/go/_std_1.21/src/runtime/debug/stack.go:24 +0x5e
github.com/ydb-platform/nbs/cloud/tasks/errors.newNonRetriableError(...)
/-S/cloud/tasks/errors/errors.go:123
github.com/ydb-platform/nbs/cloud/tasks/errors.NewNonRetriableErrorf({0x49e08a?, 0xc000651dbc?}, {0x0?, 0x0?, 0x0?})
/-S/cloud/tasks/errors/errors.go:104 +0x34
github.com/ydb-platform/nbs/cloud/tasks.(*scheduler).WaitTaskSync.func1()
/-S/cloud/tasks/scheduler_impl.go:517 +0x22b
github.com/ydb-platform/nbs/cloud/tasks.(*scheduler).WaitTaskSync(0xc000 …
```
=> [Disk Manager] increase wait timeout in TestTasksInflightLimit, add taskID to logs

cloud/blockstore/libs/storage/partition_nonrepl/lagging_agent_migration_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_state.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_state.h, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_state_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_checksumblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_readblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_ut.cpp, cloud/blockstore/libs/storage/volume/actors/shadow_disk_actor.cpp
Reverts ydb-platform/nbs#3075 and ydb-platform/nbs#3149
В #3075 потеряли гарантию что пользователь не пишет в мигрируемый диапазон. Из-за этого после наливки фреша реплики могут отличаться по данным. 
Сценарий:
1. в миррор партишен пришел запрос на запись в рендж [x, y]
2. в реплике с мигрирующим фрешом запись  в [x, y] блоки прошла во фреш девайc
3. начинаем мигрировать рейндж, который включает в себя рейндж блоков [x, y]
4. читаем из остальных реплик данные, в которые еще не прошла запись из пункта 1 и перетираем в мигрурующей реплике уже записанные пользователем данные.
5. запись из пункта 1 проходит в оставшиеся реплики и получаем расхождения по данным
=> Revert "issue-3: read from mirror partition during fresh device migration"

cloud/blockstore/config/storage.proto, cloud/blockstore/libs/storage/core/config.cpp, cloud/blockstore/libs/storage/core/config.h, cloud/blockstore/libs/storage/partition_nonrepl/checksum_range.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_fastpath_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_util.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_util.h, cloud/blockstore/libs/storage/partition_nonrepl/resync_range.cpp, cloud/blockstore/libs/storage/partition_nonrepl/resync_range.h, cloud/blockstore/libs/storage/partition_nonrepl/resync_range_block_by_block.cpp, cloud/blockstore/libs/storage/partition_nonrepl/resync_range_block_by_block.h, cloud/blockstore/libs/storage/partition_nonrepl/resync_range_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/ya.make
Добавил эвристик при починке мажорного расхождения 4Мб блока. Если раньше просто выбиралась какая то реплика и ее содержимое копировалось всем, то теперь чуть сложнее:
1. Делаем попытку собрать кворум для каждого отдельного блока, может так повезти, что все расхождения починятся. 
2. Считаем сколько раз реплика имела правильные данные при починке минорных расхождений.
3. Выбираем "лучшую" реплику, которая наибольшее количество раз была правильной.
4. Оставшиеся мажорные расхождения чиним содержимым этой "лучшей" реплики.
Новую логику реализует новый актор, по умолчанию он не используется, чтобы он начал работать потребуется включить политику через настройки.
=> Resync major replica mismatch block by block

.clang-tidy
Убрал предупреждение clang-tidy что у перечислений слишком большой базовый тип
=> Suppress performance-enum-size clang-tidy warning

cloud/filestore/libs/storage/tablet/tablet_actor_addblob.cpp, cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp
https://github.com/ydb-platform/nbs/issues/3096
The compaction map becomes inconsistent when:
1. WriteBatch is enabled.
2. The amount of data written to a range in a single batch is greater than the batch size.
Suggested workaround: do not overwrite DeletionsCount.
=> [Filestore] Fix inconsistency in compaction metrics calculation when adding data #3096

cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync.h, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor_resync.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_util.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_util.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_events_private.h, cloud/blockstore/libs/storage/partition_nonrepl/resync_range.cpp, cloud/blockstore/libs/storage/partition_nonrepl/resync_range.h, cloud/blockstore/libs/storage/partition_nonrepl/resync_range_block_by_block.cpp, cloud/blockstore/libs/storage/partition_nonrepl/resync_range_block_by_block.h, cloud/blockstore/libs/storage/partition_nonrepl/resync_range_ut.cpp, cloud/blockstore/libs/storage/volume/volume_actor_startstop.cpp, cloud/blockstore/libs/storage/volume/volume_state.h
Продолжение https://github.com/ydb-platform/nbs/pull/3239
1. Теперь все политики по ресинку применяются и можно гибко настроить как чинить разъехавшиеся блоки.
2. научил старый актор ресинка учитывать политику и не чинить только миноры, если задана такая политика.
3. Новый актор для ресинка научился перед тем как начать работу узнавать чексуммы из всех реплик, и если чексуммы совпадают, то ничего не делать. Это нужно для автоматического или force-ресинка.
=> Apply resync policy to all

cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp
```
$(SOURCE_ROOT)/cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp:5595:46: error: non-constant-expression cannot be narrowed from type 'ui64' (aka 'unsigned long') to 'long' in initializer list [-Wc++11-narrowing-const-reference]
5595 |                     {"filesystem", "test"}}, block + 1_KB},
|                                              ^~~~~~~~~~~~
```
=> Fix non-constant-expression cannot be narrowed from type error

cloud/filestore/public/api/protos/data.proto, cloud/filestore/public/api/protos/headers.proto, cloud/filestore/public/sdk/go/client/grpc.go, cloud/filestore/public/sdk/python/client/base_client.py
These changes are done to get rid of `UTF8` validation function calls and increase performance.
The measurements were done using the command:
```sh
fio --name test --size 16M --bs 4k --time_based --ioengine=libaio --rw=read --runtime 60s
```
The command was used 5 times before the changes and 5 times after the changes. The latency results were min-ed, max-ed and avg-ed across the 5 runs.
Before:
- min = 921 `ns`
- avg = 12.193 `us`
- max = 17.289 `ms`
After:
- min = 921 `ns`
- avg = 11.820 `us`
- max = 8.365 `ms`
It can be seen that the `max` latency was lowered significantly, and the average latency was lowered by `~370ns` or by `~3%`.
FlameGraph before:
FlameGraph after:
=> [Filestore] Change type from string to bytes in Protobuf messages

cloud/blockstore/apps/disk_agent/ya.make, cloud/blockstore/apps/server/ya.make, cloud/filestore/apps/server/ya.make, cloud/filestore/apps/vhost/ya.make, cloud/storage/core/libs/kikimr/ya.make
Кажется разобрался почему у нас не линковался тест.
1. есть символ https://github.com/ydb-platform/nbs/blob/main/contrib/ydb/core/blobstorage/crypto/default.h#L8 который объявлен extern
2. есть определение, которое должно попадать в релизный бинарь https://github.com/ydb-platform/nbs/blob/main/contrib/ydb/library/keys/default_keys.cpp#L6
3. есть определение, которое должно попадать в тестовые бинари https://github.com/ydb-platform/nbs/blob/main/contrib/ydb/core/testlib/basics/services.cpp#L40
4. кроме этого много где в тестах символ переопределен прям в cpp например https://github.com/ydb-platform/nbs/blob/main/contrib/ydb/core/blobstorage/ut_vdisk/vdisk_test.cpp#L21
5. мы добавляли зависимость от contrib/ydb/library/keys в промежуточной либе cloud/storage/core/libs/kikimr которая …
=> Fix duplicate symbol error for YdbDefaultPDiskSequence

cloud/storage/core/libs/endpoints/keyring/keyring.cpp
Ошибка выравнивания под ubsanitizerом
```
<----- TKeyringEndpointsTest
[exec] TKeyringEndpointsTest::ShouldGetStoredEndpointsFromKeyring...
__NR_keyctl failed with error: 126, Required key not available
/place/sandbox-data/tasks/6/3/2938837536/__FUSE/mount_path_8581ac2f-9e9b-4447-9f09-25815c4fddcf/contrib/libs/cxxsupp/libcxx/include/__string/constexpr_c_functions.h:227:33: runtime error: load of misaligned address 0x0000022df609 for type 'const NCloud::TKeyring *', which requires 4 byte alignment
0x0000022df609: note: pointer points here
00 00 00  18 73 40 61 2a 5a 16 42  0d b5 51 21 29 00 00 00  07 00 00 00 00 00 00 00  30 00 00 00 00
^ 
#0 0xfb5b5e in __constexpr_memmove<NCloud::TKeyring, const NCloud::TKeyring, 0> /-S/contrib/libs/cxxsupp/libcxx/include/__string/constexpr_c_functions.h: …
```
=> keyring ub-sanitizer fix

.github/workflows/build_and_test_on_demand.yaml
Differrence is comically big
https://github.com/librarian-test/nbs/actions/runs/14196590910/job/39773076391 1h23m for build
https://github.com/librarian-test/nbs/actions/runs/14198904719/job/39780755567 4m21s for build with fix
https://github.com/ydb-platform/nbs/actions/runs/14201270002/job/39789160507 with fix
https://github.com/ydb-platform/nbs/actions/runs/14201277706/job/39788606837 without
=> fix: typo in github attribute caused build-and-test to not use network cache when workflow build_and_test_on_demand.yaml is executed directly

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_allocate.cpp, cloud/blockstore/libs/storage/volume/volume_actor_allocatedisk.cpp, cloud/blockstore/libs/storage/volume/volume_ut.cpp
#2945
После обсуждения с командой DM было решено не конвертировать `E_TRY_AGAIN` в `E_REJECTED` в ситуации, когда создание локального диска ожидает окончания `SecureErase` на неком числе девайсов, чтобы отличать эту сиуацию от других ситуаций вида `E_REJECTED`
Помимо этого, было решено полагаться на сообщение об ошибке для определения этой специфической ситуации в DM'е (соответствующий [PR](https://github.com/ydb-platform/nbs/pull/3285)), поэтому здесь же добавил комментарий о том, что менять это сообщение об ошибке стоит аккуратно
=> [NBS] Do not convert E_TRY_AGAIN to E_REJECTED on local disk allocation retries

cloud/blockstore/libs/storage/volume/volume_actor.h, cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp, cloud/blockstore/libs/storage/volume/volume_actor_resync.cpp, cloud/blockstore/libs/storage/volume/volume_actor_startstop.cpp
Название вводило в заблуждение, потому что метод рестартовал партишены любого типа.
=> Rename RestartDiskRegistryBasedPartition method

cloud/blockstore/libs/storage/partition_nonrepl/resync_range_block_by_block.cpp, cloud/blockstore/libs/storage/partition_nonrepl/resync_range_ut.cpp
Исправлен баг режима RESYNC_POLICY_MINOR_BLOCK_BY_BLOCK
Для воспроизведения нужно:
1.  имелось мажорное расхождение
2. в одной или двух репликах имелись минорные расхождения
3. реплика без минорного расхождения #0 
К чему приводило:
1. в реплику/реплики c минорным расхождением вместе с починкой приезжали мажорные  расхождения чужой реплики. 
2. после этого расхождения превращались в минорные
3. на следующий ресинк эти расхождения чинились
=> Fix replicas mess when only minors healed in second or third replicas

cloud/filestore/public/sdk/go/client/grpc.go
cloud/filestore/public/sdk/go/client/ut <govet>
```
------ sole chunk ran 1 test (total:0.73s - test:0.71s)
[fail] filestore-public-sdk-go-client.vet.txt::govet [default-linux-x86_64-relwithdebinfo] (0.32s)
$S/cloud/filestore/public/sdk/go/client/grpc.go:40:6: "ST1003: var idempotenceId should be idempotenceID"
$S/cloud/filestore/public/sdk/go/client/grpc.go:40:6: "ST1003: if you believe this report is false positive, please silence it with //nolint:st1003 comment"
$S/cloud/filestore/public/sdk/go/client/grpc.go:61:6: "ST1003: var traceId should be traceID"
$S/cloud/filestore/public/sdk/go/client/grpc.go:61:6: "ST1003: if you believe this report is false positive, please silence it with //nolint:st1003 comment"
$S/cloud/filestore/public/sdk/go/client/grpc.go:317:6: "ST1003: var …
```
=> [Filestore] fixed code-style in filestore-public-sdk-go-client

cloud/filestore/public/sdk/go/client/grpc.go
Еще ошибки код стайла
```
$S/cloud/filestore/public/sdk/go/client/grpc.go:61:6: "ST1003: var traceId should be traceID"
$S/cloud/filestore/public/sdk/go/client/grpc.go:61:6: "ST1003: if you believe this report is false positive, please silence it with //nolint:st1003 comment"
```
=> [Filestore] fix for code style 

cloud/blockstore/tests/csi_driver/e2e_tests_part1/test.py, cloud/blockstore/tools/csi_driver/internal/driver/node.go, cloud/blockstore/tools/csi_driver/internal/driver/node_test.go
statfs returns two fields:
```
f_bfree;   /* Free blocks in filesystem */
f_bavail;  /* Free blocks available to unprivileged user */
```
It's better to use f_bfree to calculate used space and f_bavail to calculate available space. Otherwise nbs used bytes metric for disk can be less than used space reported by kubelet.
However in this case totalBytes!=availableBytes+usedBytes
https://man7.org/linux/man-pages/man2/statfs.2.html
=> [CSI] fix used bytes stats

cloud/blockstore/libs/storage/protos/volume.proto, cloud/blockstore/libs/storage/volume/model/follower_disk.cpp, cloud/blockstore/libs/storage/volume/model/follower_disk.h, cloud/blockstore/libs/storage/volume/testlib/test_env.cpp, cloud/blockstore/libs/storage/volume/testlib/test_env.h, cloud/blockstore/libs/storage/volume/volume_actor.cpp, cloud/blockstore/libs/storage/volume/volume_actor_link_volume.cpp, cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp, cloud/blockstore/libs/storage/volume/volume_database.cpp, cloud/blockstore/libs/storage/volume/volume_database_ut.cpp, cloud/blockstore/libs/storage/volume/volume_events_private.h, cloud/blockstore/libs/storage/volume/volume_schema.h, cloud/blockstore/libs/storage/volume/volume_state.cpp, cloud/blockstore/libs/storage/volume/volume_state.h, cloud/blockstore/libs/storage/volume/volume_state_ut.cpp, cloud/blockstore/libs/storage/volume/volume_tx.h, cloud/blockstore/libs/storage/volume/volume_ut.cpp
Продолжение https://github.com/ydb-platform/nbs/issues/2999
Сделано сохранение в БД прогресса наливки связанного диска.
=> Persist migration progress for linked disks

cloud/blockstore/libs/storage/partition_nonrepl/lagging_agent_migration_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/lagging_agent_migration_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/lagging_agents_replica_proxy_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/lagging_agents_replica_proxy_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/lagging_agents_replica_proxy_ut.cpp
#3
Добавляю механизм сброса состояния одного лагающего агента при нескольких лагающих агентах
=> Destroy lagging migration actor for each agent

cloud/blockstore/libs/storage/api/partition.h, cloud/blockstore/libs/storage/model/requests_in_progress.h, cloud/blockstore/libs/storage/model/requests_in_progress_ut.cpp, cloud/blockstore/libs/storage/partition/part_actor.cpp, cloud/blockstore/libs/storage/partition/part_actor.h, cloud/blockstore/libs/storage/partition2/part2_actor.cpp, cloud/blockstore/libs/storage/partition2/part2_actor.h, cloud/blockstore/libs/storage/partition_common/drain_actor_companion.cpp, cloud/blockstore/libs/storage/partition_common/drain_actor_companion.h, cloud/blockstore/libs/storage/partition_common/drain_actor_companion_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/lagging_agent_migration_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/lagging_agent_migration_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/lagging_agents_replica_proxy_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/lagging_agents_replica_proxy_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/lagging_agents_replica_proxy_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_lagging_devices_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_events_private.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.h
#3
Добавляю новый тип drain: `WaitForInFlightWrites`. Это запрос, который дожидается завершения всех записей в полёте на момент получения сообщения. Нужно это перед началом миграции лагающего диска. 
Мигрировать сразу мы не можем, т.к. миграционный партишн не знает о текущих записях пользователя и начинает вычитывать из этих диапазонов, что может привести к чтению устареших данных.
=> Wait for in-flight writes before the lagging agent migration

cloud/filestore/tests/loadtest/service-kikimr-localdb-compaction-test/create-remove.txt
Уменьшаю размер теста, что бы он перестал под санитайзерами таймаутиться.
Сейчас под memory sanitizer'ом
```
------ [5/7] chunk ran 1 test (total:791.87s - setup:0.01s recipes:59.95s test:695.36s recipes:25.63s)
Chunk exceeded 600s timeout and was killed
List of the tests involved in the launch:
test.py::test_load[ops3-create-remove] (timeout) duration: 684.25s
Log: http://proxy.sandbox.yandex-team.ru/8288153229/cloud/filestore/tests/loadtest/service-kikimr-localdb-compaction-test/test-results/py3test/run_test.log
Logsdir: http://proxy.sandbox.yandex-team.ru/8288153229/cloud/filestore/tests/loadtest/service-kikimr-localdb-compaction-test/test-results/py3test/chunk5/testing_out_stuff
Stderr: http://proxy.sandbox.yandex-team.ru/8288153229/cloud/filestore/tests/loadtest/service-kikimr-localdb …
```
=> [Filestore] reduce service-kikimr-localdb-compaction-test memory footprint size

cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_ut.cpp
#3
После временной недоступности диск агента, таймауты от прошлых запросов могут приходить ещё какое-то время. Тут я отбрасываю "старые" таймауты, после начала которых уже были успешные ответы. 
Это нужно, чтобы не ложно нотифицировать волюм об лагающих девайсах.
=> Ignore timeouts after last successful request

cloud/blockstore/libs/client/throttling.cpp, cloud/blockstore/libs/client/throttling_ut.cpp
Removing the artificial volume quota bandwidth limit of 4 GiB/s.
=> [Blockstore] remove hardcoded quota limit of 4GiB

cloud/blockstore/libs/storage/partition_nonrepl/model/disjoint_range_set.cpp, cloud/blockstore/libs/storage/partition_nonrepl/model/disjoint_range_set.h, cloud/blockstore/libs/storage/partition_nonrepl/model/disjoint_range_set_ut.cpp
Убираю ограничение на одинаковый размер мигрируемого диапазона. Оказалось, что у нас есть старые диски, которые имеют рамер девайса не кратный 4 MiB
=> Allow to migrate different range sizes

cloud/blockstore/libs/service/checksum_storage_wrapper.cpp, cloud/blockstore/libs/service/device_handler_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_mirror.cpp
1. Столкнулись что некоторые клиенты генерируют тысячи DiskChecksumMismatchUponWrite. Чтобы не замусоривать логи пишем крит эвент один раз для одного диска.
2. Удобнее вытаскивать имя диска из логов когда оно заключено в кавычки
=> Report crit event DiskChecksumMismatchUponWrite once per disk

cloud/blockstore/libs/storage/volume/volume_tx.h
Поправил для конвенции. Сам Clear() тут никогда не вызывается
=> Unset ShouldStartResync in TRemoveLaggingAgent::Clear

cloud/disk_manager/internal/pkg/facade/testcommon/common.go
https://github.com/ydb-platform/nbs/issues/1950
WaitForNoCheckpointsExist is needed for tests with [failing shadow disks](https://github.com/ydb-platform/nbs/pull/3004), since can't get concrete checkpoint from inside the code of the test.
In order to deduplicate the code of existing WaitForCheckpointDoesNotExist function and added WaitForNoCheckpointsExist function, we use waitForCheckpointsWithPredicate function.
=> [Disk Manager] testcommon: use predicate when await for checkpoints, add WaitForNoCheckpointsExist function

cloud/filestore/libs/storage/tablet/tablet_actor_readdata.cpp, cloud/filestore/libs/storage/tablet/tablet_ut_cache.cpp
References #3341
This leak was introduced by the completion of https://github.com/ydb-platform/nbs/issues/324
=> issue-3341: mixed index ranges should be unreferenced upon the DescribeData completion

.github/actions/build/action.yaml, .github/actions/test/action.yaml, .github/workflows/build_and_test_ya.yaml, cloud/blockstore/tests/loadtest/local-encryption/ya.make, cloud/disk_manager/internal/pkg/dataplane/snapshot/storage/tests/ya.make
Unintended consequences of setting oom_score_adj for ya-bin is that all child processes also have this score and when shovel comes to shove it kills, for example github agent itself, like it did [here](https://github.com/ydb-platform/nbs/actions/runs/14330059235).
So idea here is, basically to set more correct distribution of scores to ensure that:
1. Runner itself is killed last (with adj 0)
2. ya-bin second to last (adj 1 using choom)
3. ydbd/qemu or other memory intensive processes should be thrown under OOM bus. (adj 500)
Another thing to do is to increase memory request for specific tests to allow ya to schedule them better to prevent OOM in the first place.
=> fix: increase memory limit for two testsuites and configure oom_score_adj

cloud/blockstore/libs/storage/partition_nonrepl/agent_availability_monitoring_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/agent_availability_monitoring_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/config.h, cloud/blockstore/libs/storage/partition_nonrepl/lagging_agents_replica_proxy_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/lagging_agents_replica_proxy_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/lagging_agents_replica_proxy_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_lagging_devices_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_state.cpp
#3
Переделал на проверку живости агента запросами напрямую в диск агента. Это нужно в первую очередь для того чтобы было проще отслеживать живость агента на который мы мигрируем.
=> Check lagging agent availability by direct requests to disk agent

cloud/disk_manager/internal/pkg/resources/images.go, cloud/disk_manager/internal/pkg/resources/images_test.go, cloud/disk_manager/internal/pkg/resources/mocks/storage_mock.go, cloud/disk_manager/internal/pkg/resources/snapshots.go, cloud/disk_manager/internal/pkg/resources/snapshots_test.go, cloud/disk_manager/internal/pkg/resources/storage.go, cloud/disk_manager/internal/pkg/services/images/create_image_from_disk_task.go, cloud/disk_manager/internal/pkg/services/images/create_image_from_image_task.go, cloud/disk_manager/internal/pkg/services/images/create_image_from_snapshot_task.go, cloud/disk_manager/internal/pkg/services/images/create_image_from_url_task.go, cloud/disk_manager/internal/pkg/services/snapshots/create_snapshot_from_disk_task.go
https://github.com/ydb-platform/nbs/issues/1950
Now CheckpointID field in image/snapshot meta works similar to *Size and *StorageSize fields. In is not set on CreateImage/CreateSnapshot. Instead, it is set on ImageCreated/SnapshotCreated.
Needed for retries of checkpoint creation for failed shadow disks, since we don't know checkpoint id untill snapshot/image is created.
=> [Disk Manager] add checkpointID to image meta, set checkpointID to snapshot/image meta on created

cloud/blockstore/libs/endpoint_proxy/server/server.cpp
1. Add to Socket2Endpoint map only successfully restored endpoints
2. create directory for socket as it can be missing after host restart
=> issue-3366: fix endpoint restoration

cloud/blockstore/libs/endpoints/endpoint_manager.cpp, cloud/blockstore/libs/endpoints_vhost/vhost_server.cpp, cloud/blockstore/libs/vhost/server.cpp, cloud/blockstore/libs/vhost/server.h, cloud/blockstore/libs/vhost/server_ut.cpp, cloud/blockstore/libs/vhost/server_ut_stress.cpp, cloud/blockstore/libs/vhost/vhost.cpp, cloud/blockstore/libs/vhost/vhost.h, cloud/blockstore/libs/vhost/vhost_test.cpp, cloud/blockstore/public/api/protos/endpoints.proto, cloud/blockstore/tools/csi_driver/internal/driver/node.go
issue: #3371
enable discard/zeroblocks features for vhost device when StartEndpoint request contains "Discard Enabled" flag.
=> [Blockstore] enable discard/zeroblocks features for vhost device

cloud/blockstore/tests/e2e-tests/test.py, cloud/blockstore/tests/e2e-tests/ya.make
Мы здесь делаем 2 вещи:
1.  Под tsan-ом меняем тест на large, чтобы у него было больше времени (с возвратом параллельности)
2. Убираем проверку статуса, про это ниже
В ядре, которое используется в нашем образе для тестов, не поддержаны ретраи при таймаутах запросов – https://elixir.bootlin.com/linux/v5.4/source/drivers/block/nbd.c#L398. Для сравнения, более новое ядро – https://elixir.bootlin.com/linux/v5.15.130/source/drivers/block/nbd.c#L419
То есть in-flight запросы завершались ошибкой, а новые запросы ждали переподключения – https://elixir.bootlin.com/linux/v5.4/source/drivers/block/nbd.c#L903 + из-за особенностей обработки ошибок fio, если numjobs > 1, весь процесс мог завершиться без ошибок
Сценарий, который мы пытаемся воспроизвести, приводит к зависанию процесса в D-state, поэтому …
=> make multiple_errors test large under tsan

cloud/blockstore/config/storage.proto, cloud/blockstore/libs/storage/core/config.cpp, cloud/blockstore/libs/storage/core/config.h, cloud/blockstore/libs/storage/core/volume_model.cpp, cloud/blockstore/libs/storage/core/volume_model_ut.cpp, cloud/blockstore/libs/storage/model/public.h, cloud/blockstore/libs/storage/partition/part_schema.h, cloud/blockstore/libs/storage/partition/part_state_ut.cpp, cloud/blockstore/libs/storage/partition2/part2_schema.h, cloud/blockstore/libs/storage/partition2/part2_state_ut.cpp
Under the current calculation scheme for the number of merged and mixed channels in hybrid drives, we end up with large drives that have a huge number of merged channels and very few mixed channels (for example, 100TB drives have 248 merged channels and only 3 mixed channels). The opposite situation occurs with small drives, which may have an excessive number of mixed channels.
This solution adds a new parameter that sets the percentage of mixed channels relative to the calculated merged channels; it is intended to set it to 15-20%.
=> [NBS] add parameter to calculate mixed channel count as percent from merged channel count

cloud/disk_manager/internal/pkg/resources/images_test.go
```
$S/cloud/disk_manager/internal/pkg/resources/images_test.go:346:2: "SA4006: this value of err is never used"
$S/cloud/disk_manager/internal/pkg/resources/images_test.go:346:2: "SA4006: if you believe this report is false positive, please silence it with //nolint:sa4006 comment"
```
This check was redundant: id and folder id are already checked in requireImagesAreEqual.
=> [Disk Manager] remove redundant check in test

cloud/blockstore/libs/storage/model/composite_id.h, cloud/blockstore/libs/storage/volume/multi_partition_requests.cpp, cloud/blockstore/libs/storage/volume/partition_info.cpp, cloud/blockstore/libs/storage/volume/partition_info.h, cloud/blockstore/libs/storage/volume/volume_actor.cpp, cloud/blockstore/libs/storage/volume/volume_actor.h, cloud/blockstore/libs/storage/volume/volume_actor_allocatedisk.cpp, cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp, cloud/blockstore/libs/storage/volume/volume_actor_forward.cpp, cloud/blockstore/libs/storage/volume/volume_actor_startstop.cpp, cloud/blockstore/libs/storage/volume/volume_actor_stats.cpp, cloud/blockstore/libs/storage/volume/volume_actor_statvolume.cpp, cloud/blockstore/libs/storage/volume/volume_actor_updateconfig.cpp, cloud/blockstore/libs/storage/volume/volume_state.cpp, cloud/blockstore/libs/storage/volume/volume_state.h
Продолжение https://github.com/ydb-platform/nbs/issues/2999
1. так как актор партишена может быть скрыт внутри оберток, то удобнее при получении сообщения в вольюм, проверить что это партишен или его обертки, чем пропускать все сообщения через цепочку оберток, гарантируя что сообщения будут всегда приходить из верхней обертки.
2. упростил вызов колбэков на умирание акторов партишенов. Колбэки вызываются в порядке вызовов StopPartition.
3. иногда тип диска определялся через GetDiskRegistryBasedPartitionActor() - заменил на IsDiskRegistryMediaKind()
4. добавил в счетчик запросов вольюма небольшой запас, чтобы когда он исчерпался для обычных запросов была возможность им еще немного пользоваться для сервисных нужд, не усложняя код.
=> Save partition actors and wrappers in stack

cloud/blockstore/config/storage.proto, cloud/blockstore/libs/storage/service/service_ut_mount.cpp, cloud/blockstore/libs/storage/service/volume_session_actor_start.cpp
https://github.com/ydb-platform/nbs/issues/3252
падал тест ДМа на миграцию 
потому что волум удалялся после WaitReady и волум уходил в бесконечное ожидание партишнов, которые уже не могли подняться, тк диск был удален
при этом hive триггерил lockLost и раньше мы ребутали таблетку и поэтому все было ок 
делаю фикс этого сценария
=> [Blockstore] Shutdown volume after locklost on volume deletion during mounting

cloud/blockstore/tools/csi_driver/internal/driver/node.go, cloud/blockstore/tools/csi_driver/internal/driver/node_test.go
issue: #3371
1. Enable discard for ydb-based disks
2. Use DescribeVolume to determine disk type as we can't rely on disk type information from the storage class
=> [CSI] enable discard in vm mode for ydb-based disks

cloud/blockstore/apps/client/README.md
List of possible media kinds is taken from here https://github.com/ydb-platform/nbs/blob/main/cloud/storage/core/libs/common/media.cpp#L109
=> Update blockstore client docs: add missing options of --storage-media-kind flag

cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_events_private.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_checksumblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_readblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_readblocks_local.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_writeblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_zeroblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_ut.cpp, cloud/blockstore/libs/storage/volume/volume_events_private.h
#3 
Adding volume notifying if some of requests time outed or rdma endpoint unavailable
В отдельном пре уменьшу колличесвто бойлер плейт кода в рдма ревест хэндлерах. в этом только добавляю отправку нотификации о  таймаутах запросов в девайсы
=> issue-3: add device timeout notify to rdma partition

cloud/blockstore/config/storage.proto, cloud/blockstore/libs/storage/core/config.cpp, cloud/blockstore/libs/storage/core/config.h, cloud/blockstore/libs/storage/core/proto_helpers.cpp, cloud/blockstore/libs/storage/core/proto_helpers.h, cloud/blockstore/libs/storage/partition/part_actor_writequeue.cpp, cloud/blockstore/libs/storage/partition/part_ut.cpp
A potential issue was discovered during testing. If a user heavily loads multiple HDD drives on a single host for writing, memory overflow can occur because data cannot be moved from the fresh channel fast enough, while not reaching the size threshold for the specific disk’s fresh channel.
To solve this problem, we are introducing a new write threshold for HDD drives and adding the ability to write user data to the mixed channel, bypassing the fresh channel. Thus, HDD drives will have two thresholds: one for writing to merged and another for writing to mixed. All data larger than the merged threshold will be written directly to merged channels, data exceeding the mixed threshold will be written to mixed channels, while the remaining data will be written to fresh channel and processed …
=> Add parameter WriteMixedBlobThresholdHDD as minimum request size in bytes to write to the mixed channel.

cloud/blockstore/libs/daemon/ydb/bootstrap.cpp, cloud/blockstore/libs/storage/stats_service/stats_service_actor.h, cloud/blockstore/libs/storage/stats_service/stats_service_actor_ydb.cpp, cloud/blockstore/libs/storage/stats_service/stats_service_ut.cpp, cloud/blockstore/libs/ydbstats/ydbrow.cpp, cloud/blockstore/libs/ydbstats/ydbrow.h, cloud/blockstore/libs/ydbstats/ydbscheme.h, cloud/blockstore/libs/ydbstats/ydbstats.cpp, cloud/blockstore/libs/ydbstats/ydbstats.h, cloud/blockstore/libs/ydbstats/ydbstats_ut.cpp
Refactored code in ydbstats. Motivation: we are going to add more tables to ydbstats (in order to resolve partition tablet id or blob storage group id into volume id). If we add these tables without refactoing, there will be too much boilerplate and duplicate code.
=> Refactoring: move TYdbRowData from service_stats to ydbstats, deduplicate some code in ydbstats, rename TYdbRow into TYdbStatsRow

cloud/blockstore/tools/ci/migration_test/lib/main.py
If disk is not found, the test doesn't reach the corresponding check. Instead, if fails earlier with a misleading error:
```
File "cloud/blockstore/tools/ci/migration_test/lib/main.py", line 106, in __init__
[09:03:20 ](https://teamcity.aw.cloud.yandex.net/buildConfiguration/NBS_NbsTests_Nbs_MigrationTests_HwNbsStableLab_MigrationTestRdma/20423531?buildTab=log&focusLine=227&logView=flowAware&linesState=227)      host = args.nbs_host if args.nbs_host else self.instance.compute_node
[09:03:20 ](https://teamcity.aw.cloud.yandex.net/buildConfiguration/NBS_NbsTests_Nbs_MigrationTests_HwNbsStableLab_MigrationTestRdma/20423531?buildTab=log&focusLine=228&logView=flowAware&linesState=228)                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
[09:03:20 …
```
=> Minor fix of migration test: throw correct exception if disk is not found

cloud/filestore/libs/storage/service/service_ut_sharding.cpp
FIxing this TODO: https://github.com/ydb-platform/nbs/blob/e8e991ccfb1c92604673029172d9223afbf28cad/cloud/filestore/libs/storage/service/service_ut_sharding.cpp#L155-L157
=> [Filestore] cleanup `service_ut_sharding.cpp` test

cloud/blockstore/libs/storage/partition_nonrepl/lagging_agent_migration_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/lagging_agent_migration_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/lagging_agents_replica_proxy_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_lagging_devices_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_state.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_state.h, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_state_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_checksumblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_readblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_ut.cpp, cloud/blockstore/libs/storage/volume/actors/shadow_disk_actor.cpp, cloud/blockstore/tests/loadtest/local-mirror/local-mirror2-fresh-device-migration.txt, cloud/blockstore/tests/loadtest/local-mirror/local-mirror2-split-read-column.txt, cloud/blockstore/tests/loadtest/local-mirror/local-mirror2-split-read-cross.txt, cloud/blockstore/tests/loadtest/local-mirror/test.py
#3 продолжение #3292 для починки бага из #3273
В этом пре я собираюсь вернуть обратно изменения, которые привели к появлению бага (чтение при миграции из MigrationSrcActorId, который в случае фреш миграций будет являться миррор партишеном) и прикрутить отправку LockAndDrainRange сообщений к миграциям (добавить нормальную перегрузку функции IMigrationOwner::GetActorToLockAndDrainRange, которая возвращает миррор партишен, а не пустой актор айди)
=> issue-3: added locking ranges for write requests in mirror partition during fresh device migration

cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_base_request.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_ut.cpp
#3
Добавляю флаг `EF_INSTANT_RETRIABLE` для отменённых запросов в лагающий агент. Их можно ретраить сразу же, т.к. запросы гарантированно попадут в живые реплики
=> Do an instant retry for cancelled requests due to lagging

cloud/storage/core/libs/common/error.cpp
Печатаю теперь все флаги ошибок, а не только `EF_SILENT`.
=> Print every error flag in the FormatError()

cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp, cloud/blockstore/libs/storage/volume/volume_actor_lagging_agents.cpp
Логи печатаются на каждый смигрированный диапазон. Многовато получается.
=> Decrease logs verbosity level

cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_agents_info.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_checkpoint.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_cms.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_config.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_create.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_lagging_agents.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_migration.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_mirrored_disks.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_pending_cleanup.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_pools.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_suspend.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_updates.cpp, cloud/blockstore/libs/storage/disk_registry/testlib/test_state.cpp, cloud/blockstore/libs/storage/disk_registry/testlib/test_state.h, cloud/blockstore/tools/testing/disk-registry-state-generator/main.cpp
#1155
Сейчас `TDiskRegistryState` - большой монолит. Для распила его на кусочки или добавления нового "модульного" кода мешает тот факт, что этот класс можно копировать и перемещать. Это не позволяет создавать дочерние классы, которые бы хранили raw/weak указатель на `TDiskRegistryState`.
=> Delete copy and move constructors of TDiskRegistryState

cloud/blockstore/config/ydbstats.proto, cloud/blockstore/libs/daemon/ydb/bootstrap.cpp, cloud/blockstore/libs/ydbstats/config.cpp, cloud/blockstore/libs/ydbstats/config.h, cloud/blockstore/libs/ydbstats/ydbrow.cpp, cloud/blockstore/libs/ydbstats/ydbrow.h, cloud/blockstore/libs/ydbstats/ydbscheme.cpp, cloud/blockstore/libs/ydbstats/ydbscheme.h, cloud/blockstore/libs/ydbstats/ydbstats.cpp, cloud/blockstore/libs/ydbstats/ydbstats.h, cloud/blockstore/libs/ydbstats/ydbstats_ut.cpp
В базу данных ydbstats добавляются две таблицы: Partitions и Groups. Записи данных в эти таблицы пока нет, сделаем в отдельном pr.
Таблица Partitions содержит колонки
```
DiskId, VolumeTabletId, PartitionTabletId, Timestamp
```
Первичный ключ -- PartitionTabletId.
Таким образом, с помощью таблицы partitions можно резолвить partition tablet id в disk id и volume tablet id.
Таблица Groups содержит колонки
```
PartitionTabletId, Channel, Generation, GroupId, Timestamp.
```
Здесь Channel -- номер канала, Generation -- поколение канала (растёт при reassing-ах канала).
Первочный ключ состоит сразу из четырёх колонок: PartitionTabletId, Channel, Generation, GroupId.
Таким образом, с помощью таблицы partitions можно резолвить group id в partition tablet id. Наоборот, можно по partition tablet id …
=> [Blockstore] diagnostics: introduce new ydb tables in ydbstats database for information about partition tablets and bs groups

cloud/blockstore/libs/ydbstats/ydbrow.h
```
Test crashed (return code: 100)
==995313==WARNING: MemorySanitizer: use-of-uninitialized-value
warning: address range table at offset 0x30 has a premature terminator entry at offset 0x40
warning: address range table at offset 0x60 has a premature terminator entry at offset 0x70
warning: address range table at offset 0x90 has a premature terminator entry at offset 0xa0
warning: address range table at offset 0xc0 has a premature terminator entry at offset 0xd0
warning: address range table at offset 0x180 has a premature terminator entry at offset 0x190
warning: address range table at offset 0x1b0 has a premature terminator entry at offset 0x1c0
warning: address range table at offset 0x1e0 has a …
```
=> Test fix: fix use of uninitialize values in ydbstats

cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_checksumblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_writeblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_zeroblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_ut.cpp
#3
Когда диск агент недоступен, то скорее всего RDMA партишн даже не попытается отправить запрос, т.к. аллокация памяти сфейлится. Здесь я добавляю учёт этой ошибки, чтобы `DeviceTimedOut` сообщение отправлялось стабильнее. Оно ялвяется триггером к лаганию
=> Send DeviceTimedOut on request allocation failure in the RDMA partition

cloud/filestore/libs/vfs_fuse/fs_ut.cpp
Под Fsan  падали тесты из-за data race в коде
Ошибки:
```
Number of suites skipped by tags: 1
cloud/filestore/libs/vfs_fuse/ut <unittest> [size:medium] nchunks:7 [tags: sb:MULTISLOT, sb:cores=8, sb:logs_ttl=3, sb:ssd, sb:ttl=3]
------ [2/7] chunk ran 6 tests (total:3.04s - test:3.02s)
[crashed] TFileSystemTest::ShouldNoFailRequestIfSessionIsAbleToRecover [default-linux-x86_64-release-FORCE_STATIC_LINKING=yes-tsan] (0.64s)
Test crashed (return code: 100)
WARNING: ThreadSanitizer: data race (pid=738793)
Write of size 8 at 0x7b100000f580 by main thread:
#0 operator delete(void*) /home/sazonov99/arcadia/contrib/libs/clang16-rt/lib/tsan/rtl/tsan_new_delete.cpp:126:3 (cloud-filestore-libs-vfs_fuse-ut+0xee948f) (BuildId: 33008ce6d6f4040c11525ef888059e2058db9fc4)
#1 void …
```
=> [Filestore] data race in vfs_fuse tests fixed for tsan

cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.h
#3 в пре #3292 убрал использование структуры TRequestCtx и забыл убрать ее из кода
=> issue-3: removed unused struct TMirrorPartitionActor::TRequestCtx

cloud/blockstore/libs/rdma_test/client_test.cpp, cloud/blockstore/libs/rdma_test/client_test.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_checksumblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_readblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_readblocks_local.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_writeblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_zeroblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/ut_env.h
#3 продолжение #3187 Добавил отмену запросов при получении сообщения, что агент стал недоступен. При отправке запросов запоминаем индексы девайсов и рдма реквест айди отправленных сообщений.  При обработке сообщения TEvNonreplPartitionPrivate::TEvAgentIsUnavailable прохожусь по всем In flight запросам и если он попадает в лагающего агента отменяю его. При отмене конвертирую ошибку E_CANCELLED в  E_REJECTED, т.к. необходимо чтобы запрос поретраился и попал в другую реплику, а не завершился с ошибкой.
=> issue-3: reject requests if agent has become unavailable

cloud/blockstore/libs/client/client.cpp, cloud/filestore/libs/client/client.cpp
issue: #3462 
Fixes TServerTest flaps. Test failure is reproducible under the stress. Fixed by setting wait_for_ready on the client side. With this flag RPC doesn't fail fast if channel is in CONNECTING state.
https://github.com/grpc/grpc/blob/master/doc/wait-for-ready.md
Also applying the same fix for blockstore client
=> issue-3462: avoid RPC failure in the filestore/blockstore client when channel is in CONNECTING state

cloud/storage/core/libs/kikimr/config_initializer.cpp, cloud/storage/core/libs/kikimr/config_initializer_ut.cpp, cloud/storage/core/libs/kikimr/options.cpp, cloud/storage/core/libs/kikimr/options.h, cloud/storage/core/libs/kikimr/ut/ya.make, cloud/storage/core/libs/kikimr/ya.make
Introducing `--actor-system-available-cpu-cores-percentage` cmd-line flag which adjusts `System`, `User`, `IC` thread pool sizes (if those sizes are equal) according to available CPU cores percentage
=> Add ability to adjust actor system thread count according to available CPU cores percentage

cloud/disk_manager/pkg/admin/run.go
Requiring config presence to generate completions would be illogical in the first place.
=> [Disk Manager] Allow completion generation without configs present

cloud/blockstore/libs/storage/core/disk_counters.h, cloud/blockstore/libs/storage/core/request_info.h, cloud/blockstore/libs/storage/partition_common/get_device_for_range_companion.cpp, cloud/blockstore/libs/storage/partition_common/get_device_for_range_companion.h, cloud/blockstore/libs/storage/partition_nonrepl/model/device_stats.cpp, cloud/blockstore/libs/storage/partition_nonrepl/model/device_stats.h, cloud/blockstore/libs/storage/partition_nonrepl/model/ya.make, cloud/blockstore/libs/storage/partition_nonrepl/multi_agent_write_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_mirror.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_writeblocks_multi_agent.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_events_private.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/ya.make, example/0-setup.sh, example/4-start_disk_agent.sh, example/nbs/nbs-diag.txt
продолжение https://github.com/ydb-platform/nbs/issues/1720
1. Запросы теперь проходят через TNonreplicatedPartitionActor, что позволяет обновлять service и service_volume статистику и учитывать время последних запросов для вычисления таймаута
2. если одна из реплик таймаутит или сломана, то откатываемся на старый режим выполнения запросов. 
3. Реплики для записи теперь выбираются поочередно.
=> Execute multi-agent request through nonreplicated partition actor

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
1. Расшифровал статусы диска
2. исправил баг из-за которого часть табличек не сортировались
3. пронумеровал девайсы
4. добавил диапазон, за который отвечает девайс
5. вывел список агентов, от которых зависит диск
=> Fix sorting and filtering for tables on monpage

cloud/blockstore/libs/storage/volume/volume_state.cpp, cloud/blockstore/libs/storage/volume/volume_state_ut.cpp, cloud/blockstore/libs/storage/volume/volume_ut.cpp
Пришло время избавится от записи карты блоков для зашифрованных дисков. Эта карта не используется при чтении. 
после https://github.com/ydb-platform/nbs/pull/1771
=> Don't write obsolete used blocks map for DiskRegistry-based encrypted disks

.github/actions/build/action.yaml, .github/actions/nebius_cli/action.yaml, .github/actions/nebius_runner_create/action.yaml, .github/actions/nebius_runner_remove/action.yaml, .github/actions/nebius_threads_calculator/action.yaml, .github/actions/s3cmd/action.yaml, .github/actions/ssh_keys/action.yaml, .github/actions/test/action.yaml, .github/scripts/shell-extractor.py, .github/workflows/build_and_test_on_demand.yaml, .github/workflows/build_and_test_ya.yaml, .github/workflows/create_and_delete_vm.yaml, .github/workflows/github_actions_scripts.yaml, .github/workflows/nightly-asan.yaml, .github/workflows/nightly-msan.yaml, .github/workflows/nightly-tsan.yaml, .github/workflows/nightly-ubsan.yaml, .github/workflows/nightly.yaml, .github/workflows/packer.yaml, .github/workflows/pr-github-actions.yaml, .github/workflows/pr.yaml
For PR checks there will be 3 retries and for nightly builds - there will be no retries
Also there will be retries if ya make will fail with exit code 137 (oom)
This does not mean that if the test was ultimately successful, then there is no need to look at why the test might have failed
Examples how it will look:
Success: https://github.com/librarian-test/nbs/pull/104
All failed: https://github.com/librarian-test/nbs/pull/103
Two failed and success in the end: https://github.com/librarian-test/nbs/pull/102
Additionally there was refactoring:
1. How we assemble list of arguments for ya make
2. Replaced in-place github variables for shell env vars. It is useful for shellcheck/shfmt because otherwise we need to add automatically shellcheck disable directives for almost half of the already …
=> feat: add ability to retry failed tests on checks

cloud/blockstore/libs/rdma/impl/client_ut.cpp, cloud/blockstore/libs/rdma/impl/test_verbs.cpp
```
WARNING: ThreadSanitizer: data race (pid=95883)
Read of size 8 at 0x7b4c00000530 by thread T1:
#0 std::__y1::__function::__value_func<void (ibv_wc *)>::operator bool /actions-runner/_work/nbs/nbs/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:554:55 (cloud-blockstore-libs-rdma-impl-ut+0x2012704) (BuildId: 622a7b3eee6707380f4d71e299685cf6a9663d57)
#1 std::__y1::function<void (ibv_wc *)>::operator bool /actions-runner/_work/nbs/nbs/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:1039:32 (cloud-blockstore-libs-rdma-impl-ut+0x2012704)
#2 NCloud::NBlockStore::NRdma::NVerbs::TTestVerbs::PollCompletionQueue(ibv_cq *, NCloud::NBlockStore::NRdma::NVerbs::ICompletionHandler *)::(anonymous class)::operator() /actions-runner/_work/nbs/nbs/cloud/blockstore/libs/rdma/impl/te …
```
=> Fix data race in TRdmaClientTest::TShouldForceReconnect

cloud/blockstore/libs/storage/volume/volume_actor_lagging_agents.cpp, cloud/blockstore/libs/storage/volume/volume_lagging_agent_ut.cpp, cloud/blockstore/libs/storage/volume/volume_state.cpp, cloud/blockstore/libs/storage/volume/volume_state.h
#3
Сбрасываю прогресс миграции лагающего агента, если в процессе он снова залагал. Влияет только на метрики и отображение на мон страничке
=> Reset lagging migration progress on DeviceTimedOut message

cloud/filestore/libs/storage/service/service_ut_sharding.cpp
```
$(SOURCE_ROOT)/cloud/filestore/libs/storage/service/service_ut_sharding.cpp:634:9: error: 'this' argument to member function 'SetAutomaticShardCreationEnabled' has type 'const NProto::TStorageConfig', but function is not marked const
CREATE_ENV_AND_SHARDED_FILESYSTEM();
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$(SOURCE_ROOT)/cloud/filestore/libs/storage/service/service_ut_sharding.cpp:239:5: note: expanded from macro 'CREATE_ENV_AND_SHARDED_FILESYSTEM'
config.SetAutomaticShardCreationEnabled(true);                            \
^~~~~~
$(BUILD_ROOT)/cloud/filestore/config/storage.pb.h:4427:15: note: 'SetAutomaticShardCreationEnabled' declared here
inline void SetAutomaticShardCreationEnabled(bool value) { set_automaticshardcreationenabled(value); }
^ …
```
=>  Fix filestore build

cloud/blockstore/config/storage.proto, cloud/blockstore/libs/storage/core/config.cpp, cloud/blockstore/libs/storage/core/config.h, cloud/blockstore/libs/storage/core/disk_counters.h, cloud/blockstore/libs/storage/disk_agent/actors/multi_agent_write_device_blocks_actor.cpp, cloud/blockstore/libs/storage/disk_agent/actors/multi_agent_write_device_blocks_actor.h, cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/lagging_agents_replica_proxy_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/lagging_agents_replica_proxy_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_writeblocks_multi_agent.cpp, cloud/blockstore/libs/storage/protos/disk.proto
Продолжение https://github.com/ydb-platform/nbs/issues/1720
1. в запросе к агенту теперь на каждый подзапрос задается свой таймаут, что позволяет узнавать какой из диск-агентов затаймаутил
2. если таймаутит агент, через который делается запрос, то обновляется статистика по девайсу и девайс может быть признан сломаным 
3. поправил отправку статистики 
4. добавил обработку TEvGetDeviceForRangeRequest в TLaggingAgentsReplicaProxyActor
=> For multi-agent request make timeout on disk-agent side

.github/scripts/nebius-manage-images.py, .github/scripts/nebius-manage-vm.py
```2025-05-13 12:33:35,037: INFO: Runner with name computeinstance-e00cv993pbh4axbemm found
2025-05-13 12:33:35,389: INFO: Removed runner with name computeinstance-e00cv993pbh4axbemm and id 13543
2025-05-13 12:35:12,037: INFO: Deleted VM with ID computeinstance-e00cv993pbh4axbemm
2025-05-13 12:35:12,208: ERROR: Failed to find disk with name disk-pr-3494-14994259836-1
```
https://github.com/ydb-platform/nbs/actions/runs/14994259836/job/42132612469
There was a situation where there was ~30vms/disks created at given time and page_size is 10.
=> fix: handle multiple paged response for list operations

cloud/blockstore/libs/storage/core/monitoring_utils.cpp, cloud/blockstore/libs/storage/volume/model/requests_time_tracker.cpp, cloud/blockstore/libs/storage/volume/model/requests_time_tracker.h, cloud/blockstore/libs/storage/volume/model/requests_time_tracker_ut.cpp, cloud/blockstore/libs/storage/volume/model/ut/ya.make, cloud/blockstore/libs/storage/volume/model/ya.make, cloud/blockstore/libs/storage/volume/volume_actor.h, cloud/blockstore/libs/storage/volume/volume_actor_forward.cpp, cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp, cloud/blockstore/tests/monitoring/test.py
Новая вкладка на страничке мониторинга.
1. количество выполненных запросов в разбивке по размеру и типу запроса
2. гистограмма времени выполнения запросов
3. количество запросов "в полете" и сколько времени они уже выполняются
4. итоги по всем временам выполнения
5. итоги по всем размерам запросов
6. запросы завершившиеся ошибкой
7. суммарный размер запросов
8. данные в табличке обновляются раз в секунду
Это позволяет отвечать на вопросы:
1. почему какие-то запросы выполняются быстро, а другие медленно (потому что они разных размеров)
2. Видеть зависшие запросы, они оказываются в колонке inflight и перемещаются в перцентили с бОльшим временем 
3. видеть что запросы по какой-то причине отменяются партишеном (они оказываются в колонке failed)
4. видеть что запросы таймаутятся 
5. видеть с …
=> Latency tab has been added to the volume mon page to view request execution latency

.github/config/muted_ya.txt
Disabled until we understand what's going on
=> [Disk Manager] temporarily mute failing filesystem_service_nemesis_test::TestFilesystemServiceCreateExternalFilesystem test

cloud/blockstore/libs/diagnostics/critical_events.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
Изначально этот крит эвент добавлялся с целью удостовериться, что PurgeHost вызывается инфрой в тот момент, когда мы уже можем удалить все девайсы (т.е. все диски смигрировали).
Стало понятно, что он имеет право срабатывать, например, в ситуации когда агент ушёл в unavailable, а инфра дергает PurgeHost или RemoveHost.
=> Remove DiskRegistryCleanupAgentConfigError crit event

cloud/blockstore/libs/storage/volume/volume_actor_allocatedisk.cpp, cloud/blockstore/libs/storage/volume/volume_ut.cpp
Добавил `State`, `StateTs` и `StateMessage` поля у протобафа `TDeviceConfig` в игнориуемые. Их изменение не должно никак влиять на тип реалокации (lite или нет).
=> Devices state change should not disable lite reallocation

cloud/blockstore/libs/storage/volume/model/requests_time_tracker.cpp, cloud/blockstore/libs/storage/volume/model/requests_time_tracker.h, cloud/blockstore/libs/storage/volume/model/requests_time_tracker_ut.cpp, cloud/blockstore/libs/storage/volume/volume_actor_forward.cpp, cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp
1. Добавил отображение запросов DescribeBlocks. Нужно чтобы смотреть как себя ведет базовый диск.
2. добавил табличку с перцентилями времени выполнения запросов.
=> Show statistics for DescribeBlocks request. Show percentiles.

.github/config/muted_ya.txt
```
[[bad]]less-or-equal assertion failed at cloud/filestore/libs/storage/tablet/model/shard_balancer_ut.cpp:282, virtual void NCloud::NFileStore::NStorage::NTestSuiteTShardBalancerTest::TTestCaseShouldBalanceShardsRandom::Execute_(NUnitTest::TTestContext &): count <= iterations / 2 + rangeToleration [[rst]]
[[alt1]]NUnitTest::NPrivate::RaiseError(char const*, TBasicString<char, std::__y1::char_traits<char> > const&, bool)+128 (0x17A86A0)
NCloud::NFileStore::NStorage::NTestSuiteTShardBalancerTest::TTestCaseShouldBalanceShardsRandom::Execute_(NUnitTest::TTestContext&)+9012 (0x16230F4)
NCloud::NFileStore::NStorage::NTestSuiteTShardBalancerTest::TCurrentTest::Execute()::'lambda'()::operator()() const+70 (0x162C1A6)
NUnitTest::TTestBase::Run(std::__y1::function<void ()>, TBasicString<char, …
```
=> Mute TShardBalancerTest.ShouldBalanceShardsRandom

cloud/blockstore/libs/storage/partition_nonrepl/lagging_agents_replica_proxy_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/lagging_agents_replica_proxy_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/lagging_agents_replica_proxy_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_lagging_devices_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/ut_env.h
Продолжение https://github.com/ydb-platform/nbs/issues/1720
Здесь учимся отменять запросы, пересекающиеся по номеру девайса с залагавшей репликой.
Т.е. если у нас залагал девайс №7 в реплике №1, мы отменим  запросы на запись к девайсам №7 во всех репликах, но запросы на чтение отменим только к девайсу №7 реплики №1.
=> Cancel requests in all replicas when agent starts lagging

cloud/filestore/libs/storage/core/config.cpp
Accidentally, this policy was enabled by default due to the backward compatibility concerns:
https://github.com/ydb-platform/nbs/blob/2d4fa644857b0da0f94929f0d511d5cc766acfec/cloud/filestore/libs/storage/tablet/tablet_actor_createhandle.cpp#L391-L393
=> issue-3295: do not enable `GCT_SECOND_READ` guest caching policy by default

cloud/blockstore/tests/vhost-server/ya.make
Somtimes it fails by timeout https://github-actions-s3.storage.eu-north1.nebius.cloud/ydb-platform/nbs/Nightly-build-(asan)/15106258959/1/nebius-x86-64-asan/summary/1/ya-test.html#FAIL
=> Make cloud/blockstore/tests/vhost-server medium

.github/config/muted_ya.txt, cloud/filestore/libs/storage/tablet/model/shard_balancer.cpp, cloud/filestore/libs/storage/tablet/model/shard_balancer_ut.cpp
#3493 
1. This code will fail if randomValue is zero: https://github.com/ydb-platform/nbs/blob/ff695720198806609d8e769f60c8d33374da534a/cloud/filestore/libs/storage/tablet/model/shard_balancer.cpp#L192
We should have been using UpperBound instead of LowerBound
2. Range toleration in tests has been increased twice to ensure the probability of false negative test failure is closer to zero. Compare: [x=100](https://www.wolframalpha.com/input?i=erf%28%28x+%2B+0.5%29+%2F+sqrt%282+*+5000+*+1%2F2+*+1%2F2%29%29+at+x+%3D+100) and [x=200](https://www.wolframalpha.com/input?i=erf%28%28x+%2B+0.5%29+%2F+sqrt%282+*+5000+*+1%2F2+*+1%2F2%29%29+at+x+%3D+200)
=> issue-3493: stabilize and unmute `ShouldBalanceShardsRandom` and `ShouldBalanceShardsWeightedRandom` tests

cloud/blockstore/libs/daemon/ydb/bootstrap.cpp, cloud/blockstore/libs/storage/stats_service/stats_service_actor_ydb.cpp, cloud/blockstore/libs/storage/stats_service/stats_service_ut.cpp, cloud/blockstore/libs/ydbstats/public.h, cloud/blockstore/libs/ydbstats/ya.make, cloud/blockstore/libs/ydbstats/ydbscheme.h, cloud/blockstore/libs/ydbstats/ydbstats.cpp, cloud/blockstore/libs/ydbstats/ydbstats.h, cloud/blockstore/libs/ydbstats/ydbstorage.cpp, cloud/blockstore/libs/ydbstats/ydbstorage.h
Перегруппировал зависимости  так, чтобы те кто инклюдят из `cloud/blockstore/libs/ydbstats` не подключали (явно или неявно) `cloud/blockstore/libs/ydbstats/ydbscheme.h` потому что он подключает в себя `contrib/ydb/public/sdk/cpp/client`, а эта зависимость может вызывает совершенно неожиданные неоднозначности разрешения имен. 
```
In file included from $(SOURCE_ROOT)/cloud/blockstore/libs/daemon/ydb/bootstrap.cpp:47:
$(SOURCE_ROOT)/cloud/blockstore/libs/ydbstats/ydbscheme.h:24:24: error: reference to 'NTable' is ambiguous
24 |     const TMaybe<NYdb::NTable::TTtlSettings> Ttl;
|                  ~~~~~~^
$(SOURCE_ROOT)/contrib/ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/topic/write_session.h:14:28: note: candidate found by name lookup is 'NYdb::V3::NTable'
14 | namespace NYdb::inline …
```
=> The contrib/ydb/public/sdk/cpp/client was removed from implicit dependencies through nested #include

cloud/blockstore/libs/daemon/ydb/bootstrap.cpp, cloud/blockstore/libs/ydbstats/ydbstats.cpp, cloud/blockstore/libs/ydbstats/ydbstats.h
Продолжение https://github.com/ydb-platform/nbs/pull/3557
Через `#include <cloud/blockstore/libs/ydbstats/ydbstorage.h>`
тоже пролезала зависимость. 
Убрал использование этого инклюда.
=> The contrib/ydb/public/sdk/cpp/client was removed from implicit dependencies through nested #include (#2)

cloud/blockstore/config/storage.proto, cloud/blockstore/libs/storage/api/stats_service.h, cloud/blockstore/libs/storage/core/config.cpp, cloud/blockstore/libs/storage/core/config.h, cloud/blockstore/libs/storage/service/service_ut.cpp, cloud/blockstore/libs/storage/stats_service/stats_service_actor.cpp, cloud/blockstore/libs/storage/stats_service/stats_service_actor.h, cloud/blockstore/libs/storage/stats_service/stats_service_actor_solomon.cpp, cloud/blockstore/libs/storage/stats_service/stats_service_actor_ydb.cpp, cloud/blockstore/libs/storage/stats_service/stats_service_state.h, cloud/blockstore/libs/storage/stats_service/stats_service_ut.cpp, cloud/blockstore/libs/storage/volume/volume_actor.h, cloud/blockstore/libs/storage/volume/volume_actor_startstop.cpp
- Send info about channels and groups of the partition tablet to stats service actor. We do this on partition start (namely, in In TVolumeActor::HandleBootExternalResponse).
- In stats volume actor, we send the corresponding information to ydb tables that were introdiced here https://github.com/ydb-platform/nbs/pull/3433.
=> [Blockstore] send info about partitions and channels to stats service on partition start; upload this information to ydbstats

cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp
```
$(SOURCE_ROOT)/cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp:2632:18: error: non-constant-expression cannot be narrowed from type 'ui64' (aka 'unsigned long') to 'long' in initializer list [-Wc++11-narrowing-const-reference]
2632 |                  value},
|                  ^~~~~
$(SOURCE_ROOT)/cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp:2635:18: error: non-constant-expression cannot be narrowed from type 'ui64' (aka 'unsigned long') to 'long' in initializer list [-Wc++11-narrowing-const-reference]
2635 |                  threshold},
|                  ^~~~~~~~~
$(SOURCE_ROOT)/cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp:2648:18: error: non-constant-expression cannot be narrowed from type 'ui64' (aka 'unsigned long') to 'long' in initializer list …
```
=> Fix clang-18 build

cloud/disk_manager/internal/pkg/services/shards/config/config.proto, cloud/disk_manager/internal/pkg/services/shards/config/ya.make, cloud/disk_manager/internal/pkg/services/shards/interface.go, cloud/disk_manager/internal/pkg/services/shards/mocks/service_mock.go, cloud/disk_manager/internal/pkg/services/shards/mocks/ya.make, cloud/disk_manager/internal/pkg/services/shards/service.go, cloud/disk_manager/internal/pkg/services/shards/ya.make, cloud/disk_manager/internal/pkg/services/ya.make
We introduce a new service to manage shard selection when creating disks. By default, disks are created in the first shard defined in the configuration. 
**Added features:**
- ShardService: a new component, that would be used by DiskService to select the target shard before disk creation.
- Default selection strategy: always use the first shard from the configuration.
=> [Disk Manager, SU] Introduce Shards service

cloud/blockstore/libs/storage/service/service_actor.h, cloud/blockstore/libs/storage/service/service_actor_actions.cpp, cloud/blockstore/libs/storage/service/service_actor_actions_mark_replacement_device.cpp, cloud/blockstore/libs/storage/service/service_ut_actions.cpp, cloud/blockstore/libs/storage/service/ya.make, cloud/blockstore/libs/storage/testlib/disk_registry_proxy_mock.h
На всякий случай добавляю ручку в blockstore-client, которая умеет менять состояние девайса fresh/не fresh
=> Add private API to mark devices as replacements

cloud/blockstore/libs/storage/volume/model/requests_time_tracker.cpp, cloud/blockstore/libs/storage/volume/model/requests_time_tracker.h, cloud/blockstore/libs/storage/volume/model/requests_time_tracker_ut.cpp, cloud/blockstore/libs/storage/volume/model/ya.make, cloud/blockstore/libs/storage/volume/volume_actor.h, cloud/blockstore/libs/storage/volume/volume_actor_forward.cpp
Сделал что по логам видно, через сколько после создания актора, диск начал отвечать на запросы. Именно в секундах, а не искать в логах старт таблетки, потом смотреть ну вот теперь ретраи кончились, наверное диск заработал
```
2025-05-24T11:52:12.109400Z :BLOCKSTORE_VOLUME INFO: [72075186224037890] Disk: "vol0", Generation: 20. The first successful Read request was started at 3.503s finished at 3.504s. The very first request was started at 3.503s Failed requests: 0
2025-05-24T11:52:12.342278Z :BLOCKSTORE_VOLUME INFO: [72075186224037890] Disk: "vol0", Generation: 20. The first successful Write request was started at 3.707s finished at 3.737s. The very first request was started at 3.707s Failed requests: 0
```
=> Log first request execution time and offset from volume creation

cloud/disk_manager/internal/pkg/facade/disk_service_test/.gitignore, cloud/disk_manager/internal/pkg/facade/disk_service_test/common_test.go, cloud/disk_manager/internal/pkg/facade/disk_service_test/disk_service_sharded_test.go, cloud/disk_manager/internal/pkg/facade/testcommon/common.go, cloud/disk_manager/internal/pkg/services/disks/service.go, cloud/disk_manager/internal/pkg/services/shards/config/config.proto, cloud/disk_manager/internal/pkg/services/shards/interface.go, cloud/disk_manager/internal/pkg/services/shards/mocks/service_mock.go, cloud/disk_manager/internal/pkg/services/shards/service.go, cloud/disk_manager/pkg/app/controlplane.go, cloud/disk_manager/test/recipe/disk_manager_launcher.py
We introduce a new service to manage shard selection when creating disks. By default, disks are created in the first shard defined in the configuration. We also add a mechanism to restrict shard placement for premium customers.
**Changes:**
- Blacklist / Whitelist support: define folders for which shard selection is allowed or disallowed.
- Added test for blacklist 
- Renamed folders in test recipe to better match the actual cluster
=> [Disk Manager, SU] Add shard service

cloud/blockstore/libs/daemon/common/bootstrap.cpp, cloud/blockstore/libs/daemon/common/bootstrap.h, cloud/blockstore/libs/daemon/local/config_initializer.cpp, cloud/blockstore/libs/daemon/local/config_initializer.h, cloud/blockstore/libs/disk_agent/bootstrap.cpp, cloud/filestore/libs/daemon/common/bootstrap.cpp, cloud/filestore/libs/daemon/common/bootstrap.h, cloud/storage/core/libs/daemon/config_initializer.h, cloud/storage/core/libs/diagnostics/logging.cpp, cloud/storage/core/libs/diagnostics/logging.h, cloud/storage/core/libs/diagnostics/ya.make, cloud/storage/core/libs/kikimr/config_initializer.cpp, cloud/storage/core/libs/kikimr/config_initializer.h
This PR enables support of `BackendFileName` option for server component. 
As for now, server component use its own logging service that only write to console. For actor components `BackendFileName` option is already working (it is parsed here https://github.com/ydb-platform/nbs/blob/main/contrib/ydb/core/log_backend/log_backend_build.cpp#L12-L14)
=> Enable logging to file for server component (`BackendFileName` option)

cloud/blockstore/libs/storage/init/server/actorsystem.cpp, cloud/blockstore/libs/storage/model/log_title.cpp, cloud/blockstore/libs/storage/model/log_title.h, cloud/blockstore/libs/storage/model/log_title_ut.cpp, cloud/blockstore/libs/storage/model/ut/ya.make, cloud/blockstore/libs/storage/model/ya.make, cloud/blockstore/libs/storage/partition/part.cpp, cloud/blockstore/libs/storage/partition/part.h, cloud/blockstore/libs/storage/partition/part_actor.cpp, cloud/blockstore/libs/storage/partition/part_actor.h, cloud/blockstore/libs/storage/partition/part_actor_initfreshblocks.cpp, cloud/blockstore/libs/storage/partition/part_actor_initschema.cpp, cloud/blockstore/libs/storage/partition/part_actor_loadstate.cpp, cloud/blockstore/libs/storage/partition/part_ut.cpp, cloud/blockstore/libs/storage/service/volume_session_actor_start.cpp, cloud/blockstore/libs/storage/testlib/test_env.cpp, cloud/blockstore/libs/storage/volume/partition_info.cpp, cloud/blockstore/libs/storage/volume/partition_info.h, cloud/blockstore/libs/storage/volume/testlib/test_env.cpp, cloud/blockstore/libs/storage/volume/volume.cpp, cloud/blockstore/libs/storage/volume/volume.h, cloud/blockstore/libs/storage/volume/volume_actor.cpp, cloud/blockstore/libs/storage/volume/volume_actor.h, cloud/blockstore/libs/storage/volume/volume_actor_addclient.cpp, cloud/blockstore/libs/storage/volume/volume_actor_allocatedisk.cpp, cloud/blockstore/libs/storage/volume/volume_actor_initschema.cpp, cloud/blockstore/libs/storage/volume/volume_actor_loadstate.cpp, cloud/blockstore/libs/storage/volume/volume_actor_startstop.cpp, cloud/blockstore/libs/storage/volume/volume_actor_updateconfig.cpp, cloud/blockstore/libs/storage/volume/volume_state.cpp
Начинаю приводить все логи NBS к единообразию.
пример:
```
2025-05-30T08:14:12.246206Z :BLOCKSTORE_VOLUME INFO: [v:72075186224037901 g:6 d:a7lqlcq73epjevval9 t:9.192ms] Activated executor
2025-05-30T08:14:12.266864Z :BLOCKSTORE_PARTITION INFO: [p1:72075186224037900 g:6 d:a7lqlcq73epjevval9 t:9.885ms] Schema initialized
2025-05-30T08:14:12.266865Z :BLOCKSTORE_PARTITION INFO: [p0:72075186224037899 g:6 d:a7lqlcq73epjevval9 t:9.894ms] Schema initialized
2025-05-30T11:06:47.617523Z :BLOCKSTORE_PARTITION INFO: [p:72075186224037890 g:15 d:dfgdgdfgdfgdfg t:35.351ms] Send garbage collector completed
```
Где:
v - таблетка вольюма
p - таблетка партишена, если партишен один
p0 - таблетка первого партишена
p1 - таблетка второго партишена
g - поколение
d - идентификатор диска
t - время в …
=> New format for log title

cloud/blockstore/libs/storage/volume/volume_actor_updateconfig.cpp
Сделал чтобы при создании диска в логи имя диска начинало писаться по-раньше.
```
2025-06-03T08:55:24.081490Z :BLOCKSTORE_VOLUME INFO: [v:72075186224037895 g:1 d:??? t:24.982ms] Activated executor
2025-06-03T08:55:24.082051Z :BLOCKSTORE_VOLUME INFO: [v:72075186224037895 g:1 d:??? t:25.526ms] Switched state "Boot" -> "Init" (system: [50000:7511644073264367462:4157], user: [50000:7511644073264367467:57], executor: [50000:7511644073264367478:57])
2025-06-03T08:55:24.096460Z :BLOCKSTORE_VOLUME INFO: [v:72075186224037895 g:1 d:??? t:39.946ms] Schema initialized
2025-06-03T08:55:24.096621Z :BLOCKSTORE_VOLUME INFO: [v:72075186224037895 g:1 d:??? t:40.118ms] State data loaded, time: 15.096ms
2025-06-03T08:55:24.097276Z :BLOCKSTORE_VOLUME INFO: [v:72075186224037895 g:1 d:nrd1 t:40.767ms] …
```
=> Update diskId for logging when disk created as soon as possible

cloud/blockstore/tests/client/test_with_client.py, cloud/blockstore/tests/config_dispatcher/test.py, cloud/blockstore/tools/cms/patcher/tests/data/files/dca1-ct5-13.cloud.net/nbs-names.txt, cloud/blockstore/tools/cms/patcher/tests/data/files/dca1-ct5-17.cloud.net/nbs-names.txt, cloud/blockstore/tools/cms/patcher/tests/data/files/dca1-ct5-18.cloud.net/nbs-names.txt, cloud/filestore/bin/dynamic/Configure-Root.txt, cloud/filestore/bin/nfs/names.txt, cloud/filestore/bin/static/names.txt, cloud/filestore/tests/config_dispatcher/test.py, example/dynamic/Configure-Root.txt, example/nbs/nbs-names.txt, example/static/names.txt
Get rid of warnings in examples:
```
[libprotobuf WARNING /home/dvrazumov/nbs/contrib/libs/protobuf/src/google/protobuf/text_format.cc:350] Warning parsing text-format NKikimrClient.TConsoleRequest: 65:15: text format contains deprecated field "Body"
[libprotobuf WARNING /home/dvrazumov/nbs/contrib/libs/protobuf/src/google/protobuf/text_format.cc:350] Warning parsing text-format NKikimrClient.TConsoleRequest: 66:13: text format contains deprecated field "WalleLocation"
```
=> Rename `WalleLocation` to `Location` and remove deprecated `Body` field

.github/config/muted_ya.txt, cloud/tasks/storage/storage_ydb_impl.go
The `TestFilesystemServiceCreateExternalFilesystem` test was failing because
`forceFinish` didn't set the end time. This caused `ClearEndedTask` to
prematurely clean the external task, leading retries to schedule new external
tasks. This commit fixes the issue by ensuring the end time is set when
`forceFinish` is called.
=> [Disk Manager] issue-3419: fix missing EndedAt when force finishing task

cloud/blockstore/libs/storage/testlib/test_runtime.h, cloud/blockstore/libs/storage/volume/testlib/test_env.cpp, cloud/blockstore/libs/storage/volume/testlib/test_env.h
Делаю юнит-тесты на вольюм чуть более похожими на реальное окружение:
1. можно делать два  вольюма в одном тесте (и не сложно расширяется)
2. добавляю схемшард, в который регистрируется вольюм при первом вызове UpdateVolumeConfig
=> Prepare volume unit tests to test multiple volumes

cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_lagging_devices_ut.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.cpp
Продолжение https://github.com/ydb-platform/nbs/issues/1720
Здесь синхронизируем код TNonreplicatedPartitionRdmaActor и TNonreplicatedPartitionActor который отменяет запросы в залагавшую реплику, чтобы было одинаково.
Начало было тут: https://github.com/ydb-platform/nbs/pull/3496
=> Multi-agent writes. Cancel write requests for all replicas with rdma backend

cloud/filestore/tests/python/lib/client.py, cloud/filestore/tests/recipes/vhost-endpoint/__main__.py
If we have multiple qemu instances in the test, only one session will be created because the session is retrieved using client_id (see: [tablet_actor_createsession](https://github.com/ydb-platform/nbs/blob/f335cf13806f31965fbf21692d17c1ea3661c57f/cloud/filestore/libs/storage/tablet/tablet_actor_createsession.cpp#L264)), and client_id is empty in the vhost_endpoint recipe. As a result, if we enable WriteBackCache or AsyncDestroyHandle, both clients will use the same FileRingBuffer, since the path to the FileRingBuffer is created using the SessionId, and the SessionId will be the same
=> issue-1541: set client_id upon start_endpoint in tests

cloud/blockstore/libs/storage/model/log_title.cpp, cloud/blockstore/libs/storage/model/log_title.h, cloud/blockstore/libs/storage/model/log_title_ut.cpp, cloud/blockstore/libs/storage/volume/volume_actor_acquire.cpp, cloud/blockstore/libs/storage/volume/volume_actor_forward.cpp, cloud/blockstore/libs/storage/volume/volume_actor_startstop.cpp
1. Сделал новый класс, который нужно использовать в дочерних акторах. Он печатает заголовок, указывая два времени, когда актор был рожден относительно времени родительского актора и когда случилось событие относительно времени рождения дочернего актора.  [v:72075186224037889 g:23 d:nrd1 t:1m 36s + 37us] означает что дочерний актор был создан в 1 мин 36 секунд, а событие залогировалось через 37 нс.
2. Привел к единому стилю логи вольюма про start-stop.
```
2025-06-10T17:01:58.757674Z :BLOCKSTORE_VOLUME INFO: [v:72075186224037889 g:23 d:nrd1 t:1m 36s + 37us] Sending acquire devices requests for client: "6d2f0c6-53c5462a-dc5efec1-2c1a93b3", targets: ( remote1-1024-1@remote1.cloud-example.net )
```
=> Introduce LogTitle for child actor. Use LogTitle for TAcquireDeviceActor and start-stop logs

cloud/disk_manager/internal/pkg/facade/filesystem_service_test/filesystem_service_test.go
It's not enough to wait for 10 seconds for external task to be scheduled.
https://github-actions-s3.storage.eu-north1.nebius.cloud/ydb-platform/nbs/Nightly-build/15512548490/1/nebius-x86-64/logs/cloud/disk_manager/internal/pkg/facade/filesystem_service_nemesis_test/test-results/filesystem_service_nemesis_test/chunk1/testing_out_stuff/filesystem_service_nemesis_test.TestFilesystemServiceCreateExternalFilesystem.log
=> fix failing TestFilesystemServiceCreateExternalFilesystem test

cloud/blockstore/libs/client/throttling_ut.cpp, cloud/blockstore/libs/diagnostics/request_stats.cpp, cloud/blockstore/libs/diagnostics/request_stats.h, cloud/blockstore/libs/diagnostics/server_stats.cpp, cloud/blockstore/libs/diagnostics/server_stats.h, cloud/blockstore/libs/diagnostics/server_stats_test.h, cloud/blockstore/libs/diagnostics/volume_stats.cpp, cloud/blockstore/libs/diagnostics/volume_stats.h, cloud/blockstore/libs/diagnostics/volume_stats_test.h, cloud/blockstore/libs/endpoint_proxy/server/proxy_storage.cpp, cloud/blockstore/libs/service_throttling/throttler_logger_ut.cpp, cloud/storage/core/libs/diagnostics/request_counters.cpp, cloud/storage/core/libs/diagnostics/request_counters.h, cloud/storage/core/libs/diagnostics/request_counters_ut.cpp
issue: #3371 
zero blocks requests can exceed 4 GiB
=> issue-3371: fix request bytes metric for large requests

cloud/blockstore/libs/storage/init/server/actorsystem.cpp, cloud/blockstore/libs/storage/model/log_title.cpp, cloud/blockstore/libs/storage/model/log_title.h, cloud/blockstore/libs/storage/model/log_title_ut.cpp, cloud/blockstore/libs/storage/service/service.cpp, cloud/blockstore/libs/storage/service/service.h, cloud/blockstore/libs/storage/service/service_actor.cpp, cloud/blockstore/libs/storage/service/service_actor.h, cloud/blockstore/libs/storage/service/service_actor_mount.cpp, cloud/blockstore/libs/storage/service/volume_session_actor.cpp, cloud/blockstore/libs/storage/service/volume_session_actor.h, cloud/blockstore/libs/storage/testlib/test_env.cpp
Размечаю логи сессий NBS-2, которые поднимается при blue-green обновлении значком ~.
```
2025-06-12T06:32:26.135055Z :BLOCKSTORE_SERVICE INFO: [~vs:72075186224037889 d:nrd1 s:1e1b1bd9-3a11f636-4f2bc03f-ef3d8a7b t:20.438ms] Mount completed for client "858fb7b1-522135b4-2efa48e5-675f9ad4", msg binding BINDING_REMOTE, msg source SOURCE_NONE, time "12983185534100", binding BINDING_REMOTE, source SOURCE_NONE
```
=> Make session logs better. Part 2. Show NBS-2 mark.

cloud/disk_manager/test/recipe/disk_manager_launcher.py
Handle connection errors which occur because the nemesis process restarts disk-manager.
=> [Disk Manager] Fix test flaps with nemesis

cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp, cloud/blockstore/libs/storage/volume/volume_actor_stats.cpp, example/3-start_nbs.sh
Добавлены подписи полей к кнопке Change Throttling Policy
и Throttling Policy status, который отображается, 
как Default, если настроена дефолтная throttling policy:
и как Custom, если пользователь указал свои кастомные значения для 
throttling policy: 
Также исправлены счетчики: MaxReadBandwidth, MaxWriteBandwidth, MaxReadIops, MaxWriteBandwidth, RealMaxWriteBandwidth.
В них передавались дефолтные значения, теперь передаются значения переопределённые с мон страницы.
=> Throttling policy fix

cloud/storage/core/tools/common/python/core_pattern.py
```
cloud/storage/core/tools/common/python/core_pattern.py:4: [F401] 'os.path.join' imported but unused
```
=> Fix linter error

cloud/disk_manager/internal/pkg/cells/cells.go, cloud/disk_manager/internal/pkg/cells/interface.go, cloud/disk_manager/internal/pkg/cells/mocks/cells_mock.go, cloud/disk_manager/internal/pkg/facade/disk_service_test/common_test.go, cloud/disk_manager/internal/pkg/facade/disk_service_test/disk_service_cells_test.go, cloud/disk_manager/internal/pkg/facade/disk_service_test/disk_service_test.go, cloud/disk_manager/internal/pkg/services/disks/service.go, cloud/disk_manager/internal/pkg/services/disks/service_test.go, cloud/disk_manager/internal/pkg/services/disks/ya.make
https://github.com/ydb-platform/nbs/issues/3614
This pull request adds support for the following operations in the Disk Manager API when working with cells:
- `ResizeDisk`
- `AlterDisk`
- `StatDisk`
- `MigrateDisk`
- `DescribeDisk`
To implement this, a new method `prepareZoneIDForExistingDisks` has been introduced in the `diskService`. Its main responsibility is to verify that a requested operation targets a valid disk in the correct zone.
The method will return an error if:
- The specified disk is not found.
- The disk's actual zone does not match the zone provided in the request.
=> [Disk Manager] Support other disk operations in scale units

cloud/blockstore/libs/daemon/common/bootstrap.cpp, cloud/blockstore/libs/endpoints/endpoint_manager.cpp, cloud/blockstore/libs/endpoints/endpoint_manager.h, cloud/blockstore/libs/endpoints/endpoint_manager_ut.cpp, cloud/blockstore/libs/endpoints/service_endpoint_ut.cpp, cloud/blockstore/libs/service/auth_scheme.cpp, cloud/blockstore/libs/service/request.h, cloud/blockstore/libs/service/request_helpers.h, cloud/blockstore/libs/storage/api/service.h, cloud/blockstore/libs/storage/service/service_actor_remove_client.cpp, cloud/blockstore/libs/storage/service/ya.make, cloud/blockstore/public/api/grpc/service.proto, cloud/blockstore/public/api/protos/endpoints.proto, cloud/blockstore/public/api/protos/volume.proto, cloud/blockstore/public/sdk/python/client/client.py, cloud/blockstore/tests/direct_device_acquire/test.py, cloud/blockstore/tests/direct_device_acquire/ya.make, cloud/blockstore/tools/testing/chaos-monkey/monkey_test.go
#1345 
keyring не песистентное хранилище, поэтому когда хост перезапускается из-за отключения питания, нбс поднимается и не находит эндпоинты в кейринге и соответственно ничего не ресторит. После приходит компьют и делает StopEndpoint, поскольку мы ничего не ресторили, этого эндпоинта у нас нет и мы отвечаем "hasn't been started yet".
После этого делаем KickEndpoint и на монтирование сперва отпраляем запрос на захват девайса, однако диск агент помнит что у него еще есть клиент, который не освободил девайс и отвечает ошибкой.
Компьют начнет передавать нам DiskId  и ClientId в StopEndpoint запросе, и если мы ничего не знаем об этом эндпоинте мы будет пытаться сделать RemoveClient и удаление эндпоинта
=> issue-1345: try to remove client if endpoint is unknown on StopEndpoint

cloud/filestore/config/server.proto, cloud/filestore/libs/service_local/config.cpp, cloud/filestore/libs/service_local/config.h, cloud/filestore/libs/service_local/fs_node.cpp, cloud/filestore/libs/service_local/index.cpp, cloud/filestore/libs/service_local/index.h, cloud/filestore/libs/service_local/index_ut.cpp, cloud/filestore/libs/service_local/lowlevel.cpp, cloud/filestore/libs/service_local/lowlevel.h, cloud/filestore/libs/service_local/lowlevel_ut.cpp, cloud/filestore/libs/service_local/session.h
=> [Filestore] issue-3687: implement pagination during ListNodes for local filestore

cloud/blockstore/libs/diagnostics/critical_events.h, cloud/blockstore/libs/storage/disk_agent/model/device_client.cpp, cloud/blockstore/libs/storage/disk_agent/model/device_client_ut.cpp, cloud/blockstore/libs/storage/disk_agent/model/public.h, cloud/blockstore/libs/storage/testlib/disk_registry_proxy_mock.h, cloud/blockstore/libs/storage/volume/model/checkpoint.cpp, cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp, cloud/blockstore/libs/storage/volume/volume_events_private.h, cloud/blockstore/libs/storage/volume/volume_ut_checkpoint.cpp
Этот pull request решает проблему: [NBS] Shadow disk does not release its devices after destruction #3097.
Shadow disk не освобождал свои девайсы после удаления чекпоинта, 
теперь эта проблема решена.
=> [NBS] shadow disk release devices after destruction

cloud/blockstore/config/server.proto, cloud/blockstore/libs/daemon/common/bootstrap.cpp, cloud/blockstore/libs/endpoints_vhost/external_vhost_server.cpp, cloud/blockstore/libs/endpoints_vhost/external_vhost_server.h, cloud/blockstore/libs/endpoints_vhost/external_vhost_server_ut.cpp, cloud/blockstore/libs/endpoints_vhost/ya.make, cloud/blockstore/libs/server/config.cpp, cloud/blockstore/libs/server/config.h, cloud/blockstore/vhost-server/backend_aio.cpp, cloud/blockstore/vhost-server/backend_null.cpp, cloud/blockstore/vhost-server/backend_rdma.cpp, cloud/blockstore/vhost-server/options.cpp, cloud/blockstore/vhost-server/options.h, cloud/blockstore/vhost-server/options_ut.cpp, cloud/blockstore/vhost-server/server_ut.cpp
#3743
Столкнулись с проблемой повышенного потребления памяти процессами blockstore-vhost-server из-за VmPTE. Это происходит из-за маппинга памяти гостя в наш процесс. При этом чем больше дисков у ВМки и чем она жирнее, тем хуже проблема. 
В качестве припарки я добавляю в конфиг параметр, который позводит включить сброс маппингов каждые N байт пропущенных через диск.
=> Add parameter to server config to configure vmpte flush threshold in the blockstore-vhost-server

cloud/blockstore/apps/client/lib/start_endpoint.cpp, cloud/blockstore/config/server.proto, cloud/blockstore/libs/daemon/common/bootstrap.cpp, cloud/blockstore/libs/endpoint_proxy/client/device_factory.cpp, cloud/blockstore/libs/endpoint_proxy/client/ya.make, cloud/blockstore/libs/endpoint_proxy/server/server.cpp, cloud/blockstore/libs/endpoints/endpoint_manager.cpp, cloud/blockstore/libs/endpoints/endpoint_manager.h, cloud/blockstore/libs/endpoints/endpoint_manager_ut.cpp, cloud/blockstore/libs/nbd/client_handler.cpp, cloud/blockstore/libs/nbd/device.cpp, cloud/blockstore/libs/nbd/device.h, cloud/blockstore/libs/nbd/netlink_device.cpp, cloud/blockstore/libs/nbd/netlink_device.h, cloud/blockstore/libs/nbd/utils.h, cloud/blockstore/libs/server/config.cpp, cloud/blockstore/libs/server/config.h, cloud/blockstore/tests/e2e-tests/test.py, cloud/blockstore/tools/nbd/bootstrap.cpp, cloud/blockstore/tools/nbd/options.cpp, cloud/blockstore/tools/nbd/options.h, cloud/storage/core/libs/netlink/message.h
- generalize netlink library to easily construct new messages
- use sysfs to find free nbd device when using ioctl
- let the driver find or allocate free device when using netlink
- add config option to toggle between new and old behavior
- remove 'reconfigure' parameter from TNetlinkDevice, because it was never used
- modify nbd client to correctly handle retries
=> implement automatic device allocation; resolves #1833 #3729 #3754

cloud/blockstore/tools/csi_driver/cmd/nbs-csi-driver/main.go, cloud/blockstore/tools/csi_driver/internal/driver/driver.go, cloud/blockstore/tools/csi_driver/internal/driver/node.go, cloud/blockstore/tools/csi_driver/internal/driver/node_test.go
issue: #3763 
Set retry timeout for StartEndpointRequest below grpc timeout to avoid GRPC_DEADLINE_EXCEEDED errors and dangling endpoints
=> [CSI] Set retry timeout for StartEndpointRequest

cloud/blockstore/libs/storage/volume/model/client_state.cpp, cloud/blockstore/libs/storage/volume/model/client_state.h, cloud/blockstore/libs/storage/volume/model/client_state_ut.cpp, cloud/blockstore/libs/storage/volume/volume_database.cpp, cloud/blockstore/libs/storage/volume/volume_state_ut.cpp
Лучше смотреть по-коммитно: в первом был сделан рефакторинг, во втором изменения логики.
Мы столкнулись с проблемой, когда при релизе после переключения клиента на новый NBS, из NBS-2 прилетает запоздавшее сообщение, которое деактивирует локальный пайп, и после этого на все запросы клиента отдается ошибка "E_BS_INVALID_SESSION No local mounter found".
Класс TVolumeClientState упорядочивает запросы одного клиента, которые идут через разные пайпы, так как клиент при blue-green обновлении подключается через разные процессы и в какой-то момент времени имеет несколько подключений. 
Общая идея TVolumeClientState в том что сообщения всегда принимаются только из одного пайпа, и сообщение из нового пайпа запрещает работу с предыдущим активным пайпом. Мы столкнулись с гонкой, когда NBS-2 два раза …
=> [Blockstore] request from remote pipe should not deactivate local pipe

cloud/filestore/libs/service/error.cpp, cloud/filestore/libs/service/error.h, cloud/filestore/libs/service_local/fs_data.cpp, cloud/filestore/libs/service_local/fs_node.cpp, cloud/filestore/libs/service_local/index.cpp, cloud/filestore/libs/service_local/index.h, cloud/filestore/libs/service_local/lowlevel.cpp, cloud/filestore/libs/service_local/lowlevel.h, cloud/filestore/libs/service_local/lowlevel_ut.cpp, cloud/filestore/libs/service_local/ya.make
#3617
After reverting previous not atomic implementation (create + chown). Use CAP_DAC_OVERRIDE to skip permission checks on the backend fs. The file/directory are going to be created atomically with proper uid/gid since with change euid/egid before executing the creation. But the backend won't complain on permissions since we restore the CAP_DAC_OVERRIDE capability
=> [Filestore] issue-3617: trust guest kernel to validate file permissions in local filestore

cloud/blockstore/libs/storage/model/public.h, cloud/blockstore/libs/storage/partition/part_actor_collectgarbage.cpp, cloud/blockstore/libs/storage/partition/part_actor_trimfreshlog.cpp, cloud/blockstore/libs/storage/partition/part_state.h, cloud/blockstore/libs/storage/partition/part_ut.cpp, cloud/blockstore/libs/storage/partition2/part2_actor_collectgarbage.cpp, cloud/blockstore/libs/storage/partition2/part2_actor_trimfreshlog.cpp, cloud/blockstore/libs/storage/partition2/part2_state.h, cloud/blockstore/libs/storage/partition_common/actor_trimfreshlog.cpp, cloud/blockstore/libs/storage/partition_common/actor_trimfreshlog.h, cloud/filestore/libs/storage/tablet/tablet_actor_collectgarbage.cpp, cloud/filestore/libs/storage/tablet/tablet_state.cpp, cloud/filestore/libs/storage/tablet/tablet_state.h
В BS барьеры складываются по ключу и значению.
Ключ это поколение таблетки и счетчик в рамках данного поколения. Значение это поколение барьера (у нас оно такое же как и таблетки) и шаг.
Если послать в BS барьер с уже существующим ключом, но другим значением, то сработает верифайка и соотв-но рестарт.
В текущей схеме мы берем commitId из очереди GarbageQueue и из него получаем поколение и шаг, попадает оно туда вызовом AcquireBarrier.
Сама очередь никак не сохраняется и существует только в памяти.
С включением фичи UncorfimedBlobs мы получили, ситуацию, когда после рестарта таблетки для всех загруженных неподтвержденных блобов мы дергаем AcquireBarrier, в который передаем commit id из "прошлого" и соответственно при следующей сборке мусора мы пошлем барьеры с прошлым поколением и …
=> [NBS] send current tablet generation (instead of generation parsed from commit id) in TEvBlobStorage::TEvCollectGarbage request

cloud/blockstore/libs/endpoints_vhost/external_vhost_server.cpp, cloud/blockstore/tests/vhost-server/run_and_die/__main__.py, cloud/blockstore/tests/vhost-server/test.py, cloud/blockstore/vhost-server/main.cpp, cloud/blockstore/vhost-server/options.cpp, cloud/blockstore/vhost-server/options.h
Флакающие тесты нашли проблему, что если процесс blockstore умирал сразу после запуска external_vhost_server, то external_vhost_server не успевал получить сигнал о смерти родителя и продолжал работать бесконечное время, вместо того чтобы выйти по таймауту. 
https://github-actions-s3.storage.eu-north1.nebius.cloud/ydb-platform/nbs/Nightly-build-(asan)/15965969456/1/nebius-x86-64-asan/test_data/actions-runner/_work/nbs/nbs/cloud/blockstore/tests/vhost-server/test-results/py3test/chunk1/testing_out_stuff/stdout
=> Fix infinite vhost run when parent exit immediately after fork

cloud/storage/core/libs/common/file_io_service.cpp, cloud/storage/core/libs/common/file_io_service.h, cloud/storage/core/libs/common/file_io_service_ut.cpp
#3314
Add TConcurrentFileIOService adaptor that submits requests to underlying IFileIOService from a single thread.
=> issue-3314: add TConcurrentFileIOService adaptor

cloud/storage/core/libs/common/file_ring_buffer.cpp
Extracted from https://github.com/ydb-platform/nbs/pull/3790
Code deduplication: consolidate memory access code in a single place.
Motivation: the same logic should be used in `Visit`, `PopFront`, `PushBack` but currently there already exists inconsistency. For example, in the case of corruption, `Visit` and `PopFront` may produce different results.
Next: https://github.com/ydb-platform/nbs/pull/3816
=> TFileRingBuffer: refactoring - extract memory access related code to TFileRingBufferData

cloud/blockstore/apps/client/lib/command.cpp, cloud/blockstore/config/server.proto, cloud/blockstore/libs/client/bench/main.cpp, cloud/blockstore/libs/daemon/common/bootstrap.cpp, cloud/blockstore/libs/encryption/encryption_client.cpp, cloud/blockstore/libs/encryption/encryption_client.h, cloud/blockstore/libs/encryption/encryption_client_ut.cpp, cloud/blockstore/libs/encryption/encryption_service_ut.cpp, cloud/blockstore/libs/endpoints/endpoint_manager_ut.cpp, cloud/blockstore/libs/endpoints/session_manager_ut.cpp, cloud/blockstore/libs/server/config.cpp, cloud/blockstore/libs/server/config.h, cloud/vm/blockstore/lib/plugin.cpp
При чтениях мы смотрим на содержимое блока, и если он заполнен нулями, то его не нужно расшифровывать.
Это позволяет для TZeroBlocksRequest не писать шифрованные блоки с нулями, а делать обычный ZeroBlocks. 
Discard запросы от клиента могут быть очень большие, и шифровать гигабайтные блоки и писать их выходит очень медленно.
=> Remove encryption in zero blocks request

cloud/blockstore/tools/csi_driver/internal/driver/node.go, cloud/blockstore/tools/csi_driver/internal/monitoring/monitoring.go, cloud/blockstore/tools/csi_driver/internal/monitoring/monitoring_test.go, cloud/blockstore/tools/csi_driver/internal/ya.make
issue: #3804
Report mount conflict errors using a separate counter, as we want to configure alerts differently for various CSI error types.
1. return AlreadyExists error code if StartEndpoint returned E_MOUNT_CONFLICT
2. Report mount conflicts errors as a separate counter
=> [CSI] Report mount conflicts as a separate counter

cloud/blockstore/libs/endpoints/endpoint_manager.cpp
ProcessException can potentially yield control to another coroutine executing ProcessException. This leads to a race condition if it was invoked after endpoint's generation has already been increased
=> fix race condition during error handler execution

cloud/filestore/libs/vfs_fuse/fs_impl_data.cpp, cloud/filestore/libs/vfs_fuse/write_back_cache/write_back_cache.h
=> issue-1751: fix crash when server write-back cache is enabled but was not successfully initialized

cloud/blockstore/tools/csi_driver/internal/driver/node.go, cloud/blockstore/tools/csi_driver/internal/monitoring/monitoring.go, cloud/blockstore/tools/csi_driver/internal/monitoring/monitoring_test.go
issue: https://github.com/ydb-platform/nbs/issues/3804
Count Aborted(another operation is in progress), AlreadyExists(mount conflict) and Unavailable(grpc unavailable) as retriable errors
=> [CSI] Split counters for fatal and retriable errors

cloud/blockstore/libs/storage/core/monitoring_utils.cpp, cloud/blockstore/libs/storage/core/monitoring_utils.h, cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp
Раньше страница перерисовывалась каждую секунду и оставляла об этом лог. Теперь должны быть соблюдены 3 условия для обновления:
- включено автообновление;
- вкладка сайта открыта;
- выбран пункт Transactions/Latency.
=> Reduce frequency of log writes on tablet monitoring page

cloud/tasks/config/config.proto, cloud/tasks/runner.go, cloud/tasks/runner_test.go, cloud/tasks/tasks_tests/tasks_test.go
#1950
We have MaxRetriableErrorCount parameter in tasks config (100 by default). This value might not be reasonable for some types of tasks. Add ability to set this parameter by task type.
Further we are going to use this parameter for `dataplane.CreateDRBasedDiskCheckpoint` task in order to limit the number of shadow disks that can be created by a single task.
=> [Disk Manager] Add max retriable error count per task type

cloud/blockstore/libs/daemon/common/bootstrap.cpp, cloud/blockstore/libs/disk_agent/bootstrap.cpp, cloud/blockstore/tools/testing/rdma-test/bootstrap.cpp, cloud/filestore/libs/daemon/common/bootstrap.cpp, cloud/storage/core/libs/diagnostics/trace_processor_mon_ut.cpp, cloud/storage/core/libs/diagnostics/trace_reader.cpp, cloud/storage/core/libs/diagnostics/trace_reader.h, cloud/storage/core/libs/opentelemetry/impl/trace_convert.cpp, cloud/storage/core/libs/opentelemetry/impl/trace_convert.h, cloud/storage/core/libs/opentelemetry/impl/trace_reader.cpp, cloud/storage/core/libs/opentelemetry/impl/trace_reader.h, cloud/storage/core/libs/opentelemetry/impl/trace_ut.cpp, cloud/vm/blockstore/bootstrap.cpp
#1223 
В этом пре рефакторинг Trace ридеров, чтобы их код можно было переиспользовать и прикручивание экспорта трейсов для медленных запросов
=> issue-1223: refactor trace readers and add traces export for slow requests

cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_lagging_agents.cpp
Если лагал источник миграции, то мы заменяем его на цель миграции (и делаем его фрешом). После этого ПРа замененённые девайсы попадут в "AutomaticallyReplacedDevices". Плюс выставляю сообщение в девайс для прозрачности
=> Add lagging replaced device to AutomaticallyReplaced; Update device state message

cloud/storage/core/libs/common/file_ring_buffer.cpp, cloud/storage/core/libs/common/file_ring_buffer_ut.cpp
Mitigation for https://github.com/ydb-platform/nbs/issues/3792: do nothing when the capacity value is changed.
=> TFileRingBuffer: do not fail when the requested capacity differs from the existing capacity

cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_notify.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_private.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_cms.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_lagging_agents.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_migration.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_mirrored_disks.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_tx.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_lifecycle.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor.cpp, cloud/blockstore/libs/storage/protos/volume.proto, cloud/blockstore/libs/storage/volume/volume_actor_allocatedisk.cpp, cloud/blockstore/libs/storage/volume/volume_actor_lagging_agents.cpp, cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp, cloud/blockstore/libs/storage/volume/volume_actor_reallocatedisk.cpp, cloud/blockstore/libs/storage/volume/volume_actor_startstop.cpp, cloud/blockstore/libs/storage/volume/volume_actor_stats.cpp, cloud/blockstore/libs/storage/volume/volume_events_private.h, cloud/blockstore/libs/storage/volume/volume_lagging_agent_ut.cpp, cloud/blockstore/libs/storage/volume/volume_state.cpp, cloud/blockstore/libs/storage/volume/volume_state.h
#3505
Сейячас есть проблема: DR может "за раз" отстрелить 2 реплики у диска и пронотифицировать его об этом. А у того третья реплика может быть в lagging. В итоге получаем три fresh девайса в ряду.
Здесь первый шаг чтобы это починить: добавляю в ответ реаллокации текущие лагающие девайсы. 
Следущий шаг: менять только одну реплику за нотификацию.
=> Add lagging devices to the reallocation response

cloud/blockstore/libs/discovery/ping.cpp, cloud/blockstore/libs/endpoint_proxy/client/client.cpp, cloud/blockstore/libs/kms/impl/compute_client.cpp, cloud/blockstore/libs/kms/impl/kms_client.cpp, cloud/blockstore/libs/root_kms/impl/client.cpp, cloud/storage/core/libs/opentelemetry/impl/trace_service_client.cpp, cloud/storage/core/libs/opentelemetry/impl/trace_service_client_ut.cpp, cloud/storage/core/libs/opentelemetry/impl/ut/ya.make, cloud/storage/core/libs/opentelemetry/impl/ya.make
#1223
После раскатки бинаря с трейсами на некоторых хостах, на которых не был поднят эндпоинт принимающий трейсы, начал переодически крашиться нбс, причем делал он это достаточно часто и с абсолютно рандомными стек трейсами.
Запустил бинарь под асаном и нашел UAF при неудачных попытках экспортировать трейсы.
Место в котором происходло обращение к освобожденной памяти:
```
0x557f8400e5a3 is in NCloud::(anonymous namespace)::TTraceServiceClient::Export() (/home/iajwjw/arcadia/util/generic/ptr.h:560).
```
место где память освобождалась
```
0x557f7fbc42bd is in operator delete() (/home/iajwjw/arcadia/contrib/libs/clang16-rt/lib/asan/asan_new_delete.cpp:152).
0x557f8400c230 is in NCloud::(anonymous namespace)::TTraceServiceClient::ThreadProc() …
```
=> issue-1223: fix use after free in GRPC clients

cloud/blockstore/libs/storage/partition_nonrepl/model/device_stats.cpp
После того как пользователь сделал 2^32 - 10 запросов, `ResponseTimes.TotalSize()` становится недостижим для ui32 и получается вечный цикл
=> Fix NBS going into infinite loop

cloud/blockstore/libs/storage/core/config.cpp, cloud/blockstore/libs/storage/core/config_ut.cpp, cloud/blockstore/tests/local_ssd/test.py
Заметили проблему, что значение, которое имеет ненулевой дефолт в коде нельзя занулить через proto файл
=> Fix storage config overrides with proto

cloud/storage/core/libs/opentelemetry/impl/trace_convert.cpp, cloud/storage/core/libs/opentelemetry/impl/trace_ut.cpp
#1223 
В SU из-за  передачи тейсов между хостами spanId зануляются и у нас получаются невалидные трейсы: 
```
[["RequestStarted",0,"WriteBlocks","1","12195966460240083936","fsahing5ucj5vjbjqmjr","5256160","4096"],
["RequestReceived",10,"WriteBlocksLocal","1","12195966460240083936","fsahing5ucj5vjbjqmjr"],
["RequestEnqueued",19,"12195966460240083936"],
["SendRequestStarted",34,"12195966460240083936"],
["SendRequestCompleted",63,"12195966460240083936"],
["RecvResponseCompleted",725,"12195966460240083936"],
["RequestReceived_Cells",108],
["RequestSent_Proxy",120,"WriteBlocksLocal","0"],
["RequestReceived_Service",124,"WriteBlocksLocal","0"],
["RequestReceived_Volume",127,"WriteBlocksLocal","0"],
["RequestAdvanced_Volume",129,"WriteBlocksLocal","0"],
["Fork",131,"0"],
["Join",637,"0","11"], …
```
=> issue-1223: parse traces even if span IDs are invalid

cloud/blockstore/libs/endpoints/endpoint_manager.cpp, cloud/blockstore/tests/direct_device_acquire/test.py
#1345 в случае если на StopEndpoint эндпоинт не нашелся мы делаем RemoveClient и удаляем сокет.
Если диск был удален то ошибка от схемшарда тупа прокидывапется наружу, к чему компьют не готов. Необходимо игнорировать такую ошибку и успешно завершать вызов StopEndpoint
=> issue-1345: ignore path not found error from schemeshard while removing client on StopEndpoint

cloud/blockstore/libs/storage/partition_nonrepl/lagging_agent_migration_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_mirror.cpp, cloud/blockstore/libs/storage/volume/actors/shadow_disk_actor.cpp, cloud/blockstore/libs/storage/volume/partition_info.cpp, cloud/blockstore/libs/storage/volume/partition_info.h, cloud/blockstore/libs/storage/volume/volume_actor.h, cloud/blockstore/libs/storage/volume/volume_actor_startstop.cpp
Продолжение https://github.com/ydb-platform/nbs/issues/2999
1. При помещении актора или обертка и стек явно указываю что это за актор
2. даю возможность тонкой настройки владения акторами источника и назначения для миграционного актора.
3. При удалении реплицированного партишена явно удаляю актор-обертку (если он есть).
=> Refactor actors ownership for migration-related actors

cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp
Починил отображение значений латенси на стороне фронтенда.
=> Fix update info in latency table

cloud/blockstore/libs/disk_agent/bootstrap.cpp, cloud/blockstore/libs/disk_agent/bootstrap.h
У диск агента создавался `StatsFetcher`, но никогда не запускался. Из-за этого сбор метрики cpu wait не работал и сыпались крит эвенты раз в 15 секунд
=> Fix cpu wait sensor for disk agent

.github/actions/test/action.yaml
Removing binaries that get into logs dir, trim logs and remove NVMENBS devices
```2025-06-20 06:51:56    4.3 GiB ydb-platform/nbs/Nightly-build-(ubsan)/15770371815/1/nebius-x86-64-ubsan/logs/cloud/blockstore/apps/server/nbsd
2025-06-22 07:04:03    4.3 GiB ydb-platform/nbs/Nightly-build-(ubsan)/15802401659/1/nebius-x86-64-ubsan/logs/cloud/blockstore/apps/server/nbsd
2025-06-23 06:58:51    4.3 GiB ydb-platform/nbs/Nightly-build-(ubsan)/15814431634/1/nebius-x86-64-ubsan/logs/cloud/blockstore/apps/server/nbsd
2025-06-24 06:48:54    4.3 GiB ydb-platform/nbs/Nightly-build-(ubsan)/15840299123/1/nebius-x86-64-ubsan/logs/cloud/blockstore/apps/server/nbsd
2025-06-20 05:59:34    7.4 GiB ydb-platform/nbs/Nightly-build/15767722792/1/nebius-x86-64/logs/cloud/blockstore/apps/server/nbsd
2025-06-21 …
```
=> fix: additional things not to store at s3

cloud/blockstore/tools/csi_driver/internal/driver/node.go
issue: #3804 
fmt.Errorf doesn't use error code and return codes.Internal
=> [CSI] return the correct error code

cloud/filestore/libs/service_local/service_ut.cpp
Test [failure](https://github-actions-s3.storage.eu-north1.nebius.cloud/ydb-platform/nbs/PR-check/16423472213/1/nebius-x86-64/logs/1/cloud/filestore/libs/service_local/ut/test-results/unittest/chunk12/testing_out_stuff/LocalFileStore.ShouldStatFileStore.err) due to file creation race on test filesytem
=> fix race in ShouldStatFileStore unit test

cloud/blockstore/libs/storage/core/config.cpp
Поведение никак не меняется. Заменил вызовы `NCloud::HasField()` с лукапом по хешмапе на обычные вызовы методов `HasXxx()` или `XxxSize()`. Для этого пришлось выделить отдельный макрос для repeated полей в proto, но кажется оно того стоит.
=> Get rid of NCloud::HasField in storage config

cloud/blockstore/libs/client/client.cpp
```
$(SOURCE_ROOT)/cloud/blockstore/libs/client/client.cpp:849:24: error: use 'template' keyword to treat 'ExecuteRequest' as a dependent template name
849 |         return Client->ExecuteRequest<TWriteBlocksMethod>(
|                        ^
|                        template 
$(SOURCE_ROOT)/cloud/blockstore/libs/client/client.cpp:860:31: error: use 'template' keyword to treat 'ExecuteRequest' as a dependent template name
860 |         auto future = Client->ExecuteRequest<TReadBlocksMethod>(
|                               ^
|                               template 
2 errors generated.
```
=> Fix clang-20 compilation error

cloud/blockstore/libs/diagnostics/critical_events.cpp, cloud/blockstore/libs/diagnostics/critical_events.h, cloud/blockstore/libs/endpoints/endpoint_manager.cpp, cloud/blockstore/libs/rdma/iface/protobuf.cpp, cloud/blockstore/libs/service_kikimr/service_kikimr.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_migration.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_register.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp, cloud/blockstore/libs/storage/model/composite_task_waiter.cpp, cloud/blockstore/libs/storage/partition/part_actor.cpp, cloud/blockstore/libs/storage/partition/part_actor.h, cloud/blockstore/libs/storage/partition/part_actor_addconfirmedblobs.cpp, cloud/blockstore/libs/storage/partition/part_actor_compaction.cpp, cloud/blockstore/libs/storage/partition/part_actor_confirmblobs.cpp, cloud/blockstore/libs/storage/partition/part_actor_readblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_actor_resync.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_state.cpp, cloud/blockstore/libs/storage/service/service_actor_sync_manually_preempted_volumes.cpp
Теперь функции Report<EventName> принимают дополнительно список пар ключ-значение, которые форматируются в строку и добавляются к основному сообщению.
Так было раньше: `CRITICAL_EVENT:AppCriticalEvents/EndpointRestoringError:Endpoint restoring error occurred for endpoint ID: 5, socket path: wrongSocket1`
так сейчас:  `CRITICAL_EVENT:AppCriticalEvents/EndpointRestoringError:Endpoint restoring error occurred; endpoint_id=5; socket_path=wrongSocket1`
То есть структура лога —` <сообщение>; <ключ1>=<значение1>; <ключ2>=<значение2>; ...`
апдейт репортов с ResyncFailed до ReleaseShadowDiskError
=> Unification for report logs and adding description

contrib/ydb/core/driver_lib/run/kikimr_services_initializers.cpp
https://github.com/ydb-platform/ydb/pull/21959
=> Use unique_ptr to allocate TInterconnectListenerTCP in kikimr_services_initializers.cpp to aviod memory leak on Bind() failure

cloud/blockstore/config/storage.proto, cloud/blockstore/libs/storage/core/config.cpp, cloud/blockstore/libs/storage/core/config.h, cloud/blockstore/libs/storage/ss_proxy/ss_proxy_actor_describescheme.cpp, cloud/blockstore/libs/storage/ss_proxy/ss_proxy_ut.cpp, cloud/blockstore/libs/storage/testlib/test_env.cpp, cloud/blockstore/tests/mount/test.py, example/nbs/nbs-storage.txt
Коллеги из YDB посоветовали отказаться от использования TxProxy для дескрайбов и перейти на SchemeCache. 
Во-первых, TxProxy считается deprecated кодом. Во-вторых, он и так ходит в SchemeCache для получения нужной информации. То есть логика здесь сильно не поменяется.
=> Add ability to use SchemeCache directly instead of TxProxy

cloud/blockstore/libs/storage/api/disk_registry.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_get_cluster_capacity.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_ut_allocation.cpp, cloud/blockstore/libs/storage/disk_registry/testlib/test_env.h, cloud/blockstore/libs/storage/disk_registry/ya.make, cloud/blockstore/libs/storage/protos/disk.proto, cloud/blockstore/libs/storage/service/service_actor.h, cloud/blockstore/libs/storage/service/service_actor_actions.cpp, cloud/blockstore/libs/storage/service/service_actor_actions_get_cluster_capacity.cpp, cloud/blockstore/libs/storage/service/service_ut_actions.cpp, cloud/blockstore/libs/storage/service/ya.make, cloud/blockstore/libs/storage/testlib/disk_registry_proxy_mock.h, cloud/blockstore/private/api/protos/disk.proto
https://github.com/ydb-platform/nbs/issues/3614
Add `GetClusterCapacity` handler that collects cluster utilization information from YDB and DiskRegistry and returns it grouped by disk types.
This handler will be used by `Disk Manager` to intelligently distribute newly created disks across shards.
For collecting data from Disk Registry, an analogous handler has been added. For collecting from YDB, `GetStorageStatsRequest` is used (https://github.com/ydb-platform/ydb/blob/911050b753e7fb532f13324f65d2a167e8045e37/ydb/core/protos/sys_view.proto#L353-L358)
=> [Blockstore] Add GetClusterCapacity handler

cloud/filestore/libs/storage/service/service_actor_xattr.cpp
It may happen that during release the vhost and the server temporary have different versions.
The code in TStorageServiceActor didn't take into account.
Now HasXAttrs flags is hidden under LazyXAttrsEnabled flag.
=> [Filestore] Patch. Hide HasXAttrs under LazyXAttrsEnabled flag on TStorageServiceActor side

cloud/blockstore/libs/storage/volume/testlib/test_env.cpp, cloud/blockstore/libs/storage/volume/testlib/test_env.h, cloud/blockstore/libs/storage/volume/volume_ut.cpp
Наступил в проблему, что когда происходит рестарт таблетки, то тестовая акторная система НЕ вызывает установленные фильтры и обработчики. Все потому, что на это время создается TTabletScheduledEventsGuard, который временно заменяет все обработчики на свой, и НЕ вызывает по цепочке старые.
Это приводит к забавным спецэффектам, что акторы, созданные во время RebootTablet, не видны нашему обработчику, который делает EnableScheduleForActor(), также сообщения не видны фильтру сообщений в самом тесте.
=> Fix missing events during tablet reboot

cloud/filestore/libs/storage/service/service_actor_readdata.cpp, cloud/filestore/libs/storage/service/service_ut.cpp, cloud/filestore/tools/testing/loadtest/lib/request_data.cpp
issue: https://github.com/ydb-platform/nbs/issues/3988
Move  BlockBuffer to response and use set buffer offset field.
=> issue-3988: refactor TReadDataActor to avoid data buffer copy

cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_readblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
Делаю возможным быстрый ретрай запроса чтения, у которого не совпала чексумма по данным и чексумма диск агента. 
Код в durable клиенте не позволит одному запросу поретраиться без задержки больше одного раза. Поэтому проблем это создать не должно.
=> Allow to instantly retry read2 checksum mismatch

cloud/blockstore/libs/storage/partition/part_actor_stats.cpp, cloud/blockstore/libs/storage/partition2/part2_actor_stats.cpp
Если сообщение TEvPartitionCommonPrivate::TEvGetPartCountersRequest придет слишком рано когда мы не инициализировали состояние то будет краш
```
#0 NCloud::NBlockStore::NProto::TPartitionMeta::_internal_stats (this=0x0) at /-B/cloud/blockstore/libs/storage/protos/part.pb.h +5066
#1 NCloud::NBlockStore::NProto::TPartitionMeta::stats (this=0x0) at /-B/cloud/blockstore/libs/storage/protos/part.pb.h +5072
#2 NCloud::NBlockStore::NProto::TPartitionMeta::GetStats (this=0x0) at /-B/cloud/blockstore/libs/storage/protos/part.pb.h +1650
#3 NCloud::NBlockStore::NStorage::NPartition::TPartitionState::GetStats (this=0x0) at /opt/buildagent/work/4ec98910e7de170b/__FUSE/mount_path/cloud/blockstore/libs/storage/partition/part_state.h +1405
#4 NCloud::NBlockStore::NStorage::NPartition::TPartitionState::Get …
```
=> [NBS] dont extract partition counters if there is no state

cloud/blockstore/libs/storage/disk_registry/disk_registry_self_counters.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_self_counters.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
Cleaning obsolete counters (more info in commit https://github.com/ydb-platform/nbs/commit/c18bfdf04b8a5b189d6abb0dd87a7bf6567330c8)
The counters should be replaced to the new ones:
```
PlacementGroupsWithRecentlyBrokenSingleDisk -> PlacementGroupsWithRecentlyBrokenSinglePartition
PlacementGroupsWithRecentlyBrokenTwoOrMoreDisks -> PlacementGroupsWithRecentlyBrokenTwoOrMorePartitions
PlacementGroupsWithBrokenSingleDisk -> PlacementGroupsWithBrokenSinglePartition
PlacementGroupsWithBrokenTwoOrMoreDisks -> PlacementGroupsWithBrokenTwoOrMorePartitions
```
=> [NBS] remove obsolete PlacementGroupWith*Disk counters

cloud/blockstore/libs/storage/model/log_title.cpp, cloud/blockstore/libs/storage/model/log_title.h, cloud/blockstore/libs/storage/model/log_title_ut.cpp, cloud/blockstore/libs/storage/partition/part_actor.cpp, cloud/blockstore/libs/storage/partition2/part2_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.h, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_checksumblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_readblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_writeblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_writeblocks_multi_agent.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_zeroblocks.cpp, cloud/blockstore/libs/storage/service/volume_client_actor.cpp, cloud/blockstore/libs/storage/service/volume_session_actor.h, cloud/blockstore/libs/storage/service/volume_session_actor_start.cpp, cloud/blockstore/libs/storage/volume/actors/forward_write_and_mark_used_ut.cpp, cloud/blockstore/libs/storage/volume/actors/read_and_clear_empty_blocks_actor_ut.cpp, cloud/blockstore/libs/storage/volume/actors/read_disk_registry_based_overlay_ut.cpp, cloud/blockstore/libs/storage/volume/actors/volume_as_partition_actor_ut.cpp, cloud/blockstore/libs/storage/volume/volume_actor.cpp, cloud/blockstore/libs/storage/volume_proxy/volume_proxy.cpp
before
`2025-08-11T10:30:26.571690Z node 39 :BLOCKSTORE_PARTITION INFO: [vol0] Agent "agent-2" has become unavailable`
after
`2025-08-11T10:25:41.210592Z node 39 :BLOCKSTORE_PARTITION INFO: [nrd:vol0 t:27.482ms] Agent "agent-2" has become unavailable`
также было решено переделать процесс создания TLogTitle , чтобы избежать путаницы
=> Logtitle refactoring, partition nonrepl remake.

.github/actions/test/action.yaml, .github/scripts/tests/generate-summary.py, .github/scripts/tests/transform-ya-junit.py
fixes few problems:
* orig_junit.xml was not original, it was after transform-ya-junit.py
* in case of `test.py.test_csi_sanity_nbs_backend[/var/lib/kubelet/pods/123/volumes/kubernetes.io~csi/456/mount-mount-True-skip_tests2]` LOGS ARE EMTPY message was wrong, because it was identified incorrectly because of `kubernetes.io` string in test parameters
=> fix: LOGS ARE EMPTY are wrong in case of dot in test arguments

cloud/filestore/libs/vfs_fuse/write_back_cache/disjoint_interval_map.cpp, cloud/filestore/libs/vfs_fuse/write_back_cache/disjoint_interval_map.h, cloud/filestore/libs/vfs_fuse/write_back_cache/disjoint_interval_map_ut.cpp, cloud/filestore/libs/vfs_fuse/write_back_cache/ut/ya.make, cloud/filestore/libs/vfs_fuse/write_back_cache/write_back_cache.cpp, cloud/filestore/libs/vfs_fuse/write_back_cache/write_back_cache.h, cloud/filestore/libs/vfs_fuse/write_back_cache/write_back_cache_impl.h, cloud/filestore/libs/vfs_fuse/write_back_cache/write_back_cache_util.cpp, cloud/filestore/libs/vfs_fuse/write_back_cache/write_back_cache_util_ut.cpp, cloud/filestore/libs/vfs_fuse/write_back_cache/ya.make
Switch from long running linear search (in about ~250k elements) to O(log n) algorithm.
=> issue-1751: Optimize CalculateDataPartsToRead in TWriteBackCache using disjoint interval tree

cloud/filestore/libs/vfs_fuse/write_back_cache/write_back_cache.cpp, cloud/filestore/libs/vfs_fuse/write_back_cache/write_back_cache.h, cloud/filestore/libs/vfs_fuse/write_back_cache/write_back_cache_impl.h, cloud/filestore/libs/vfs_fuse/write_back_cache/write_back_cache_ut.cpp, cloud/filestore/libs/vfs_fuse/write_back_cache/write_back_cache_util.cpp
=> issue-1751: split TWriteDataEntry::IsFinished into IsCorrupted and IsFlushed; rename TWriteDataEntry::Finish to FinishFlush; cleanup comments

cloud/blockstore/tools/csi_driver/internal/driver/node.go, cloud/blockstore/tools/csi_driver/internal/driver/node_test.go, cloud/blockstore/tools/csi_driver/internal/monitoring/monitoring.go
1. handle DeadlineExceded error as retriable
2. return statusError to avoid error code loosing
3. Modify GetGrpcErrorCode to convert all error codes(nbs/nfs/csi) to grpc error codes
=> csi: handle deadline exceeded error as retriable

cloud/blockstore/config/storage.proto, cloud/blockstore/libs/endpoints/endpoint_manager.cpp, cloud/blockstore/libs/storage/api/volume.h, cloud/blockstore/libs/storage/core/config.cpp, cloud/blockstore/libs/storage/core/config.h, cloud/blockstore/libs/storage/volume/volume_actor.h, cloud/blockstore/libs/storage/volume/volume_actor_addclient.cpp, cloud/blockstore/libs/storage/volume/volume_actor_release.cpp, cloud/blockstore/libs/storage/volume/volume_actor_removeclient.cpp, cloud/blockstore/libs/storage/volume/volume_tx.h, cloud/blockstore/libs/storage/volume/volume_ut.cpp, cloud/blockstore/tests/direct_device_acquire/test.py
#1345
В этом пре я поменял порядок действий для нрд дисков, сначала мы выполняем транзакцию AddClient\RemoveClient, и уже только после этого делаем все нужные захваты освобождения девайсов. И таким образом когда хост выйдет по питанию и стартанет заного мы придем в волум с новым запросом на монтирование, волум выбьет старого клиента (т.к. он слишком много времени был неактивен) транзакцией AddClient, после нее мы сделаем сначала Release от всех старых клиентов и сделаем Acquire для нового клиента и только после этого ответим, что успешно добавили нового клиента
Для удаления клиента ситуация аналогичная: сначала мы выполняем транзакцию RemoveClient, которое сделает все, что нужно с локальной базой, и только после этого посылаем запросы на освобождение девайссов
=> issue-1345: changed the order of AddClient\RemoveClient transactions and Acquire\Release devices during mount operations for DR-based disks

cloud/blockstore/libs/diagnostics/stats_aggregator.cpp, cloud/blockstore/libs/diagnostics/stats_aggregator_ut.cpp, cloud/storage/core/libs/user_stats/counter/user_counter.cpp
**Summary**
Update TStatsAggregator to be compatible with the recent changes introduced in [ydb-platform/nbs#4029](https://github.com/ydb-platform/nbs/pull/4029)
**Motivation**
Recent changes in [PR #4029](https://github.com/ydb-platform/nbs/pull/4029) modified the way counters are handled. As a result, TStatsAggregator was no longer compatible, causing several load test to fail (`cloud/blockstore/tests/loadtest/local*`). This PR aligns TStatsAggregator with the new behavior and restores the affected tests.
=> Fix TStatsAggregator

cloud/blockstore/libs/diagnostics/user_counter_ut.cpp, cloud/storage/core/libs/user_stats/counter/user_counter.cpp
Currently user counters work only through multiple-counter histogram:
```
histogram=Time:
sensor=0.001ms: 248
sensor=0.1ms: 15
sensor=0.2ms: 23
...
sensor=10000ms: 7
sensor=35000ms: 6
sensor=Inf: 0
```
This PR make it possible to calculate `users_stats` with single-counter histogram as well:
```
sensor=Time:
bin=0.001: 248
bin=0.1: 15
bin=0.2: 23
...
bin=10000: 7
bin=35000: 6
bin=inf: 0
```
=> [NBS, Filestore] Make user counter able to work with both single and multiple counter histograms

cloud/filestore/config/storage.proto, cloud/filestore/libs/storage/core/config.cpp, cloud/filestore/libs/storage/core/config.h, cloud/filestore/libs/storage/tablet/model/mixed_blocks.cpp, cloud/filestore/libs/storage/tablet/tablet_actor.h, cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp, cloud/filestore/libs/storage/tablet/tablet_database.cpp, cloud/filestore/libs/storage/tablet/tablet_database.h, cloud/filestore/libs/storage/tablet/tablet_state.cpp, cloud/filestore/libs/storage/tablet/tablet_state_cache.cpp, cloud/filestore/libs/storage/tablet/tablet_state_cache.h, cloud/filestore/libs/storage/tablet/tablet_state_iface.h, cloud/filestore/libs/storage/tablet/tablet_ut_cache.cpp, cloud/filestore/libs/storage/tablet/tablet_ut_cache_stress.cpp, cloud/filestore/libs/storage/tablet/tablet_ut_state_cache.cpp, cloud/filestore/tests/common_configs/nfs-storage-newfeatures-patch.txt, cloud/filestore/tests/loadtest/service-kikimr-newfeatures-test/nfs-storage.txt, cloud/storage/core/libs/common/lru_cache.h, cloud/storage/core/libs/common/lru_cache_ut.cpp
=> issue-4231: populate per-parentNodeId isExhaustive flag for the TInMemoryIndexCache upon single-page lists

cloud/filestore/config/storage.proto, cloud/filestore/libs/storage/tablet/tablet_state_cache.cpp, cloud/filestore/libs/storage/tablet/tablet_state_cache.h, cloud/filestore/libs/storage/tablet/tablet_ut_cache.cpp
References #4231
Follow-up after #4232
=> issue-4231: do not use per-node exhaustive flag if the corresponding cache is not configured to be non-empty

cloud/blockstore/libs/diagnostics/user_counter_ut.cpp, cloud/storage/core/libs/user_stats/counter/user_counter.cpp
**Motivation**
The user counters `disk.read_throttler_delay` and `disk.write_throttler_delay` are currently broken (after https://github.com/ydb-platform/nbs/pull/4217). They rely on the `units=usec` label, but the underlying `ThrottlerDelay` counter (calculated via `volume_service`) does not provide this label. As a result, these counters do not work as intended.
**Summary**
This PR updates the implementation of the user counters so that they function correctly regardless of the presence or absence of the units label. In addition, proper tests are introduced to cover this behavior and prevent regressions.
=> [NBS] fix "disk.{read,write}_throttler_delay" user counter

cloud/filestore/tests/client_two_stage_read/test.py, cloud/filestore/tests/client_two_stage_read/ya.make
1. fix bug with write_size equal 0
2. write/read data as binary string
3. log seed/write_size/offset
4. increase nfs logs verbosity
=> [Filestore] fix empty file error in test_zero_range_read_rand_data

cloud/blockstore/libs/diagnostics/server_stats.cpp, cloud/blockstore/libs/diagnostics/server_stats_ut.cpp
https://github.com/ydb-platform/nbs/issues/3783
We don't want to see errors for inter-cell requests in target host metrics. For instance we send describe volume request to all cells and only one of the replies with success. In this case other cells should not report errors in metrics
=> hide inter-cell error from metrics

cloud/blockstore/libs/storage/partition2/part2_actor_initfreshblocks.cpp, cloud/blockstore/libs/storage/partition_common/actor_loadfreshblobs.cpp, cloud/blockstore/libs/storage/partition_nonrepl/migration_request_actor.h, cloud/blockstore/libs/storage/service/service_actor_create.cpp, cloud/blockstore/libs/storage/stats_fetcher/stats_fetcher.cpp, cloud/blockstore/libs/storage/volume_balancer/volume_balancer_actor.cpp
Заменил вывод ошибки через `TError::GetMessage()` на `FormatError()`
=> Use FormatError instead of TError::GetMessage in logs

cloud/blockstore/buildall/ya.make, cloud/blockstore/config/storage.proto, cloud/blockstore/libs/daemon/ydb/bootstrap.cpp, cloud/blockstore/libs/daemon/ydb/config_initializer.cpp, cloud/blockstore/libs/daemon/ydb/config_initializer.h, cloud/blockstore/libs/storage/core/config.cpp, cloud/blockstore/libs/storage/core/config.h, cloud/blockstore/libs/storage/volume_balancer/volume_balancer_actor.cpp, cloud/blockstore/libs/storage/volume_balancer/volume_balancer_actor.h, cloud/blockstore/libs/storage/volume_balancer/volume_balancer_state.cpp, cloud/blockstore/libs/storage/volume_balancer/volume_balancer_state.h, cloud/blockstore/libs/storage/volume_balancer/volume_balancer_ut.cpp, cloud/storage/core/libs/kikimr/config_dispatcher_helpers.cpp, cloud/storage/core/libs/kikimr/config_dispatcher_helpers.h, cloud/storage/core/libs/kikimr/config_initializer.h, cloud/storage/core/libs/kikimr/node.cpp, cloud/storage/core/libs/kikimr/node.h, cloud/storage/core/protos/config_dispatcher_settings.proto, contrib/ydb/core/protos/nbs/blockstore.proto, example/2-init_storage.sh, example/nbs/nbs-storage.txt, example/prepare_binaries.sh, example/ydb/config.yaml
Introduce Configs Dispatcher over NBS config
1. Load them on start from Console (this includes using correct node labels that are consistent with the ones used later)
1. Map configs that we receive on boot to our `StorageConfig`
1. Subscribe our actor (in this example -- `VolumeBalancer`) to changes in this config and allow him to react to them
=> Dynamically disable VolumeBalancer via ConfigDispatcher

cloud/blockstore/libs/storage/volume/volume_actor_removeclient.cpp, cloud/blockstore/libs/storage/volume/volume_ut_session.cpp, cloud/blockstore/tests/direct_device_acquire/test.py
#1345
Возможно следующее залипание:
- Пусть у диска есть клиент client-1 и включена фича NonReplicatedVolumeAcquireDiskAfterAddClientEnabled
- Делаем RemoveClient для client-1:
- Выполняется транзакция и удаляет client-1 из бд
- Посылаем ReleaseDevice и по какой-то причине это сообщение теряется
- Отдаем в ответе ошибку
- Ретраим RemoveClient для client-1:
- Не находим client-1 в локальной бд и отвечаем S_ALREADY
- Сообщения снова начинают доходить до DA
- Посылаем AddClient для client-2:
- Запрос приходит в DA И фейлится, т.к. мы не зарелизили девайс от client-1
и так мы нге сможем примонтировать диск пока  client-1 в DA не протухнет
=> issue-1345: added releasing devices after RemoveClient transactions, even if client have already been removed

cloud/blockstore/config/storage.proto, cloud/blockstore/libs/daemon/ydb/bootstrap.cpp, cloud/blockstore/libs/disk_agent/bootstrap.cpp, cloud/blockstore/libs/storage/core/config.cpp, cloud/blockstore/libs/storage/core/config.h, cloud/blockstore/tests/python/lib/config.py, cloud/blockstore/tests/python/lib/daemon.py, cloud/blockstore/tests/registration/timeout_test.py, cloud/blockstore/tests/registration/ya.make, cloud/filestore/libs/daemon/common/config_initializer.cpp, cloud/storage/core/libs/kikimr/node.cpp, cloud/storage/core/libs/kikimr/node_registration_settings.h
В этом пр-е добавлен тайм аут для регистрации клиента в новом способе регистрации:
https://github.com/ydb-platform/nbs/blob/c6d2257e61a6eba4787316aac02dfaabbc8638d7/cloud/storage/core/libs/kikimr/node.cpp#L326 
До этого тайм аута не было. Из-за чего при зависании сервера, nbs зависал
=> [NBS] Added client timeout in new NodeRegistration

cloud/filestore/libs/storage/tablet/tablet_state_cache.cpp, cloud/filestore/libs/storage/tablet/tablet_ut_cache.cpp, cloud/filestore/libs/storage/tablet/tablet_ut_state_cache.cpp
#4231
Imagine a situation where we know that all children of a given node are in memory, and a client tries to do stat(node, non-existent-children). In those situations, we should not perform a real transaction, looking up a non-existent row in a NodeRefs table, but we should use only in-memory information. 
This is what this PR does
=> issue-4231 use per-directory IsExhaustive flag for stats of non-existent files

cloud/tasks/storage/storage_ydb_impl.go, cloud/tasks/storage/storage_ydb_test.go, cloud/tasks/tasks_tests/tasks_test.go
Part of #3738
Current `updateTaskTx` implementation has a bug: when the task dependency is added, ChangedStateAt was not modified (even with actual status transitioning).
This resulted to incorrect WaitingDuration calculating when the task was running inflight for some time before `WaitTask` call - InflightDuration was duplicated to WaitingDuration, thus leading to incorrect tasks with `inflight_duration + waiting_duration > (ended_at - created_at)` being true (sum of inflight_duration, waiting_duration and stalling_duration cannot be less than total duration in any case).
This PR fixes it by moving corresponding code block with ChangeStateAt updating after dependency adding and enhances tests for `WaitingDuration` to handle this case.
=> [DM] Fix ChangedStateAt not being changed on dependency add

cloud/disk_manager/internal/pkg/clients/nbs/ya.make, cloud/disk_manager/internal/pkg/clients/nfs/ya.make, cloud/disk_manager/internal/pkg/common/ya.make, cloud/disk_manager/internal/pkg/dataplane/url/common/ya.make, cloud/disk_manager/internal/pkg/facade/interceptor.go, cloud/disk_manager/internal/pkg/services/disks/delete_disk_task.go, cloud/tasks/errors/ya.make, cloud/tasks/persistence/ydb_logger.go, cloud/tasks/runner.go
добавил в ya.make
```
SET(
GO_VET_FLAGS
-printf=false
)
```
т.к. аркадийный ci ругается подобным образом 
```
$S/cloud/disk_manager/internal/pkg/facade/interceptor.go:89:53: "printf: non-constant format string in call to google.golang.org/grpc/status.Errorf"
$S/cloud/disk_manager/internal/pkg/clients/nbs/factory.go:28:21: "printf: non-constant format string in call to a.yandex-team.ru/cloud/tasks/logging.Error"
$S/cloud/disk_manager/internal/pkg/clients/nbs/factory.go:33:21: "printf: non-constant format string in call to a.yandex-team.ru/cloud/tasks/logging.Error"
$S/cloud/disk_manager/internal/pkg/clients/nbs/factory.go:43:20: "printf: non-constant format string in call to a.yandex-team.ru/cloud/tasks/logging.Warn"
$S/cloud/disk_manager/internal/pkg/clients/nbs/factory.go:48:20: "printf: …
```
=> fix printf linter errors in arcadia ci

cloud/blockstore/libs/storage/service/service_actor_update_volume_throttling_config.cpp
- If VolumeThrottlingManager is disabled (`VolumeThrottlingManagerEnabled` is `false`) we don't get response. Send it immediatly 
- Add timeout to `VolumeThrottlingManager` response
=> [NBS] Make request to VolumeThrottlingManager fail fast

cloud/blockstore/tools/testing/eternal_tests/eternal-load/bin/test.cpp, cloud/blockstore/tools/testing/eternal_tests/eternal-load/lib/public.h, cloud/blockstore/tools/testing/eternal_tests/eternal-load/lib/test_executor.cpp, cloud/blockstore/tools/testing/eternal_tests/eternal-load/lib/test_executor.h
Issue https://github.com/ydb-platform/nbs/issues/4336
Extracted from https://github.com/ydb-platform/nbs/pull/4234
Split `TTestExecutor` into two parts: the test logic itself and an executor proving file IO service for the test.
Also this PR fixes a data race where the read operation could start before the callback for the previous write operation had finished. This could result in a false-positive data verification error (the behavior is well-observed when lowering the alternate phase duration to 1s and file size to 1GiB).
=> issue-4336: Refactoring allowing extensibility for using different file IO services and test scenarios in eternal-load

cloud/blockstore/tools/testing/eternal_tests/range-validator/lib/validate_ut.cpp
https://github-actions-s3.storage.eu-north1.nebius.cloud/ydb-platform/nbs/Nightly-build/17813006975/1/nebius-x86-64/summary/1/ya-test.html#FAIL_BUILD
```
test name                                                                    | elapsed | status
---------------------------------------------------------------------------- | ------- | ----------
cloud/blockstore/tools/testing/eternal_tests/range-validator/lib/ut/unittest | 0.000s  | FAIL BUILD
```
=> Fix broken build for "cloud/blockstore/tools/testing/eternal_tests/range-validator/lib/ut/unittest"

cloud/blockstore/libs/storage/disk_registry/disk_registry_self_counters.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_self_counters.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut.cpp
DisksInMigrationState is an obsolete copy of DisksInWarningState.
It's necessary to replace DisksInMigrationState with DisksInWarningState in infrastructure scripts before merge this PR.
=> Remove obsolete sensor DisksInMigrationState

cloud/blockstore/tools/testing/eternal_tests/eternal-load/lib/test_executor.cpp, cloud/blockstore/tools/testing/eternal_tests/range-validator/lib/validate_ut.cpp
https://github-actions-s3.storage.eu-north1.nebius.cloud/ydb-platform/nbs/Nightly-build-(ubsan)/17847114373/1/nebius-x86-64-ubsan/test_data/1/actions-runner/_work/nbs/nbs/cloud/blockstore/tools/testing/eternal_tests/range-validator/lib/ut/test-results/unittest/chunk0/testing_out_stuff/ut.err
```
###subtest-started:ValidateTest::ValidateRange
2025-09-19T04:25:34.533077Z :ETERNAL_EXECUTOR INFO: cloud/blockstore/tools/testing/eternal_tests/eternal-load/lib/test_executor.cpp:124: Started TTestExecutor
/actions-runner/_work/nbs/nbs/cloud/blockstore/tools/testing/eternal_tests/eternal-load/lib/test_executor.cpp:590:31: runtime error: inf is outside the range of representable values of type 'unsigned long' …
```
=> Fix division by zero in ValidateTest::ValidateRange

cloud/blockstore/config/storage.proto, cloud/blockstore/libs/diagnostics/critical_events.h, cloud/blockstore/libs/storage/core/config.cpp, cloud/blockstore/libs/storage/core/config.h, cloud/blockstore/libs/storage/partition/part_actor_collectgarbage.cpp, cloud/blockstore/libs/storage/partition/part_ut.cpp, cloud/blockstore/libs/storage/partition2/part2_actor_collectgarbage.cpp, cloud/blockstore/libs/storage/partition2/part2_ut.cpp, cloud/blockstore/libs/storage/partition_common/actor_trimfreshlog.cpp
This is a follow up for https://github.com/ydb-platform/nbs/pull/4266
We finally decided to support and use the deadline parameter in TEvBlobStorage::EvCollectGarbage.
According to the YDB team, this functionality has been available since 24-1, and in 25-1 tests for deadlines in the BS proxy were implemented. These tests are green, and since the functionality has not changed since 24-1, we may assume that it also works in 24-1.
Deadlines are now supported in both CollectGarbage and TrimFreshLog operations.
=> switch to deadlines in collect garbage request

cloud/blockstore/libs/storage/partition/part_actor_statpartition.cpp, cloud/blockstore/libs/storage/partition/part_actor_writeblocks.cpp, cloud/blockstore/libs/storage/partition/part_actor_writefreshblocks.cpp, cloud/blockstore/libs/storage/partition/part_actor_writemergedblocks.cpp, cloud/blockstore/libs/storage/partition/part_actor_writemixedblocks.cpp, cloud/blockstore/libs/storage/partition/part_events_private.h, cloud/blockstore/libs/storage/partition/part_ut.cpp, cloud/blockstore/public/api/protos/volume.proto
В случае ошибок записи фрэш блоков не освобождаются барьеры, что приводит к тому, что мы не двигаем LastTrimFreshLogToCommitId, и при следующем ребуте таблетки можем не загрузить огромный кусок фрэша в память и получить OOM.
=> release the trim fresh log barriers in case of write blocks error

cloud/storage/core/libs/common/dynamic_persistent_table_ut.cpp
https://github-actions-s3.storage.eu-north1.nebius.cloud/ydb-platform/nbs/Nightly-build-(ubsan)/17964890345/1/nebius-x86-64-ubsan/logs/1/cloud/storage/core/libs/common/ut/test-results/unittest/testing_out_stuff/TDynamicPersistentTableTest.ShouldAllocAndStoreVariableSizeRecords.err
=> copy data to proper variables in dynamic persistent table tests

cloud/blockstore/libs/storage/volume/volume_actor.h, cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp
You can achieve that by running (after setup, disk creation (`vol0` in this example) and mount):
```shell
./blockstore-client.sh updatevolumethrottlingconfig --proto --input nbs/nbs-volume-throttling.txt
```
Though there're two rules...
https://github.com/ydb-platform/nbs/blob/a8a30c1a4dd3d2d393681e905cf948e4666fb019/example/nbs/nbs-volume-throttling.txt#L1-L22
...specific disk rule (one that target disks by their ID) prevails
You can achieve that by running the same command from the previous step, but changing Version to 2 and deleting the second rule:
=> [NBS] Add volatile throttling info to volume monpage

cloud/blockstore/libs/diagnostics/critical_events.h, cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_allocate.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp, cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut_mirrored_disks.cpp, cloud/blockstore/libs/storage/disk_registry/testlib/test_state.cpp, cloud/blockstore/libs/storage/testlib/test_env_state.cpp, cloud/blockstore/libs/storage/volume/volume_actor.h, cloud/blockstore/libs/storage/volume/volume_actor_allocatedisk.cpp, cloud/blockstore/libs/storage/volume/volume_ut_session.cpp
ПР состоит из двух частей: 
1) В DR чиню баг, из-за которого не сохранялось в базу назначение девайса fresh'ом при замене. 
2) Правки в Volume, которые добавляют предохранитель на такие случаи. То есть если девайс был заменён, но он не fresh и не цель миграции, значит что-то пошло не так.
=> Fix mirror disks device replacement without 'fresh' tag

.github/scripts/nebius-manage-vm.py
I checked why  https://github.com/ydb-platform/nbs/actions/runs/18145885940 cancelled itself. And came to the conclusion that runner's systemd-unit stopped because of the oom kill of the child inside slice.
```Oct 01 05:20:42 computeinstance-e00dkf4nsr3dwrymnr systemd[1]: actions.runner.ydb-platform-nbs.computeinstance-e00dkf4nsr3dwrymnr.service: Failed with result 'oom-kill'.```
And when runner is stopped - task autocancels itself.
This change should:
1. Prevent stopping of the systemd unit
2. Allow, if needed, run ya make in a systemd scope like this
```
JOB_MEMORY_HIGH="${JOB_MEMORY_HIGH:-0}"   # e.g. "240G" (0 = unset)
JOB_MEMORY_MAX="${JOB_MEMORY_MAX:-0}"     # e.g. "270G" hard cap (0 = unset)
JOB_SWAP_MAX="${JOB_SWAP_MAX:-0}"         # e.g. "8G" or "0" to forbid swap for the job …
```
=> fix: this should prevent runner itself from stopping after childs OOM

cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_readblocks.cpp, cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp, cloud/blockstore/libs/storage/testlib/disk_agent_mock.h
#2988
Если включена фича подсчёта контрольных сумм на диск агенте, то можем им доверять и не считать их в NBS на read2 операции mirror дисков.
=> Use disk agent checksums for read2 if present

cloud/blockstore/libs/storage/ss_proxy/path_description_backup.cpp, cloud/storage/core/libs/hive_proxy/tablet_boot_info_backup.cpp
Текстовый парсинг из файлика работает только с текстовыми данными, а не бинарными 
Поэтому меняю их местами, чтобы избежать крешей 
- Сначала идет бинарный парсинг, который читает все что угодно
- Потом текстовый, который читает только текст
=> [Blockstore] fix backups load

cloud/tasks/config/config.proto, cloud/tasks/runner.go, cloud/tasks/runner_test.go, cloud/tasks/tasks_tests/tasks_test.go
Part of #3738 
Add `EstimatedInflightDurationOverrideByTaskType` and `EstimatedStallingDurationOverrideByTaskType` fields to config which handles keys as task types and values as estimated durations.
If set, estimates for selected task types will be automatically set in `lockTaskToExecute`. As SetEstimatedInflightDuration and SetEstimatedStallingDuration allows to set estimate only once, this estimate won't be overrided by the task.
This allows temporarily changing estimates for tasks without needing to change the code and deploying new release.
=> [DM] Allow overriding EstimatedInflightDuration and EstimatedStallingDuration via tasks config
